### ISSUE TITLE
using tabs for channel names

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1009]
**Reported by Nakre on 30 Oct 2010 22:31:50 UTC**
could we get eachtime another channel by using tabs like if we had #aa #ab and when u try #a tab first it will show #aa if u do 2nd tab which you will get #ab (same as the nick tab)..

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1009

**Comment by DarthGandalf** [comment]
**Comment by ambossarm on 30 Oct 2010 23:28:55**
that does already work for me in KVIrc 4.1.1.

I don't think that this is a new feature

**Comment by DarthGandalf** [comment]
**Comment by Nakre on 31 Oct 2010 10:08:39**

```
(12:07:19) 5 matches: #KVIrc, #kvirc, #kewf, #kwefew, #klol
when you try k + tab you will have only #K at the input, 
what im saying can it move first tab #KVIrc, next tab to #kvirc and so #kewf ... 
```

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 31 Oct 2010 15:28:06**
Currently the "bash style completion" and the "zsh style completion" works for only for nicknames. I think the feature request here is to make them work (at least) for #channels, too

---

Version: none → 4.1 Equilibrium

**Comment by un1versal** [comment]
I cant see this being useful, anyone?

**Comment by un1versal** [comment]
actually after some testing regarding  #2126 this seems to work, so will close as works for me.
