### ISSUE TITLE
"Tab" Viewing

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1035]
**Reported by Tron on 09 Dec 2010 22:41:37 UTC**
A great GUI option is to have a "tabs"-based output window as it is done in browsers (ex: Firefox) - with tabs spread out in the top line of the output window.  This would work nicely with the option to quickly switch between 'tree' layout (in Window List window) and 'tabs' layout (in the Output window).  Such a switch would allow to close the tree window and save space on the screen if needed. 

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1035

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 11 Dec 2010 10:20:34**
Such a feature already exists, look out for the classic (tabbed) window list.

---

Resolution: none → worksforme
Status: new → closed

**Comment by DarthGandalf** [comment]
**Comment by Tron on 12 Dec 2010 07:22:45**
The current "Classic Window List" is button based and does not allow to close the "Window List" window.  This is very different than having the option to close this window with all the tree (or button) displayed items turning into tabs in the main "Output" window.

---

Resolution: worksforme → none
Status: closed → reopened

**Comment by un1versal** [comment]
how about a optional toolbar button to quickly toggle between tree view or classic list.

Ill have a look into adding this
