### ISSUE TITLE
Toolbar mouse-overs

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1036]
**Reported by Tron on 09 Dec 2010 23:48:04 UTC**
Another nice GUI feature that would allow to save screen space:  in the button tool bar, during a mouse over to have text describing the button appear just below it in a small window rather than at the bottom of the screen in the IRC status bar.  This would make it reasonable to close the IRC bar and either have more lines for text in the main window or just have KVIrc in a smaller window on the screen.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1036

**Comment by un1versal** [comment]
All toolbar buttons have tooltips, so this is already possible, if I understand this right.

@DarthGandalf if this was closing in error feel free to reopen.
