### ISSUE TITLE
Option to globlally disable the user list

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1042]
**Reported by robm on 10 Dec 2010 22:43:26 UTC**
The config/settings dialog should have an option that allows to disable the userlist once and for every joined channel.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1042

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 12 Dec 2010 02:11:28**
you can close it using one of the button on top of the userlist

---

Version: 4.0.2 Insomnia → 4.1 Equilibrium

**Comment by un1versal** [comment]
Like HelLViS69 already said this is possible via

![capture](https://cloud.githubusercontent.com/assets/3521959/10907769/f73ff798-8224-11e5-895d-b306bf105539.PNG)

closing as works for me.
