### ISSUE TITLE
/who replies

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1047]
**Reported by TheRock on 16 Dec 2010 13:50:11 UTC**
If I give the command /who #namechannel, the reply can be seen ONLY in the window of the #namechannel. I wish it could be possible to see it in the server window (or in any other window)

(kvirc 4 build 5132 on winxp sp3)

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1047

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 16 Dec 2010 13:56:10**
I wish it could be possible => feature request

---

Type: Bug → Feature request

**Comment by un1versal** [comment]
afaik this is already possible

show in active window (could be any (active) window thats is not server window) or shown in server window aka console.

![capture](https://cloud.githubusercontent.com/assets/3521959/15878446/e8b79e8a-2d12-11e6-8ab6-e90443457e48.PNG)

so closing this as works for me
