### ISSUE TITLE
Method for entering Italic Text

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1070]
**Reported by kZard on 12 Jan 2011 22:17:45 UTC**
There does not seem to be any method for entering ''Italic'' text in KVirc.
I am told this feature used to be bound to Ctrl+I, which now calls emoticons.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1070

**Comment by DarthGandalf** [comment]
**Comment by wodim on 20 Jan 2011 02:29:11**
As far as I know, there's no standard way of using Italic text in IRC. This means that this feature would be only useable in KVIrc.

**Comment by DarthGandalf** [comment]
**Comment by kZard on 23 Jan 2011 12:10:32**
mIRC has recently implemented italic text ([http://www.mirc.com/whatsnew.txt]) using "control code 29."
Konversation uses "the ASCII 0x1d character" ([http://konversation.kde.org/]).
Mibbit seems to use the same inline formatting as mIRC ("The most common scheme is the mIRC encoding, Mibbit uses this standard." - from Mibbit's [http://wiki.mibbit.com/index.php/Formatting wiki]).

**Comment by DarthGandalf** [comment]
**Comment by pragmaware on 08 Mar 2011 21:40:14**
Decimal 29 is 0x1d, so it's the same code.
KVIrc uses 0x1d for icons (and also the same CTRL+I key sequence)...

So we have a backward-compatibility problem here.

An option is to switch the icon control code to, say, 28.
But we'll have no way to remain compatible with older versions
of the client. Need input for this.

**Comment by DarthGandalf** [comment]
**Comment by kZard on 20 Aug 2011 19:19:05**
As far as I know, neither (special) icons or italic text are used very frequently. I think it would be possible to switch with minimal interruption / confusion if it is changed in both the stable and beta versions of KVIrc at the same time. (I don't know whether this can be done)

This will fix compatibility with both mIRC and Konversation, so there should be a nett gain in compatibility. 

(Also, as a side note, I don't know how mIRC and Konversation indicate special icons. Maybe this should be made the same too? Perhaps another ticket should be made?)

**Comment by DarthGandalf** [comment]
**Comment by kZard on 20 Aug 2011 19:58:16**
Edit to my previous comment:

I see mIRC does not support emoticons. (http://forums.mirc.com/ubbthreads.php/ubb/postlist/Board/6)

Konversation does support it, but the option needs to be enabled. I do not know whether Konversation uses some controll code for it. I would assume that they don't.

**Comment by alanhuang122** [comment]
Personally, I would prefer italics to icons.
