### ISSUE TITLE
Subgroup windows in the tree windowlist (was: minimizin windows)

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1097]
**Reported by Nakre on 14 Feb 2011 13:05:10 UTC**
any chance of being able to minimize  windows ie: your  query windows, windows created by ctcp dcc and the others by user script/addons (probably needs tabs to take these windows there when they created) without minimizing all by console minimize

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1097

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 13 Mar 2011 21:56:43**
This tickets refers to the ability to subgroup windows in the tree windowlist. Actually windows are grouped on a per-context tree. The ticket proposes to add a subgroping for windows type.

---

Summary: minimizin windows → Subgroup windows in the tree windowlist (was: minimizin windows)
Version: none → 4.1 Equilibrium

**Comment by un1versal** [comment]
If I understand this right, MDI windows is gone, so you cant do this anymore without undocking a channel windows. 

@ctrlaltca closing this, for that reason, if this is incorrect please feel free to reopen or ping me..
