### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1104]
**Reported by Meliorator on 04 Mar 2011 20:18:20 UTC**
I seem to be having a few issues connecting multiple servers using SSL. All the connections are set to automatically connect when KvIrc starts. some of the connections are established fine, but about half (5/9) do not. If I then manually connect to each one that was not established, they connect fine.

Here an example of some output for one of the connections that failed:

```
Starting Secure Socket Layer handshake
[SSL ERROR]: unknown protocol
[SOCKET ERROR]: Secure Socket Layer error
```

I've tried upgrading to 4.1.1 r5132, but no joy :(
Please help!

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1104

**Comment by DarthGandalf** [comment]
**Comment by Meliorator on 04 Mar 2011 20:20:52**
I should also mention that the "servers" that I am connection to, are all connections to psybnc. I had to disable "Query extended capabilities on connect" for each server entry. I also tried switching STARTTLS on/off, which didn't seem to make any difference.

**Comment by DarthGandalf** [comment]
**Comment by ambossarm on 04 Mar 2011 20:26:05**
possibility related to Windows Half-Open-(TCP)-Connection-Limit
perhaps KVIrc should check for finished handshakes before it connects to the next server

**Comment by DarthGandalf** [comment]
**Comment by Meliorator on 09 Mar 2011 15:11:37**
I have just tried Gizmokid's latest build (http://papps.gizmokid2005.com/KVIrc4_nightly/r5541/KVIrc-4.1.1-r5541-dev.exe) and it has the same issue.

**Comment by DarthGandalf** [comment]
**Comment by Meliorator on 22 Jul 2012 13:25:04**
This issue is still present in the 4.2.0 release. However, I have come up with a workaround, which looks something like the code below. I would very much appreciate this being fixed properly sometime soon!

Aliases:

```

[IrcServerConnect]
_Buffer=    if ( %IrcServerConnectPosition >= %IrcServerConnectList[]# ) return

        if ( %IrcServerConnectPosition == 0 )
        {
            server id:%IrcServerConnectList[%IrcServerConnectPosition]
        }
        else
        {
            server -n id:%IrcServerConnectList[%IrcServerConnectPosition]
        }

        %IrcServerConnectPosition++

[IrcServerConfig]
_Buffer=    %IrcServerConnectList[0] = id1
        %IrcServerConnectList[1] = id2
        %IrcServerConnectList[2] = id3
        %IrcServerConnectList[3] = id4
        %IrcServerConnectList[4] = id5
        %IrcServerConnectList[5] = id6
        %IrcServerConnectList[6] = id7
        %IrcServerConnectList[7] = id8

        %IrcServerConnectPosition = 0

```

Events:

```

[OnKVIrcStartup]
Buffer0=    IrcServerConfig

        %IrcServerConnectPosition = 0

        IrcServerConnect
Name0=CONNECT
NHandlers=1
Enabled0=true

[OnIRCConnectionEstablished]
Buffer0=IrcServerConnect
Name0=CONNECT
NHandlers=1
Enabled0=true

```

**Comment by DarthGandalf** [comment]
**Comment by Love4Boobies on 07 Nov 2012 22:02:53**
Hi,

I am experiencing the same issue with 4.1.3. This is preventing me from using SASL. Since the issue has not been closed, I assumed no measure has been taken so far, so I didn't bother checking a more recent version.

Cheers,
Bogdan

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 13 Oct 2013 17:08:09**
Can you test r6359? it introduces some bugfixes on ssl connections error handling.

**Comment by un1versal** [comment]
Is this still an issue? I connect to multiple servers all SSL some via ZNC, havent experienced this issue since started using KVIrc in 4.2.0 is this networks specific?

**Comment by un1versal** [comment]
Since theres no feedback from ANYONE and I cant duplicate this try as I might Im closing this as works for me.

@blindsighttf2  for second thoughts (sorry to ping you but noone seems very active in these parts)
