### ISSUE TITLE
High Xorg CPU usage when running KVIrc

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1126]
**Reported by IppatsuMan on 04 Apr 2011 16:42:45 UTC**
Having KVIrc window not minimized causes high CPU usage by Xorg. On my Intel i7 720QM keeping KVIrc window open makes Xorg take about 5% od CPU time (measured using top). Upon joining several channels, Xorg CPU load raises up to 15%. This figure does not change even if KVIrc window is not fullscreen and it is hidden by other windows. If KVIrc shows a channel where there are users with an animated avatars, Xorg easily take 25% of CPU. By minimizing KVIrc window, either to taskbar or tray icon, Xorg CPU usage drops to 0-1%. Other Qt-based software does not exhibit this behavior.

Additional info:
KVIrc compiled from sources r5750
Linux 2.6.35
Qt 4.7.0
Video driver: ATI fglrx 8.780

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1126

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 10 Jun 2011 16:31:38**
I've attached a patch that removes the font width caching in inputbar and ircview that could be related (previous user investigation using callgrind found FcFontMatch being the culprit).

**Comment by pragmaware** [comment]
Old bug, probably fixed in these years.
Please reopen if still persisting.
