### ISSUE TITLE
logs ridiculously large / messed up logs cause log viewer crash

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1139]
**Reported by TheRipper on 21 Apr 2011 21:10:43 UTC**
as mentioned in freenode/#kvirc I encounterd a few unusual large log files(record: 1GB) while investigating the reason for the crash when searching in logs.
This could possibly be caused by a strange behaviour when 'gzip log files' is enabled, because all log files before were normal.
This strange behaviour shows in writing the same log entries multiple times(a few 1000+++ times, idk). 
Only channels where I have another clone are affected.

It seems like kvirc combined with gzip can't handle this situation with 2 clones whereas kvirc alone does fine.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1139

**Comment by DarthGandalf** [comment]
**Comment by TheRipper on 26 Apr 2011 15:42:14**
deactivating gzip fixed the size problem, but log viewer still crashes.

As mentioned above, this only happens on channels that are logged twice. The majority of the log itself is fine, but there a still parts in it that can cause the log viewer to fail (e.g. wrong msgtype[finding msgtype 5742 could be pretty hard])

I could change this one into a feature request, requesting the log viewer shouldn't be connected to the core irc program and causing both to crash or that the it doesn't try the impossible anymore, but I think this bug has higher priority.

---

Priority: Normal → Crash
Summary: logs ridiculously large → logs ridiculously large / messed up logs cause log viewer crash

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 01 Jan 2012 17:31:25**
The crash related to msgtype has been fixed in r6012, thank you.
Regarding the "2 windows logging to the same gzipped file" problem, first it would be a nice idea to have those 2 windows log to different files..

**Comment by pragmaware** [comment]
Probably fixed. If still persisting please reopen.
