### ISSUE TITLE
Certificate can't be used if the path contains Russian symbols

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1150]
**Reported by wRAR on 14 May 2011 17:46:04 UTC**
If the SSL certificate contains a directory with a Russian name in its path, KVIrc shows "File I/O error" when trying to use it. Windows 7 64bit, r5829 official. It works on Debian r5829.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1150

**Comment by un1versal** [comment]
imo @DarthGandalf is the only one who can determine the validity of this report atm so shall be assigned to him, since thers no other way to get the reporter to do jack here anymore..

**Comment by DarthGandalf** [comment]
@un1versal anyone can create a file with non-English letters in filename.
But it still happens on 64bit windows build of f67bdb05b41e5d90957ca580a454b9d0dbcc8a36

**Comment by un1versal** [comment]
Ok thx.
