### ISSUE TITLE
Keyboard mess after restore from tray (Win7)

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1152]
**Reported by tedych on 19 May 2011 10:45:09 UTC**
Hi. I was testing 4.0.4. I find it probably the best IRC for Windows. It is a Win7 x64 Ent.
There is some bug with input field after I restore KVIRC from the tray.
KVIRC is on, and minimized to tray. I do something else, and some minutes later I decide to bring it back, I click the tray icon, and KVirc show up but is not made focused. Ok, I click the window and most of the time when I start typing (cyrillic UTF8 server) in the input field, the symbols appear but keys like Enter, backspace, Del etc do not function, instead strange symbols appear, and the only way to send the message is Ctrl+Enter (guessed it). If I take the focus away from kvirc, then focus it again, everything works fine. My current workaround is to never minimize it to the tray.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1152

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 08 Jan 2012 16:40:09**
So the issue seems related to the window being showed as foreground, but missing some focus/activation routine. I've added a test patch in r6040, maybe someone can test it..

---

Owner: pragmaware → ctrlaltca
Status: new → assigned

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 02 Jan 2015 14:50:28**
Version: 4.0.4 Insomnia → 4.2.0 Equilibrium

**Comment by un1versal** [comment]
Assigned as per svn indication.

Also no idea if this is related to https://github.com/kvirc/KVIrc/issues/1749 in some weird way.
