### ISSUE TITLE
setting windows props as default

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1185]
**Reported by Nakre on 28 Jul 2011 10:22:45 UTC**
ok so far the "set for windows props as default" working on new created channels only.. maybe we can use another one as well where setting default for old channels too and that would change existing "specific chanel configs".

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1185

**Comment by DarthGandalf** [comment]
**Modified by ctrlaltca on 25 Aug 2011 13:27:26**
Version: 4.0.4 Insomnia → 4.1 Equilibrium

**Comment by un1versal** [comment]
Somewhat related https://github.com/kvirc/KVIrc/issues/1197

**Comment by un1versal** [comment]
There is a global setting already so tbh this is all covered afaik **/option boolWindowsRememberProperties**

So closing here

![capture](https://cloud.githubusercontent.com/assets/3521959/15879172/8f949a0e-2d19-11e6-92e7-7e0cfc45ce75.PNG)

properties are lost randomly and its buggy but thats already reported
