### ISSUE TITLE
duplicate mask types

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1204]
**Reported by Nakre on 24 Aug 2011 23:13:03 UTC**

```
21: *!*user@*.host.top (*!user@*XXX.XXX.*)
26: *!*user@*.host.top (*!user@*XXX.XXX.*)

19: *!~user@*.host.top (*!~user@XXX.XXX.*)
24: *!~user@*.host.top (*!~user@XXX.XXX.*)

18: nick!*@*.host.top (nick!*@XXX.XXX.*)
23: nick!*@*.host.top (nick!*@XXX.XXX.*)
```

Instead of these duplicates replaced or just as new ones can we these added ?

```
*!*@*abc.host*
*!*@*host.top
*!*@*top
```

```

```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1204

**Comment by DarthGandalf** [comment]
**Comment by Nakre on 24 Aug 2011 23:19:51**
no editing sux.. :x

also pls _!_@abc*

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 25 Aug 2011 12:27:02**
From the documentation of $mask:

---

The masks 22-26 are the smart versions of the masks 17-21 that try take care of masked ip addresses in the form xxx.xxx.INVALID-TOP-MASK. If a masked ip address is found then the XXX.XXX.\* or XXX.\* host mask is returned instead of the (wrong) *.INVALID-TOP-MASK

**Comment by un1versal** [comment]
It seems to me that explanations says it all.

closing as wontfix, if anyone disagrees, state your reasons and reopen or ask to reopen ticket
