### ISSUE TITLE
Setup window opens whether setup has been made or not

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1206]
**Reported by kartagis on 03 Sep 2011 08:31:08 UTC**
Hi,

I set up my servers and everything, and yet setup window opens every time I open KVIrc.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1206

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 04 Sep 2011 15:08:49**
can you tell us:
- your os;
- the revision of kvirc you're running;
- is it a new config or an old one (from kvirc3, moved from another pc, ??)
- if this directory exists: /echo $file.localdir (run this command inside kvirc and check if the resulting directory exists)
- if this directory exists: /echo $file.globaldir (run this command inside kvirc and check if the resulting directory exists)
- if the directory contains a _portable_ file: /echo $file.globaldir (run this command inside kvirc and check if the resulting directory contains a file _portable_)
- if a file named kvirc4.ini or .kvirc4.rc exists in your home directory (/home/username/ on linux, c:\Users\username on win7, c:\documents and settings\username\ on winxp)
- the content of the previous file, if existing (at least the LocalKvircDirectory and SourcesDate values)

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 04 Sep 2011 15:12:33**
(Resending my comment, wikiformatting sucks, i should always use the preview, sorry)
can you tell us:
- your os;
- the revision of kvirc you're running;
- is it a new config or an old one (from kvirc3, moved from another pc, ??)
- if this directory exists: /echo $file.localdir (run this command inside kvirc and check if the resulting directory exists)
- if this directory exists: /echo $file.globaldir (run this command inside kvirc and check if the resulting directory exists)
- if the directory contains a _portable_ file: /echo $file.globaldir (run this command inside kvirc and check if the resulting directory contains a file _portable_)
- if a file named kvirc4.ini or .kvirc4.rc exists in your home directory (/home/username/ on linux, c:\Users\username on win7, c:\documents and settings\username\ on winxp)
- the content of the previous file, if existing (at least the LocalKvircDirectory? and SourcesDate? values)

**Comment by DarthGandalf** [comment]
**Comment by kartagis on 05 Sep 2011 19:23:14**
- My OS is Ubuntu GNU/Linux
- The revision is 5902
- New config
- The dir from /echo $file.localdir is /home/tolga/.config/KVIrc, which exists
- The dir from /echo $file.globaldir is /usr/share/kvirc/4.1, which also exists
- The dir from /echo $file.globaldir does NOT contain _portable_
- .kvirc4.rc existed and that caused the setup screen to appear every time; wodim told me to delete it and so I did, and the problem disappeared.
- The content of .kvirc4 (as renamed) is:
  cat .kvirc4 
  # KVIrc configuration file
  [Main]
  LocalKvircDirectory=/home/tolga/.config/KVIrc
  SourcesDate=537986600

Regards,

**Comment by pragmaware** [comment]
Closing the issue as very old.
Please reopen if the problem still persists.
