### ISSUE TITLE
kvirc crashes on dcc get when kvirc hidden on tray

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1214]
**Reported by uNmowed on 17 Sep 2011 15:28:37 UTC**
this case haven't crash data and core dump

```
$ kvirc
$
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1214

**Comment by DarthGandalf** [comment]
**Comment by wodim on 17 Sep 2011 15:36:02**
Not a crash, déjà vu there (did this happen with the options dialog as well, clean exit on close?)

**Comment by DarthGandalf** [comment]
**Comment by uNmowed on 17 Sep 2011 15:40:25**
it happens all time, when I get any file via DCC at a time when kvirc hidden on tray

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 19 Sep 2011 11:22:42**
well.. just searching for any exit() in the dcc code i found this in

```
void DccMarshal::doSSLHandshake(int)
{
#ifdef COMPILE_SSL_SUPPORT
...
#else  //!COMPILE_SSL_SUPPORT
    qDebug("Ops.. ssl handshake without ssl support!...aborting!");
    exit(-1);
#endif //!COMPILE_SSL_SUPPORT
}
```

this could be the case.. but of course since we don't know:
- what revision of kvirc you are running
- if you compiled it by yourself or grabbed a package from somewhere
- if you compiled by yourself, the flags you used at compile time
  it's hard to tell you something precise.

**Comment by DarthGandalf** [comment]
**Comment by uNmowed on 19 Sep 2011 21:44:34**
in 4.0.4 or  4.1.1 were crashes.

i install with FreeBSD Ports, but 4.1.1 manual.

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 20 Sep 2011 07:05:54**
I don't fully get what you mean, it crashed when using 4.1.1 freebsd's ports package but now that you're using a self-compiled 4.1.1 it doesn't crash anymore, but exit cleanly instead?
Please copypaste here the output of the cmake step during compilation

**Comment by DarthGandalf** [comment]
**Comment by uNmowed on 20 Sep 2011 07:52:02**

```
$ cmake CMakeLists.txt
-- Found Subversion 1.6.17
-- Current revision is 4768
-- Phonon Version: 4.4.2
-- Found Python 2.6.6
--  
-- Ok, this is the configuration I've worked out:
-- (I found an old config that was exactly the same and kept it to save compilation time)
--  
--   Binary Path                 : /usr/local/bin/kvirc
--   Library Path                : /usr/local/lib/
--   Modules Path                : /usr/local/lib/kvirc/4.1/
--   Man Path                    : /usr/local/share/man/
--   Debug                       : No (Stripped)
--   Verbose Output              : No
--   Coexistence Support         : No
--   Threading Support           : POSIX
--   X11 Support                 : Yes
--   Qt-DBus Support             : Yes
--   Qt-WebKit Support           : Yes
--   KDE4 Support                : Not available
--   OpenSSL Support             : Yes
--   Crypt Support And Engines   : Yes
--   IPv6 Support                : Yes
--   Pseudo-Transparency Support : Yes
--   Perl Support                : Yes, used for scripting+doc
--   Python Support              : Yes
--   IPC Support                 : Yes
--   System memmove Support      : Yes
--   GSM Support                 : Yes
--   DCC Canvas Support          : User disabled
--   DCC Voice Support           : Yes, found sys/soundcard.h
--   DCC Video Support           : User disabled
--   Ogg/Theora Support          : User disabled
--   Apple Universal Binary      : Not available
--   ix86 asm Support            : No
--   Memory Profile Support      : No
--   Memory Checks Support       : No
--   GetText Support             : Yes, + extra
--   GetText Messages Tidying    : Yes
--   Doxygen Support             : Yes
--   Enabled Audio Backends      : Phonon;Esd;Oss+AudioFile
--  
--   Build Date                  : 2011-09-20 07:50:37 UTC
--  
-- I'm ready to build KVIrc for you: please type 'make' now...
--  
-- Patching for FreeBSD...
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/home/user/Desktop/kvirc-4.1.orig
```

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 24 Sep 2011 14:22:50**
I've tested a bit dcc.send/recv and dcc.get with a configuration similar to yours, but i couldn't reproduce the problem.

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 31 Dec 2011 14:12:53**
The only way to understand what's going on would be to debug the application while it's running, possibly using strace on a debug-enabled kvirc.

---

Resolution: none → need feedback
Status: new → closed

**Comment by ekolis** [comment]
Something similar is happening to me in 4.3.1 on Windows 10. If I enable "close to tray", then close KVIrc and come back a while later, I find that it isn't running and I have to restart it.

**Comment by DarthGandalf** [comment]
@ekolis there is no such thing as 4.3.1. Please say which exact version you use.
4.3.1 is an umbrella for lots of different svn (and now git) commits.

**Comment by ekolis** [comment]
I used this build:

http://kvirc.d00p.de/files/KVIrc-4.3.1-r3cf0289-dev-x86_64-d00p.exe
