### ISSUE TITLE
Emoticons gone after Client Restart

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1224]
**Reported by gamer1990 on 10 Oct 2011 07:31:23 UTC**
The Graphics for Emoticons like ":D :)" and so on, are gone after Client-Restart, reset the Emoticons over the Settings fix this problem, but after a restart the Graphics are gone again.

KVIrc Equilibrium 4.1.3, revision: 5980, sources date: 20110830, built on: 2011-10-05 09:15:52 UTC

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1224

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 08 Jan 2012 14:52:29**
Does it happen with a clean config?

**Comment by DarthGandalf** [comment]
**Comment by gamer1990 on 15 Jan 2012 00:51:37**
Yes

**Comment by un1versal** [comment]
https://github.com/kvirc/KVIrc/issues/1364 Is a duplicate of this but I feel that https://github.com/kvirc/KVIrc/issues/1364 has more meat on the bones and Im not copying and pasting commnets to close the newer report. so am marking this as duplicate and merging with https://github.com/kvirc/KVIrc/issues/1364 and closing this.
