### ISSUE TITLE
Custom nick format

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1256]
**Reported by _KaszpiR_ on 08 Feb 2012 19:05:54 UTC**
Feature request to allow user custom nick formatting.
Whe you are in Configure Theme - Text - Message Style - Nick section, then you are able to define PREFIX and SUFFIX.

I would like to be able to format nick so that I could change it to convert all nicks to 15 chars aligned to right padded with spaces.

That would allow chat text to be starting from certian place, very useful when using monospace font on the screen.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1256

**Comment by un1versal** [comment]
This is possible, just add 15 non breaking spaces to the prefix, if I understand the request.

![capture](https://cloud.githubusercontent.com/assets/3521959/16159007/23c66892-34b8-11e6-887b-e40d7437f690.PNG)
![capture2](https://cloud.githubusercontent.com/assets/3521959/16159011/2b9c4a00-34b8-11e6-9fb0-98a439b8f802.PNG)
![capture](https://cloud.githubusercontent.com/assets/3521959/16159180/25fd8216-34b9-11e6-97a0-1a0eac42be34.PNG)

and you can also do that to timestamp as well

closing here as worksforme

if anyone disagrees, feel free to open or ask to reopen
