### ISSUE TITLE
"EN" Not available in language selection list

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1261]
**Reported by Gallion on 28 Feb 2012 00:16:27 UTC**
Windows 7 is set to "English (Canada)" with "Canadian French" as a keyboard layout.

KVIrc installed in French (oh the horror).

The default language setting is set to Automatic Detection. Although it is in French, "Fr" is listed while "En" is not. Selecting "Fr" and restarting KVIrc will cause "Fr" to appear twice in the list while "En" still won't be listed. I had to select a different language from the 2 and restart to be able to see "En" in the list and select it.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1261

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 01 Apr 2012 21:53:46**
This is strange: to avoid such a situation, we hardcode a "en" entry just after the "automatic detection" one (i.e. the second entry on the list). what version of kvirc are you using?

**Comment by DarthGandalf** [comment]
**Comment by Visitor_099 on 01 Apr 2012 22:24:47**
4.1.3.

**Comment by Dessa** [comment]
works here, used version is ancient, reopen if its still an issue.
