### ISSUE TITLE
Different output for channel and private notices

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1270]
**Reported by oyaebu on 11 Mar 2012 10:38:35 UTC**
Channel notice (NOTICE #foo) and private notice (NOTICE username) looks the same by default.

I think that channel notices should be different. With "[C]" or other mark. For example.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1270

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 18 Mar 2012 19:18:27**
Currently you can change the messages appearance (color, background and icon) from within the "configure theme" settings.
If you want to filter the message and add a prefix to it, you can use some ad-hoc kvs code, binding the OnChannelNotice and OnQueryNotice events and halting their original output.
Additionally, from "configure kvirc" you can decide if you want kvirc to create a query window when you first receive a notice, and show notices there.
You have a point on the fact that it's hard to distinct channel and private notices on kvirc, but it's easy to change them as you want. We prefer not to hardcode something like that, since it will affect also users that doesn't want/like it that way.
If you end up with a nice script on this, we can review it and add it to kvirc's builtin event hanlders.

---

Resolution: none → wontfix
Status: new → closed

**Comment by DarthGandalf** [comment]
**Comment by oyaebu on 19 Mar 2012 13:12:43**
Hm.

KVIrc already has different formats for CTCP:
"CTCP VERSION request from" and "Channel CTCP VERSION request from".

A couple of years ago I used this:

```
event(OnChannelNotice,channelnotice)
{
    echo -i=$msgtype(ChannelNotice) "[#] *$u$chan.getflag($0)$link($0,nick)$u* $1"
    halt;
}
```

But it can't highlight nick same color as in the userlist.

BTW KVIrc already shows notices like "NOTICE @#foo :test" as "_nick_ [>> @#foo] test". Normal channel notices can be showed the same way.

---

Resolution: wontfix → none
Status: closed → reopened

**Comment by un1versal** [comment]
This is also theme dependent and fully configurable so meh, whats this doing still open?

Aside from that has nice example in reply to suit all tastes.

closing...
