### ISSUE TITLE
Paste Last Channel/Query Log Options Not Working

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1281]
**Reported by cryptobear on 04 Apr 2012 12:41:33 UTC**
I have enabled the paste last channel log and paste last query log, and set the lines to 50 and the days to 10, but I've never been able to get it to work. When opening a channel or query for which there are definitely log files, nothing is pasted into the window.

The log files definitely exist and are browseable using the log viewer, but the paste log functionality is broken  (for me at least).

Any guidance on troubleshooting this would be much appreciated. I don't have any weird path names.

I'm running the 32-bit KVIrc on Win 7 x64. I am running it in portable mode (with settings files installed in program folder), and my logs folder is set to a /documents/logs/kvirc on the same drive KVIrc is installed to.

Thanks

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1281

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 02 Jan 2015 14:49:50**
Version: 4.0.4 Insomnia → 4.2.0 Equilibrium

**Comment by un1versal** [comment]
this requires more testing but as is so far Im more inclined to the conformed side than not.

**Comment by un1versal** [comment]
this definitely doesn't work,

**Comment by CyberShadow** [comment]
Should be fixed by https://github.com/kvirc/KVIrc/pull/2050

**Comment by un1versal** [comment]
OK Ill mark this under development, would you mind to add **resolves #1281** to your commit message....? thx ;)

**Under development**  label is old I**n progress** label fyi.
