### ISSUE TITLE
Set text color in hex

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1284]
**Reported by oyaebu on 18 Apr 2012 12:54:32 UTC**
HTML-like color setting.

Configure theme - Text - Message colors

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1284

**Comment by un1versal** [comment]
mmm this is possible already in 4.3.2 as far as I know.

@DarthGandalf can you confirm?

**Comment by un1versal** [comment]
OK, current 4.3.2 Qt5 builds support this while Qt4 builds dont.

**Comment by un1versal** [comment]
Qt5
![capture](https://cloud.githubusercontent.com/assets/3521959/10191553/a70c7f62-676c-11e5-8d08-b25e915915b9.PNG)

Qt4 doesn't have that.

**Comment by ctrlaltca** [comment]
Yep, the color picker is implemented by Qt, and it's typically the one exported by the operating system.

**Comment by un1versal** [comment]
Well that doesnt seem to export with Qt4 at least thats not how it looks in Qt4 and you cannot do HTML colors.

Closing here as all nighty builds are Qt5
