### ISSUE TITLE
neo layout special characters problem

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1286]
**Reported by ego on 18 Apr 2012 20:28:42 UTC**
Hello, I am using a keyboard layout called neo 2.0.
The layout has a 3rd layer for symbols like \/{}*?():' etc
See: ebene 3 http://www.neo-layout.org/
When I try to insert them I need to hit the button twice for those symbols to appear. 
That is very annoying. Do you have a solution?

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1286

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 19 Apr 2012 20:12:37**
Sincerely, i have no idea.<br/>
I saw the animated layout image following the url, and i saw that the 3rd layout is activated using the "caps lock" button, that is indeed uncommon. We don't handle input directly, but let the qt libraries handle that for kvirc, so i suppose that the bad behaviour should be common to other qt-based applications.<br/>
Unfortunately you did not mention your os.. i guess that if you're running linux/kde you'd surely noticed this very same problem on other apps, but since you did not mention it i guess you are probably on windows.<br/>
In this case, i can suggest you to try a development snapshot of kvirc from ftp://ftp.kvirc.de/pub/kvirc/snapshots/win32/ : since they bundle a more recent version of the qt libraries, there's a chance that they actually fixed this problem.

**Comment by DarthGandalf** [comment]
**Comment by ego on 19 Apr 2012 20:44:17**
This is the first time such a problem occured to me. vOv
Yes, I am on win7.
I installed the kvirc version from the link you posted but that didn't seem to fix it.

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 02 Jan 2015 14:49:35**
Version: 4.0.4 Insomnia → 4.2.0 Equilibrium

**Comment by pragmaware** [comment]
This is quite old and might be solved by recent KviInputEditor related commits.
Reopen if still reproduceable.
