### ISSUE TITLE
Option to set kvirc to not reset selection on mouse release

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1295]
**Reported by gry on 12 Jun 2012 10:55:24 UTC**
When selecting text and releasing mouse button, KVIrc currently copies text to clipboard and removes the selection.

While this is useful to save time on Windows, on Linux, the OS already uses a buffer for unix-style copy and paste; when anything at all is selected, it can be "pasted" into another application using middle click. This is why resetting the selection is A) useless as a Linux user can copy just by selecting already B) unexpected to users of other IRC clients (xchat, irssi, smuxi, quassel, chatzilla) who see such behavious as "new".

In my view, KVIrc should have an option of not resetting the selection when releasing mouse button (at least for Linux systems).

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1295

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 16 Jul 2012 22:56:59**
I almost agree with your point that the current selection system is somewhat weird (as in: not to be found anywhere else) and uncomfortable for first time users.<br/>
This is due to the way selection was first implemented in the kvirc's ircview, and even if it has been modified a lot it always kept this same behaviour to avoid cutting away what can be considered as a feature on windows.<br/>
I'll turn this into a feature

---

Summary: Set kvirc to not reset selection (on linux systems at least) → Option to set kvirc to not reset selection on mouse release
Version: 4.0.4 Insomnia → 4.3.1 Aria

**Comment by DarthGandalf** [comment]
**Modified by ctrlaltca on 16 Jul 2012 22:57:23**
Type: Bug → Feature request

**Comment by un1versal** [comment]
@staticfox wouldnt this be indirectly fixed by your recent commit https://github.com/kvirc/KVIrc/commit/4fa5b389e853065181447f11985b7b985de9165b

**Comment by un1versal** [comment]
Since Im still waiting for a reply, Ill answer it myself.

This has been added by https://github.com/kvirc/KVIrc/commit/4fa5b389e853065181447f11985b7b985de9165b so closing here
