### ISSUE TITLE
Allow Single-line Editor to handle long messages

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1298]
**Reported by Fezi on 21 Jun 2012 21:39:24 UTC**
Currently, the single-line message editor will not accept input past the 400th character, forcing the user to change to the Multi-line Editor to create longer messages. While not experience-breaking, the forced switch can be annoying, especially if you don't care about where the line breaks end up.

Would it be possible to allow the Single-line Editor to accept messages and actions as long as the user desires, and then split them into smaller messages on output as the Multi-line Editor does? 

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1298

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 30 Dec 2014 02:17:40**
Version: 4.0.4 Insomnia → 4.3.1 Aria

**Comment by un1versal** [comment]
This sounds like a duplicate of #1207

**Comment by un1versal** [comment]
Merging with #1207 and closing this
