### ISSUE TITLE
Background color on active item at tree window list is not working

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1304]
**Reported by tbs on 16 Jul 2012 15:16:45 UTC**
At '''Settings -> Configure Theme -> Window List -> Tree Window List -> Background -> Selected'''. This config take no effect. Issue cofirmed in version 4.2.0, specially the portable one from http://portableapps.com/apps/internet/kvirc_portable which I use.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1304

**Comment by DarthGandalf** [comment]
**Comment by Gizmokid2005 on 16 Jul 2012 16:12:56**
What version of windows are you running?

**Comment by DarthGandalf** [comment]
**Comment by tbs on 16 Jul 2012 20:47:32**
I tried on Windows 7 and 8. Previous version 4.0.4 has no issue.

If you need more info or custom tests let me know.

**Comment by DarthGandalf** [comment]
**Comment by Gizmokid2005 on 16 Jul 2012 20:52:14**
I can confirm the issue with 4.2.0 on Win7 enterprise x64. I'll check this evening on a different machine with Win7Ultx64.

**Comment by DarthGandalf** [comment]
**Comment by tbs on 15 Aug 2012 02:23:32**
So, it is fixed?

**Comment by un1versal** [comment]
This is fixed in 4.3.2 (Windows 7 64bit / Linux 64bit) Ive tested against git-5292-gb397f4d and its been working for a long time before since 4.3.1-SVN at least.
