### ISSUE TITLE
Icons in toolbar gone, and some icons corrupted

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1309]
**Reported by waser on 26 Jul 2012 02:03:11 UTC**
I closed kvirc one night, it was fine, reopened it the next day, and all icons are a mess. The Toolbar still is set at "icons" (and not text). I recompiled, and the problem still persist.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1309

---

**EDIT by team** Adding a screenshot from duplicate report #1645
![manage_themes_-_kvirc_2015-09-30_22-04-52](https://cloud.githubusercontent.com/assets/75278/10205049/5ade1260-67bf-11e5-8fef-5e3444056d20.png)

**Comment by DarthGandalf** [comment]
**Modified by waser on 27 Jul 2012 01:35:53**
Component: Core → GUI

**Comment by DarthGandalf** [comment]
**Modified by waser on 11 Sep 2012 22:31:48**
Summary: Icons in toobar gone, and some icons corrupted → Icons in toolbar gone, and some icons corrupted

**Comment by DarthGandalf** [comment]
**Comment by waser on 15 Oct 2012 21:32:42**
As it turns out, I've installed kvirc on a Windows machine and imported my configurations from the buggy linux compilation, and the bug is still present, so I suspect a configuration problem causing all this. I have yet to find what is the source of the corrupted images.

**Comment by un1versal** [comment]
Ive experienced this once or twice with 4.3.1 some SVN build and up to 4.3.2 so this isnt 4.3.2 specific.

What happened here last time this issue appeared was the large icons in the active theme somehow got corrupted. The coresmall icons remained OK though, weird it was only the toolbar ones.

Why that happened Ive no idea. At the time, I was testing recent theme changing fixes **after** #1542 and #1541 were merged had to restart KVIrc after changing themes a great deal of times.

Always Linux though.

**Comment by un1versal** [comment]
This happened again yesterday, seems if you change themes a few times in a row seems to trigger this, I should have grabbed a screenshot of it last night...

**Comment by un1versal** [comment]
#1314  #1645 where closed since this is the original report and still applies. So we keep this and close the others.

**Comment by un1versal** [comment]
Also **Icon corruption bug** only happens to the **big icons**. the small icons survive whatever #1645, #1314, and this reports cause is.

:warning: Changed priority of report due to multiple reports and how many times this has happened to myself alone. It renders KVIrc unusable so this is beyond normal.

**Comment by Stanzilla** [comment]
Just figured out when this happens, it's when you had icons saved with your theme. I always did that and now that I switched my theme to not have icons saved with it, everything shows up right.

**Comment by un1versal** [comment]
> Just figured out when this happens, it's when you had icons saved with your theme. I always did that and now that I switched my theme to not have icons saved with it, everything shows up right.

Not exclusively, but yes, it can aslo happen then.

**Comment by un1versal** [comment]
I just duplicated this 4 times.... most of targe icons get corrupted on theme save.
![capture](https://cloud.githubusercontent.com/assets/3521959/12223044/66648268-b7c4-11e5-958b-d58a5c68fd64.PNG)

Shows small icons because they arent corrupt.. any of them...

when opening the containing folder you have

![capture](https://cloud.githubusercontent.com/assets/3521959/12223049/845574b2-b7c4-11e5-8937-9d135ead50e8.PNG)

All the purple ones are dead.

**Comment by wodim** [comment]
You mean they aren't well copied?

**Comment by un1versal** [comment]
> You mean they aren't well copied?

If you been paying attention, it means they are dead, corrupted, gone, unusable, unreadable never to come back again.

Not being all copied implies some werent copied, thats not what happens here, they do get all copied but put through some random blender that makes them useless.

**Comment by staticfox** [comment]
This is probably resolved in an upcoming commit

**Comment by wodim** [comment]
I can't repro this. It certainly has happened to me in the past, but I can't repro it anymore. Can someone tell me how can I repro it?

**Comment by wodim** [comment]
This is thought to be fixed.
