### ISSUE TITLE
Find a way to avoid default scripts from breaking when upgrading

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1310]
**Reported by KodaK on 29 Jul 2012 01:29:12 UTC**
In version 4.2.0 Is needed to '''Restore default scripts''' to let it work normal, it looks like scripts on version 4.2.0 are FAILED; Because right-click popup isnt working and double-click on URL links isnt working!!!

Please fix in new version

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1310

**Comment by DarthGandalf** [comment]
**Comment by ambossarm on 29 Jul 2012 01:32:41**
as "restore default script" worked, the script in 4.2 is working, just the updating from older versions fail :/

**Comment by DarthGandalf** [comment]
**Comment by wodim on 30 Jul 2012 21:39:43**
Not an actual error in scripts, yet something we have to resolve.

---

Summary: Scripts Error → Find a way to avoid default scripts from breaking when upgrading
Version: 4.2.0 Equilibrium → 4.3.1 Aria

**Comment by un1versal** [comment]
Cant find any way to dup this in current builds...

The issue we have is when new entries and features are added to these, any existing users that upgrade builds will not get these updates. But that imo is not an issue related to this report.
