### ISSUE TITLE
Custom Emoticons smaller then before after upgrading from 4.0.4 to 4.2.0

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1311]
**Reported by icep on 31 Jul 2012 17:49:22 UTC**
I recently upgraded my KVIrc installation from 4.0.4 to 4.2.0. Now our custom emoticons we use in chat are smaller than before. Our custom icon are not square, but have more width than height (for instance 60x20). The are now scaled down so they fit into a square, this makes the emoticons almost unrecognizable. Could we please get the old behavior back please, in which the icons were only scaled by the vertical axis?

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1311

**Comment by un1versal** [comment]
if this is still and issue in current build please reopen, cant see any issues with this.
