### ISSUE TITLE
Ctrl+Tab sloppy under Windows

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1313]
**Reported by tedych on 07 Aug 2012 10:14:47 UTC**
Ctrl+Tab to switch between channels/console subwindows has always been very sloppy for me, under Windows 7 Ent x64. 4.0.4 first, then 4.2.0 Equilibrium.
About 30% of the cases it doesn't really catch and I noticed the Ctrl has to be hold some more time for it to work. Also switching this way is very slow, it switches the windows after about 1/3 to 1/2 of the second. Maybe this has something to do with the problem.
Definitely the feel of Ctrl+Tab is far from that of other Win32 apps that are 'native'. Maybe it is a Qt issue.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1313

**Comment by un1versal** [comment]
fixed by https://github.com/kvirc/KVIrc/commit/c227da04490d9097a4e99c0f48139d363bfca73d
