### ISSUE TITLE
Configure Theme - Text - Message colors - Icon change menu corrupt

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1314]
**Reported by tedych on 18 Aug 2012 11:42:01 UTC**
Windows 7 Ent. 64 bit. KVirc 4.2.0.
I just noticed that there was no icon for the channel message when my nick was highilghted and decided to assign an icon to that.
Settings - Configure theme... - Text - Message colors. There I select a line and try to change the icon from the small button down.
A corrupted menu with one and a half choice appears. The half is on the same line half visible, numbered 1 and 2..
I'm not sure if this is a latent bug because this is the first time I've been trying to change icons.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1314

**Comment by DarthGandalf** [comment]
**Modified by tedych on 18 Aug 2012 11:44:05**
Summary: Configure Theme - Text - Message colors - Icon change menu corrupted → Configure Theme - Text - Message colors - Icon change menu corrupt

**Comment by DarthGandalf** [comment]
**Modified by Visitor_099 on 19 Jan 2013 13:44:24**
Component: Core → GUI

**Comment by un1versal** [comment]
I may have accidentally seen this issue for the first time yesterday, current master compile, more testing required.

**Comment by heinrich5991** [comment]
Perhaps I have a similar bug. When I open the icon menu mentioned above, it shows me exactly zero choices, although the messages in the various channels I'm in _do_ have icons.

**Comment by un1versal** [comment]
Duplicate reports #1309 #1645 closing this.
