### ISSUE TITLE
fakelag aka text being sent very slowly

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1316]
**Reported by Cronus on 20 Aug 2012 05:25:26 UTC**
I've noticed since i upgraded to this latest release of kvirc. That whenever i send a larger amount of text (10+ lines) to my irc server, that it is sent very slowly, before if i sent even 100 lines it would all be sent instantly, and be fine. Now it sends it very slowly, over several seconds in some cases a minute.  Is this something new? or just activated in recent versions? I've never had this happen previously. and I know on other clients this is not an issue. (to rule out my irc server being the problem)

Any insight into this would be greatly appreciated!

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1316

**Comment by DarthGandalf** [comment]
**Comment by Cronus on 10 Sep 2012 06:05:13**
I hate to bump this, but this is getting increasingly annoying. Being an oper on my network and others, I do send text faster than normal users. Is there anyway to disable this?  I just tried to send a mass command to my services, and it took 20+ seconds to send 15 commands.

**Comment by DarthGandalf** [comment]
**Comment by Visitor_099 on 19 Jan 2013 12:45:18**
If you paste a large amount of lines in the input box, KVIrc should automatically switch to commandline mode, where you can do ctrl + enter to send all your text at once. You can also trigger that mode by doing ctrl + enter.

I just tested this on a fresh config and it works.

**Comment by DarthGandalf** [comment]
**Comment by Visitor_099 on 19 Jan 2013 13:36:40**
Try with a fresh config and report back if it doesn't work?

**Comment by pragmaware** [comment]
You possibly have the "Limit outgoing traffic per connection" option set.
That slows down messages to avoid flooding the server.
