### ISSUE TITLE
Configuration files not in $HOME/.config/KVIrc

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1318]
**Reported by kartagis on 27 Aug 2012 19:12:06 UTC**
Hi,

I've obtained 4.3.1 from SVN, compiled it, and realised that its configuration files don't reside in $HOME/.config/KVIrc anymore, but the directories are in $HOME. I'm guessing this is a bug, hence, well, the ticket.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1318

**Comment by DarthGandalf** [comment]
**Comment by TheRipper on 28 Aug 2012 05:18:43**
Search for your kvirc4 config file (I believe $HOME/kvirc4.ini or so) and change 

```
LocalKvircDirectory=<your desired path here>
```

**Comment by DarthGandalf** [comment]
**Comment by kartagis on 28 Aug 2012 06:46:43**
Hi,

It would be impossible to do this, as these files/directories don't get created unless kvirc is started the first time.

**Comment by un1versal** [comment]
I recently found in current 4.3.2 that some settings ARE NOT being re-written to the config files which seems to be very odd and I somehow feel this is a little related., requires more investigation.

**Comment by un1versal** [comment]
Cannot confirm this with current builds or any builds Ive ever done and works as expected, KVIrc once ran first time it creates a KVIrc folder in $HOME/.config/ without fail.
