### ISSUE TITLE
KVIRC 100%CPU

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1320]
**Reported by Caterpillar on 01 Sep 2012 08:46:39 UTC**
while using KDE desktop enviroment with Oxygen as style in KDE settings and QTCurve in GTK applications. Make a substitution: change both of them into Clearlooks, then get back to older settings. Then KVirc will start using 100% cpu

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1320

**Comment by DarthGandalf** [comment]
**Comment by Caterpillar on 01 Sep 2012 08:47:01**
Fedora 17
KDE 4.8.5

**Comment by DarthGandalf** [comment]
**Modified by nucleo on 11 Sep 2012 19:43:03**

**Comment by pragmaware** [comment]
Probably a bug in the theming engine.
Might be fixed with recent KDE version.
Please reopen if still reproduceable.
