### ISSUE TITLE
Channel content disappears in small screen

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1323]
**Reported by Morkovich on 15 Sep 2012 00:14:49 UTC**
I already mentioned this in ticket https://svn.kvirc.de/kvirc/ticket/1283

But i'll start a new one (as requested) if this has already been resolved in a newer version i'm sorry ;) .

All channel content disappears when the window is smaller then the timestamp. In v4.0.4 the content was wrapped and started on the new line on a fixed position... this has been changed (i'm testing 4.1.3r6140 and 4.2.0r6190) to the size of the timestamp. As i have a big timestamp (like [2012-04-11T18:19:11]) there is just a small space for content. I would like to be able to set this space independently from the timestamp (but this may belong in a feature request).

I found setting Theme Preferences>Output>Features>Use line wrap margin, where i can disable the margin for linewrap (this works for every screen bigger then the timestamp), but when i uncheck this option and make the screen smaller then the timestamp the content disappears (no wrap within the timestamp).

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1323

**Comment by un1versal** [comment]
Confirmed in current builds, but since this is a really really unlikely edge case Ive also change priority to low
