### ISSUE TITLE
KVIrc breaks on Windows 7 when doing scripting

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1329]
**Reported by prole92 on 11 Oct 2012 09:07:21 UTC**
Hi there, I have a problem with KVIrc 4.2.0 Equilibrium... Whenewher I try to write some code in scripting area the KVIrc just breaks without any warnings or messages... It just disappears from process list... The bug happens when I try to write something but not if scripting windows just hangs opened. The operating system I'm using is Windows 7

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1329

**Comment by pragmaware** [comment]
Possibly fixed in recent builds.
If it happens again please reopen the issue.
