### ISSUE TITLE
problem with cut-and-paste highlighting UTF-8 text

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1332]
**Reported by kb3cs on 24 Oct 2012 00:22:47 UTC**
when selecting text in the following line, the end of the highlighted jumps to the right, making it impossible to select only the arabic chars:

[23:34] Z-xoX-lOvE [~z-xox-lov@unaffiliated/z-xox-love] has left #KVIrc: " في بعض الاحيان نفقد انفسنا وفي بعض الاحيان نفض احبابنا لكن من الصعب جدا ان ترى من فقده لا يكترث لامرك ابدا"

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1332

**Comment by un1versal** [comment]
Can confirm even with a monospaced font... 

After testing seems related and probably same issue as https://github.com/kvirc/KVIrc/issues/1665

**Comment by pragmaware** [comment]
Text with ligatures is problematic.
A=لك  
is the version with ligature of
B+C= ل ك
and it's easy to see that with of A != width of B+C.
This breaks both KviIrcView and KviInputEditor algorithms. We should probably take care of never splitting ligature components in separate pieces... but that would require rethinking the algorithms completly.
Arabic text is also right to left, something the KviIrcView and KviInputEditor don't take into account. 
Honestly I don't exactly know how to fix it. We'd need advice from someone experienced in implementing RTL/Ligature support in UI programs...

**Comment by ctrlaltca** [comment]
We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix and report if this issue is still present. Thank you
