### ISSUE TITLE
PATCH for not working DCC SSL sends

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1341]
**Reported by htozehizzo on 24 Nov 2012 14:54:13 UTC**
secure sends will fail either right at the start or after a few kbs.
The issue highly depends on the OS, and is caused most likely by not proper or missing ssl_error handlin within the ssl_read accessing threads: 
https://svn.kvirc.de/kvirc/browser/trunk/kvirc/src/modules/dcc/DccFileTransfer.cpp sendack() / Run()

secure sends from a windows kvirc to a linux kvirc work (more or less at least), same for linux to linux. The biggest issues are when securely sending to a windows kvirc from windows and iirc also from linux kvirc to win kvirc, hence its the ssl_read implementation thats probably causing the issue.

sidenote: Lowering the packetsize to 1/4K(i dont remember anymore which one of both, 1K or 4K) fixes it, but it will give very very very bad speeds (under windows and partially under linux) due ssl_write not waiting to fill up the 16K ssl_Write buffer but instead sending every packet right away which causes a great speed penalty, 16K should be the way to go.

If you want to reproduce this bug, just try to securely dcc send yourself a file.

This ticket is a dupe of ticket 1306, just in a way more detailed way.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1341

**Comment by DarthGandalf** [comment]
**Comment by htozehizzo on 18 Mar 2013 01:09:16**
As already stated earlier, ssl errors need to be properly handled, proposed fix:

DccFileTransfer.cpp:
line 471 ~:
if (!m_pSSL && !handleInvalidSocketRead(readLen))
 break;
ssl transfers will be handled in the switch element before and bail out of the for loop

plus in general add this to all ssl error switches:
                            switch(m_pSSL->getProtocolError(readLen))
                            {

```
                            case KviSSL::ZeroReturn:
                                readLen = 0;
                            break;
                            case KviSSL::Success:
                            case KviSSL::WantRead:
                            case KviSSL::WantWrite:
```

you simply forgot to add the case KviSSL::Succes: 

sends might still hickup, you'd have to fixup the sendack routine by the same principle as formerly mentioned - proper ssl error handling. Dont just close sockets on ret -1 when on ssl, since ret -1 doesnt equal = serious error. You can pretty much neglect them if they are ssl_want_write/want_read or success on nonblockin sockets as long you keep polling for socketdata in general.
This will fix up dcc ssl sends, I tested it and it worked fine (same high speeds as without ssl).
While your at change:
#define KVI_DCC_RECV_BLOCK_SIZE 8192
#define KVI_DCC_RECV_75PERCENTOF_BLOCK_SIZE 6150
to
#define KVI_DCC_RECV_BLOCK_SIZE 16384
#define KVI_DCC_RECV_75PERCENTOF_BLOCK_SIZE 12280

Best regards
sanchez!

---

Summary: secure dcc send not working properly, due inproper ssl_error handling withing the ssl_read()  accessing function [OS dependent issue] → PATCH for not working DCC SSL sends
Version: 4.2.0 Equilibrium → 4.3.1 Aria

**Comment by DarthGandalf** [comment]
**Comment by htozehizzo on 18 Mar 2013 21:56:19**
Complete .diff file: http://pastebin.com/dBDmkVmB
verified working for different people on windows.

todo: wrap ssl error zero return and check eventually against EAGAIN etc to make sure only remotely closed connections also get localy closed (not every zero return means remote connection got also closed :) )

sanchez

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 13 Oct 2013 17:31:11**
I suppose this has been already fixed by r6323?

**Comment by un1versal** [comment]
I dont see any issues with SSL DCC under any circumstances Both Linux/Windows

With exception for https://github.com/kvirc/KVIrc/issues/1447 Im not aware of any other issues.

**Comment by ghost** [comment]
This was patched in a couple of years ago and is currently working.

**Comment by un1versal** [comment]
thx
