### ISSUE TITLE
DCC over proxy

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1343]
**Reported by andypower on 26 Nov 2012 15:23:06 UTC**
It is possible to support the DCC over proxy connection?

Thank you.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1343

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 01 Jan 2015 21:47:52**
Version: 4.2.0 Equilibrium → 4.3.1 Aria

**Comment by un1versal** [comment]
I think this works anyway, at least it seem to work, anyone care to confirm?

**Comment by DarthGandalf** [comment]
I'd instead remove support for DCC altogether :)

**Comment by un1versal** [comment]
> I'd instead remove support for DCC altogether :)

and find a new client. 

This isnt ZNC, which decides to remove features clients supports :tongue: wodim still foaming in the mouth about that :grinning:

**Comment by un1versal** [comment]
afaik this works over any connection, so closing here... If anyone disagrees feel free to post your findings and reopen or ask to reopen.

**Comment by Seeder101** [comment]
Hi 
I've just recently started to use proxy with DCC and unfortunately it doesn't work with all connections, it works ok with IRC in general but not with DCC or extended DCC, when running wireshark it still leaks to the isp while downloading stuff also when downloading it tells me that it's using my localnetwork ip + isp ip 
I'm using Fedora 30 with KVIrc 5.0.0 with SOCKSV5 proxy through SSH tunneling

**Comment by Seeder101** [comment]
the funny thing is that when I use proxychains with kvirc it works flawlessly "[TRANSFER 5]: Local end is 127.0.0.1:PORT" when checking wireshark, it doesn't leak anything and go through the proxy
