### ISSUE TITLE
KVIRC and Python27 64 Bit Causes Crash

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1354]
**Reported by rfliam on 27 Jan 2013 20:36:22 UTC**
Took me a bit to sort through this one but here it is to reproduce:

Windows 7 64bit
Python 2.7.3 64bit
Kvirc (win32)
/python.load

-> Immediate program exit.

Not sure how to "fix" this, but a check on the compiled target of python might do it. Alternatively it would be worthwhile to document that kvirc requires a 32 bit python install.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1354

**Comment by Dessa** [comment]
it is already documented, closing.
