### ISSUE TITLE
Find better system tray icons for KDE (was: System tray icon is always grayed out)

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1358]
**Reported by PaulW2U on 11 Feb 2013 16:56:05 UTC**

> ''Revision #6313 restored the system tray icon to KDE bit it is always grayed out, at least in Kubuntu 13.04 which is the only KDE distribution that I currently have available.''

We need better icons for KDE system tray, by now someone (CtrlAltCa?) has uploaded greyscale icons that may confuse some users, thinking they are disabled.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1358

**Comment by DarthGandalf** [comment]
**Modified by PaulW2U on 11 Feb 2013 17:09:06**
Milestone: none → Review the log engine

**Comment by DarthGandalf** [comment]
**Comment by wodim on 13 Feb 2013 17:25:22**
It is sort of intended, we need new icons to match the ones that KDE uses; sorry but I'll edit this ticket a little bit, thanks for the report

---

Component: Core → GUI
Milestone: Review the log engine → none
Summary: System tray icon on Kubuntu 13.04 is always grayed out → Find better system tray icons for KDE (was: System tray icon is always grayed out)
Description:

``` diff
--- 
+++ 
@@ -1 +1,3 @@
-Revision #6313 restored the system tray icon to KDE bit it is always grayed out, at least in Kubuntu 13.04 which is the only KDE distribution that I currently have available.
+> ''Revision #6313 restored the system tray icon to KDE bit it is always grayed out, at least in Kubuntu 13.04 which is the only KDE distribution that I currently have available.''
+
+We need better icons for KDE system tray, by now someone (CtrlAltCa?) has uploaded greyscale icons that may confuse some users, thinking they are disabled.

```

**Comment by un1versal** [comment]
I dont use KDE but is this still an issue? what icons specifically are used?

**Comment by un1versal** [comment]
@DarthGandalf you use KDE? Can you elaborate on this? 
Screenshots would be helpful

If so Ill see what can be done icon side

**Comment by ctrlaltca** [comment]
When KDE4 started following MacOSX on removing colors from tray icons, a similar change was checked in by me in https://github.com/kvirc/KVIrc/commit/2bba9b4665b992ce10d11ad356c91e4fb90f6a30
If this is considered confusing (i never liked it, too), just revert that change.

**Comment by un1versal** [comment]
+1 for reverting then

**Comment by DarthGandalf** [comment]
I never saw KDE4 following OSX... Of course, colored icon is better than gray one.

@ctrlaltca I don't know what that change did, but I still see pink icon in tray.

**Comment by ctrlaltca** [comment]
Let me clarify:
OSX's tray icons are black, so most third party software when run on this OS uses monochrome icons, too, to avoid the user felling the icon "out of place".
Around KDE 4.4, the default theme (oxygen, iirc) switched from colored tray icons to white/shades of gray icons.

Commit https://github.com/kvirc/KVIrc/commit/2bba9b4665b992ce10d11ad356c91e4fb90f6a30 adds a set of kvi_dock_mono\* icons and uses them instead of the colored ones if `defined(COMPILE_KDE_SUPPORT) || defined(COMPILE_ON_MAC)`, so reverting that commit will restore the use of colored icons for those platforms.

**Comment by un1versal** [comment]
its being worked on https://github.com/kvirc/KVIrc/issues/1840

since this was on purpose its not a bug per say so since im working on them ill do this as a feature request
