### ISSUE TITLE
/list output saving doesn't work on Windows

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1359]
**Reported by wodim on 13 Feb 2013 17:20:35 UTC**
/list output saving doesn't work on Windows, no "Save as" dialog appears. Tested on Linux, it works both with KDE support enabled or disabled

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1359

**Comment by VFiber** [comment]
It works with KVIrc Aria 4.3.2, revision: git-5252-gb6f5cd5, sources date: 20141230, built on: 2015-08-31 23:26:30 UTC, please test again.

**Comment by un1versal** [comment]
Yes current builds from master this works fully.

If no one has any objections this can be closed.
