### ISSUE TITLE
/away does not work when default away message is blank

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1360]
**Reported by wodim on 13 Feb 2013 17:22:03 UTC**
When default away message is blank, KVIrc supposedly sends a "AWAY :" message to the server, which disables away mode, so it is not possible to enable away by any GUI means (menu, systray...)

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1360

**Comment by un1versal** [comment]
IMO this is broken again

if you disable AWAY message with  `/option boolUseAwayMessage 0` and then try to run `/away ""` this will not work so you actually need to add a space `/away " "`
