### ISSUE TITLE
Ability to select encryption on SASL authentication

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1369]
**Reported by Obi_Wan on 07 Mar 2013 11:04:53 UTC**
I think it would be best if there would be an ability to select which encryption should be used on SASL authentication. For example:
- AUTO (let KVIrc decide)
- Blowfish
- PLAIN

The reason is that there still exist some IRC authentication services which would only understand plain SASL authentication and would abort with blowfish. Currently KVIrc seems to always do blowfish if it is compiled with SSL.

Thanks.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1369

**Comment by DarthGandalf** [comment]
**Modified by Obi_Wan on 07 Mar 2013 11:06:50**

**Comment by DarthGandalf** [comment]
**Comment by k_sze on 11 Feb 2014 01:45:11**
This ticket should be more important now because Freenode has disabled dh-blowfish since the beginning of February and many KVirc users can no longer use SASL with Freenode.

---

Version: 4.2.0 Equilibrium → 4.3.1 Aria

**Comment by DarthGandalf** [comment]
**Comment by wodim on 19 Aug 2014 22:26:35**
Atheme has decided to stop supporting Blowfish: https://github.com/atheme/atheme/commit/15f6d84bdbb8ecd6b34ffece1eec5adadc216c2c

This means that, probably, networks will follow.

**Comment by DarthGandalf** [comment]
**Comment by wodim on 23 Nov 2014 10:18:31**
Someone on IRC:

11:00:27 < Mikaela> I would like to comment on https://svn.kvirc.de/kvirc/ticket/1369 that I am on 7 networks where SASL BLOWFISH is unsupported, because they are running Atheme 7.2.0+

11:01:42 < Mikaela> The register link gives Not found error for me. The networks are: hackint, entropynet, piratenet, freenode testnet, yolo-swag, athemenet, interlinked and I have also heard chatspike users complaining even if their Atheme is 7.1.

**Comment by IceN9ne** [comment]
There's currently only one choice for SASL authentication since BLOWFISH was removed.
