### ISSUE TITLE
Rework of "Paste last log"

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1381]
**Reported by ambossarm on 25 Apr 2013 20:59:18 UTC**
The paste of the last log does not work on channels with a - in the name, it could be that this is caused by the filename of the logfile. kvirc-de is kvirc%2dde, so the - is urlencoded with %2d.

Add options to the GUI to manage which type of messages paste (mode changes, joins/parts, etc)

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1381

**Comment by DarthGandalf** [comment]
**Comment by wodim on 07 May 2013 23:13:18**
pasting of lastlogs actually sucks, it needs to be rewritten since it, for example, assumes . is the date parts separator, which is the default but may be changed by the user

---

Summary: Pastelaslog does not work on channels with - → Paste lastlog does not work on channels with -

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 05 Jan 2015 15:02:57**
Summary: Paste lastlog does not work on channels with - → Rework of "Paste last log"
Type: Bug → Feature request
Description:

``` diff
--- 
+++ 
@@ -1 +1,3 @@
-The paste of the last log does not work on channels with a - in the name, it could be that this is caused by the filename of the logfile. kvirc-de is kvirc%2dde, so the - is urlencoded with %2d.
+The paste of the last log does not work on channels with a - in the name, it could be that this is caused by the filename of the logfile. kvirc-de is kvirc%2dde, so the - is urlencoded with %2d.
+
+Add options to the GUI to manage which type of messages paste (mode changes, joins/parts, etc)

```

**Comment by CyberShadow** [comment]
Works for me, possibly fixed by https://github.com/kvirc/KVIrc/pull/2050

**Comment by un1versal** [comment]
excellent consider adding fixes #1381 to your commit msg on #2050 Im inclined to believe this issue would have fixed itself but who knows.

**Comment by CyberShadow** [comment]
BTW, what's going on in this issue? It started with a bug report (- not working for log loading) and turned into an unrelated feature request ("Add options to the GUI to manage which type of messages paste")?

**Comment by un1versal** [comment]
its never been a bug report looking at the labeling/unlabeling history above :mask: 

DarthGandalf added C: Core P: Normal T: Feature request V: 4.3.1 Aria labels on 26 Jul 2015
Closed
Control output of "Paste last channel log" #1395
Closed
@un1versal un1versal removed the 4.3.2 Aria label on 3 Nov 2015
@un1versal un1versal removed the Prio: Normal label on 13 Apr
un1versal added Status ■ Works for Me and removed Status ■ Works for Me labels 10 minutes ago

edit I take that back it was a bug report in SVN

**Comment by CyberShadow** [comment]
> its never been a bug report looking at the labeling/unlabeling history above 😷

Yes it was?

> Type: Bug → Feature request

**Comment by un1versal** [comment]
> edit I take that back it was a bug report in SVN

edited ticket when I saw

It was before moving to git so idk what their reasons were, but if its a bug relabel it I honestly dont have a clew :)

---
