### ISSUE TITLE
Notify list is notifying for the wrong people

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1392]
**Reported by Andrio on 12 Jun 2013 10:08:19 UTC**
I frequently visit several IRC networks, and I've had reason to add acquaintances to KVIrc's notify list. However, sometimes I'm getting notify list alerts from people whom I didn't add to the list, but who have the same nicknames as people I added.

For example, I added the mask Emily!_Emma@operations.mil.nf to my notify list, but am being alerted with the mask Emily!~mirioki@191e2813.141bd0a1.wavecable.com (who is on a different network and with whom I have no common channels).
I'm also being alerted by psuedo-bots with services._ masks.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1392

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 22 Jul 2013 16:26:44**
Depending on the server software, kvirc could be using a different method to populate the notify list.
Please have a read at http://kvirc.net/doc/doc_notify_list.html that explains how these methods work.
I suppose kvirc is using the "stupid ISON method" and missing to correctly check the user mask.
You can try to tune the settings as Configure KVIrc -> IRC -> Tools -> Contacts, but if the server only supports the ISON method we won't be able to fix your problem.

**Comment by pragmaware** [comment]
As explained by ctrlaltca this may be due to the notify list method configuration.
If it's not the please include the relevant socketspy output.
