### ISSUE TITLE
Store encryption keys and give options for Mircryption and fish

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1393]
**Reported by Meliorator on 12 Jun 2013 17:33:53 UTC**
I am would ideally like there to be a feature implemented to store/recall the crypto keys set in the native KVIrc encryption key interface. However, if it is any simpler, implemeting some events to dd/remove/change/enable/disable/etc would make it possible to implement this via a KVIrc script.

I also need to be able to adjust the encryption paramters (ebc,cbc,etc) for Mircryption and fish.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1393

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 22 Jul 2013 16:12:15**
Cryption: https://svn.kvirc.de/kvirc/browser/trunk/scripts/cryption/ is a script that should do exactly what you mean.

**Comment by DarthGandalf** [comment]
**Comment by Meliorator on 22 Jul 2013 19:08:30**
Replying to [comment:1 ctrlaltca]:

> Cryption: https://svn.kvirc.de/kvirc/browser/trunk/scripts/cryption/ is a script that should do exactly what you mean.
> The native encryption controls have no effect on this script.

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 23 Jul 2013 09:18:06**
Replying to [ticket:1393 Meliorator]:

> I am would ideally like there to be a feature implemented to store/recall the crypto keys set in the native KVIrc encryption key interface.
> The cryption script does exactly this: stores/recall the crypto keys set by the user for each window in kvirc in/from a config file.
> 
> However, if it is any simpler, implemeting some events to dd/remove/change/enable/disable/etc would make it possible to implement this via a KVIrc script.
> The cryption script uses the window.setCryptEngine method and binds to the OnChannelSync and OnQueryWindowCreated.
> 
> I also need to be able to adjust the encryption paramters (ebc,cbc,etc) for Mircryption and fish.
> use window.setCryptEngine

Replying to [comment:2 Meliorator]:

> The native encryption controls have no effect on this script.
> I don't get what you mean by "native encryption controls".

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 01 Jan 2015 21:47:38**
Version: 4.2.0 Equilibrium → 4.3.1 Aria

**Comment by IceN9ne** [comment]
This is 100% doable currently from KVS.  Set keys in events `OnChannelWindowCreated`, `OnQueryWindowCreated` and `OnDCCChatWindowCreated`.  Use `window.setCryptEngine` to set/remove keys and set the cipher method.

Your choice between blowfish-cbc and blowfish-ecb can be chosen by how you prefix the key. `old:<key>` and `ecb:<key>` will cause Mircryption to use blowfish-ecb and `cbc:` or no prefix at all will cause it to use blowfish-cbc.

For storing/retrieving keys, you can create your own aliases (maybe `/setkey` and `/delkey`) to call `window.setCryptEngine` on the appropriate window and store/retrieve the keys from a file.
