### ISSUE TITLE
Connect to server

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1397]
**Reported by kartagis on 17 Jul 2013 07:35:09 UTC**
Hi,

IMHO, Servers dialog should close itself once user clicks on Connect now and connects successfully.

Regards,
K.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1397

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 22 Jul 2013 16:08:01**
I suppose this would worry people used to connect to more than one server at a time (open the dialog, connect to first server, reopen the dialog, re-scroll the list, connect to the second server, ...).

Anyway, we could implement an option "Close the connection dialog after a successfull connection", but there's a problem since there's no way for the "server dialog" itself to know if (and when) a connection has been completed successfully; it just knows when the user presses the "connect" button. That's a good approximation in my opinion.

As an alternative, we could introduce a function that closes a specific option dialog and than you could bind this to the "OnIrc" event using one line of kvs.

I'd go the the option, any comment?

**Comment by pragmaware** [comment]
Implemented options.close
Use
   options.close OptionsWidget_servers; 
inside a handler for OnIrc.
