### ISSUE TITLE
Rework $str.grep

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1404]
**Reported by ReggX on 13 Aug 2013 17:10:13 UTC**

== [This bug requires both, code and documentation fixes] ==

The documentation for $str.grep states the following:

```
If the flag 'p' is specified the returned array will contain at its index 0 the text that matched the full pattern, and in the following array indexes the captured texts that matched each parenthesized subpattern.
```

Using the flag 'p', one encounters strange behaviour that diverges from the one documented.

Using grep(p) on a single string returns the index of the string AFTER the matched part. No index of when it starts or how long the matching part is.

Using grep(p) on an array of multiple strings returns an array of matching parts. No index where the part matches in the string or on which the string the match applies.

```
//KVS code to illustrate bug
echo $str.grep("[C-H]:\\\\","123C:\\Windows\\System32",rp);

%s[0] = "no match";
%s[1] = "C:\\Windows\\System32"; 
%s[2] = "no match";
%s[3] = "C:\\Windows\\System32"; 
%s[4] = "I:\\Windows\\System32"; 

echo $str.grep("[C-H]:\\\\",%s,rp);

```

---

Secondly, the code for $str.grep in libkvistr reveals an undocumented flag 'x', as seen in Line 1558

```
bool bExcludeCompleteMatch = szFlags.indexOf('x',0,Qt::CaseInsensitive) != -1;
```

---

I conclude that $str.grep needs a major moverhaul.

''Thanks to #kvirc user road|runner for bringing this to my attention.''

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1404

**Comment by pragmaware** [comment]
The p and x options are a hack... they were added to make a script work
but they don't really belong to $str.grep(). The feature should be moved
to another function (say $str.extract() or something similar).
I have removed the documentation for the two options (the code is still
there in case someone relies on it, but it will be removed in some years).
If you need $str.extract() please open a ticket and I will add it :)
