### ISSUE TITLE
kvirc crashes when editing a network

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1409]
**Reported by Fersure on 17 Aug 2013 18:55:37 UTC**
I installed kvirc and it crashed when I started editing a network.

Happened on both 4.2.0 and 4.3.1

Windows 7 Ultimate x64

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1409

**Comment by pragmaware** [comment]
Need a stack trace to reproduce it.
