### ISSUE TITLE
SASL authentication failed

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1413]
**Reported by Kult on 29 Aug 2013 16:09:31 UTC**
Having a $ in a nick password makes it impossible to authenticate on SASL.<br/>
Perhaps the issue could be the same with other special characters, but  it hasn't been tested.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1413

**Comment by DarthGandalf** [comment]
**Comment by ReggX on 29 Aug 2013 16:15:48**
I did a little digging in the code

```
kvilib/net/KviSASL.cpp
kernel/KviIrcConnection.cpp
```

Can we trust the encodeText() function to do the right encoding? Maybe we should notify the user that the encoding has to be set up correctly?

**Comment by un1versal** [comment]
I can confirm this with 4.3.2, its not encoding related no matter what its set to or what you set it too, special characters like $%/*& in password and sasl seem to cause trouble on login.

**Comment by pragmaware** [comment]
In theory $ is not a special character. Its 8-bit rappresentation should be the same in all encodings.
We should take a look at what is actually being sent to the server (via socket spy).

**Comment by un1versal** [comment]
its not just $ other like %£*& make this fail also.

**Comment by staticfox** [comment]
Cannot reproduce the issue...

KVIrc
`KVIrc Aria 4.9.2, revision: git-6376-ge4cecac-dirty, sources date: 20160102, built on: 2016-04-12 22:55:42 UTC`

Atheme Services git revision
`59ca306d8faf1b7a69a82e3d37bb3c751e680f13`

Charybdis git revision
`4f2b9a4fd1884852dfecf4855299787fe0553cc8`

**Comment by un1versal** [comment]
Self fixing bugs, nice. Will have to test this again then to see if anything to do with something else.

**Comment by staticfox** [comment]
Just tested on freenode..

`:asimov.freenode.net 903 * :SASL authentication successful`

Closing this unless someone can repro it in some other manner
