### ISSUE TITLE
python doc contain non-python (broken) example and other question

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1421]
**Reported by asl97 on 20 Sep 2013 23:43:36 UTC**
http://www.kvirc.net/doc/doc_python_and_kvs.html

```
Passing parameters to the python script

    python.begin("","Hello world!","Now I CAN",1,2,3)
    for(i=0;i<5;i++)
        kvirc.echo(aArgs,40)
    python.end
```

that is not python code, the ++ and -- operators don't exist in Python, the python way to do it is like this
(a direct version of the example above):

```
    python.begin("","Hello world!","Now I CAN",1,2,3)
    i = 0
    while i<5:
        kvirc.echo(aArgs[1])
        i+=1
    python.end

```

but using range is more efficient:

```
    python.begin("","Hello world!","Now I CAN",1,2,3)
    for l in range(0,5):
        kvirc.echo(aArgs[l])
    python.end

```

and maybe someone could put a note somewhere where it say that aArgs is a list

and one more question:

```
    %pippo = test
    %Pluto = 12345
    python.begin
    mypippo = kvirc.getLocal("pippo")
    mypippo += " rox"
    mypluto = kvirc.getGlobal("Pluto")
    mypluto += " rox"
    kvirc.setLocal("pippo",mypluto) # here
    kvirc.setGlobal("Pluto",mypippo) # and here
    python.end
    echo "\%pippo is" %pippo
    echo "\%Pluto is" %Pluto

```

why did someone swap the variable?
not only will it confusing when someone miss read it, there also no need to swap them, it should just be:

```
    kvirc.setLocal("pippo",mypippo)
    kvirc.setGlobal("Pluto",mypluto)
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1421

**Comment by SolarAquarion** [comment]
@universal i guess some more area for doc cleanup

**Comment by SolarAquarion** [comment]
@uNiversal i guess more stuff for doc cleanup

**Comment by SolarAquarion** [comment]
@universai i guess more stuff that can be a doc cleanup

**Comment by un1versal** [comment]
> @universai i guess more stuff that can be a doc cleanup

If you are volunteering, sure .... :smile: I dont really understand the topic enough in order to document or fix the documentation though.

I see https://github.com/kvirc/KVIrc/commit/14adfc54b4b946be6fa0e787d602bc732c2bf8b0 however.

**Comment by HelLViS69** [comment]
Il 07/set/2015 08:14, "uNiversaI" notifications@github.com ha scritto:

> > @universai i guess more stuff that can be a doc cleanup
> 
> If you are volunteering, sure .... I dont really understand the topic
> enough in order to document or fix the documentation though.

Create a milestone if trac didn't export the old "code cleanup and
documentation"

HelLViS69

**Comment by un1versal** [comment]
> enough in order to document or fix the documentation though.

Its already done in https://github.com/kvirc/KVIrc/commit/14adfc54b4b946be6fa0e787d602bc732c2bf8b0

and no I wouldnt have known where to do that either.

**Comment by un1versal** [comment]
Since the fix already been merged to master in https://github.com/kvirc/KVIrc/commit/14adfc54b4b946be6fa0e787d602bc732c2bf8b0 I think someone needs to trigger generation of new docs for KVIrc-www

I did something at https://github.com/kvirc/kvirc-www/pull/7 please check that

Once thats done this can be closed.
