### ISSUE TITLE
multicast + checkbox on the users feature.

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1426]
**Reported by innercircle on 01 Nov 2013 19:22:28 UTC**
i need  multicast feature badly as it's way tooo easy for one wrongdoer to spoil 100 people's fun on some chatrooms.

what i want is not only ignore them but also don't give them any food for thought, that is multicast feature.

in order to use it easyly, i dream about that there are a checkbox on every user's nickname. i will ignore them and don't send them any message if i enable his or her checkbox.
Best Regards.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1426

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 01 Jan 2015 21:47:13**
Version: 4.2.0 Equilibrium → 4.3.1 Aria

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 05 Jan 2015 00:18:08**
Milestone: Code cleanups and documentation → none

**Comment by pragmaware** [comment]
Can't really understand the request / not feasible.
