### ISSUE TITLE
KVIrc should define its window class name

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1458]
**Reported by dermoth on 24 Jan 2014 20:06:23 UTC**
I'm forced to use Windows at work, and KVIrc is a great client on it. I'm also using AutoClipX to enable select/middle-mouse copy/paste to applications that doesn't natively support it.

KVIrc on Windows supports copy-paste by itself, which is also working better than the AutoClipX hack. However the only way to blacklist the application, since the title often changes, is with the Window or Control Class Name (other similar copy-paste tools works the same way, using classes to identify whitelisted/blacklisted apps).

Unfortunately the name appears to be left to its default, QWidget, which is too generic and could easily match other applications. It would be great if you could change the application's Window Class name name so that it's unique, easily identifiable and doesn't change.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1458

**Comment by DarthGandalf** [comment]
**Comment by wodim on 01 Feb 2014 13:46:40**
This is a known limitation in Qt. It's currently reported as QTBUG-11487.

https://bugreports.qt-project.org/browse/QTBUG-11487

---

Version: 4.2.0 Equilibrium → 4.3.1 Aria

**Comment by pragmaware** [comment]
There is currently no way to do this without patching Qt :(
See https://wiki.qt.io/Qt_project_org_faq (search for "window class")
