### ISSUE TITLE
Weird bug with a very specific network

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1459]
**Reported by SoniEx2 on 10 Feb 2014 00:10:32 UTC**
I'm having a problem with KVIrc and Snoonet, here's how to reproduce it:
1. Connect to the network, any nick'll do.
2. Hit the disconnect button. Change the nickname field on the network settings.
3. Hit the connect button. ('''Not''' the Connect Now button)
4. Try to join a channel.

I'm not sure if this is a server bug or a client bug, and the IRCOps told me to post it here, so I'm posting it here...

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1459

**Comment by pragmaware** [comment]
I tried the procedure and it seems to work properly (or I can't figure out what actually should be wrong).
