### ISSUE TITLE
KVIrc doesn't like channel names ending with *

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1467]
**Reported by SoniEx2 on 16 Feb 2014 20:53:08 UTC**
I joined a network, made a channel ##trans\* (which's ok according to the RFC), and when I rightclicked the channel and did a /WHO, it didn't send the *.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1467

**Comment by pragmaware** [comment]
Can't reproduce it.
On freenode I have joined ##test_, did a /WHO ##test_ manually (or via popup) and it worked fine.

If you still reproduce it then please include the relavant socketspy output.
