### ISSUE TITLE
'Favorites' list in KVIrc

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1477]
**Reported by mhoes on 07 Feb 2015 09:22:43 UTC**
An editable list of your favorite servers and server/channels. Somewhat like the 'favorites' or 'bookmarks' lists in some browsers. So you can easily navigate to one of your top server/channels. 

Currently there is 'only' the 'most recently used list', which is not necessarily the same as your favorites, and 'Settings -> Configure Servers' which is a list of _all_ 'known' IRC servers out there.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1477

**Comment by un1versal** [comment]
updated as per https://github.com/kvirc/KVIrc/wiki#bugreport-ticket

Features are automatically reassigned to the the current development version.
