### ISSUE TITLE
Channel hopping via left channel treeview breaks when a channel is scrolled out of view

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1480]
**Reported by Omega on 28 Feb 2015 23:03:39 UTC**
Decrease the size of KVIrc's window until the left channel treeview gets a scrollbar, scroll away so that the current channel is no longer visible in the treeview, click on a new channel to activate, and then click on this channel again - KVIrc should then hop back to the original channel, but doesnt (the channel it hops to is wrong, sometimes you end up in a console window).

There also seems to be a similar problem where sometimes if you select a channel, scroll down so that it is no longer visible, then click on another channel, a completely different channel is activated  (possibly different from the one highlighted in the list, can't seem to recreate it consistently).

Looking into this.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1480

**Comment by DarthGandalf** [comment]
**Modified by Omega on 28 Feb 2015 23:04:01**
Owner: pragmaware → Omega Weapon

**Comment by DarthGandalf** [comment]
**Comment by Omega on 08 Mar 2015 23:07:41**
Spent many hours on this over a few days so far. The best I can say currently is that (for the first bug) KVIrc knows what is is doing - src/kvirc/ui/KviMdiManager.cpp KviMdiManager::processWindowStateChanged and KviMdiManager::focusPreviousTopChild pick the correct child window to activate (so subWindowList(QMdiArea::StackingOrder) is also returning a sensible list).

However after showAndActivate is called but before src/kvirc/ui/KviTreeWindowList.cpp KviTreeWindowListItemDelegate::paint starts getting called, the selected treelist item breaks - KviTreeWindowListItemDelegate::paint's 'treeWidget->currentItem() == item' demonstrates this. I'd like to say it is a Qt4 screwup but KVIrc is customising a lot of this. I haven't been able to understand some of the codeflow inside Qt4 too easily, not too sure what to do next to fight this.

**Comment by DarthGandalf** [comment]
**Comment by Omega on 05 Apr 2015 19:43:11**
I'm going to give up on this - I can't seem to get at a good tool to output all functions called that allows me to get at a concise list of what is going on between these two points (probably because C++ is too overcomplicated for its own good with all the class methods and inlining, and then all the irrelevant library function calls), and I don't really want to have a project understanding how Qt4's treeview is actually implemented.

The Qt5 build is heavily visually broken here, but it does appear to share this bug I think. Might be worth relooking at this when the Qt5 build is official.

**Comment by un1versal** [comment]
reassigned this to Omegaphil so its not forgotten.

However I can no longer duplicate this in current master 4.3.2 Linux 

MDI is gone now so this is likely fixed. closing for now and if anyone likes to reopen fell free.

**Comment by OmegaPhil** [comment]
Finally reached this - I've just upgraded to v4.9.1, and it looks like the channel hopping functionality has been removed - if you click more than once on a channel it doesn't hop to the previous one, so naturally the problem won't happen anymore. Was only a minorly useful feature so thats fine I guess.
