### ISSUE TITLE
KvIRC authentication error: Improper variable handling

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1486]
**Reported by jcdenton2k on 12 Jun 2015 22:08:01 UTC**
Downloaded from here:
http://kvirc.d00p.de/

Version:
4.3.1-r6445

**ERROR**
[KVS] Runtime Error: Call to undefined function 'account'
[KVS]   in script context "commandline::kvs", line 1, near character 31

**REPRODUCTION STEPS**
1 - Register an account on the irc.mordor.io IRC service run by Aaron Jones
https://github.com/aaronmdjones

2 - Use command:
/msg HostServ TAKE mordor/user/$account

**CAUSE**
Kvirc does something as stupid as interpret a $ as a variable to replace with in the message and there is no such 'account' variable in kvirc. try prefixing the $ with \ ?
Kvirc is interpreting untrusted arbitrary data, that is incredibly stupid and dangerous

**WORKAROUND**
Use this command instead:
/msg hostserv take mordor/user/\$account

**Thoughts**
KVIRC needs to update their code not to interpret $ as a variable and not to attempt to interpret untrusted arbitrary data.  The issue seems to be in the script "commandline::kvs" on line 1 near character 31.

Thank you for your time.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1486

**Comment by DarthGandalf** [comment]
**Comment by jcdenton2k on 12 Jun 2015 22:16:59**
Your SVN has issues as well..

Command that causes issue:  /msg hostserv take mordor/user/$account

Workaround:  /msg hostserv take mordor/user/\$account

**Comment by DarthGandalf** [comment]
**Comment by aaronmdjones on 12 Jun 2015 22:24:21**
As the person running the IRC network I can confirm this issue - KVIrc should not be interpreting all user messages by default.

E.g. in WeeChat (my client of choice), you have to prefix your message with the /eval command if you wish for it to interpret any special meaning in it.

That KVIrc does this by default is incredibly stupid, dangerous, and confusing to the user.

**Comment by DarthGandalf** [comment]
**Comment by SoulRaver on 13 Jun 2015 00:20:27**
I can confirm this issue.
Got exact this error trying the above mentioned command.

Something seems to get misinterpreted there.

Also I am worried about possible security issues if this is not resolved.

**Comment by pragmaware** [comment]
Use the "user-friendly" commandline mode and your variables won't be interpreted.
This is even in the FAQ.
