### ISSUE TITLE
Quiet ban list GUI stopped working on freenode

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#1487]
So the thing is that years ago you asked for quiet bans using the usual syntax

```
/mode #channel q
```

And freenode responded with the list of quiet bans in an awkward way: using the same numeric as bans. Now that changed, they have their own numeric, so that has to be fixed

**Comment by wodim** [comment]
Some day I will understand all the new labels.

**Comment by DarthGandalf** [comment]
The labels are just migrated from trac fields.

**Comment by xrogaan** [comment]
The quiet ban list for freenode is probably handled in [KviIrcServerParser::parseNumeric367](https://github.com/kvirc/KVIrc/blob/16d3c016112fac39e10c20a851bb4f229209840b/src/kvirc/sparser/KviIrcServerParser_numericHandlers.cpp#L729).
