### ISSUE TITLE
Remove Avatar

### ISSUE THREAD

**Issue by Stanzilla** [kvirc/KVIrc#1488]
I'm all for it, it was never adopted by any other client ever.

https://github.com/wodim/kvirc/commit/c7ab51736b7d680ffa9f0e957bbe332dee2e22f9
https://github.com/wodim/kvirc/commit/ce10bd7163fcf3a3149f62f38a35c7c7904138f3

**Comment by DarthGandalf** [comment]
ZNC has a module which sends avatar to kvirc.
http://wiki.znc.in/Kvirc

**Comment by pragmaware** [comment]
I like avatars! :D

**Comment by swarfega** [comment]
I use the avatar and would like to keep it. ZNC has support for this feature via a module as Darth says.

I vote to keep.

**Comment by HelLViS69** [comment]
Isn't there an option to disable it? Why remove?

HelLViS69

**Comment by swarfega** [comment]
There is and exactly.

**Comment by DarthGandalf** [comment]
I can say though, that the mechanism of transferring avatar should be changed from "magic hidden characters in realname + CTCP" to http://ircv3.net/specs/core/metadata-3.2.html

**Comment by ctrlaltca** [comment]
I saw the IRCv3.2 metadata specification, but actually it's supported by almost no server ( http://ircv3.net/software/servers.html ) and i don't see this situation changing soon. We can surely add support for it if the server has this capability.

**Comment by un1versal** [comment]
Dont like them dont use them and disable them, problem solved.

**Comment by HelLViS69** [comment]
Btw, are avatars still supported? what are those commits by @wodim ?

**Comment by wodim** [comment]
@HelLViS69 those are a fork I did for fun several years ago (only difference was that I removed avatars)

**Comment by un1versal** [comment]
Closing this, no one is obligated to use any features in KVIrc they dont like.
The majority have spoken also... :tongue:
