### ISSUE TITLE
Auto-join channel list gets cut off

### ISSUE THREAD

**Issue by Coldblackice** [kvirc/KVIrc#1500]
I've been wondering why not all of the channels from a server's auto-join list were opening. I thought maybe the config wasn't getting saved properly, even between program exits/restarts -- but nope, it's saving correctly. I think I've finally figured out the issue -- it appears there's a character limit to this auto-join channel list (in passing to the actual channel-join function, not the list variable itself).

I exported this auto-join list and determined where exactly it stops as far as channels opening -- precisely halfway through the name of _one_ of the channels -- suddenly it makes sense why I've been auto-joining an empty channel with just a few letters to its name.

Can this be addressed? It appears it's a KVIrc issue rather than the server's.

---

Running KVIrc 4.3.1 Aria x64 (4.3.1-r3cf0289) on Windows 7 x64

**Comment by xrogaan** [comment]
Here is how kvirc handle auto-join: https://github.com/kvirc/KVIrc/blob/master/src/kvirc/kernel/KviIrcConnection.cpp#L1921

It just send the whole list of channels to the server in one go. Now, sendFmtData truncate all that data to 510 bytes. If you have a very long list of channels (or very long channels names), some might be cut off at the end. But I am not knowledgeable enough in C++ to be sure of it.

**Comment by Coldblackice** [comment]
Aha! There it is. Darth Gandalf mentioned it's for IRC protocol (understandably).

I wondered about the possibility of having it loop, but then thought, if the channel list spills over the 510-byte limit, why not just split the remainder into another join line? There could even be a wait period of 1-2 seconds so as not to hit any flood/rate-limiting issues.
