### ISSUE TITLE
Port the http object to Qt5

### ISSUE THREAD

**Issue by pragmaware** [kvirc/KVIrc#1510]
Port the http object to Qt5. Currently it's commented out.

**Comment by DarthGandalf** [comment]
The same for src/modules/objects/KvsObject_ftp.cpp

src/kvirc/kernel/KviApplication.cpp and src/modules/my/Idle_x11.cpp don't do something in case of Qt5, but I can't say what exactly they don't do.
Also src/kvirc/ui/KviInputEditor.cpp mentions some missing feature.

**Comment by pragmaware** [comment]
Most of the stuff should be Qt5-aware now.
The only thing I couldn't figure out how to port is the IM listing popup in KviInputEditor.
I'm not even sure it's really important: someone really using an IM method should eventually look into this  and decide.
