### ISSUE TITLE
Installer is extremely slow on Windows, at least for the 4.3.1 dev versions

### ISSUE THREAD

**Issue by ekolis** [kvirc/KVIrc#1513]
Takes several minutes to load. Perhaps some sort of security thing with Windows?

**Comment by DarthGandalf** [comment]
Which exact installer are you talking about?
It's slow during which exact step?

**Comment by DarthGandalf** [comment]
Also what windows?

**Comment by swarfega** [comment]
Its fine for me. (Windows 10)

**Comment by wodim** [comment]
It probably is your system. You can use `resmon.exe`, Disk tab, to figure out what's going on.

**Comment by ekolis** [comment]
Windows 10. I was using this installer:

http://kvirc.d00p.de/files/KVIrc-4.3.1-r3cf0289-dev-x86_64-d00p.exe

It was slow when I first loaded it up; the UAC prompt took so long to appear that I thought it was completely blocked from running. I ran it a few more times, and a few minutes later the prompts started popping up one by one!

**Comment by wodim** [comment]
That's probably SmartScreen. No code from the installer is executed until after you hace accepted the UAC prompt.

**Comment by ekolis** [comment]
Hmm, what I'm saying it it takes a long time for the UAC prompt to even
appear, so long that I think the installer didn't even run when I
double-clicked it.

**Comment by DarthGandalf** [comment]
Installer has no control over when UAC prompt appears. So it's your system which makes UAC slow.

**Comment by ekolis** [comment]
Hmm, OK, thanks then. Wonder why it would only affect the KVIrc installer
and not other executables?

**Comment by wodim** [comment]
I told you to try and check `resmon.exe` and see what files were being accessed, if any.

**Comment by ekolis** [comment]
Oops, sorry, must have missed that. Oh well, if it's just my system it's
probably not a big deal anyway; how often do I need to reinstall KVIrc to
begin with?

**Comment by wodim** [comment]
Never... I guess.

**Comment by DarthGandalf** [comment]
Well, it's good to upgrade to a newer version from time to time.
