### ISSUE TITLE
Emoji rendering is iffy

### ISSUE THREAD

**Issue by justastranger** [kvirc/KVIrc#1514]
The input cursor becomes slightly misaligned every time an emoji is used, getting worse with every emoji.

![ss 2015-08-17 at 11 33 36](https://cloud.githubusercontent.com/assets/6827479/9310265/66ca796e-44d4-11e5-9799-cb11232532c0.png)

**Comment by wodim** [comment]
#527 #1241 etc

(Not implying it's a dupe since those are closed, but...)

**Comment by justastranger** [comment]
I'm bad at searching. Sorry.
In any case, this is happening on the 64-bit build of 4.3.1

**Comment by pragmaware** [comment]
The problem may be related to the fact that most emoji are rappresented by a surrogate pair. QChar supports only 16 bit unicode points and the actual KviInput implementation (but also all the other widgets that paint text) work directly on QChars. We should either add "manual" support for surrogate pairs or maybe try to use QTextLayout that might support them out of the box. Not an easy job either way though.

**Comment by pragmaware** [comment]
This might have been fixed in 90b4eef.
