### ISSUE TITLE
Make installation of language related stuff optional

### ISSUE THREAD

**Issue by Stanzilla** [kvirc/KVIrc#1517]
- [ ] Language files of the client itself
- [ ] Enchants spell checker itself
  - [ ] Enchants spell checker dictionary files for languages

**Comment by wodim** [comment]
First option is a no in my opinion.

Second option, cool.

Third option, meh.

**Comment by DarthGandalf** [comment]
Second option is useless as is. If any dictionary is installed, spell checker itself should exist too.

**Comment by Stanzilla** [comment]
Think of it as a suboption for 2, edited for clarity

**Comment by un1versal** [comment]
This sounds like an improvement or enhancement not a feature. So labelled as that.

@Stanzilla are you submitting a PR with your proposed changes?

**Comment by Stanzilla** [comment]
I've never worked with NSIS so I wasn't planning to, no.

**Comment by un1versal** [comment]
If you had your proposals as PR's maybe it be easier to evaluate the benefits/drawbacks and even possible implement some improvements.

**Comment by staticfox** [comment]
Considering two other devs already expressed disinterest in the idea, I don't see why forcing him to make a PR is a good idea. If the idea gets considered then I or alexey or Dessa can do it. Otherwise if the idea is leaning towards no then I don't see how turning words in to code will convince otherwise. I'm not saying no to this but I'd rather everyone think it through before we put effort in to this.

**Comment by un1versal** [comment]
Its not just a PR for this, clearly stanzilla has some thoughts and ideas on improving the installers defaults as its substantiated by his other requests, so if not for this, for the other requests (any of them) then.

IMO its a fair request and I encourage anyone to get involved and submit PRs and learn more about the things that they demonstrate interest for.

So we are clear Im in favour of anything that improves the user experience and first impressions.

Getting involved is a great thing, learning something new is definitely a good thing.
