### ISSUE TITLE
Integrated Gravatar support

### ISSUE THREAD

**Issue by swarfega** [kvirc/KVIrc#1521]
I would like to see the integration of Gravatar support. I have seen too many times where KVirc was unable to download someones avatar for whatever reason.

Adding this would resolve this issue.

**Comment by HelLViS69** [comment]
Il 26/ago/2015 13:59, "swarfega" notifications@github.com ha scritto:

> I would like to see the integration of Gravatar support. I have seen too
> many times where KVirc was unable to download someones avatar for whatever
> reason.

The only reason is that avatar are sent through DCC.. If you use an http
url there's no problem

But yeah, gravatar option is another option we could add

HelLViS69

**Comment by swarfega** [comment]
Currently it doesn't seem to be supported on 4.3.1.

 Avatar download failed for <random person> and url http://www.gravatar.com/avatar/c972c6f3de5db8ba6e5c3f81577a3232?s=512: Can't open file "E:\data\KVirc\Settings\avatars\http.www.gravatar.com_avatar_c972c6f3de5db8ba6e5c3f81577a3232_s=512" for writing

Presumably because theres no hard url to a file like random.jpg.

**Comment by wodim** [comment]
I think this is better scripted.

**Comment by swarfega** [comment]
Not all of us are script commandos :p

**Comment by un1versal** [comment]
Works in current nightlies now, closing
