### ISSUE TITLE
New smilies for core icon set.

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1525]
This is to **open a discussion** for the the possibility of including new smilies in the new icon set.
RE: https://github.com/kvirc/KVIrc/pull/1519#issuecomment-134776607

I'm willing in principle to do the graphical work.necessary to add new smilies to core.
As long as someone volunteers a hand with any C++ side changes that may be required.

If anyone has seen any smilies online that illustrate what they would like to see) please provide link.
We can only include things from online resources if they are properly licensed or license allows. Just in case we use anything as a base for modification. 

On that note: https://github.com/twitter/twemoji ( I haven't looked at it really )

Things I would like to see improved in this subject. (todo checklist)
- [ ] New smilies that still match the new core icons style. (say no to mix and match) 
- [x] **Not Apple**. Must be opensource or something easily gotten for reference.
- [ ] Unique smilies only e.g. currently `biggrin` and `lol` are exact replicas same for `prrr` and `:p` (remove duplicates?) Im in favor of [K.i.s.s. principle](https://en.wikipedia.org/wiki/KISS_principle) 
- [ ] Slightly larger smilies sizes, if possible 24x24 max canvas size (depends on what line size allows?)
- [ ] Animated smilies?
- [ ] C++ work necessary (volunteer name goes here)

As this progresses the todo lists can grow depending on what others say.

How does this sound?

**Comment by Stanzilla** [comment]
I personally like the iOS emoji icon set, what's the license on those? I see them used in many programs.

**Comment by DarthGandalf** [comment]
Related: #1475

**Comment by DarthGandalf** [comment]
(and I hate any kind of graphical smiles)

**Comment by un1versal** [comment]
> I personally like the iOS emoji icon set, what's the license on those? I see them used in many programs.

Apple, hell no! I rather stay on DarthGandalf side, and doubt they make anything opensource or anywhere related to it. Aside from this their emoji are just insensitive. I wouldn't even use them for reference and avoid Apple anything (that isn't the fruit) like the plague. :grin:

**Comment by SolarAquarion** [comment]
probably the twitter ones

**Comment by SolarAquarion** [comment]
GPL emoji https://github.com/Ranks/emojione?

**Comment by un1versal** [comment]
Yep with some decoration http://emojione.com/ that could work. but alas line height idk whats the max icon size it can take before it looks odd

**Comment by un1versal** [comment]
Well, Im closing this, since Ive added a few more icons and the current feature is somwhat broken and I suspect theres not much support from picture based emoticons anyway.
