### ISSUE TITLE
Wrong icons used in menus and when switching themes.

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1541]
OK this is a twofold bug/issue and gets confusing on KVIRC menu...

1) Some of the menu icons are using the large icons resized to 16x16 and ignoring the coresmall icons that should be used for these menus.

For instance.
Currently by default this is loaded. **wrong**
![capture](https://cloud.githubusercontent.com/assets/3521959/9609262/af326552-50ca-11e5-869b-ec7970dc7364.PNG)

**Right** (This is what it should look like using coresmall)

![capturea](https://cloud.githubusercontent.com/assets/3521959/9609351/2a7d3110-50cb-11e5-8653-cebda249401d.PNG)

Again **wrong** Looks like they are resized from 32x32 to 16x16 even if it seems the correct icons are shown.

![capture2](https://cloud.githubusercontent.com/assets/3521959/9609378/4acae250-50cb-11e5-96a8-5e28568b6dee.PNG)

**right**  (This is what it should look like using coresmall)
![capture1a](https://cloud.githubusercontent.com/assets/3521959/9609382/5109b3e4-50cb-11e5-8d7f-42117b2a9a78.PNG)

**wrong**
![captured](https://cloud.githubusercontent.com/assets/3521959/9609603/876a5b40-50cc-11e5-9b19-22b4df865cc2.PNG)

**Right**  (This is what it should look like using coresmall)
![captureda](https://cloud.githubusercontent.com/assets/3521959/9609616/93f50b26-50cc-11e5-966d-d127518583c1.PNG)

---
### Fixed by https://github.com/kvirc/KVIrc/commit/67cf996535cca7103c098dce9925455cd4e71fc9

~~#### And this is the confusing one  **wrong"" using kcs_terminal in coresmall for newcontext icon
Should be using ***kcs_newitem***~~

**Right**
![c](https://cloud.githubusercontent.com/assets/3521959/9609697/f7aac87c-50cc-11e5-95a5-e0a86d69d2e5.PNG)

---

2) The second issue is that the right icons dont get loaded on theme changes or if the theme doesn't have coresmall directory with a copy of the coresmall icons.

**Comment by un1versal** [comment]
> 2) The second issue is that the right icons dont get loaded on theme changes or if the theme doesn't >have coresmall directory with a copy of the coresmall icons.

A -> B - OK (Icons change to wrong defaults if previously OK e.g. coresmall)
B -> A - NOK (Icons stay as the wrong defaults)

But it still doesnt load coresmall :( except for one icon newitem

**Comment by pragmaware** [comment]
Are you 100% sure?
I see coresmall icons in the menus now...

**Comment by un1versal** [comment]
Well Ill test somemore but if I change themes they are bailing atm... no idea why.

Only on restart does it work (but thats always worked and only time it works here)... back to testing.

MAybe its being cached somewhere since its not a clean install (just recompiled and reinstalled) and you cant really make uninstall.
