### ISSUE TITLE
Icons don't get properly reloaded with certain themes

### ISSUE THREAD

**Issue by pragmaware** [kvirc/KVIrc#1542]
The right icons dont get loaded on theme changes or if the theme doesn't have coresmall directory with a copy of the coresmall icons

**Comment by pragmaware** [comment]
Hm... can't really reproduce this anymore.

**Comment by un1versal** [comment]
I can, doesn't work except for the newitem icon is now right on Kvirc menu the rest is apparently still as it was before. Sorry https://github.com/kvirc/KVIrc/issues/1541 everything in there applies except for the last one Ill mark as fixed.

https://github.com/kvirc/KVIrc/issues/1541#issuecomment-136883834

> 2) The second issue is that the right icons dont get loaded on theme changes or if the theme >doesn't >have coresmall directory with a copy of the coresmall icons.

Let me elaborate. If you change the theme from current it works, but not when you change it back.

A -> B - OK (Icons change to wrong defaults if previously OK e.g. coresmall)
B -> A - NOK (Icons stay as the wrong defaults)

But it still doesnt load coresmall :(
