### ISSUE TITLE
User list width lost on KVIrc restart

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1543]
Before as set
![capture](https://cloud.githubusercontent.com/assets/3521959/9620222/d66ee59c-510f-11e5-8453-ddc76a75c683.PNG)

After restart.
![capture](https://cloud.githubusercontent.com/assets/3521959/9620346/2acb53c2-5111-11e5-9690-2dba6baacabc.PNG)

I have 3 servers and various channels on these 3 servers the main servers one that loads ontop looses size of the user list width I set all the time to half or more when all channels finish reloading. If it helps this is a read only channel

**Comment by un1versal** [comment]
Possible workaround, so far good results https://github.com/kvirc/KVIrc/issues/1544#issuecomment-137184693

Now based on that new information maybe pragma or whoever can, can deduce a proper fix.

**Comment by HelLViS69** [comment]
Duplicate of #1544

**Comment by un1versal** [comment]
> Duplicate of #1544

Not by a long mile, the two never manifest themselves together... in any case MDI windows is gone and this hasnt re-happened

**Comment by un1versal** [comment]
Duplicate of #900, merging with that.
