### ISSUE TITLE
Topic is covered by channel modes on Kvirc restart

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1544]
Similar to https://github.com/kvirc/KVIrc/issues/1543

On Kvirc restart
![capture](https://cloud.githubusercontent.com/assets/3521959/9620376/7fb3d2e2-5111-11e5-92bd-d745f35a31c3.PNG)

Before
![capture](https://cloud.githubusercontent.com/assets/3521959/9620412/dfe91a0a-5111-11e5-81a4-40d7d995e53c.PNG)

This affects many channels but not all. and its server independent.

**Comment by xrogaan** [comment]
Ah yes, I have this too. Always reset to the same gigantic size.

**Comment by DarthGandalf** [comment]
There was a similar bug, with both nick list and topic. But it was fixed
ages ago (but after 4.2.0)
You're on which git commit?

2015-09-02 4:43 GMT+01:00 Ludovic Bellière notifications@github.com:

**Comment by ctrlaltca** [comment]
I can confirm this has never been really fixed. It's about QSplitters not returning their correct width for its widgets if the parent widget is not visible (or has never become visible). Anyway, it's hard to reproduce at will.

**Comment by wodim** [comment]
@ctrlaltca do you confirm that? Is it then a Qt bug? Maybe for the interest of efficiency the width of a widget is never calculated if the parent has never been drawn?

**Comment by ctrlaltca** [comment]
> Is it then a Qt bug?

Not really; Qt would like us to use a specific method (http://doc.qt.io/qt-4.8/qsplitter.html#saveState) that's made to be used only with Qt's own QSettings class. Instead, we try to fetch the sizes in pixels directly.

> Maybe for the interest of efficiency the width of a widget is never calculated if the parent has never been drawn?

I suppose so. I remember i tried to go deep into this, but never found a way to workaround it.

**Comment by un1versal** [comment]
> You're on which git commit?

If that question was for me...
Im on exactly git HEAD of master 7a34b4082f87e64b5287a63ea5c5da80b8b7c7e3

I use QT4 also if it matters with GTK+ default qt style, but its not a QT style issue as Ive tried cleanlooks for instance with no change.to either of my 2 latest issues reported.which have been there since I can remember.

**Comment by un1versal** [comment]
I think I found a workaround for this issue and https://github.com/kvirc/KVIrc/issues/1543.
So far my tests all seem to yield positive results after quite a few KVIrc restarts. So fingers crossed.

If you run channel windows in maximized window mode atm you will need to disable it.
**So it seems that windows sizes when not in maximized mode here matters **for correct operation.**

1) Click the **restore down** on one channel window (this seems to automatically remove ALL channels from maximized window mode.
2) Now go to **each channel window** focus it and goto Menu > Window > Expand Vertically / Expand Horizontally (**very important both expand vertically and expand Horizontally are clicked here for each channel**.
3) You should at this time also **per channel**) adjust the size of channel mode bar size and user list width to your liking. while you are here right click each channel entry server tree navigation and select **Save windows props as default** 

Rinse and repeat for all channels until all are configured correctly. Once done you can restart kvirc a few times to ensure the settings stuck if they dindt repeat the above for the channel that didnt stick *\* they all stuck here**

Now that you see that window size/ user width and channel modes sizes and widths are being kept you can maximize one window and all will be maximized with it and fingers crossed this is you done.

**Comment by un1versal** [comment]
Just as an update to the above workaround for this issue and #1543, its been chugging along just fine with no side effects or signs of any loss or any changes from the sizes I had set.

If anyone else could confirm it also works for them perhpas the workaround itself could give pointers to fixing the issue properly in core. Not that Ide know about that. :D

**Comment by pragmaware** [comment]
Btw, have you tried a Qt5 version? It doesn't seem to loose topic sizes here.

**Comment by un1versal** [comment]
Ive not tried QT5 it complains about some things not found and havent looked at actually fixing them.
It seems the issue is the windows sizes are all over the place and I think expanding them vertically and horizontally did the trick.

QT5 error, this is what happens currently when I configure with -DWANT_QT4=0 and totally ignores QT5 as it still detects QT 4.8.6, perhaps QT5 is not properly installed idk like I said haven't really looked at all.

```
-- Current revision is git-5266-gdb3a52c
CMake Warning at CMakeLists.txt:427 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed
```

**Comment by pragmaware** [comment]
Yep, you need Qt5 "dev" packages.

**Comment by un1versal** [comment]
Im working on improving the INSTALL readme (amongst others), 

for missing libs for QT5 here seems to be (for documenting sake)

libphonon4qt5-dev qtbase5-dev libqt5svg5-dev libqt5webkit5-dev libqt5x11extras5-dev libphonon4qt5experimental-dev qtmultimedia5-dev libphonon4qt5experimental-dev 

Currently its a nightmare to follow and its long winded and has tons of unnecessary and irrelevant info  instead of the practical stuff like the actual lib names required for a full compile not just a barebones compile.

Believe it or not I had to look at debian files for a full list of the required dependencies back when I started compiling Kvirc.

**Comment by un1versal** [comment]
With QT5 now compiled... lets see...

**Comment by un1versal** [comment]
mmm, This doesnt seem to be happening so often now. mostly new channels display this.

**Comment by un1versal** [comment]
Will leave open for a little longer needs a few more tests.

**Comment by Heufneutje** [comment]
I've noticed this issue on my client as well for a good while. I'll keep an eye on it too.

**Comment by un1versal** [comment]
duplicate of https://github.com/kvirc/KVIrc/issues/900, merging and closing here.
