### ISSUE TITLE
Git hash is being mangled in build revision

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1548]
Essentially g is being appended to all the hashes.

First noticed at d00p while checking the progress of the site.

![capture](https://cloud.githubusercontent.com/assets/3521959/9684914/8bbd5c54-5312-11e5-9eaf-2c5975b01663.PNG)

looking at https://github.com/kvirc/KVIrc/pull/1546 you can see the resulting builds all have a **g** appended to hash https://ci.appveyor.com/project/DarthGandalf/kvirc/build/0.0.0.0.1-branch-master-build-315/job/4sq89ayh47vgswc3/artifacts

I presume we are stripping g**it** and leaving the g behind which is OK for filenames but when you follow the hash it results into a 404

Its also is being added to version

```
-- Build Date                     : 2015-09-04 14:23:23 UTC
-- Build Version                  : 4.3.2
-- Build Codename                 : Aria
-- Build Revision                 : git-5275-g7d14b49
```

On a side note this should read 

-- Build Revision                 : 5275-git-7d14b49

since 5275 is NOT a git hash

**Comment by DarthGandalf** [comment]
This g is coming from "git describe".
Btw, d00p, I can add the full git hash to the "latest" json, to be used in
the link...

2015-09-04 14:44 GMT+01:00 uNiversaI notifications@github.com:

**Comment by un1versal** [comment]
Knowing what g is, is not obvious, the **g** there stands for **git** according to git describe docs, but adding that to hash is wrong imo and just because the git describe tool does it it doesn't make that right.

Not only is the hash mangled but for those who know what g stands for git, you also read that as is - **git**-5275-**git**7d14b49, does that sound right to you?

Even github and git itself doesn't recognize it as a valid hash  We currently do g7d14b49 and the correct is 7d14b49 (one is linked automatically here and one is not)

**Comment by DarthGandalf** [comment]
> its not right anyway. the g there stands for git according to git describe docs, but adding that is not right.

why?..

> Even github doesnt recognize it 7d14b49 vs g7d14b49 (one is linked automatically here and one is not)

Of course it doesn't recognize some random part of what it does recognize. `https://github.com/kvirc/KVIrc/commit/git-5275-g7d14b49` works: https://github.com/kvirc/KVIrc/commit/git-5275-g7d14b49

**Comment by DarthGandalf** [comment]
Btw, d00p's website already got fixed, and doesn't mention this `g` now.

**Comment by un1versal** [comment]
> Of course it doesn't recognize some random part of what it does recognize. https://github.com/kvirc/KVIrc/commit/git-5275-g7d14b49 works: git-527

Forgive me, I dont want to argue why this is wrong and you cant convince me that its right or acceptable. lol

> Btw, d00p's website already got fixed, and doesn't mention this g now.

One more reason why this should be fixed where it matters, in source, not in 3rd party.
