### ISSUE TITLE
Update Python support to 3.4

### ISSUE THREAD

**Issue by HelLViS69** [kvirc/KVIrc#1553]
And drop the old 2.7

**Comment by un1versal** [comment]
Some Linux releases still only use 2.7

Is there any benefit other than bragging rights for using 3.4?
Do you have any plans for something that can only be achieved with 3.4?

**Comment by DarthGandalf** [comment]
Those Linux releases have _both_ 2.7 and 3
And sure there are benefits, check e.g.
http://python-notes.curiousefficiency.org/en/latest/python3/questions_and_answers.html

2015-10-22 9:03 GMT+01:00 un1versal notifications@github.com:

**Comment by un1versal** [comment]
I meant as in any benefits to KVIrc directly as is without breaking stuff... I dont know honestly hence why I asked. As for reading pyhton docs explanation doesnt really answer my question as I dont know what Idle be looking for + dont feel and will not be reading the intrawebs to find out.

**Comment by Heufneutje** [comment]
I think the biggest issue is that Python 2 and 3 aren't fully compatible with each other, so switching over might break existing scripts.

**Comment by staticfox** [comment]
That is what I was thinking. If we were to deprecate 2.7 then we'd need to
at least give a lot of advanced warning. IMO if 2.7 isn't difficult to
support then we shouldn't rush dropping support.

**Comment by ctrlaltca** [comment]
I'd drop perl instead, with all the problems it creates to be embedded :)

About python, maybe we should keep a python module for python2 and create a new python3 module?
This way old scripts can still use python.begin; new scripts will use python3.begin

**Comment by Heufneutje** [comment]
:+1:

**Comment by staticfox** [comment]
:+1: to python3 module, :-1: to dropping perl :p

**Comment by wodim** [comment]
#2269

Some stuff to be done (fix docs, make cmake more aware of which version is used, etc) but it basically works now.

**Comment by wodim** [comment]
Done and doner.
