### ISSUE TITLE
White boxes return

### ISSUE THREAD

**Issue by swarfega** [kvirc/KVIrc#1554]
If you remember we had the problem of white boxes (namely topic and chanmode boxes) so we couldnt see the text. The problem seems to have returned in 4.3.2.

**Comment by un1versal** [comment]
Screenshot and OS at least and specific KVIRC revision this happens, so the rest of the people who dont remember, know what you're talking about. 

In other words it works fine here with current master both qt4 qt5 and Linux.

**Comment by swarfega** [comment]
Those who worked on 4.3.1 will remember but anywho here they are. This started with the first d00p 64-bit build of 4.3.2 and has continued to the latest build.

![whiteboxes](https://cloud.githubusercontent.com/assets/2217248/9713611/711174b4-554a-11e5-871b-1fa274238d6f.PNG)

**Comment by un1versal** [comment]
Now you hope people know which was the first d00p revision...

I think it works fine here on windows as well at least windows 7 its OK.

**Comment by swarfega** [comment]
I'm on Windows 10 Pro 64-bit. I can't remember the first build number and theres no history on his website.

**Comment by un1versal** [comment]
Well then its a windows 10 issue, it works OK on win7.

**Comment by swarfega** [comment]
Have you tried 8.1? This first appeared in 8/8.1 on version 4.3.1.

**Comment by un1versal** [comment]
No, IMO Windows OS dies with v7 here. So I wont go there. AT least we established 5 posts on what OS is the issue, which should be part of first post.

**Comment by swarfega** [comment]
lol well this issue still needs fixing for those of us "unfortunates" who still use it.

**Comment by un1versal** [comment]
> lol well this issue still needs fixing for those of us "unfortunates" who still use it.

Well self inflicted haha. You must love spyware.

ikd if Bill Gates cares about this issue. :grimacing:  but Ive no clew if it can be fixed in KVIrc or needs fixing in QT or Windows.

**Comment by swarfega** [comment]
Thats because hes retired and busy giving out his millions.

**Comment by swarfega** [comment]
I can confirm this bug as fixed. Thanks guys.
