### ISSUE TITLE
Wrong icon in settings menu

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1559]
![capture](https://cloud.githubusercontent.com/assets/3521959/9764804/ead4ab12-5708-11e5-8d82-600df69b7bfd.PNG)

Should be https://github.com/kvirc/KVIrc/blob/master/data/pics/coresmall/kcs_raw.png

I think I found the issue PR to fix shortly for review

**Comment by pragmaware** [comment]
Hm... not sure. "Raw Event Editor Window" sounds closer to RawEvent than to Raw, but in fact we could also think about adding a specialized icon (?)

**Comment by un1versal** [comment]
Can do. I can modify that icon as I dont think its used anywhere else either.
