### ISSUE TITLE
Rotate tiled windows method

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#156]
**Reported by thell on 03 Jun 2008 16:41:28 UTC**
Requesting a feature that would allow the window frame positions to be set and saved and a hot-key to rotate which channel is shown in the existing frames.

ie:
a window space similar to the Pragma Vertical 6 grid except with 5 frames and the fifth being double the width of the others (on the bottom row).  Then a hotkey (say ctrl+alt+R and ctrl+shift+R) is pressed the all channels rotate yet the display layout remains the same.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/156

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 03 Jun 2008 22:09:50**
Summary: Feature request: Rotate tiled windows method → Rotate tiled windows method
Type: Bug → Feature request
Version: none → 4.0 Insomnia

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 19 Dec 2009 16:44:48**
Version: 4.0 Insomnia → 4.0rc2 Insomnia

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 02 Feb 2010 14:12:49**
Version: 4.0rc2 Insomnia → 4.0 Insomnia

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 27 Jun 2010 15:17:43**
Version: 4.0 Insomnia → 4.1 Equilibrium

**Comment by DarthGandalf** [comment]
**Modified by ctrlaltca on 20 Jul 2010 06:18:36**

**Comment by wodim** [comment]
We have no MDI system now, so this feature request makes no sense anymore.
