### ISSUE TITLE
spell checker - barely visible underlining lines

### ISSUE THREAD

**Issue by Zybyr** [kvirc/KVIrc#1562]
Hi guys, 

On my Samsung 1080 monitor which is normally pretty bright, the underlining red line of spell checker is barely visible against black or dark backgrounds. I typically use solid black background and mostly white foreground. I tried different variations shades of darker blue, and darker gray, however the spell checker line is barely visible. 

It might only look visible against white, but still pretty difficult to see it. 

I also use kvirc with same settings on a Dell monitor, which is much dimmer, and still barely visible. 

Is it possible to request the underlining of misspelled words to be emboldened and lighter red color line or even make customization in colors, and thickness of the spell checker line? 

Thanks very much in advance, 
greatly appreciated for all work and effort.

**Comment by un1versal** [comment]
Because a picture speaks 1000 words click to enlarge

![capture](https://cloud.githubusercontent.com/assets/3521959/9777918/9ddc2778-5761-11e5-824b-d697c343b06b.PNG)

**Comment by Zybyr** [comment]
the spell checker looks better on yours, and probably because you use lighter background. 
Also, does your theme text input have smart nicknames enabled to get those colored nicks? 

![line](https://cloud.githubusercontent.com/assets/11053449/9778089/d7dec20a-5739-11e5-9626-dbc3e28e83b4.png)
