### ISSUE TITLE
Reordering tree network tabs

### ISSUE THREAD

**Issue by MyWay** [kvirc/KVIrc#1564]
I'd like to specify the order of networks in the tabs tree (I'm using autoconnect to more than one network), is there a way to achieve it? So I'd like to have a network before another one, when connected. If it's not possible can you add this feature? Thank you.

**Comment by ghost** [comment]
What is the "tabs tree"?

**Comment by un1versal** [comment]
I imagine the OP is referring to the server lists (and by extension) the window tree list, where you cant reorder servers/channels manually and are stuck between the default order and where channels/servers in window tree/classic list, broken sort options and whatever the connection order happens to place them in the order.

I think the classic window list suffers from this limitation as well.

There was a request somewhere for allowing click and drag custom ordering to these things... let me see if I can find it. 

This seem like a duplicate of https://github.com/kvirc/KVIrc/issues/99

I think this is a duplicate and therefore merge them.

**Comment by ghost** [comment]
The window tree list is auto-sorted by name and doesn't care about connection order, that's why I'm confused.  It should be the same order every time.

**Comment by un1versal** [comment]
All discussion and ticket merged with #99 please continue all discussion there.
