### ISSUE TITLE
Get rid of KVI_SOURCES_DATE and have a version handle the sources date - Merge #1566 and #1548: 

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1566]
The value of 
# define KVI_SOURCES_DATE "20150910"
# define KVI_SOURCES_DATE_NUMERIC 0x20150910

Should be something Dynamic for instance in Linux you can do:

Reference: 5fa4ce8d882cb03e6a2a79cbac45e5e2f2870d17
#### Edit Sat Oct  3 11:59:38 BST 2015

In reference to https://github.com/kvirc/KVIrc/pull/1649#issuecomment-145236664

It makes no sense to manually update these fields and also since discussion in https://github.com/kvirc/KVIrc/pull/1649 I think that things could be handled better automatically and in a saner manner.

Im not proposing that we ditch git describe just that we ditch #define KVI_SOURCES_DATE and improve kvirc versioning to include that automatically.

So I submit to your consideration revising the program version number in a way that doesn't break git describe and handles this sources date.

Suggestions at 

https://github.com/kvirc/KVIrc/pull/1649#issuecomment-145211207
https://github.com/kvirc/KVIrc/pull/1649#issuecomment-145211569
https://github.com/kvirc/KVIrc/pull/1649#issuecomment-145211681

The date is extracted as described by **ctrlaltca** in  https://github.com/kvirc/KVIrc/issues/1566#issuecomment-139749165

Previously suggested formats:

```
2015-10-02-7d8be0f 
2015-10-02-g7d8be0f  (if that works with git describe) 
2015-10-02-5484-g7d8be0f 
```

Or any other better suggestions?

**Comment by pragmaware** [comment]
That defines are meant to reflect the "release" date of the source code, not compilation date...
Or I'm missing something?

**Comment by un1versal** [comment]
idk, it seems weird that we have to manually edit this every time theres a release. hence the thought above as is that field is no longer correct today.

**Comment by pragmaware** [comment]
Ideally it should be changed to the late of the last commit... but well, I guess that it's not very easy to do.

**Comment by un1versal** [comment]
stat -c %y .git/FETCH_HEAD does that

**Comment by pragmaware** [comment]
On my system it returns a different date every time I git pull.
The sources date should refer to the date of the last commit, not the last pull.

**Comment by un1versal** [comment]
Yes, probably not simple to achieve automatically.

I think you meant to say different time not date date is always 2015-09-12 (or whatever the day is) unless youre pulling 6 months later. But none the less git -show of stating head is not gonna work like I thought.

**Comment by ctrlaltca** [comment]
What about `git log -1 --date=short --pretty=%cd`?
That's the best we can get using git by now, since support for strftime-like formats has been merged only a month ago: https://github.com/git/git/commit/d939af12bd96db7ad3e671a0585ad8570aa7e9d3

**Comment by un1versal** [comment]
Nice... How does that work if you are pulling the source one month later then the one the last commit went in?

**Comment by ctrlaltca** [comment]
That command returns the date of the last commit; one month later with no new commit in, it will return the same date.

**Comment by un1versal** [comment]
Fantastic thanks, idk how to make those fields dynamic using that is only issue here (have some very loose idea). Lets see what pragma says.

I doubt that would work but no idea if that would work like:

```
DATE="git log -1 --date=short --pretty=%cd"
#define KVI_SOURCES_DATE "${DATE}"
#define KVI_SOURCES_DATE_NUMERIC 0x"${DATE}"
```

**Comment by ctrlaltca** [comment]
We already do something similar to get the revision number from git.

CMake runs git: https://github.com/kvirc/KVIrc/blob/master/CMakeLists.txt#L107 in order to get the revision number in CMAKE_KVIRC_BUILD_REVISION.
This value is then used in cmake https://github.com/kvirc/KVIrc/blob/master/CMakeLists.txt#L1361 to create a .h using this template: https://github.com/kvirc/KVIrc/blob/master/cmake/kvi_sysbuildinfo.h.cmake#L19
The header file can then be #included as normal.

The only problem here is defining a fallback method to get the value if the sources are not inside a git tree (eg, official sources for a release). This problem has been already addressed for CMAKE_KVIRC_BUILD_REVISION.

**Comment by un1versal** [comment]
Thx, Im not sure I will be able to do this myself but :+1:  sounds good.

**Comment by Stanzilla** [comment]
I don't think a sources date is even useful. What does it represent? If someone wants to know the date of the last commit he can just look at the git log?

**Comment by staticfox** [comment]
:+1: @Stanzilla IMO since most people are going to be downloading KVIrc pre-compiled, looking at the compilation date is more than enough. At that, they can just look at $version output for the last commit and figure it out from there.

**Comment by un1versal** [comment]
Only a very very very small subset of users is that geeky that would care or know what to do, but yea, dropping it is also a good move as its fairly useless for debugging.

What would be nice for debugging is some way option to start KVIrc in debug or output automatically some stacktrace into a file if it crashes that any user can easily upload to show us.

**Comment by un1versal** [comment]
anyway can we not just get rid of these entries altogether, they are useless afaik for any purpose.

**Comment by staticfox** [comment]
I was actually working on getting them to sync with `git show` right now, but cmake is being extremely unfriendly. Up to you.

EDIT: pebkac, almost done.

**Comment by un1versal** [comment]
either one or the other, if youre working on something already, lets not waste that effort if it works.

**Comment by Stanzilla** [comment]
Still no idea why we would need it at all?
