### ISSUE TITLE
Lag Meter

### ISSUE THREAD

**Issue by swarfega** [kvirc/KVIrc#1577]
Could we change the measurement to ms please. I find that easier to read.

**Comment by un1versal** [comment]
it is, isnt it?

![capture](https://cloud.githubusercontent.com/assets/3521959/9836186/bebbec1e-5a07-11e5-9d54-d794823ddcee.PNG)

Or maybe I should go get some sleep...

**Comment by swarfega** [comment]
I was thinking more in this sort of format. 
![nnslagmeter](https://cloud.githubusercontent.com/assets/2217248/9836203/3ec0eac2-5a08-11e5-9b63-12dc0be1dd34.PNG)
