### ISSUE TITLE
URL detection breaks on some characters

### ISSUE THREAD

**Issue by Stanzilla** [kvirc/KVIrc#1582]
When you take this URL for example `https://play.google.com/music/listen#/album/Bfny7uzwzj4vdndyrwcywu7qghe/Leaves'+Eyes/King+of+Kings` KVIrc stops at the `'` and therefore makes the link invalid.
![2015-09-14_04-35-54](https://cloud.githubusercontent.com/assets/75278/9840976/1f7e4bfe-5a9a-11e5-9f1f-2ba00ad886de.png)

**Comment by un1versal** [comment]
I think bug reports should come with more information. Like KVIrc Version and OS Version at the very least. Where people have tested other OS I would guess that's also useful.

**Comment by Stanzilla** [comment]
True, there you go:

```
KVIrc 4.3.2 'Aria'

Runtime Info:
System Name: Windows Release : 6.2.9200
System Version: Windows 8 Professional (x64) (Build 9200)
Architecture: Intel64 Family 6 Model 58 Stepping 9

Build Info:
Build Date: 2015-09-03 06:35:01 UTC
Sources Date: 20141230
Revision Number: git-5266-gdb3a52c
System Name: Windows-6.2
CPU Name: AMD64
Build Command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build Flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler Name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler Flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
```

**Comment by un1versal** [comment]
I went and just copied this link into KVIrc, when I pressed enter it was posted to #kvirc and it broke exactly there. Im on Linux here with a build from today's source

FYI, your build is already outdated, If you compile them yourself try one from tomorrow at least.

**Comment by Stanzilla** [comment]
02:31:20 ∙ Pragma: yep, that's a bug in skip_to_end_of_url
02:31:28 ∙ Pragma: fix should be easy
