### ISSUE TITLE
Aria theme: Visual oddity in Network view address bar

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1589]
Because a picture speaks 1000 words.
![capture](https://cloud.githubusercontent.com/assets/3521959/9866130/9edbc27a-5b56-11e5-97b8-79e92b146ac1.PNG)

Looking at the code responsible there no icon assigned and if none is required we could assign assign  **KviIconManager::Url**

I tried it and broke KVIrc 3 times so here is my request.

```
    KviTalToolTip::add(m_pAddressEdit,__tr2qs("Current IRC URI"));
    connect(m_pAddressEdit,SIGNAL(activated(const QString & )),this,SLOT(ircUriChanged(const QString & )));
    connect(m_pAddressEdit,SIGNAL(returnPressed(const QString & )),this,SLOT(ircUriChanged(const QString & )));
    connect(g_pApp,SIGNAL(recentUrlsChanged()),this,SLOT(recentUrlsChanged()));

```

**Comment by un1versal** [comment]
This is only present with Aria theme. So I presume its due to the background image being used.

![capture](https://cloud.githubusercontent.com/assets/3521959/9867690/7ac6f14a-5b68-11e5-939f-e8de62e15308.PNG)

Its actually supposed to be the Arrow on drop down for this part.

![capture](https://cloud.githubusercontent.com/assets/3521959/9867707/b36e63f2-5b68-11e5-86d9-14a8fc9f286c.PNG)

**Comment by pragmaware** [comment]
Does it also happen if you restart after applying the Aria theme?
Looks like the Qt theme didn't adapt to the background change or something like that...

**Comment by un1versal** [comment]
Yea doesnt matter, restart with theme applied or not this happens, maybe its Qt5 specific? I'll compile with Qt4 and check, I dont like the mouseover Qt5 style anyway. :stuck_out_tongue_closed_eyes:

**Comment by un1versal** [comment]
![capture](https://cloud.githubusercontent.com/assets/3521959/9979948/450a9eb2-5f7d-11e5-8702-f3d7b27d9c6c.PNG)

Yep seems its Qt5.x related with Qt4.x  you have the arrow but thers some dark line below this area there.

**Comment by pragmaware** [comment]
Do you still reproduce this?

**Comment by un1versal** [comment]
yes

**Comment by un1versal** [comment]
![capture](https://cloud.githubusercontent.com/assets/3521959/12078763/56d01f2c-b217-11e5-90d6-b7b86d947f19.PNG)

recent screenshot... so the issue has definitely remained unchanged

**Comment by pragmaware** [comment]
Does it depend on KDE style?
Does it happen when you start, say, kvirc -style=windows ?

**Comment by un1versal** [comment]
no KDE style here, Im in linux though.

```
KVIrc 4.9.1 'Aria'

Runtime Info:
System name: Linux 3.13.0-71-generic
System version: #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015
Architecture: x86_64
Qt version: 5.2.1
Qt theme: fusion

Build Info:
Build date: 2016-01-03 10:45:59 UTC
Sources date: 20160102
Revision number: git-6023-g84fc6de
System name: Linux-3.13.0-71-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.2.1
```

**Comment by un1versal** [comment]
with `kvirc -style=windows` this goes away

**Comment by un1versal** [comment]
its interesting after using ``` kvirc -style=windows ```  and now going back to normal, cant seem to reproduce this..

has something related to that style been saved somewhere?

**Comment by un1versal** [comment]
since its a style issue its Qt, and sod Qt bugs no one cares.
