### ISSUE TITLE
Light ignore

### ISSUE THREAD

**Issue by Stanzilla** [kvirc/KVIrc#1605]
Requesting a feature that lets you only ignore highlights from a certain user, instead of all messages. The message would still show in the channel/query window but not trigger the highlighting system, so task bar flash on Windows, the notifier popup etc.

**Comment by wodim** [comment]
This should be possible recreating the message using `echoprivmsg` with the `-n` flag.

**Comment by wodim** [comment]
Well, I'll reopen because after all the ignore system already has one thousand checkboxes, so one more would not hurt. Anyway, it can still be done with scripting.

**Comment by wodim** [comment]
This is the script, specific for the `OnChannelMessage` event.

```
if ($0 == "idiot") {
    echoprivmsg -n -i=$msgtype(ChannelPrivateMessage) $0 $1 $2 $3;
    halt;
}
```

**Comment by un1versal** [comment]
Ignore function is almost completely broken anyway https://github.com/kvirc/KVIrc/issues/1511

So really that needs fixing before anything else is added.
