### ISSUE TITLE
Qt5 menus do not appear

### ISSUE THREAD

**Issue by staticfox** [kvirc/KVIrc#1610]
##### Problem

SEE https://github.com/kvirc/kvirc-scripts/issues/8 for backlog.

All Qt menus are blank. e.g. http://i.imgur.com/YVrUpkN.jpg with QT5 Ubuntu 15.04 PPA
Apologies for using my phone for the photo, couldn't get scroll to behave with the drop down opened.
##### KVirc Version that fails

KVIrc Aria 4.3.2, revision: git-5378-g1468326, sources date: 20150915, built on: 2015-09-17 19:01:19 UTC
##### Scripts Revision

https://github.com/kvirc/kvirc-scripts/tree/33986ce6182ad95cee2ee3dc3260742aa04fc926
#### Software/Hardware:

matt@matt-Lenovo-Yoga-2-Pro:~$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.04
DISTRIB_CODENAME=vivid
DISTRIB_DESCRIPTION="Ubuntu 15.04"
NAME="Ubuntu"
VERSION="15.04 (Vivid Vervet)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.04"
VERSION_ID="15.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

matt@matt-Lenovo-Yoga-2-Pro:~$ uname -a
Linux matt-Lenovo-Yoga-2-Pro 3.19.0-26-generic #28-Ubuntu SMP Tue Aug 11 14:16:32 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
### Build Information

KVIrc 4.3.2 'Aria'

Runtime Info:
System Name: Linux 3.19.0-26-generic
System Version: #28-Ubuntu SMP Tue Aug 11 14:16:32 UTC 2015
Architecture: x86_64

Build Info:
Build Date: 2015-09-17 19:01:19 UTC
Sources Date: 20150915
Revision Number: git-5378-g1468326
System Name: Linux-3.19.0-28-generic
CPU Name: x86_64
Build Command: /usr/bin/cmake
Build Flags: 
MANDIR=share/man
CMAKE_INSTALL_PREFIX=/usr
LIB_SUFFIX=/x86_64-linux-gnu
Threads=POSIX
Compiler Name: /usr/bin/x86_64-linux-gnu-g++
Compiler Flags: -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2

---

---
## 

-- Paths:
--    Binary Path                 : /usr/local/bin/
--    Library Path                : /usr/local/lib/
--    Modules Path                : /usr/local/lib/kvirc/4.3/modules/
--    Man Path                    : /usr/local/share/man/
-- Compilation:
--    Debug                       : No (Release)
--    Verbose Output              : No
--    Coexistence Support         : No
--    Threading Support           : POSIX
--    Apple Universal Binary      : Not available
--    Memory Profile Support      : No
--    Memory Checks Support       : No
-- Features:
--    X11 Support                 : Yes, with screensaverproto
--    Qt Version                  : 4.8.6
--    Qt-DBus Support             : Yes
--    Qt-WebKit Support           : Yes
--    Qt-Svg Support              : Yes
--    Qt/X11 Interface            : Yes
--    KDE Support                 : Not available (KDE4 not found)
--    IPv6 Support                : Yes
--    Pseudo-Transparency Support : Yes
--    Spell Checker Support       : Yes
--    IPC Support                 : Yes
--    Audio Backends              : Phonon
-- Cryptography:
--    Crypt Support And Engines   : Yes
--    OpenSSL Support             : Yes
-- Scripting:
--    Perl Support                : Yes, used for scripting+doc
--    Python Support              : Yes
-- DCC features:
--    DCC Voice Support           : Yes, found linux/soundcard.h
--    GSM Support                 : Yes
--    DCC Video Support           : No
--    Ogg/Theora Support          : No
-- Documentation:
--    GetText Support             : Yes, + extra
--    GetText Messages Tidying    : Yes
## --    Doxygen Support             : Yes

-- Build Date                     : 2015-09-18 10:31:24 UTC
-- Build Version                  : 4.3.2
-- Build Codename                 : Aria
## -- I'm ready to build KVIrc for you: please type 'make' now...

-- Configuring done
-- Generating done
-- Build files have been written to: /home/matt/projects/KVIrc/release
matt@matt-Lenovo-Yoga-2-Pro:~/projects/KVIrc/release$ cmake -DWANT_QT4=true ..

KVIrc 4.3.2 'Aria'

Runtime Info:
System Name: Linux 3.19.0-26-generic
System Version: #28-Ubuntu SMP Tue Aug 11 14:16:32 UTC 2015
Architecture: x86_64

Build Info:
Build Date: 2015-09-18 10:31:24 UTC
Sources Date: 20150915
Revision Number: git-5385-g50798ae
System Name: Linux-3.19.0-26-generic
CPU Name: x86_64
Build Command: /usr/bin/cmake
Build Flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr/local
   LIB_SUFFIX=
   Threads=POSIX
Compiler Name: /usr/bin/c++
Compiler Flags: N/A

The issue appears to only exist in Qt5.
http://i.imgur.com/x8BtTMl.jpg

**Comment by un1versal** [comment]
Fan freakin tastic. So now we know QT5 and Ubuntu 15.04 dont play well together.

Apparently KDE5 plasma also suffers from this, had a report on IRC the other night but guy didn't open a bug report.

**Comment by HelLViS69** [comment]
Are you sure?
Qt Version : 4.8.6

**Comment by un1versal** [comment]
Yes you need to goto https://github.com/kvirc/kvirc-scripts/issues/8 to read whats going on

And if you read the OPs post you see the toop info is for QT5 Ubuntu ppa

and further down its a manual compile I asked him to do on https://github.com/kvirc/kvirc-scripts/issues/8 (which works foine as he says down the end)

**Comment by HelLViS69** [comment]
KVIrc you are using is compiled against Qt 4.8.6, not Qt5.
Read the build info, and btw, Qt4 was enabled at CMake configuration (-DWANT_QT4=true)

**Comment by un1versal** [comment]
Read https://github.com/kvirc/kvirc-scripts/issues/8

the bug is being reported againt QT5

The build that works is QT4, again I asked for this test specifically in https://github.com/kvirc/kvirc-scripts/issues/8

**Comment by staticfox** [comment]
Here's more information to clear up any trailing confusion with a fresh Qt5 build:

### Qt5 build on Linux

### KVirc Version

KVIrc Aria 4.3.2, revision: git-5385-g50798ae, sources date: 20150915, built on: 2015-09-18 11:03:25 UTC

### OS

matt@matt-Lenovo-Yoga-2-Pro:~/projects/KVIrc/release$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.04
DISTRIB_CODENAME=vivid
DISTRIB_DESCRIPTION="Ubuntu 15.04"
NAME="Ubuntu"
VERSION="15.04 (Vivid Vervet)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.04"
VERSION_ID="15.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
matt@matt-Lenovo-Yoga-2-Pro:~/projects/KVIrc/release$ uname -a
Linux matt-Lenovo-Yoga-2-Pro 3.19.0-26-generic #28-Ubuntu SMP Tue Aug 11 14:16:32 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### KVirc Executible Information

KVIrc 4.3.2 'Aria'

Runtime Info:
System Name: Linux 3.19.0-26-generic
System Version: #28-Ubuntu SMP Tue Aug 11 14:16:32 UTC 2015
Architecture: x86_64

Build Info:
Build Date: 2015-09-18 11:03:25 UTC
Sources Date: 20150915
Revision Number: git-5385-g50798ae
System Name: Linux-3.19.0-26-generic
CPU Name: x86_64
Build Command: /usr/bin/cmake
Build Flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr/local
   VERBOSE
   LIB_SUFFIX=
   Threads=POSIX
Compiler Name: /usr/bin/c++
Compiler Flags: N/A

### CMake output

## -- Ok, this is the configuration I've worked out:

-- Paths:
--    Binary Path                 : /usr/local/bin/
--    Library Path                : /usr/local/lib/
--    Modules Path                : /usr/local/lib/kvirc/4.3/modules/
--    Man Path                    : /usr/local/share/man/
-- Compilation:
--    Debug                       : Yes
--    Verbose Output              : Yes
--    Coexistence Support         : No
--    Threading Support           : POSIX
--    Apple Universal Binary      : Not available
--    Memory Profile Support      : No
--    Memory Checks Support       : No
-- Features:
--    X11 Support                 : Yes, with screensaverproto
--    Qt Version                  : 5.4.1
--    Qt Modules                  : Widgets;Sql;Xml;Network;PrintSupport;Multimedia;DBus;WebKitWidgets;Svg;X11Extras
--    Qt/X11 Interface            : Yes
--    KDE Support                 : Not available (ECM not found)
--    IPv6 Support                : Yes
--    Pseudo-Transparency Support : Yes
--    Spell Checker Support       : Yes
--    IPC Support                 : Yes
--    Audio Backends              : Phonon;Qt5Multimedia
-- Cryptography:
--    Crypt Support And Engines   : Yes
--    OpenSSL Support             : Yes
-- Scripting:
--    Perl Support                : Yes, used for scripting+doc
--    Python Support              : Yes
-- DCC features:
--    DCC Voice Support           : Yes, found linux/soundcard.h
--    GSM Support                 : Yes
--    DCC Video Support           : No
--    Ogg/Theora Support          : No
-- Documentation:
--    GetText Support             : Yes, + extra
--    GetText Messages Tidying    : Yes

## --    Doxygen Support             : Yes

-- Build Date                     : 2015-09-18 11:03:25 UTC
-- Build Version                  : 4.3.2
-- Build Codename                 : Aria

## -- Build Revision                 : git-5385-g50798ae

## -- I'm ready to build KVIrc for you: please type 'make' now...

-- Configuring done
-- Generating done
-- Build files have been written to: /home/matt/projects/KVIrc/release
matt@matt-Lenovo-Yoga-2-Pro:~/projects/KVIrc/release$ cmake -DWANT_DEBUG=true -DWANT_VERBOSE==true ..

### Bug

http://i.imgur.com/VFoj4St.jpg

**Comment by Afforess** [comment]
@uNiversaI I think I was the guy on IRC. I built from git, revision 9f0acd564e91c798c6279cff896c338dc6eb0856, following the instructions for QT5. I am on Ubuntu 15.10, Wily-RC1. I can also give full cmake output / flags if desired.

QT 4.8.3 menus work fine, and what I re-built with and ended up using.

**Comment by un1versal** [comment]
@Afforess I presume you could post your cmake compile flags and output, if in doubt post the information rather than not.

So it seem sits Qt5 related in any case since you compiled with Qt4.x and dont have the issue anymore.

**Comment by SolarAquarion** [comment]
@Afforess @uNiversaI i was the guy

**Comment by staticfox** [comment]
For what it's worth, the same thing happens within Fedora 22 and Arch/Antegros. Running Qt 5.5.0 on Arch and Qt 5.5.0 on Fedora.

![zjxblis](http://i.imgur.com/eG4ZnFU.png)
![zjxblis](http://i.imgur.com/WUPktxH.png)

**Comment by wodim** [comment]
A workaround is to run KVIrc with another style such as Plastique

```
$ kvirc -style=plastique
```

**Comment by ctrlaltca** [comment]
What style is being used when the menus are not working? I suppose that it should be QGtkStyle under ubuntu, but we are already blacklisting it since it caused problems in the past (https://github.com/kvirc/KVIrc/blob/master/src/kvirc/kernel/KviApplication.cpp#L241)

**Comment by wodim** [comment]
GTK I guess. Can also be fixed with

```
$ XDG_CURRENT_DESKTOP=kde kvirc
```

**Comment by ctrlaltca** [comment]
Hum.. i see a lot of `QCommonStyle::drawComplexControl: Control 1 not handled` in the console window in your screenshot, maybe they are related? Do they disappear when using the plastique style?

EDIT: sorry, that was @blindirc 's screenshot;

**Comment by wodim** [comment]
Remember `WANT_GTKSTYLE`? It's off by default, but if you turn it on, everything works well. Maybe that workaround is no longer needed and should be ditched for Qt 5?

**Comment by wodim** [comment]
I remember we added that flag because for example it hid the icons in menu entries but that is not a problem anymore, at least on LXDE.

**Comment by ctrlaltca** [comment]
IIRC it was causing problems with dark themes with inverted colors (white text on black background). Gtk was enforcing the text to be black, so we ended up with black text on a black background. If this is no more a problem, we can remove the workaround.

**Comment by ctrlaltca** [comment]
related to the workaround: #777, #988, #964
