### ISSUE TITLE
Frequent crashes on 5385

### ISSUE THREAD

**Issue by swarfega** [kvirc/KVIrc#1611]
I've had about four crashes so far with this build where-as previous version was stable. Please let me know what further info you require.

**Comment by un1versal** [comment]
Logs please!

**Comment by DarthGandalf** [comment]
What is 5385?

**Comment by staticfox** [comment]
I think he means revision 5385, i.e. commit g50798ae https://github.com/kvirc/KVIrc/tree/50798aefe179ed6da830bcdfc98a7b4355bf2182

[KVIrc Aria 4.3.2, revision: git-5385-g50798ae]

**Comment by un1versal** [comment]
> I've had about four crashes so far with this build where-as previous version was stable. Please let me know what further info you require.

Previous version was stable... Just a thought here. Are we supposed to guess what that was?

**Comment by pragmaware** [comment]
Stack trace, logs or at least a procedure to reproduce the crash is needed.

**Comment by swarfega** [comment]
Subsequent builds seem stable so I think we can close this issue.

**Comment by un1versal** [comment]
Closed :grinning: , next time some more specific and relevant information would be nice.
