### ISSUE TITLE
texticon typing doesnt trigger some icons unless you use texticon control character.

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1614]
Reference:

```
static KviTextIconAssocEntry default_associations[] =
{
    { ":)"  , KviIconManager::Smile       },
    { ":*"  , KviIconManager::Kiss        },
    { ":D"  , KviIconManager::BigGrin     },
    { ":("  , KviIconManager::Ugly        },
    { ":/"  , KviIconManager::Angry       },
    { ":O"  , KviIconManager::Surprised2  },
    { ":P"  , KviIconManager::Tongue      },
    { "BP"  , KviIconManager::Tongue2     },
    { ";)"  , KviIconManager::Eye         },
    { ":')" , KviIconManager::TearSmile   },
    { ":'"  , KviIconManager::Cry         },
    { ":S"  , KviIconManager::Afraid      },
    { ":|"  , KviIconManager::Demoralized },
    { ":P'" , KviIconManager::Slurp       },
    { 0     , 0                           }
};
```

Some icons like `":')" , KviIconManager::TearSmile``  typing`:')``` doesnt trigger the associated icon in fact quite a few of these dont do anything.

You need to press ctrl+I to have the texticon control character prefixed in before things like `:')` work.

![capturea](https://cloud.githubusercontent.com/assets/3521959/9980347/f7ad6996-5f8c-11e5-9f15-91b75f69ab98.PNG)
![s](https://cloud.githubusercontent.com/assets/3521959/9980350/573d86ac-5f8d-11e5-8392-33d81d6fbb04.PNG)

This isn't true for all the examples here for instance `:)` works out of the box without any control character.

So why do some need it and why do some dont? Why do we need a control character at all?

---

There is also an issue with texticon control character that you end up with two of them if you press ctrl+i then select an icon with mouse in this pop up menu. Which seems like a separate issue. https://github.com/kvirc/KVIrc/issues/1615

**Comment by un1versal** [comment]
This is Qt version independent it happens with Qt4.x or Qt5.x

**Comment by un1versal** [comment]
related bug report https://github.com/kvirc/KVIrc/issues/1364 from 4.2.0 so this has been broken forever it seems my attempts at fixing failed and didnt make issue better or worst.

**Comment by pragmaware** [comment]
This is because in many cases KVIrc can't reliably determine that a character sequence should be rendered as a text icon. Having all "BP" sequences rendered as a tongue would be wrong.
Only some very special sequences are interpreted and I don't think this can be improved further.
