### ISSUE TITLE
texticons control character issues

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1615]
There's two issues with the texticons control character

1) When pressing `ctrl+I` you cant immediatly type a key combination with keyboard while selection box is popup

![capture](https://cloud.githubusercontent.com/assets/3521959/9980354/b817dfae-5f8d-11e5-886b-36283c220d3e.PNG)

So you only option is to select and icon with mouse or exit that popup so you can type something like `:'` see https://github.com/kvirc/KVIrc/issues/1614

2) Pressing `ctrl+I` and selecting an icon from the pop up you end up with 2 texticons control characters.

![capture1](https://cloud.githubusercontent.com/assets/3521959/9980359/2ebdf652-5f8e-11e5-9a76-b574b7ef55f5.PNG)

**Comment by DarthGandalf** [comment]
There should be no texticon control character at all, see #1475 
The same comment applies to #1614

**Comment by un1versal** [comment]
Right, indeed, In #1614 the issue is exactly that, without it doesn't work some of the key combos at all and I dont understand why.

And here the issue is completely different it just adds extra control characters without any reason..

**Comment by un1versal** [comment]
This is Qt version independent it happens with Qt4.x or Qt5.x
