### ISSUE TITLE
I/O transfer graph doesnt output any traffic at all.

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1619]
Dead like a dodo, tested with Qt4.x and Qt5.x broken^2

![capture](https://cloud.githubusercontent.com/assets/3521959/12198696/3e7e25d0-b60a-11e5-9cb7-915004ad63b5.PNG)

```
KVIrc 4.3.2 'Aria'

Laufzeitinformationen:
Systemname: Linux 3.13.0-63-generic
Systemversion: #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015
Architektur: x86_64

Erstellungsinfo:
Erstellungsdatum: 2015-11-25 14:31:58 UTC
Datum der Quelldateien: 20151123
Revisionsnummer: git-5730-gf6795df
Systemname: Linux-3.13.0-63-generic
CPU-Name: x86_64
Erstellungsbefehl: /usr/bin/cmake
Erstellungs-Flags: 
   MANDIR=man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler-Name: /usr/bin/c++
Compiler-Flags: N/A
```

Test with any active dcc transfer in progress.

**Comment by pragmaware** [comment]
You mean the one you open with /iograph.open?
That one shows IRC traffic only...

**Comment by un1versal** [comment]
> You mean the one you open with /iograph.open?
> That one shows IRC traffic only...

Would be more useful if it actually showed all dcc input/output traffic + socket traffic etc.

As is imo its not really useful then.

**Comment by un1versal** [comment]
@TheReign you think this should show all traffic?

Currently for me no matter what is always 0 this to me is broken here.

**Comment by ghost** [comment]
This works for me on 4.3.2

Also, I don't think it should show dcc traffic.  Make a separate one for dcc, or a toggle to switch between server and dcc.

**Comment by un1versal** [comment]
> This works for me on 4.3.2

Well for me, its never worked, no matter what happens in IRC and no matter what KVIrc version... I open the graph and it has a spike and goes to 0 and stays there. :sob:  hwo is this suppose to indicate anything?

o matter how much activity goes on in my socket spy window this one is 100% dead.

![capture](https://cloud.githubusercontent.com/assets/3521959/12198696/3e7e25d0-b60a-11e5-9cb7-915004ad63b5.PNG)

> Also, I don't think it should show dcc traffic. Make a separate one for dcc, or a toggle to switch between server and dcc.

Yep that would also be nice. Anyone feeling generous? :grinning:

**Comment by staticfox** [comment]
It'll spike at an influx of messages, but in my opinion measuring bandwidth per second in IRC is kinda silly to begin with. Complaining that you aren't getting a whole lot of network I/O traffic on IRC is like complaining that you hate the cold while living in Pluto... For all intents and purposes, I'm going to close this ticket as the module works fine.

> > Also, I don't think it should show dcc traffic. Make a separate one for dcc, or a toggle to switch between server and dcc.
> 
> Yep that would also be nice. Anyone feeling generous?

If you still want this, open it as a new ticket.

**Comment by un1versal** [comment]
Works fine? it doesn't do anything ever. may as well not have it.

> Complaining that you aren't getting a whole lot of network I/O traffic on IRC is like complaining that you hate the cold while living in Pluto

Its like having square wheels on a car but doesnt matter because they dont ever turn, that is a more appropriate analogy tbh.

**Comment by staticfox** [comment]
Send ChanServ help, or a service that gives a long command list. or /info on freenode or something. It'll do stuff. And like I said.. It's IRC. how much bandwidth can you expect it to use to begin with? For the record...

![](https://staticfox.net/screenshots/1460551680.png)

**Comment by un1versal** [comment]
again nothing, its dead 100% no sign of life.

**Comment by un1versal** [comment]
Still valid with trunk

# IF ANYONE NEEDS MORE INFO PLEASE ASK

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 3.13.0-85-generic
System version: #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016
Architecture: x86_64
Qt version: 5.2.1
Qt theme: fusion

Build Info:
Build date: 2016-04-13 12:50:26 UTC
Sources date: 20160102
Revision number: git-6388-g5dbe2fa
System name: Linux-3.13.0-85-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.2.1
Features: IRC, Debug, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```
