### ISSUE TITLE
Current Windows builds have broken selected background color

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1623]
This was a bug reported by t_kns in IRC.

The actual selected background color is set to #232323 but in Windows they background bar style of the kills this.
In Linux the styled displays as intended

This issue applies to Network/Channel treelist and Userlist for the same reason.

Both Linux and Windows builds tested against are compiled against Qt5 cant test Windows with Qt4 since there's no nightly builds available to test and compiling them is a nightmare I wont ever try again.

**The workaround** is to change the foreground selected color to a darker color, but this breaks visibility in Linux so its only feasible to apply in the Users who have this issue.
Theme with workaround for testing https://github.com/uNiversaI/KVIrc/releases/download/4.2.0/IO.kvt

Because pictures speak louder than words.

![capture](https://cloud.githubusercontent.com/assets/3521959/10035488/afef1764-6192-11e5-8d04-e3a568e100df.PNG)

![capture1](https://cloud.githubusercontent.com/assets/3521959/10035489/aff11bcc-6192-11e5-87fc-38082ac40f3a.PNG)

theme settings.

![capture](https://cloud.githubusercontent.com/assets/3521959/10035556/772fd854-6193-11e5-8cdd-65fb85c6fb0f.PNG)
![capture1](https://cloud.githubusercontent.com/assets/3521959/10035557/7730db00-6193-11e5-9bd8-67dc007cff49.PNG)

**Comment by wodim** [comment]
Change the QStyle of the tree window list to something else on Windows as we do already with the KviIrcView input bar.

**Comment by un1versal** [comment]
It wont be just the treelist it will be wherever this applies. treelist is the obvious example but user list also affected.

**Comment by un1versal** [comment]
This bug is back... 

User leamon on IRC http://imgur.com/fDherJ0

<leamon> KVIrc Aria 4.9.1, revision: git-6054-gf20c74a, sources date: 20160102, built on: 2016-01-06 19:38:39 UTC
