### ISSUE TITLE
New icons are blurry at Medium size (22x22)

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1626]
16:
![selection_220](https://cloud.githubusercontent.com/assets/325092/10116401/1d59013e-642c-11e5-8850-710775e50895.png)

22:
![selection_221](https://cloud.githubusercontent.com/assets/325092/10116402/1fd32110-642c-11e5-80f8-33bdfa472895.png)

32:
![selection_222](https://cloud.githubusercontent.com/assets/325092/10116404/21d1f91e-642c-11e5-8756-f0721c57577a.png)

48:
![selection_223](https://cloud.githubusercontent.com/assets/325092/10116405/23e6593e-642c-11e5-9da9-d1c272015ba8.png)

Also, why at 16 some icons are different?
At 48 icons look the same as at 32, but centered.

**Comment by un1versal** [comment]
They are resized by program from the original at 32x32 so there's nothing to be done here from graphics side. Old design would have had same issue exactly.

If KVIrc can use a better rescaling algorithm like bicubic or better then this may improve something,

**Comment by un1versal** [comment]
So Ill reassign to whoever can change or add a better rescalling algorithm Cheeky :)

**Comment by DarthGandalf** [comment]
Hm. I see.
Old icons didn't feel as blurry at 22. Well, I've noticed it only with new icons.
Probably because old icons had less details...

**Comment by un1versal** [comment]
I think the scaling is handled by Qt, no idea even, its just a guess since I cant find any scaling code

@pragmaware probably knows

Reading http://doc.qt.io/qt-5/qimage.html points to http://doc.qt.io/qt-5/qimage.html#transformed, I still see no specific algorithms being used.

**Comment by DarthGandalf** [comment]
How does Qt rescale a rectangle with a key to a spiral fingerprint on 16x16?

**Comment by un1versal** [comment]
No idea, probably the identity icon is using who, Ill look into that
sorry fat fingers closed by mistake.

**Comment by un1versal** [comment]
> How does Qt rescale a rectangle with a key to a spiral fingerprint on 16x16?

Found the issue.

This is a general problem I solved with a few other icons already, the big icon filename and small icon filename dont match at all so end up causing issues like this.

Will submit a fix for this one soon enough.

**Comment by uNiversaI** [comment]
mmm the whole 16x16 toolbar has this same issue and needs a little more work than 1 icon fix only but will fix nonetheless.

**Comment by un1versal** [comment]
> Also, why at 16 some icons are different?

The issue is partially big icons vs small icons naming convention caused confusion when doing these originally, something I been fixing little by little.
Also the whole 16x16 toolbar is a weird mix between rescalled and non rescalled icons, jebus what a mess.
Should be fixed in https://github.com/kvirc/KVIrc/pull/1627

> At 48 icons look the same as at 32, but centered.

Again thats some internal code weirdness with scaling, but seems to me the icons are actually **smaller** than the original 32x32 and centered. Very weird. 

ViVA LA Qt Weirdness. I cant do jack about that. and will await @pragmaware comments on scaling and hopefully he can provide some better solution, currently it obviously is less than ideal.

Well all I can do here, is done! Rest I need help with like scaling improvements etc to fix the remainder of this ticket.

**Comment by pragmaware** [comment]
So this one can be closed?

**Comment by un1versal** [comment]
@pragmaware not really.

In order  to close this we need to:
- Improve the rescaling algorithm or the rescaling method used (to improve the blurriness resulting from rescaling)
- Make 48x48 actually be bigger than 32x32 not just center them and increase whitespace around icon.

If you read previous comments above, it may help you understand the main issue.
If you can help with the remainder of this ticket it will be greatly appreciated.

I'll look into code but chances are I have no clew here.

**Comment by wodim** [comment]
What I would do: have only 16x16 and 32x32 icon size options available.

**Comment by un1versal** [comment]
That also makes sense.

**Comment by un1versal** [comment]
This report is now ivalidated by https://github.com/kvirc/KVIrc/commit/7cc816029b12e1c34ff94b3fca2471d98987470a
