### ISSUE TITLE
CTCP-S Support

### ISSUE THREAD

**Issue by SoniEx2** [kvirc/KVIrc#1628]
CTCP-S is a CTCP extension both to fix and extend CTCP. It provides a mechanism similar to HTTP-X-Forwarded-For and a method for inserting inline images.

https://gist.github.com/SoniEx2/6509bf2ca6a65a69a383

Do note that displaying inline images is not required for CTCP-S support. As long as you replace the IMAGE CTCPs with the URIs, it should be 100% compliant.

**Comment by DarthGandalf** [comment]
Only after this is accepted to IRCv3. If it's accepted there at all.
When it happens, please reopen.

**Comment by SoniEx2** [comment]
CTCP is beyond the scope of IRCv3.

IRCv3 only cares about client-server and server-client communication, not client-client or server-server communication.

**Comment by DarthGandalf** [comment]
`VERSION` is already handled.

> For compatibility with previous clients, you MAY append a "null CTCP" \001\001 at the start/end of a message.

And how are you supposed to decide if it will be appended or not when you send this?

> :User!User@127.0.0.1 PRIVMSG Bridge :\001FORWARD TO BridgeUser\001Hi there, BridgeUser!

How do you even expect GUI would look like?

> You can also split the message:

No, you can't. You say this yourself:

> Second, there can be at most 1 normal message in a CTCP message.

**Comment by SoniEx2** [comment]
> > For compatibility with previous clients, you MAY append a "null CTCP" \001\001 at the start/end of a message.
> 
> And how are you supposed to decide if it will be appended or not when you send this?
> 
> > :User!User@127.0.0.1 PRIVMSG Bridge :\001FORWARD TO BridgeUser\001Hi there, BridgeUser!

It doesn't end in \001, but it starts in \001, so you put the \001\001 at the end.

> > You can also split the message:
> 
> No, you can't. You say this yourself:
> 
> Second, there can be at most 1 normal message in a CTCP message.

I said 1 normal message, but did I ever say anything about PARTS of a message?

`PART1\001CTCP\001PART2` makes the message `PART1PART2` and the CTCP `CTCP`. The CTCP should be processed first.

**Comment by DarthGandalf** [comment]
And what's the benefit of all this at all?

**Comment by SoniEx2** [comment]
For FORWARD, it's IRC bridges (IRC<->Minecraft or even IRC<->IRC). For IMAGE... well that one was a request from a reddit thread and I don't find it particularly useful .-.

**Comment by DarthGandalf** [comment]
I don't know anything about any reddit thread, but it's you proposing this here, not reddit...
May you remove useless stuff from the proposal then?

**Comment by SoniEx2** [comment]
Well, `IMAGE` is part of v1.1, not v1.0. Feel free to not implement it.

**Comment by DarthGandalf** [comment]
Don't worry, I'm free to not implement `FORWARD` either ;-)

**Comment by wodim** [comment]
1. `IMAGE` is a horrible idea. Drop it now.
2. `FORWARD` is good, but maybe you should consider writing a serious RFC and sending it to the [IRCv3 repo](https://github.com/ircv3/ircv3-specifications) for it to be discussed and implemented on every client.
3. I do not like the idea of "we are not going to implement this because we only implement whatever IRCv3 tells us to implement". We already have lots of custom of features anyway.

**Comment by DarthGandalf** [comment]
> We already have lots of custom of features anyway.

And some of them need to be dropped in favor of standard stuff. E.g. texticons (#1475)

**Comment by SoniEx2** [comment]
> 1. `IMAGE` is a horrible idea. Drop it now.

Fixed.

**Comment by pragmaware** [comment]
I don't fully understand what should be the handling of CTCP FORWARD in a normal IRC client.
Forwarding a message automatically to another user is a nasty idea since it can be used
to "make you say bad stuff" to other people. 
If this is something for a special kind of software (i.e. the one you call "bridge") then it can just
have its own specific protocol. It doesn't even need to follow the CTCP spec. It can be also
implemented as a special purpose script...

**Comment by SoniEx2** [comment]
It's not meant to make you look like another user.

Think about HTTP-X-Forwarded-For.

But now think about something more like this:

```
<SomeBridgeBot> <InGameUser> Hello there!
```

SomeBridgeBot is the e.g. IRC mod for Minecraft, InGameUser is an user that's using in-game chat, and SomeBridgeBot is sending in-game messages to IRC.

Say we want to allow in-game users to PM IRC users. That's simple enough, just send a similar message but in PM.

Say we want IRC users to be able to PM in-game users. Simple enough (altho a bit clunky), just let them prefix their message with `.msg <in-game user>`.

Say we want to add CTCPs... Oh wait, if we add the sender's/receiver's nick then the CTCP becomes invalid!

You can see the problem now. And that's what I'm trying to solve.

**Comment by pragmaware** [comment]
Still looks like a special purpose protocol to me... does not really need a CTCP.
The bot could just accept PRIVMSG commands like "say [target] [something]" to relay [something] to [target] on the other side. On the IRC side it would simply use PRIVMSG.
eggdrop bots probably support a similar feature to bridge IRC and the internal chat channel.

**Comment by DarthGandalf** [comment]
> Say we want to add CTCPs... Oh wait, if we add the sender's/receiver's nick then the CTCP becomes invalid!

You're trying to shoot yourself in foot. No new protocol can stop you from doing this, you'll still find some way.

**Comment by Mikaela** [comment]
I believe IRCv3 said that this is covered by [message intents](http://ircv3.net/specs/core/message-intents-3.3.html).
