### ISSUE TITLE
Motion to revert "thicker cursor"

### ISSUE THREAD

**Issue by Stanzilla** [kvirc/KVIrc#1632]
Commit in question: https://github.com/kvirc/KVIrc/commit/de35d68265549057f6a2ddd358f9e86d460b9469

Imo we should let the OS decide stuff like that, Windows has an option for it, not sure about Linux.
![img_53d9b242c0c10](https://cloud.githubusercontent.com/assets/75278/10125924/97a52cf6-6585-11e5-9868-7d5fb6c68691.png)

In any way, if not revert then maybe make it an option.

**Comment by wodim** [comment]
The following can be used to get the cursor width on Windows (note to self): [SystemParametersInfo(), SPI_GETCARETWIDTH](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724947%28v=vs.85%29.aspx)

That said there is no such thing on Linux. Maybe we could add an option (hidden if KVIrc is being used on Windows) to set the cursor width, and honour the system-wide width on Windows.

**Comment by un1versal** [comment]
As per comments on the commit https://github.com/kvirc/KVIrc/commit/de35d68265549057f6a2ddd358f9e86d460b9469 that added thicker cursor   its great its more visible but its fuggly tbh.

What would be ideal is optional cursors types, Windows cmd supports it, Linux supports it and would solve this request also.

![capture](https://cloud.githubusercontent.com/assets/3521959/9980384/a7ac14bc-5f8f-11e5-9374-ffae6c6b9b19.PNG)
![capture](https://cloud.githubusercontent.com/assets/3521959/9980415/8a81025c-5f90-11e5-951b-5118d4b07c82.PNG)
![capture2](https://cloud.githubusercontent.com/assets/3521959/9980416/8a8417b2-5f90-11e5-9ad7-024120b5bc56.PNG)

**Comment by swarfega** [comment]
I don't like the thicker cursor, it doesn't honour the host OS rules and looks odd since its the only program with this kind of cursor. The OS should be given control.

**Comment by un1versal** [comment]
You dont like the thicker cursor and I cant see the slim one (I find it hard to spot especially when the spellchecker depends on cursor position), hence I suggested a solution that would suit all users and that is to allow choosing cursor type/thickness like you can do on Windows OS and Linux Terminal

If that is possible to read the OS preference then Im OK with that also.

FYI, I dont like the current cursor for aesthetic reasons only.

**Comment by wodim** [comment]
I also removed those lines at the top and at the bottom that were completely out of place, is this any better? 😕

**Comment by un1versal** [comment]
So now https://github.com/kvirc/KVIrc/issues/1591 will have to be reopened then since you now need eagle eyes to spot the dammed thin cursor again.

FYI I dont use windows and I need a bigger thicker cursor.

**Comment by wodim** [comment]
Normal people can see the cursor, you have sight problems. I'll close this and let's follow this up here, #1591

**Comment by un1versal** [comment]
Lots of people have sight problems and they are normal people.
