### ISSUE TITLE
More work on getting input bar background images right

### ISSUE THREAD

**Issue by Stanzilla** [kvirc/KVIrc#1633]
After https://github.com/kvirc/KVIrc/commit/545cb367fa0de911ca92335f8cf20955e933e806 and https://github.com/kvirc/KVIrc/commit/a04cbbefaeaf65cd7abcb9ec3cb68db20fa4fee9 it looks like only the horizontal tiling is not working:

http://vgy.me/lmE6pU.png

**Comment by un1versal** [comment]
No tiling is working FYI, the whole functionality is now gone

A window is now detached or attached and maximized.

Lets ask @pragmaware if this is a bug or its the way its indented to wok from now on.

**Comment by wodim** [comment]
I am unable to reproduce this. It works well here on Ubuntu.

**Comment by wodim** [comment]
I am also unable to reproduce this on Windows. Is this still a problem?

**Comment by un1versal** [comment]
I cant reproduce: Linux Works for me

**Comment by un1versal** [comment]
Closing as its reported fixed in IRC
