### ISSUE TITLE
"Possible desync" error when connecting to a gateway

### ISSUE THREAD

**Issue by kartagis** [kvirc/KVIrc#1639]
Hi,
I am in a Slack channel and you can also connect using an IRC client. However, when I connect, I get the errors in the following screenshot. Is it me or KVIrc?

I am using `KVIrc Equilibrium 4.2.0, revision: 42021, sources date: 20120701, built on: 2013-10-21 12:24:40 UTC` and Ubuntu 14.04

![screenshot from 2015-09-30 10 04 47](https://cloud.githubusercontent.com/assets/1607518/10186624/3318fb6e-675b-11e5-9bcb-7a59c53930f9.png)

**Comment by un1versal** [comment]
Upgrade to nightly and retest.

https://github.com/kvirc/KVIrc/wiki/Downloading-KVIrc-source-or-binaries

Or compile your own.

**Comment by kartagis** [comment]
I upgraded to nightly, and that didn't fix it.

**Comment by un1versal** [comment]
@blindirc 

Since you added the last protocol expansions?

What do you think?

@kartagis 

Please attach to this report your:
- Current KVIrc build details
- OS information
- Which Network you are connected to
- Other pertinent information to help debug this.

**Comment by kartagis** [comment]
- OS is Ubuntu 14.04
- Network is cordova.irc.slack.com

**Comment by staticfox** [comment]
I've never used Slack, let me try to hunt down some documentation and see if I can manually figure it out since I don't have a slack account to test with. Can you paste the whole connection log (obviously blurring out sensitive info)? It doesn't seem like KVIrc is registering to the network.

**Comment by kartagis** [comment]
![screenshot from 2015-09-30 11 14 06](https://cloud.githubusercontent.com/assets/1607518/10187941/7748eae8-6764-11e5-8202-3e008210486b.png)

Mmm, the last bit makes me wonder if KVIrc is RFC1459-compliant.

**Comment by un1versal** [comment]
Try a different client and find out

**Comment by staticfox** [comment]
It is, the "IRCd" is not. Just like with twitch, just because you CAN turn something in to an IRC protocol doesn't necessarily mean you should (Although twitch's IRCd works pretty well for clients, it's just missing some RFC required modes but it's not really supposed to be used as a legacy IRC server anyways so what are you gonna do). The fact that KVIrc was unable to detect any modes means that their IRCd thing isn't returning 005 either correctly or flat out at all. I'm kinda nervous to see how botched their setup really is. Nevertheless, if I can find documentation I can probably write in a Slack handler for KVIrc.

**Comment by kartagis** [comment]
What kind of docs do you need?

**Comment by un1versal** [comment]
I would also aside from trying a different client to compare, I would also ask the network operators for information and report the issue (link to here if you must)

We cant assume its all the clients fault all the time.

FOr reference sake http://mail-archives.apache.org/mod_mbox/cordova-dev/201506.mbox/%3CCAE6O_-YoLd579Ssh=pqymWS5kCrdJKu=Nh28Vk7wrYE+J_4CzQ@mail.gmail.com%3E

IS that it?

**Comment by wodim** [comment]
This is a bug in how the 004 numeric is sent by the Slack gateway. It should look like this:

```
:cameron.freenode.net 004 wodim cameron.freenode.net ircd-seven-1.1.3 DOQRSZaghilopswz CFILMPQSbcefgijklmnopqrstvz bkloveqjfI
```

It instead looks like this:

```
:irc.tinyspeck.com 004 irc.tinyspeck.com IRC-SLACK gateway
```

That confuses KVIrc, which thinks your nickname is `irc.tinyspeck.com`. I have reported this bug to Slack and I'll close this issue it when they get back to me.

**Comment by un1versal** [comment]
relabeled issue as 3rd party bug and assigned to you.

**Comment by wodim** [comment]
Just for the record this is the support request I have sent

> Hello,
> 
> This is a developer of the IRC client KVIrc. Recently we found your IRC gateway does not work correctly with our IRC client. After some investigations, we found out the numeric 004 (RPL_MYINFO) is not sent correctly. It is sent like this:
> 
> :irc.tinyspeck.com 004 irc.tinyspeck.com IRC-SLACK gateway
> 
> When all numerics during login should include the user's nickname in first place. I.e., it should look like this:
> 
> :irc.tinyspeck.com 004 wodim irc.tinyspeck.com IRC-SLACK gateway
> 
> That can be checked against any other IRC server. Even though we can work around this at our side, I think it's better if you fix it.
> 
> PS: the numeric 004 should include the user and channel modes available, but this fix I have proposed would be enough for it to work--anyway, we encourage you to fully respect the protocol to avoid problems with any client.
> 
> "Server reply 004 RPL_MYINFO shows the servername, IRCd version, supported usermodes, supported channel modes, and channel modes with a parameter, for example:
> 
> <- :ircu.wiebe.netsplit.net 004 wiebe ircu.wiebe.netsplit.net u2.10.12.13-rc2 dioswkgx biklmnopstvrDR bklov"

**Comment by un1versal** [comment]
Have these guys said something yet?

**Comment by Kurt-von-Laven** [comment]
I received a quick reply when I mentioned that I could reproduce the issue described above. At least they are aware of the issue.

```
Yes, sadly our IRC gateway today does in fact not work correctly with KVIrc.

We don't have an ETA on the fix.

I know you prefer KVIrc, but many many other IRC clients do work today with the gateway. That's the best workaround I have for you today.
```

**Comment by un1versal** [comment]
Anything further?

@wodim can you post a link to report?

**Comment by wodim** [comment]
Last I heard from them:

> **Rob Campbell 91 days ago**
> 
> There has not been another IRC patch released yet, but we are in discussions of which elements are most important to work on. I'll bring this one up.
> 
> Thanks,
> 
> Rob

**Comment by staticfox** [comment]
So in essence, either way about it we can do nothing further except hard code slack support which I'd rather not do

**Comment by un1versal** [comment]
so what then we leave this open forever?
Wodim says they closed the report...

**Comment by wodim** [comment]
Why not.

**Comment by staticfox** [comment]
https://gist.github.com/staticfox/50e3202df2de976fc0853574c7722df7

**Comment by wodim** [comment]
These settings allowed me to connect

![image](https://user-images.githubusercontent.com/1001553/31693865-3dddb37a-b3a1-11e7-8895-c6b417356658.png)

Important to disable this next checkbox:

![image](https://user-images.githubusercontent.com/1001553/31693873-4b0ce8cc-b3a1-11e7-95df-6356f8be310d.png)

**Comment by wodim** [comment]
I love it when tickets get solved by themselves.

> 11:14 -!- Message of the day
> 
> Hello! We have news to share — we've decided it's time to close down the IRC and XMPP gateways to Slack.
> 
> After years of evolving, Slack is at the point where the gateways can no longer handle all of our features or security needs.
> 
> If you've been using the gateways for accessibility reasons, we're glad to let you know that it's now possible to navigate Slack by keyboard and with a screen reader — and we're making more improvements on a continual basis.
> 
> Still, we know this is a disruptive change, and we want to help with this transition in any way we can. Please follow this link to learn more about the upcoming changes:
> 
> slack.com/account/gateways
> 
> 11:14 -!- End of MOTD command
> 
> 
>

**Comment by ctrlaltca** [comment]
Closed as: worksforme^M^Mnobodyanymore
