### ISSUE TITLE
Broken icons on the Manage Themes dialog

### ISSUE THREAD

**Issue by Stanzilla** [kvirc/KVIrc#1645]
Picture says it all:

![manage_themes_-_kvirc_2015-09-30_22-04-52](https://cloud.githubusercontent.com/assets/75278/10205049/5ade1260-67bf-11e5-8fef-5e3444056d20.png)

**Comment by wodim** [comment]
#1314 #1309

**Comment by un1versal** [comment]
They not "broken" per say they are corrupted.

For reference sake the bug report that remains open is #1309 
#1314 and this one are closed as we dont need 3 reports for same issue.

Also Icon corruption bug only happens to the **big icons**. the small icons survive whatever #1309, #1314, and this reports cause is.
