### ISSUE TITLE
Recent windows builds lack Qt5Xml.dll

### ISSUE THREAD

**Issue by pragmaware** [kvirc/KVIrc#1656]
Qt5Xml.dll is not included in the recent windows builds.
libkviobjects.dll depends on it.

The symptom is that kvs object classes can't be found (and doing an /objects.load
will result in an error).

**Comment by un1versal** [comment]
Is https://github.com/kvirc/KVIrc/issues/1601 associated with this? Seems like it.

**Comment by pragmaware** [comment]
Right, it's probably the same issue.
Duplicate of #1601
