### ISSUE TITLE
KVIrc main window title does not change until you switch to other child window

### ISSUE THREAD

**Issue by staticfox** [kvirc/KVIrc#1662]
I'm probably wording this extremely weirdly, however when you initally connect to a network the title bar and task bar only show "No connection"

![](http://i.imgur.com/xqiseZW.png)
![](http://i.imgur.com/Wyp8Rgj.png)

---

Only when you join a channel does it update the title bar. I'm not sure if this is intentional or not, however only when you join channels does it fix itself.

![](http://i.imgur.com/zg0PY9z.png)
![](http://i.imgur.com/b0RS3oV.png)

Build info:
`KVIrc Aria 4.3.2, revision: git-5497-g73a5aea, sources date: 20151002, built on: 2015-10-08 07:49:34 UTC`

`OS: Microsoft Windows 7 Ultimate`

```
KVIrc 4.3.2 'Aria'

Runtime Info:
System Name: Windows Release : 6.1.7601
System Version: Windows 7 Ultimate (x64) Service Pack 1 (Build 7601)
Architecture: Intel64 Family 6 Model 60 Stepping 3

Build Info:
Build Date: 2015-10-08 07:49:34 UTC
Sources Date: 20151002
Revision Number: git-5497-g73a5aea
System Name: Windows-6.1
CPU Name: AMD64
Build Command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build Flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=G:/Projects/KVIrc/build/release
   Threads=Win32
Compiler Name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/cl.exe
Compiler Flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
```

**Comment by wodim** [comment]
a8b12f4 86f7177
