### ISSUE TITLE
Cursor position wrong

### ISSUE THREAD

**Issue by kartagis** [kvirc/KVIrc#1665]
When we type a long sentence, the cursor is actually right at the sentence but its indicator is 2-3px after the cursor itself. Allow me to demonstrate with the attached screenshot. 
![screenshot from 2015-10-09 09 40 28](https://cloud.githubusercontent.com/assets/1607518/10387474/51fe06da-6e6a-11e5-9a36-a15a915a40ef.png)

In the screenshot, cursor indicator is 2-3px after the end of the sentence, when it should have been at the end. Hitting Backspace at this point erases the last letter, in this case, e. Feel free to submit a new wording for this issue if it is not clear.

I'm on Ubuntu 14.04, Qt4, and KVIrc Aria 4.3.2 git-5475-g9a195de

**Comment by DarthGandalf** [comment]
Related: #1514 but this one is without emoji

**Comment by un1versal** [comment]
Try as I might, I cant see this issue, is it font or encoding related? #1514 seem to indicate encoding?

im on Qt5 here on a Variant (Ubuntu based but not Ubuntu) 14.04 LTS release.

**Comment by kartagis** [comment]
Text encoding is UTF-8. Even if it is font related, it still needs to be fixed, right?

**Comment by un1versal** [comment]
> Text encoding is UTF-8. Even if it is font related, it still needs to be fixed, right?

Like all other bugs reports also need fixing, I imagine :turtle:

**Comment by un1versal** [comment]
@kartagis So is this still a problem, you commneted on IRC that with latest build its not. Please can update ticket when you retest and confirm?

For future reference ensure that you are always using the absolute latest version available when submitting a report, submitting reports for already outdated versions is a bit senseless.

**Comment by kartagis** [comment]
I can confirm that this is no more when I actually type, but it is valid when I copy/paste from the web.

**Comment by un1versal** [comment]
Thanks, mmm Ill test that...

**Comment by kartagis** [comment]
Heh, there is a 5503 now. I'll test that.

**Comment by kartagis** [comment]
Using KVIrc Aria 4.3.2, revision: git-5503-g664c14a, I can confirm that this is no more. I'll reopen if anything comes up.

**Comment by kartagis** [comment]
I had said I'll reopen, hadn't I? :P Well, I am using `git-5523-g22b7356` now and the issue persists. Pleae see the below screenshot

![screenshot from 2015-10-15 11 20 26](https://cloud.githubusercontent.com/assets/1607518/10508301/f0f735fe-732e-11e5-9122-59333798bea4.png)

**Comment by un1versal** [comment]
Can you test with the same input font as the one used in output?

**Comment by kartagis** [comment]
They are the same, both `Sans-Serif`

**Comment by un1versal** [comment]
I really cant duplicate it, I tried everything and then some...

**Comment by kartagis** [comment]
My input settings as requested on IRC:

![screenshot from 2015-10-15 11 36 29](https://cloud.githubusercontent.com/assets/1607518/10508648/0d97843c-7331-11e5-8481-0bcbcaa87e68.png)

**Comment by un1versal** [comment]
Can you disable: `Warp cursor at end of line when browsing history` and `Enable the input history logging` restart KVIRc for good measure and see if you can still duplicate?

Ill do the opposite here as I have them disabled so I wonder if its _somehow_ related

**Comment by kartagis** [comment]
I am on `git-5551-gf9409ef` at the moment, disabled `Warp cursor at end of line when browsing history` enabled `Input history logging`, restarted KVIRc, copied a long line from web, pasted it in input and typed a lot of garbage; and the issue didn't seem to occur.

**Comment by un1versal** [comment]
We have to love these weird bugs...

**Comment by kartagis** [comment]
...and it comes back

**Comment by un1versal** [comment]
its a keeper.

**Comment by DarthGandalf** [comment]
An easy way to reproduce this: `fifififififififififififififififififififififififififififififififififififififififi`

`fi` is rendered as ligature, and consumes less space than `f` and `i` separately. It depends on font though, on some fonts it's not reproducible, if they don't use this ligature. `Sans Serif - Italic` is an example font which is affected.

Also not only input is affected, but output too. When you click a line where `fi` exists, text to the right of mouse moves left and right. I think, it's because of mouse selection.

**Comment by un1versal** [comment]
I can confirm with DarthGandalf foolproof method `fifififififififififififififififififififififififififififififififififififififififi` and If you are in Linux or can test this in Linux a 100% sure font that will be able to reproduce this to its extreme is FreeSerif font

But it is font dependant very odd.

**Comment by Heufneutje** [comment]
I'm having this issue on Windows as well. I just noticed it last night.

**Comment by un1versal** [comment]
Also related and probably same issue as https://github.com/kvirc/KVIrc/issues/1332
