### ISSUE TITLE
Tabcompletion breaks rendering of input

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1672]
Let's assume that only me is on channel.
1. type `dar` (with small letter `d`)
2. press Tab, it will expand to DarthGandalf
3. press Tab, it will just move cursor to end of Dar, without removing `thGandalf`
4. move cursor with arrows, cursor doesn't go out of Dar
5. type something (or press backspace), the input box will be fixed.

Using 664c14a on Gentoo with Qt4

**Comment by Stanzilla** [comment]
Can confirm on 

```
KVIrc 4.3.2 'Aria'

Runtime Info:
System Name: Windows Release : 6.2.9200
System Version: Windows 8 Professional (x64) (Build 9200)
Architecture: Intel64 Family 6 Model 58 Stepping 9

Build Info:
Build Date: 2015-10-12 23:51:14 UTC
Sources Date: 20151002
Revision Number: git-5520-gc8ae38f
System Name: Windows-6.2
CPU Name: AMD64
Build Command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build Flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler Name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler Flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
```

 which should be Qt5, no? (Standard AppVeyor release from d00p's page)

**Comment by un1versal** [comment]
Confirmed, but here this happens:

```
1   type dar (with small letter d)
2   press Tab, it will expand to DarthGandalf (and puts cursor in front of nick ready to type something)
3   press Tab, it will just move cursor to end of Dar, without removing thGandalf
4   move cursor with arrows, cursor doesn't go out of Dar
5   press tab again, puts cursor in front of nick ready to type something and the input box is also fixed.)
```

If I do 5 from your test it deletes thGandalf and reverts to dar :/

Qt5 here...

**Comment by kartagis** [comment]
Can confirm on Ubuntu 14.04 and 4.3.2 Aria  revision: git-5523-g22b7356

**Comment by staticfox** [comment]
Bug was introduced in https://github.com/kvirc/KVIrc/commit/c385848452898acb195fa428929c887c23048d03 I'll see if I can track it down further.
