### ISSUE TITLE
Confirmation dialog of restoring default script has too many buttons

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1675]
It says something like "Your copy of default scripts is fresh. Restore anyway? Yes/No/Cancel" (I see the message on Russian, so not sure how exactly it looks like on English)

The buttons No and Cancel do the same thing.

664c14a on Gentoo

**Comment by un1versal** [comment]
![capture](https://cloud.githubusercontent.com/assets/3521959/10563060/0661d54a-7571-11e5-9fb4-feaf07f537c7.PNG)

![capture1](https://cloud.githubusercontent.com/assets/3521959/10563061/06624304-7571-11e5-9575-ea8c8005cfc3.PNG)

What the issue? I think looks fine here though maybe the cancel button is one too many.

-edit-

The messages on dialog 1 themselves look like they need a once over.

**Comment by DarthGandalf** [comment]
> maybe the cancel button is one too many

Exactly. That's the issue (as I tried to express in the title)

**Comment by un1versal** [comment]
I agree, lets see if I can "fix" this. --- compiling a test as we speak

removed `,QMessageBox::Cancel` from

https://github.com/kvirc/KVIrc/blob/master/src/kvirc/kernel/KviDefaultScript.cpp#L132

If that works Ill push a PR

**Comment by un1versal** [comment]
Well that works...

![capture](https://cloud.githubusercontent.com/assets/3521959/10563102/163ed6f0-7573-11e5-9bdd-22baffa26979.PNG)

Pressing **No** closes dialog...

Do you think the messages can be improved? Ill do it in same PR.

**Comment by DarthGandalf** [comment]
Except "Clear custom scripts"/"Clear personal data" discrepancy, I don't see any issues with messages...

**Comment by staticfox** [comment]
Maybe something like..... `Would you like to restore it anyway?`

And @DarthGandalf he lives for improving messages :p

**Comment by DarthGandalf** [comment]
@blindsighttf2 Right. As a non-native English speaker, I didn't notice it :-P

**Comment by staticfox** [comment]
Actually... It may be wordy but `Your default script is already up to date.` would seem better IMO

**Comment by un1versal** [comment]
PR https://github.com/kvirc/KVIrc/pull/1676 up @DarthGandalf feel free to merge and thank you for bringing this up. :)

**Comment by staticfox** [comment]
Ahh! You made a typo in your comment! Hurry fix it! :smiley:

**Comment by un1versal** [comment]
What typo? :tongue:

**Comment by un1versal** [comment]
This is after 

![capture](https://cloud.githubusercontent.com/assets/3521959/10564274/3323b650-75a5-11e5-8723-ac5226fd0179.PNG)

![capture1](https://cloud.githubusercontent.com/assets/3521959/10564273/3303bb0c-75a5-11e5-9e09-5392a8df0030.PNG)
