### ISSUE TITLE
Unable to disconnect when not connected

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1682]
After disconnect, there is a delay before next attempt to connect.
During that delay, the button "Disconnect" on toolbar is "Connect", and there is no way to cancel the retry in future, except to close the whole context.

I believe 60ab43db81cba6b79023802c45d65a315b187db4 is the culprit, but I didn't check.

**Comment by staticfox** [comment]
Do you mean if you are connected and the server dies, there is no way to cancel the reconnect? Works on my end if that's what you mean.

```
[6:51:42 PM] [hades.arpa]: Server Terminating. Received SIGTERM
[6:51:42 PM] [SOCKET ERROR]: Remote end has closed the connection
[6:51:42 PM] Connection terminated [*redacted* (*redacted*)]
[6:51:42 PM] The connection terminated unexpectedly. Trying to reconnect...
[6:51:47 PM] Reconnect attempt aborted
```

EDIT: Seems to be a graphical glitch since the intended behavior of the button works as normal. Let me take a crack at fixing it.

**Comment by DarthGandalf** [comment]
Try to connect to a non-existing server (e.g. on localhost) to get Connection refused.
During attempt itself, I see button "Disconnect" for a moment, but the rest of time it's "Connect"...

Hmm... The button works, actually. It just looks incorrectly (icon and tooltip)
