### ISSUE TITLE
Linux only?: kvi_bigicon_helpforward and kvi_bigicon_helpback are ignored

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1683]
The 
https://github.com/kvirc/KVIrc/blob/master/data/pics/kvi_bigicon_helpforward.png
https://github.com/kvirc/KVIrc/blob/master/data/pics/kvi_bigicon_helpback.png
Both get ignored in Linux, apparently woks in Windows,,,

Looked at 
https://github.com/kvirc/KVIrc/blob/28ff60b1654707bb498e4702b4296df70fc4e6e0/src/kvirc/kernel/KviIconManager.h#L60-L61

and

https://github.com/kvirc/KVIrc/blob/fed17bbf5a6fb497173822efa543faaf7982ec6e/src/modules/help/HelpWidget.cpp#L197-L202

![capture](https://cloud.githubusercontent.com/assets/3521959/10600190/9b16c624-7700-11e5-8cd5-ac35c8600934.PNG)

No idea

**Comment by staticfox** [comment]
Windows:
![](http://i.imgur.com/nI70ZyK.png)

My linux mint VM:
![](http://i.imgur.com/vzouJR0.png)

Don't have access to a mac at the moment.

**Comment by ctrlaltca** [comment]
On a mac: ![mac](https://cloud.githubusercontent.com/assets/1631111/10604298/bdb83a0a-7723-11e5-8344-29b9bed74554.png)

**Comment by un1versal** [comment]
\o/ Linux bug only then.

Anyone have a clew why?

**Comment by ctrlaltca** [comment]
Borked installation? not up-to-date git working copy? maybe you have 2 kvirc installed in /usr and /usr/local and they mess up?

**Comment by un1versal** [comment]
nope. Its 100% up-to-date and correctly installed and definitely not 2 copies.

See @blindsighttf2 screenshot on Linux Mint.... also borked, so cant be that...

The files in question are also present and readable.

**Comment by staticfox** [comment]
I'm thinking it has something to do with this maybe? https://github.com/kvirc/KVIrc/blob/master/src/modules/help/HelpWidget.cpp#L104-L105

**Comment by un1versal** [comment]
Looks like somewhere to start poking

**Comment by staticfox** [comment]
I have it half patched. Started on it before class started.

**Comment by staticfox** [comment]
Hmm... interesting? Suddenly after updating I get this on windows now...
![](http://i.imgur.com/Ig2wcsJ.png)

EDIT: Now I'm just confused... that screenshot is from an appveyor build, while my local build has this:
![](http://i.imgur.com/04VfviR.png)

EDIT EDIT:
Yup. Lost.
Left is my dev build, right is appveyor
![](http://i.imgur.com/zxN7874.png)

**Comment by un1versal** [comment]
Nice gets better and better, not.

**Comment by wodim** [comment]
Depends on whether COMPILE_WEBKIT_SUPPORT is on or not, git gud guys

**Comment by un1versal** [comment]
> Depends on whether COMPILE_WEBKIT_SUPPORT is on or not, git gud guys

Im assuming that `-DWANT_QTWEBKIT=` is related to COMPILE_WEBKIT_SUPPORT

In that case then, in Linux it is not.`-DWANT_QTWEBKIT=` is **ON** by default according to the INSTALL docs. After reading your comment i specifically compiled with **`-DWANT_QTWEBKIT=ON`** and there's is no change here. Qt4 and Qt5 both present same result.
