### ISSUE TITLE
Missing icon and version on Windows

### ISSUE THREAD

**Issue by Stanzilla** [kvirc/KVIrc#1685]
In the `Programs and Features` control panel page, KVIrc is missing an icon and the version string:

![2015-10-22_03-46-52](https://cloud.githubusercontent.com/assets/75278/10654865/b2052612-786f-11e5-853c-f6adb483fc0f.png)

```
KVIrc 4.3.2 'Aria'

Runtime Info:
System Name: Windows Release : 6.2.9200
System Version: Windows 8 Professional (x64) (Build 9200)
Architecture: Intel64 Family 6 Model 58 Stepping 9

Build Info:
Build Date: 2015-10-12 23:51:14 UTC
Sources Date: 20151002
Revision Number: git-5520-gc8ae38f
System Name: Windows-6.2
CPU Name: AMD64
Build Command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build Flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler Name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler Flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
```

**Comment by un1versal** [comment]
Confirmed on Windows 7 as well. 
Open `Control Panel\All Control Panel Items\Programs and Features` scroll down and theres is no Icon. 

I suspect the issue is the correct icon size used in this view is missing from the icon file. Need to investigate this a little but if it is that should be easy fix.

**Comment by wodim** [comment]
related to NSIS I'd say

**Comment by staticfox** [comment]
+1 @wodim

**Comment by un1versal** [comment]
No idea, how can you find out this?

**Comment by Stanzilla** [comment]
Well NSIS is the installer, and he/me too guess it just fails to register/provide info to write into the registry.

**Comment by staticfox** [comment]
I can fiddle with this tonight and see if I can get it fixed. But yes it is
nsis related.

**Comment by staticfox** [comment]
Think I got it... testing now.

**Comment by Stanzilla** [comment]
![2015-10-24_01-12-13](https://cloud.githubusercontent.com/assets/75278/10706933/5d2ea6c6-79ec-11e5-886a-d307215fb06b.png)

\o/

**Comment by un1versal** [comment]
Nice one!
