### ISSUE TITLE
Splash screen loading bar is misaligned

### ISSUE THREAD

**Issue by staticfox** [kvirc/KVIrc#1687]
![](http://i.imgur.com/dJcTWzF.png)

Not sure if it's a code thing or a graphics thing, haven't looked in to it.

**Comment by un1versal** [comment]
Ill have a look, I cant really see this as in Linux its pretty much instant load.

Thx.

**Comment by un1versal** [comment]
This is near impossible to test in Linux, but https://github.com/kvirc/KVIrc/pull/1688 is 1 pixel higher which in turn should translate to the correct alignment based on your screenshot.
