### ISSUE TITLE
Groups or namespaces for aliases

### ISSUE THREAD

**Issue by nzde** [kvirc/KVIrc#1696]
Hi there,
is it possible to get alias groups like default and custom to make it easier to add commands please 
thank you 
Nzw1

**Comment by un1versal** [comment]
:-1: Im sorry, I dont see any benefit from this, you just create an alias (name it whatever you want) and add whatever you want to it. Couldn't be simpler or easier.

**Comment by wodim** [comment]
You can use namespaces... If I understood your question correctly.

**Comment by nzde** [comment]
its like when I create an alias it would be nice to have the option to create  folder to mange where my commands are kept i.e freenode ect

**Comment by un1versal** [comment]
mmm, OK, I see what you mean, but an alias is not network dependant it will work anywhere.

Can you give us an example of what exactly are you doing, in order to make this request make some more sense?

**Comment by nzw1** [comment]
solved

**Comment by nzde** [comment]
the Idea was to have inside Alias to have folders to mange/order where we had commands

**Comment by un1versal** [comment]
I see some value in this from a user organization point of view, even though alias are global. So Ill +1 this even though it wont stop aliases being misused where they are not intended.

**Comment by wodim** [comment]
@nzw1 you can create a namespace and then have aliases inside of it.

First, in the alias editor, you create the namespace by right-clicking the alias list:

![screen shot 2015-10-29 at 09 36 34](https://cloud.githubusercontent.com/assets/1001553/10813645/d33fd564-7e20-11e5-9343-5be9efa938a8.png)

You give it a name:

![screen shot 2015-10-29 at 09 36 57](https://cloud.githubusercontent.com/assets/1001553/10813651/d6142cae-7e20-11e5-8f23-46688c466e7e.png)

Then you right click it and add an alias inside of it:

![screen shot 2015-10-29 at 09 37 03](https://cloud.githubusercontent.com/assets/1001553/10813654/dc500dfe-7e20-11e5-8d9c-6ca3b90db5f9.png)

![screen shot 2015-10-29 at 09 37 11](https://cloud.githubusercontent.com/assets/1001553/10813656/e222e648-7e20-11e5-86b4-fda4f2e21ae7.png)

It is shown like this:

![screen shot 2015-10-29 at 09 37 14](https://cloud.githubusercontent.com/assets/1001553/10813658/e580f96a-7e20-11e5-9f5b-e8dba6ba75a4.png)

You add some code to that alias:

![screen shot 2015-10-29 at 09 37 47](https://cloud.githubusercontent.com/assets/1001553/10813663/ed933ece-7e20-11e5-9047-fb0aa16cbdd0.png)

And then you execute it using the syntax `/mynamespace::myalias`:

![screen shot 2015-10-29 at 09 38 14](https://cloud.githubusercontent.com/assets/1001553/10813666/f15a11fe-7e20-11e5-8f62-7eb239127c68.png)

**Comment by un1versal** [comment]
fantastic forgot about that... need to put that on wiki/faq

**Comment by un1versal** [comment]
created a wiki page based on this great how-to https://github.com/kvirc/KVIrc/wiki/How-to:-Use-namespaces-to-organise-aliases
