### ISSUE TITLE
Recent Channels list is never populated with any entries.

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1705]
Essentially like title says.

![2fx8869y](https://cloud.githubusercontent.com/assets/3521959/10938339/23749838-82f1-11e5-8204-82e88737d2de.png)

![capture1](https://cloud.githubusercontent.com/assets/3521959/10865921/38502950-8014-11e5-8bad-36d18af966d5.PNG)

You can join 1000 channels, not one gets added to this list, yet theres an option to clear it.

```
Build Date: 2015-10-31 07:10:14 UTC
Sources Date: 20151030
Revision Number: git-5613-gb8c034d
System Name: Linux-3.13.0-62-generic
CPU Name: x86_64
Build Command: /usr/bin/cmake
Build Flags: 
   MANDIR=man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler Name: /usr/bin/c++
Compiler Flags: N/A
```

**Comment by staticfox** [comment]
It's working fine for me on my end (win64). Can't really imagine how it'd be a linux bug? Anyone else having this problem?

**Comment by un1versal** [comment]
Ill test this on My Windows VM just to confirm.

**Comment by Heufneutje** [comment]
Works on my Windows machine as well.

**Comment by un1versal** [comment]
Anyone On Linux can confirm it doesnt work there? Clearly its a Linux bug only my Windows test VM also works fine.

**Comment by wodim** [comment]
It works well here on Linux.

**Comment by stkw0** [comment]
It works for me on Linux64 
![](http://oi67.tinypic.com/1zg7var.jpg)

**Comment by un1versal** [comment]
I cant make sense of this, it will not populate at all.

**Comment by un1versal** [comment]
I think I see whats going on, its related to a restored backup of settings, so not bug, if the settings folder wasnt created by KVirc it doesnt like it. even if permission/owner is apparently same.

**Comment by un1versal** [comment]
If you start fresh and configure everything from scratch it works, soon as you open an old backup settings file and copy its contents and paste in same newer file (with KVIrc not working of course, it doesn't like it at all and breaks all sorts. This being one of those it breaks.

 So IMO ts a bug somewhere as file permission and owner is untouched and are exact same as defaults and settings entries in files are exactly the same.

Just trying to find which file exactly causes this.

**Comment by un1versal** [comment]
Well Ill admit this was more PEBCAK then anything else,, solved now. Closing as invalid.
