### ISSUE TITLE
Default server list should be updated.

### ISSUE THREAD

**Issue by ghost** [kvirc/KVIrc#1706]
I've just installed KVirc on ArchLinux and I was surprised to see that a lot of dead URLs are in the default server list.
There's even a reference to irc0.dreamcast.com.

It should probably be easy to run a nmap script to see which servers are still up and therefore worth keeping.

**Comment by staticfox** [comment]
Yeah I've been meaning to do a full network list run through and kill off
dead ones and add new ones.

**Comment by un1versal** [comment]
marespiaut

+1, and if you found it in your heart to make a Pull Request fixing these things it would even be better

**Comment by ghost** [comment]
@un1versal I thought about it. I'll do it when I have time.
----- EDIT -----
Nevermind, here's a quick way to start seeing if the servers are still up

```
wget 'https://raw.githubusercontent.com/kvirc/KVIrc/master/data/config/serverdb.kvc'
grep Hostname serverdb.kvc | cut -d = -f 2 > url_list.txt
nmap -sn $(cat url_list.txt)
```

Here is a list of 141 dead URLs

```
Failed to resolve "aphrodite.portalx.org".
Failed to resolve "apollo.portalx.org".
Failed to resolve "ares.portalx.org".
Failed to resolve "arlington.va.us.skyyenet.org".
Failed to resolve "as.dal.net".
Failed to resolve "athena.portalx.org".
Failed to resolve "au.alphachat.net".
Failed to resolve "auckland.nz.galaxynet.org".
Failed to resolve "au.ipv6.alphachat.net".
Failed to resolve "aussie.sydney.oz.org".
Failed to resolve "b-network.azzurra.org".
Failed to resolve "brown.freenode.net".
Failed to resolve "calkins.freenode.net".
Failed to resolve "calvino.freenode.net".
Failed to resolve "chariot.adelaide.oz.org".
Failed to resolve "chat14.x-echo.com".
Failed to resolve "chat.ap.freenode.net".
Failed to resolve "cheapnet.azzurra.org".
Failed to resolve "crichton.freenode.net".
Failed to resolve "de.lightspike.net".
Failed to resolve "demeter.portalx.org".
Failed to resolve "efnet.demon.co.uk".
Failed to resolve "efnet.ipv6.xs4all.nl".
Failed to resolve "efnet.teleglobe.net".
Failed to resolve "einstein.freenode.net".
Failed to resolve "eos.portalx.org".
Failed to resolve "eu.alphachat.net".
Failed to resolve "eu.ipv6.alphachat.net".
Failed to resolve "eu.irc6.net".
Failed to resolve "fastweb.azzurra.org".
Failed to resolve "freei.us.galaxynet.org".
Failed to resolve "goethe.freenode.net".
Failed to resolve "gymnet.us.galaxynet.org".
Failed to resolve "hub.cc.tut.fi".
Failed to resolve "hub.il".
Failed to resolve "hub.uk".
Failed to resolve "ign.ie.quakenet.org".
Failed to resolve "iinet.perth.oz.org".
Failed to resolve "ipv6.chat.eu.freenode.net".
Failed to resolve "ipv6.syrolnet.org".
Failed to resolve "irc6.azzurra.org".
Failed to resolve "irc6.meganet.ru".
Failed to resolve "irc6.seb.org.ua".
Failed to resolve "irc6.tambov.ru".
Failed to resolve "irc6.tsure.ru".
Failed to resolve "irc.aau.dotsrc.org".
Failed to resolve "irc.baikal.net".
Failed to resolve "irc.c-plusnet.com".
Failed to resolve "ircd.arcti.ca".
Failed to resolve "irc.datacomm.ch".
Failed to resolve "irc.daxnet.no".
Failed to resolve "ircd.choopa.net".
Failed to resolve "ircd.desync.com".
Failed to resolve "irc.desync.com".
Failed to resolve "irc.desync.se".
Failed to resolve "ircd.he.net".
Failed to resolve "irc.dkom.at".
Failed to resolve "ircd.llnw.net".
Failed to resolve "ircd.nac.net".
Failed to resolve "ircd.snt.utwente.nl".
Failed to resolve "irc.easynews.com".
Failed to resolve "irc.efnet.ca".
Failed to resolve "irc.estpak.ee".
Failed to resolve "irc.estpak.ee".
Failed to resolve "irc.eu.abjects.net".
Failed to resolve "irc.eu.abjects.net".
Failed to resolve "irc.fei.tuke.sk".
Failed to resolve "irc.flashnet.it".
Failed to resolve "irc.fragglerock.org".
Failed to resolve "irc.freebsd.org.tw".
Failed to resolve "irc.freenet.de".
Failed to resolve "irc.fujisawa.wide.ad.jp".
Failed to resolve "irc.global-irc.net".
Failed to resolve "irc.i.cz".
Failed to resolve "irc.ipv6.alphachat.net".
Failed to resolve "irc.ipv6.cesnet.cz".
Failed to resolve "irc.ipv6.inter.net.il".
Failed to resolve "irc.ircgnet.net".
Failed to resolve "irc.ircgnet.net".
Failed to resolve "irc.leo.org".
Failed to resolve "irc.lightspike.net".
Failed to resolve "irc.nara.wide.ad.jp".
Failed to resolve "ircnet.realroot.be".
Failed to resolve "irc.nextra.sk".
Failed to resolve "irc.nightstar.net".
Failed to resolve "irc.oasis-net.net".
Failed to resolve "irc.oddnet.org".
Failed to resolve "irc.osanet.cz".
Failed to resolve "irc.othersideirc.net".
Failed to resolve "irc.ptptech.com".
Failed to resolve "irc.quakenet.eu.org".
Failed to resolve "irc.rma.edu".
Failed to resolve "irc.sci.kun.nl".
Failed to resolve "ircs.ircnet.ee".
Failed to resolve "irc.stv.su".
Failed to resolve "irc.terra.cl".
Failed to resolve "irc.tokyo.wide.ad.jp".
Failed to resolve "irc.tri-net.org".
Failed to resolve "irc.trusted-network.de".
Failed to resolve "irc.uib.no".
Failed to resolve "irc.uni-karlsruhe.de".
Failed to resolve "irc.uunet.nl".
Failed to resolve "irc.wh.verio.net".
Failed to resolve "itgate.azzurra.org".
Failed to resolve "jade.va.us.dal.net".
Failed to resolve "lem.freenode.net".
Failed to resolve "london.uk.eu.kewl.org".
Failed to resolve "miami.fl.us.othernet.org".
Failed to resolve "na.alphachat.net".
Failed to resolve "na.ipv6.alphachat.net".
Failed to resolve "nanterre.fr.eu.kewl.org".
Failed to resolve "ngnet.azzurra.org".
Failed to resolve "niven.freenode.net".
Failed to resolve "novel.fl.us.dal.net".
Failed to resolve "nz.austnet.org".
Failed to resolve "online.no.quakenet.org".
Failed to resolve "ops.ircgnet.net".
Failed to resolve "oslo1.no.eu.undernet.org".
Failed to resolve "sashimi.azzurra.org".
Failed to resolve "sbrize.azzurra.org".
Failed to resolve "sg.austnet.org".
Failed to resolve "splatterworld.de.quakenet.org".
Failed to resolve "ssitalia.azzurra.org".
Failed to resolve "ssl.atw.irc.hu".
Failed to resolve "sterling.freenode.net".
Failed to resolve "stlouis.mo.us.othernet.org".
Failed to resolve "stockholm.se.quakenet.org".
Failed to resolve "temphub.choopa.net".
Failed to resolve "thor.portalx.org".
Failed to resolve "tolkien.freenode.net".
Failed to resolve "urengoy.rusnet.org.ru".
Failed to resolve "us.lightspike.net".
Failed to resolve "vltmedia.se.galaxynet.org".
Failed to resolve "vogon.azzurra.org".
Failed to resolve "wineasy.se.quakenet.org".
Failed to resolve "wmgitalia.azzurra.org".
Failed to resolve "xs4all.nl.quakenet.org".
Failed to resolve "zaalphachat.net".
Failed to resolve "zahn.freenode.net".
Failed to resolve "zaipv6.alphachat.net".
Failed to resolve "zeus.portalx.org".
```

Note that this do not test if the URL redirect to a working IRC server but only if they redirect to a responding IP.

**Comment by ghost** [comment]
I'm currently scanning the other servers using (what I think to be) safe settings.
Here's the nmap command I use
`nmap -T 1 -p 6601,6660-6670,6697,7000,7070,7770-7780,8000-8002,9999 -v --append-output -oN result_irc.txt -Pn --open --script irc-info $(cat url_list.txt)`

**Comment by un1versal** [comment]
How do we know these servers are not just temporarily down. Freenode often take servers down for maintenance or because of DDoS attacks and they have them back up when they are ready, sometimes its days...

**Comment by staticfox** [comment]
Personally, I don't like having mainline physical servers in the server list as client and carrier servers are swapped out quiet often. Imo, it'd be better to just have RRs.

**Comment by un1versal** [comment]
Imo we should at least cleanup... maybe @marespiaut can submit a PR for this and we can merge and close this report.

**Comment by ghost** [comment]
Well, he listed `irc.eu.abjects.net` as being dead, but it's not. I'm not sure if he's only testing 1 IP in the RR or all, but occasionally servers go down, so testing at the wrong time might bring false positives.

**Comment by un1versal** [comment]
Thats what I said in https://github.com/kvirc/KVIrc/issues/1706#issuecomment-152829419

I wonder if theres not an easier and sure way to do this cleanup, other than testing servers in regular intervals over a longer time period?

**Comment by Heufneutje** [comment]
> Imo, it'd be better to just have RRs.

This sounds like the best solution to me. People can always add specific servers to their own server list if they want to.

**Comment by un1versal** [comment]
@Heufneutje Nice of you to volunteer :D thx. </sarcasm>

Another solution which you can also do is delete all servers and save, than import the list of servers from mirc, make a pr and hope for the best...

So :+1: to whoever ( Heufneutje )  does either one or the other.

**Comment by Heufneutje** [comment]
@un1versal If I had some spare time I would love to. I was merely stating my opinion on the matter.

**Comment by un1versal** [comment]
I love opinions but I lve pr's more :D

**Comment by Stanzilla** [comment]
Sync with https://github.com/hexchat/hexchat/blob/master/src/common/servlist.c maybe?

**Comment by ekolis** [comment]
from #1819:

kvirc always tries to connect to irc.quakenet.eu.org, which doesn't exist; is this a typo for irc.eu.quakenet.org? (That would be consistent with the other global servers.) Have we been DDOSing the European Union this whole time? ;)

Steps:
1. Attempt to connect to the Quakenet network without specifying a server
2. kvirc attempts to connect to the false EU server and fails with a DNS error

(Not sure why it always attempts to connect to the EU server - it's not the first server in the list, and I'm not in the EU...)

I can work around this bug by deleting the EU server from the server list, or by manually connecting to a different server (not to the network as a whole). Oddly setting a different server as a favorite has no effect; do favorites do something else?

```
Executable Information

KVIrc 4.9.1 'Aria'

Runtime Info:
System name: Windows Release : 6.2.9200
System version: Windows 8 (x64) (Build 9200)
Architecture: Intel64 Family 6 Model 58 Stepping 9
Qt version: 5.5.1
Qt theme: windowsvista

Build Info:
Build date: 2016-01-05 10:20:26 UTC
Sources date: 20160102
Revision number: git-6040-gb7fa661
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.5.1
```

**Comment by un1versal** [comment]
@ekolis thanks but that was fixed already... what I asked was no longer necessary. for this ticket.

**Comment by staticfox** [comment]
I believe this was already done. So rather then this being an on going issue, it should just be a routine task. Thus a ticket being open does not seem beneficial. Closing unless someone disagrees.

**Comment by un1versal** [comment]
its not been done

**Comment by un1versal** [comment]
it has been done, I should have checked...

fixed by https://github.com/kvirc/KVIrc/commit/8d141af183ff091554a60e3e3357fb0b39ff3f6c
