### ISSUE TITLE
Allow usage of C++11

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1707]
Or even C++14...

**Comment by staticfox** [comment]
+1million^∞

**Comment by pragmaware** [comment]
:+1:  for C++11.
I'm also pro C++14 as long as we determine that most of the compilers people use nowdays support it.

**Comment by DarthGandalf** [comment]
http://en.cppreference.com/w/cpp/compiler_support has the table.

Approximately:
C++11: GCC 4.8, Clang 3.1, MSVC 2013 (with some exceptions)
C++14: GCC 5.0, Clang 3.4, MSVC 2015
