### ISSUE TITLE
Option to turn off auto clipboard copy

### ISSUE THREAD

**Issue by Stanzilla** [kvirc/KVIrc#1709]
See title.

**Comment by un1versal** [comment]
How is this useful?

**Comment by staticfox** [comment]
Because when you're scrolling and accidentally drag along the chat, you lose whatever was in your clip board.

**Comment by Heufneutje** [comment]
:+1:

**Comment by un1versal** [comment]
Well in that case wouldn't it make sense to have something like, only add selection to clipboard after x seconds?

That way you have x time to remove selection and then not loose whatever you had in clipboard my making that mistake.

**Comment by staticfox** [comment]
I personally would just rather see an on/off toggle.

**Comment by DarthGandalf** [comment]
Alternative idea: copy to clipboard with Ctrl pressed.
Now with Shift pressed, colors are copied too.

**Comment by staticfox** [comment]
That, I could get behind.

**Comment by un1versal** [comment]
A good place for this would be the input tool bar a toggle on off or whatever for quick access

**Comment by Stanzilla** [comment]
I'd be fine with either an on/off toggle or with the <kbd>CTRL</kbd> way

**Comment by un1versal** [comment]
Im only thinking that this changes expected default behaviour so needs consideration on how its implemented.

**Comment by wodim** [comment]
It does not change the expected behaviour because the default behaviour would be the current behaviour, which is consistent with the default behaviour of all GUI IRC clients that exist.

**Comment by un1versal** [comment]
Yes, I was thinking of not adding options at all just changing defaults. no idea why I was thinking about that. Never mind
