### ISSUE TITLE
Broken registered users: use custom color in userlist

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1724]
Defining a custom color in user list for a registered user actually does not impact the user list entry it impacts the nick color on the output only.

Thats not what the name of the options suggests for a start.

Ive looked at KviIrcUserDataBase.cpp and its just gibberish to me.

![capture](https://cloud.githubusercontent.com/assets/3521959/10997865/9cc9b144-8488-11e5-9dcd-1d43121bf804.PNG)

```
Runtime Info:
System Name: Linux 3.13.0-62-generic
System Version: #102-Ubuntu SMP Tue Aug 11 14:29:36 UTC 2015
Architecture: x86_64

Build Info:
Build Date: 2015-11-06 12:26:51 UTC
Sources Date: 20151106
Revision Number: git-5667-g61e5141-dirty
System Name: Linux-3.13.0-62-generic
CPU Name: x86_64
Build Command: /usr/bin/cmake
Build Flags: 
   MANDIR=man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler Name: /usr/bin/c++
Compiler Flags: N/A
```

related:

https://github.com/kvirc/KVIrc/issues/608
https://github.com/kvirc/KVIrc/issues/876

**Comment by staticfox** [comment]
I'll test on Linux but this is from my windows build..
![](http://i.imgur.com/cHgsyuV.png)

**Comment by un1versal** [comment]
and gone
