### ISSUE TITLE
Highlight inactive window sound option not functioning.

### ISSUE THREAD

**Issue by Matakor** [kvirc/KVIrc#1730]
I've tested in the Sound System tab, and using that I get the test file to play, but in the Sound tab where I can actually customize the file, nothing plays. The file works in regular media player (music bee) and is an mp3 file.

**Comment by staticfox** [comment]
Hi! Can I get you to paste the output from `/echo $version`, the block of text found in `Help`->`About KVIrc`->`Executable Information` and your current Operating System. Thanks!

**Comment by Matakor** [comment]
echo::
KVIrc Aria 4.3.2, revision: git-5676-gff34b66, sources date: 20151107, built on: 2015-11-07 00:44:32 UTC

exec info::
KVIrc 4.3.2 'Aria'

Runtime Info:
System Name: Windows Release : 6.2.9200
System Version: Windows 8 Professional N (x64) (Build 9200)
Architecture: Intel64 Family 6 Model 60 Stepping 3

Build Info:
Build Date: 2015-11-07 00:44:32 UTC
Sources Date: 20151107
Revision Number: git-5676-gff34b66
System Name: Windows-6.2
CPU Name: AMD64
Build Command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build Flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler Name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler Flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc

**Comment by un1versal** [comment]
This is self compiled, have you tried one of our nightlies?

Im just asking though tbh I dont think there will be much difference as in Linux with current master compile I can duplicate this in Linux as well.

**Comment by Matakor** [comment]
Self compiled? I grabbed this from the nightly, using the windows binary option. I don't even have the programming software or the know-how to compile software. :P

**Comment by wodim** [comment]
Maybe you will have better luck converting it to other format, such as wav.

**Comment by un1versal** [comment]
Tiis affects all configurable events in 

![capture](https://cloud.githubusercontent.com/assets/3521959/11021428/d8f71b96-8638-11e5-94cc-165d3e732706.PNG)

Is there a limitation on the formats supported for these? If so where can such limitation documents be found?

**Comment by pragmaware** [comment]
If you use a *.wav file does it play?
What happens if you try /snd.play <path_to_sound_file> ?

**Comment by Matakor** [comment]
*.wav file does indeed work. Good to know, but a pain to convert. :P

**Comment by un1versal** [comment]
what a silly limitation... wav because admit t, wav is such an open format.

**Comment by IceN9ne** [comment]
If I set my Sound System to phonon, I was able to play mp3s.  It works for the events that play sounds.

On Ubuntu, I had to install `phonon4qt5-backend-gstreamer` to enable phonon.

I'm not sure what the Windows equivalent would be.
