### ISSUE TITLE
Input text redraws incorrectly on backlash with preceeding spaces

### ISSUE THREAD

**Issue by staticfox** [kvirc/KVIrc#1731]
as discussed on IRC, start your message with a space, add a /, type whatever and the whole things messes up.

**Comment by wodim** [comment]
Only with enchant support compiled, it seems.

**Comment by staticfox** [comment]
Er yeah.. I'm pretty sure I caused this then :x I'll fix when I get home.

**Comment by wodim** [comment]
@staticfox
