### ISSUE TITLE
Let KVIrc's Addon web repository draw from Github

### ISSUE THREAD

**Issue by staticfox** [kvirc/KVIrc#1733]
Instead of checking http://www.kvirc.de/app/ (because you know, that gets updated way too much so we should really give it a break :smile:), let's just generate a static list and put it in the root directory of https://github.com/kvirc/kvirc-scripts and have KVIrc download the addons from the repository... I'm not sure if Github has a policy on letting people use them as a file server though. Just an idea. That or I could set up a mirror on my box of the repository and we can have clients download off of that. Either way, the addons manager could use some love.

**Comment by un1versal** [comment]
+1 Or get the website to sync data from Github repo once in a while?

Not sure how any of that is setup tbh, but any updates to https://github.com/kvirc/kvirc-www ends up being sync within an hour or so.

@HelLViS69 knows this stuff backwards,

**Comment by un1versal** [comment]
relabel as bug since only one addon is available via this and that even doesnt work properly.

**Comment by un1versal** [comment]
clearly some of the old team members are no longer active and rarely have the time to do anything anymore. shame all that insight and knowledge into the source is lost.

**Comment by un1versal** [comment]
This isnt really a bug but its not really just a feature request but its a blocker anyway cause themes are drawn from website and addons we 1 addon showing up only and its broken at that

Since theres no replies either Ill assume lack of interest and that broken is OK.

**Comment by wodim** [comment]
If the only reason to keep this as a blocker is that the themes dialog already has the same thing, given that webkit is gone and so is the same thing from the themes dialog, this is no longer a blocker.
