### ISSUE TITLE
ChannelsJoinDialog: Missing password edit field label

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1734]
1) The Password label is defined in https://github.com/kvirc/KVIrc/blob/master/src/modules/channelsjoin/ChannelsJoinDialog.cpp#L88 however; this label is never shown.  
This dialog needs a bit of love.

Current dialog.
![capture](https://cloud.githubusercontent.com/assets/3521959/11030071/83efca4a-86c3-11e5-9849-655aa2eabd15.PNG)

**Comment by wodim** [comment]
Remove the "Name:" label and use setPlaceholderText() on the QLineEdits to add "Name" and "Password" on each one of them.

**Comment by Heufneutje** [comment]
:+1:

**Comment by un1versal** [comment]
Ive managed to make the **Password** label show up in https://github.com/un1versal/KVIrc/commit/7936b5337e9c5c6f75a59cf91685eb77efa1360a

SO now it looks like

![capture](https://cloud.githubusercontent.com/assets/3521959/11030882/bb9bda42-86c8-11e5-8cfc-1bc2e62dd69c.PNG)

Just needs to assign positions to these so they conform to the expected layouts FTW. :tongue:

KVIrc way of doing dialogs adding text and positioning varies too much from dialog to dialog, some ialogs are more noticeable than others; this one for instance is a good example of how grid layouts are implemented inconsistently.

**Comment by un1versal** [comment]
> Remove the "Name:" label and use setPlaceholderText() on the QLineEdits to add "Name" and "Password" on each one of them.

Im trying but its not immediately obvious to me what to do with that.

**Comment by un1versal** [comment]
> Remove the "Name:" label and use setPlaceholderText() on the QLineEdits to add "Name" and "Password" on each one of them.

Done https://github.com/un1versal/KVIrc/commit/1426c24d68056290a3aaecfddcb0b66349bd48b6  
![capture](https://cloud.githubusercontent.com/assets/3521959/11034463/bba2ee2a-86e3-11e5-9bee-882e5e8d007a.PNG)
Thats not quite what Im looking for; adding text to the field itself is not what other of this type dialogs do either (it doesnt look bad but I rather make them all consistent for now.

**Comment by un1versal** [comment]
Solution for now

![capture](https://cloud.githubusercontent.com/assets/3521959/11030882/bb9bda42-86c8-11e5-8cfc-1bc2e62dd69c.PNG)
