### ISSUE TITLE
KVirc connects twice to any or all servers on startup

### ISSUE THREAD

**Issue by KeiroD** [kvirc/KVIrc#1735]
Hi,

I'm on Linux Mint 17.2 using Cinnamon as my DM. Currently, when I start KVirc up under this setup, any servers that I've configured to auto-connect on start for KVirc immediately connects to all of the servers. And a second set of the exact same servers are also opened at the same time, resulting in duplicate connections when I only want one connection per network.

What is causing this?

Sidenote: Another friend of mine that's also using Linux Mint has encountered a similar issue as noted in the IRC we go to:

```
[08:02:22AM] <Ari> Interesting that KVIrc connects twice on XFCE
[08:02:33AM] <Ari> it doesn't do that on Mate or Cinnamon
[08:15:43AM] <Keiro> Oddly, it connects twice for me on Cinnamon.
[08:15:52AM] <Keiro> I'm still working on figuring out what the exact cause of it is, Ari.
```

**Comment by un1versal** [comment]
What version of KVirc is this? Can you copy and paste the about/Executable Information tab contents and past here please.

**Comment by WorkingC** [comment]
Hi, I am said friend. This is on Linux Mint 17.2, on the XFCE desktop environment. Here's the executable info:

```
KVIrc 4.2.0 'Equilibrium'

Runtime Info:
System Name: Linux 3.16.0-38-generic
System Version: #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015
Architecture: x86_64

Build Info:
Build Date: 2013-10-21 12:25:22 UTC
Sources Date: 20120701
Revision Number: 42021
System Name: Linux-3.2.0-37-generic
CPU Name: x86_64
Build Command: /usr/bin/cmake
Build Flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler Name: /usr/bin/c++
Compiler Flags: -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 
```

**Comment by KeiroD** [comment]
Oops, forgot to do that.

Mine is below:

```
KVIrc 4.2.0 'Equilibrium'

Runtime Info:
System Name: Linux 3.16.0-38-generic
System Version: #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015
Architecture: x86_64

Build Info:
Build Date: 2013-10-21 12:25:22 UTC
Sources Date: 20120701
Revision Number: 42021
System Name: Linux-3.2.0-37-generic
CPU Name: x86_64
Build Command: /usr/bin/cmake
Build Flags:
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler Name: /usr/bin/c++
Compiler Flags: -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2
```

**Comment by un1versal** [comment]
Can you guys try and report back with with a recent KVIrc version, please see https://github.com/kvirc/KVIrc/wiki/Downloading-KVIrc-source-or-binaries

That 4.2.0 wont get any fixes and is outdated now.

**Comment by KeiroD** [comment]
Unfortunate. I've added the Ubuntu PPA as per the wiki description.

I'll report back here in about an hour or two the results of the upgrade as I'm heading out shortly here.

**Comment by WorkingC** [comment]
Still present in 4.3.2. 

One thing I think is worth noting is that I do have KVIrc as a startup program, which might be related. If I close KVIrc, and then start it manually, it doesn't connect twice. It only does this on XFCE for me. Does not occur in Cinnamon or MATE.

```
KVIrc 4.3.2 'Aria'

Runtime Info:
System Name: Linux 3.16.0-38-generic
System Version: #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015
Architecture: x86_64

Build Info:
Build Date: 2015-11-08 15:12:21 UTC
Sources Date: 20151108
Revision Number: git-5681-gab5d1bc
System Name: Linux-3.19.0-32-generic
CPU Name: x86_64
Build Command: /usr/bin/cmake
Build Flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler Name: /usr/bin/x86_64-linux-gnu-g++
Compiler Flags: -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 
```

**Comment by un1versal** [comment]
So to duplicate you recon you need to setup KVIrc as startup program, else it works as desired?... OK Ill test

**Comment by un1versal** [comment]
I cannot duplicate this at all with CINNAMON, on LM 17.3, as a startup application or not, it works as intended.
If it is only with XFCE, or something similar and specific; I would be somewhat inclined to blame it on some 3rd party interference causing this.
Lets see what other people say what their findings are or what they think can cause it.

However Im not sure if it makes a difference I self compile my builds.

```
KVIrc 4.3.2 'Aria'

Runtime Info:
System Name: Linux 3.13.0-62-generic
System Version: #102-Ubuntu SMP Tue Aug 11 14:29:36 UTC 2015
Architecture: x86_64

Build Info:
Build Date: 2015-11-09 15:36:53 UTC
Sources Date: 20151109
Revision Number: git-5688-gc119fba
System Name: Linux-3.13.0-62-generic
CPU Name: x86_64
Build Command: /usr/bin/cmake
Build Flags: 
   MANDIR=man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler Name: /usr/bin/c++
Compiler Flags: N/A
```

**Comment by KeiroD** [comment]
Issue doesn't persist on my setup...

_However_... I wonder. I reconfigured KVirc because for whatever reason, KVirc's previous install didn't persist under the new KVirc, so I had to totally reconfigure it all again.

Does this behavior happen if you have a Network AND any given server configured under that Network set to connect on startup?

If so... I may have had that enabled on the previous install which produced that behavior.

Edit, build info:

```
KVIrc 4.3.2 'Aria'

Runtime Info:
System Name: Linux 3.16.0-38-generic
System Version: #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015
Architecture: x86_64

Build Info:
Build Date: 2015-11-08 15:12:21 UTC
Sources Date: 20151108
Revision Number: git-5681-gab5d1bc
System Name: Linux-3.19.0-32-generic
CPU Name: x86_64
Build Command: /usr/bin/cmake
Build Flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler Name: /usr/bin/x86_64-linux-gnu-g++
Compiler Flags: -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 
```

**Comment by un1versal** [comment]
Theres two of these.

Network side
![capture](https://cloud.githubusercontent.com/assets/3521959/11046580/25eef3d6-8726-11e5-9d48-bc92174b8295.PNG)

Server side
![capture1](https://cloud.githubusercontent.com/assets/3521959/11046579/25e69628-8726-11e5-839c-6bae14f3214f.PNG)

If you select on both there; **Connect to this network at startup**, bingo = your "bug".

**Comment by WorkingC** [comment]
> If it is only with XFCE, or something similar and specific; I would be somewhat inclined to blame it on some 3rd party interference causing this.

I can confirm that it is XFCE and its autostart that causes the issue, not KVIrc itself. Session and Startup disregarded my settings, so it runs KVIrc twice - once from startup and then once from reloading my session.

**Comment by un1versal** [comment]
Im not sure there's anything to be done here KVIrc side, given that tidbit.

Feel free to report it to the XFCE guys and link back to this report if you like.

IF anything happens feel free to update here in meanwhile, if this report needs reopening or whatever.

Thx.
