### ISSUE TITLE
ChannelsJoinDialog: Odd alignment between label/edit field

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1736]
Split from https://github.com/kvirc/KVIrc/issues/1734

Most other dialogs, pretty much specify something like this.

 `This field label: [________________________________]`

this dialog shows however already breaks this and goes towards.

`This field label:`
`[________________________________]`

imo this needs to be consistent with how other dialogs do it, but at this stage just fixing the missing label would go a long way.

---

![capture](https://cloud.githubusercontent.com/assets/3521959/11030882/bb9bda42-86c8-11e5-8cfc-1bc2e62dd69c.PNG)

Assist please

**Comment by un1versal** [comment]
![capture](https://cloud.githubusercontent.com/assets/3521959/16202675/9ab5479a-370e-11e6-942c-413ba97d12a9.PNG)

**Comment by IceN9ne** [comment]
Fixed in ca157d4
