### ISSUE TITLE
texticons.kvc never written to user config area

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1742]
If you edit any texticons via Kvirc Settings and click apply
![capture](https://cloud.githubusercontent.com/assets/3521959/11150868/2ab79860-8a22-11e5-85b9-b87cce2a77dc.PNG)

The **texticons.kvc** file that lives in `~/.config/KVIrc/config` is never updated

![capture1](https://cloud.githubusercontent.com/assets/3521959/11150869/2abb9bea-8a22-11e5-9a25-9b2051911e95.PNG)

This is especially a problem for any internal themes such as Aria/Minimal Dark which means the user cant write to system paths, while for intance with user installed themes the updates are written to the respective theme dir in `/home/nss/.config/KVIrc/themes/sometheme`

```
KVIrc 4.3.2 'Aria'

Runtime Info:
System Name: Linux 3.13.0-68-generic
System Version: #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015
Architecture: x86_64

Build Info:
Build Date: 2015-11-13 15:29:59 UTC
Sources Date: 20151112
Revision Number: git-5704-gb1dba92
System Name: Linux-3.13.0-68-generic
CPU Name: x86_64
Build Command: /usr/bin/cmake
Build Flags: 
   MANDIR=man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler Name: /usr/bin/c++
Compiler Flags: N/A
```

**Comment by DarthGandalf** [comment]
My workaround for this is to remove `texticons.kvc` from global dir, as removing icons from UI doesn't work. (I hate these "text icons")

**Comment by un1versal** [comment]
What I dont understand is why the ~/.config/KVIrc/config/texticons.kvc is created when you 1st run KVIrc but any user changes, never gets written to there if you're using internal themes. (the  issue you describe)

The `~/.config/KVIrc/config` - thats where things (including this) should be written to and read from, no? Then from the user theme directory.

So priority order of reading data should be, Global being a the defaults (initial priority) -> `~/.config/KVIrc/config` being user made changes -> `~/.config/KVIrc/themes/` (overriding any `~/.config/KVIrc/config`) if exists)

Isnt that right?

**Comment by pragmaware** [comment]
Can you try the latest git and look at the console after editing the text icons?
It should tell you where it's saving them.

**Comment by un1versal** [comment]
Nope, cant see anything... no messages anywhere

**Comment by pragmaware** [comment]
Interesting. I see it even twice when I press "OK" in the options dialog.
Hm.. maybe "console" is wrong: I meant "have a look at the terminal after editing the text icons"...

**Comment by un1versal** [comment]
yea, I dont usually run kvirc via terminal but I shall

**Comment by un1versal** [comment]
```
Saving text icons to /home/un1versal/.config/KVIrc/themes/I_O-Dark-2.1.9/texticons.kvc
Saving text icons to /home/un1versal/.config/KVIrc/themes/I_O-Dark-2.1.9/texticons.kvc
Saving text icons to /home/un1versal/.config/KVIrc/themes/I_O-Dark-2.1.9/texticons.kvc
Saving text icons to /home/un1versal/.config/KVIrc/themes/I_O-Dark-2.1.9/texticons.kvc
```

The only problem is that dir does not exist... 

```
un1versal@un1versal:~/.config/KVIrc/themes$ ls -all
total 8
drwxr-xr-x  2 un1versal vboxsf   27 Jan  3 01:54 .
drwxr-xr-x 14 un1versal vboxsf 4096 Dec  9 00:57 ..
-rw-r--r--  1 un1versal vboxsf   14 Jan  3 01:51 current-splash
un1versal@un1versal:~/.config/KVIrc/themes$ 
```

```
un1versal@un1versal:~$ ls -all /home/un1versal/.config/KVIrc/themes/I_O-Dark-2.1.9/texticons.kvc
ls: cannot access /home/un1versal/.config/KVIrc/themes/I_O-Dark-2.1.9/texticons.kvc: No such file or directory
```

**Comment by pragmaware** [comment]
OK. Try it now.
