### ISSUE TITLE
[Feature Request] Link previews

### ISSUE THREAD

**Issue by Stanzilla** [kvirc/KVIrc#1746]
Many chat clients have those now, maybe like this 
![2015-11-15_08-09-21](https://cloud.githubusercontent.com/assets/75278/11167751/3bae51e6-8b70-11e5-97f6-74ed65d89661.png) (Slack) but only with the title of the page? Should be enough in most cases.

**Comment by Stanzilla** [comment]
Oooor, display the title of the page in the hover popup of the link.

**Comment by wodim** [comment]
I'm not sure, but I think it can be scripted.

**Comment by AndrioCelos** [comment]
I use the following script for that: https://gist.github.com/AndrioCelos/3fe0d12e28f766ff0130

**Comment by Stanzilla** [comment]
That doesn't really work for me, I added it as a popup handler, is that correct? It downloads ever item I right click now.

**Comment by AndrioCelos** [comment]
That's the idea, but it should also show the menu when the download finishes.
Run the script using `/parse` or the script tester.

**Comment by un1versal** [comment]
He probably wants previews powered by magic (where nothing is downloaded but still somehow works)

**Comment by Stanzilla** [comment]
Well ofc it has to be downloaded to be displayed but it should be silent, with this script the download dialog popups up all the time which is not really great.

**Comment by un1versal** [comment]
This has now been added by @AndrioCelos in https://github.com/kvirc/kvirc-scripts/tree/master/URLTitle

Any further requests or contributions to improve or features/issues etc should be reported in the scripts repository.
