### ISSUE TITLE
Crash when choosing an external image file as a text emoticon

### ISSUE THREAD

**Issue by VegaDark** [kvirc/KVIrc#1747]
In the latest version, I tried to edit and add new emoticons, but kvirc crashes and don't let me do it.

**Comment by un1versal** [comment]
See https://github.com/kvirc/KVIrc/issues/1742, are you using a internal theme? If yes that explain some of your issue.

Also what version KVIrc are you using (latest is very vague)? In the About KVirc dialog thers a **Executable Information** tab please copy and paste that information to this report.

Finally upgrade your KVirc to a current nightly and test again see https://github.com/kvirc/KVIrc/wiki/Downloading-KVIrc-source-or-binaries

**Comment by wodim** [comment]
Confirmed.

**Comment by VegaDark** [comment]
I don't use any theme as far as I know when I deactivated it from the installation. The reference of my version is this:
KVIrc 4.2.0 'Equilibrium'

Información en tiempo de ejecución:
Nombre del sistema: Windows Release : 6.1.7601
Versión del sistema: Windows 7 Professional Service Pack 1 (Build 7601)
Arquitectura: x86 Family 20 Model 1 Stepping 0

Información de compilación:
Fecha de compilación: 2012-07-04 14:48:08 UTC
Fecha de las fuentes: 20120701
Número de revisión: 6190
Nombre del sistema: Windows-5.1
Nombre de la CPU: x86
Comando de compilación: C:/Programmi/CMake 2.8/bin/cmake.exe
Opciones de compilación: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/kvirc-4.2.0/build/release
   Threads=Win32
Nombre del compilador: C:/mingw/bin/g++.exe
Opciones del compilador: N/A

**Comment by un1versal** [comment]
@VegaDark your build is outdated anyway, please upgrade to nightly.
