### ISSUE TITLE
Some keys not working after switching channel window

### ISSUE THREAD

**Issue by DaVukovic** [kvirc/KVIrc#1749]
## Edit This is a input line focus issue see https://github.com/kvirc/KVIrc/issues/1749#issuecomment-235821690

Hello, 

very new to this. 

Maybe I encountered a bug. I use a  german keyboard layout and on the right to my "ß" key, there is the key for the apostroph: " ' "

On the left to my "1" key is a key which looks like that: ^

both keys are working if I set the encoding to UTF-8. But after I switched the channel from one to another, I have to select it again for make it work.

I made sure to set it all to UTF-8 in the system settings, but it seems not to work. Maybe some of you got an idea.

System info: 

```
KVIrc 4.3.2 'Aria'

Laufzeitinformationen:
Systemname: Linux 3.13.0-63-generic
Systemversion: #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015
Architektur: x86_64

Erstellungsinfo:
Erstellungsdatum: 2015-11-25 14:31:58 UTC
Datum der Quelldateien: 20151123
Revisionsnummer: git-5730-gf6795df
Systemname: Linux-3.13.0-63-generic
CPU-Name: x86_64
Erstellungsbefehl: /usr/bin/cmake
Erstellungs-Flags: 
   MANDIR=man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler-Name: /usr/bin/c++
Compiler-Flags: N/A
```

Thanks in advance

Greetings

**Comment by un1versal** [comment]
What have you set as system locale in your Linux OS?

I asked a German KVIrc user about this and he uses UTF-8 everywhere and apparently it works fine for him. So we need to exclude some OS setup blurb. (why that should be an issue when you select UTF-8 in KVIrc internally idk.)

Maybe someone can shed some light into this.

**Comment by DaVukovic** [comment]
Maybe this is usefull...

locale:

```
LANG=de_DE.UTF-8
LANGUAGE=de:en
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```

Screenshots from settings:

![bildschirmfoto1](https://cloud.githubusercontent.com/assets/7235787/11443029/09b1b6ac-951a-11e5-88bc-5123027f6726.png)
![bildschirmfoto2](https://cloud.githubusercontent.com/assets/7235787/11443033/0e0c5f86-951a-11e5-8fc0-e97ac28a5f7a.png)

Thanks for helping.

Cheers

**Comment by d00p** [comment]
In den Einstellungen habe ich beim Encoding beidemale "Sprachkodierung benutzen" drinstehen, locales sind gleich, tut wunderbar

**Comment by un1versal** [comment]
After what we discussed at IRC, Im convinced your issue is related (window focus) to main kvirc window focus that you need to go away from and come back to in order the keys work again. but no idea where to fix this tbh.

maybe someone else if familiar with code enought to know.

(as a historical reference MDI windowing was dropped, so maybe this is related to that somehow)

@staticfox thoughts? You had a MDI windowing cleanup in the works?

**Comment by DaVukovic** [comment]
As @un1versal  said, 

The keys are working, if I change the focus of the main window. For example if I press CTRL+shift+l to open the alias manager and close that again, the keys are working fine until I change the channel window from one channel to another. The same happens if I minimize the window completely and maximize it again, or at split screen if I click on any other window and come back to KVIrc. At any single step of those, the keys are working if the focus is on the main window then. But not anymore after I change the channel. 

@d00p:

I changed my settings to match yours, but still no luck.

**Comment by wodim** [comment]
Confirmed on Linux only.

**Comment by wodim** [comment]
This bug predates the MDI -> SDI transition. When dead keys are not working, it is because `KviInputEditor::inputMethodEvent` is not being called at all when you hit those keys. May it be a Qt bug?

**Comment by un1versal** [comment]
not completely fixed

user reported

```
[08:35:18] <David1977> still no fix for me
[08:35:31] <David1977> after the channel switch no ' for me
[08:36:18] <David1977> absolutely same behaviour. If I change to a browser and then come back, the key is lost
[08:36:24] <David1977> but äöü still work
```

**Comment by un1versal** [comment]
Yep its fixed, seems David had a hick up compiling new version adn now has confirmed this indeed fixed.

**Comment by DaVukovic** [comment]
Unfortunately I have to reopen that issue. 

Just compiled KVIrc today on another machine and getting the same issues like before. 

Version from today (with the issue):

KVIrc Aria 4.9.1, revision: git-6234-gf629728, sources date: 20160102, built on: 2016-02-21 06:08:00 UTC

Older version (with the issue was being fixed):

KVIrc Aria 4.9.1, revision: git-6033-gcad079d, sources date: 20160102, built on: 2016-01-04 11:23:05 UTC

If you need more info, let me know.

System is a Ubuntu 14.04.4

**Comment by staticfox** [comment]
What version of Qt?

**Comment by un1versal** [comment]
> What version of Qt?

Ubuntu 14.04 has Qt 5.2 ish

@1977David Ill reopen this for time being.

**Comment by DaVukovic** [comment]
@staticfox 

I just can't check as I'm not at home atm. But the version I have installed on the working machine are 5.2.x. As both machines running the same Ubuntu (and are updated well) I suppose it will be 5.2 on the other machine as well. 

@un1versal:

Thx for re-opening.

**Comment by Arfrever** [comment]
I can reproduce some problem which is maybe the same bug.
But I do not use any special keyboard layout and I use Fcitx input method framework (with Mozc to enter Japanese text).
Qt 5.5.1, Fcitx 4.2.9, Fcitx-Qt5 1.0.4

**Comment by un1versal** [comment]
@Arfrever and is that with the latest KVIrc nightly version? Can you post your /about.kvirc contents of the Executable Details Tab?

**Comment by DaVukovic** [comment]
I guess this is all you need 

```
KVIrc 4.9.1 'Aria'

Laufzeitinformationen:
System name: Linux 3.13.0-77-generic
System version: #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016
Architektur: x86_64
Qt version: 5.2.1
Qt theme: fusion

Erstellungsinfo:
Build date: 2016-02-21 06:08:00 UTC
Sources date: 20160102
Revision number: git-6234-gf629728
System name: Linux-3.13.0-77-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.2.1
```

lsb-release:

```
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
```

**Comment by un1versal** [comment]
@1977David is this still an issue?

**Comment by un1versal** [comment]
ping @1977David

**Comment by DaVukovic** [comment]
at least not an issue anymore with:

KVIrc Aria 4.9.2, revision: git-6386-g9010eb6, sources date: 20160102, built on: 2016-04-13 06:15:04 UTC

Didn't have the time to test with a newer version.

**Comment by un1versal** [comment]
thanks, ill close this now and if you have any further issues theres other things to try... like compiling your KVIrc against Qt 5.5.1, thers an issue open https://github.com/kvirc/KVIrc/issues/1949 if you are still using 14.04 LTS based OS.

thx

**Comment by DaVukovic** [comment]
I'm facing the same issue again:

about: 

```
KVIrc 4.9.2 'Aria'

Laufzeitinformationen:
System name: Linux 4.4.0-31-generic
System version: #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016
Architektur: x86_64
Qt version: 5.5.1
Qt theme: fusion

Erstellungsinfo:
Build date: 2016-07-27 16:07:19 UTC
Sources date: 20160727
Revision number: git-6816-g96bf84f
System name: Linux-4.4.0-31-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.5.1
Features: IRC, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Phonon, Webkit, Perl, Python, Enchant, Qt5, KVS
```

OS: Ubuntu 16.04 64bit

Edit:

The problem exists, if the focus is on the inputline and after I clicked on the chat-window (for example to select something with the mouse) and then click back to the input line...then I can't do "'" with the button next to my "ß"-button on my german keyboard layout.

**Comment by bigtomtom** [comment]
hi, Is there any update on this issue?

**Comment by wodim** [comment]
This is a problem with dead keys on Linux I experienced myself. It's about our own implementation, because regular QLineEdits didn't show the buggy behaviour.

**Comment by bigtomtom** [comment]
I find that Kvirc 4.2 works good on RHEL6. However, on RHEL7 4.2 cannot be installed, so I installed 4.9. Then problem came up. Too bad:-(

**Comment by DaVukovic** [comment]
@wodim 

Does that mean, there won't be a fix? I reported that issue over a year ago and each version I tried behaves in the same way.

**Comment by wodim** [comment]
It will be fixed before a new release occurs.

**Comment by Arfrever** [comment]
It seems that, even without commit 32c9b9ce86f6fbacce5cd14f1b1948cca2f8db77, I am no longer able to reproduce this problem, maybe due to recent upgrade of Qt from 5.7.* to 5.9.*.
