### ISSUE TITLE
Inappropriate Taskbar Highlights w/scrolling over while unfocused

### ISSUE THREAD

**Issue by Freyaday** [kvirc/KVIrc#1753]
In Windows 10 (and presumably other OSes, haven't tested) KVIrc lights up its taskbar icon when it's scrolled while unfocused. Before Windows 10, this ability was not standard to Windows, though it was available using third-party programs, and now with W10, it's a standard feature. Lighting up the taskbar in this manner is inappropriate and annoying--"Help help I'm being scrolled!!"? It is a notification full of sound and fury, signifying nothing.

**Comment by DarthGandalf** [comment]
Did you fix the issue in 2 hours by yourself?

**Comment by ctrlaltca** [comment]
PEBCAK, i suppose.
