### ISSUE TITLE
phonon with Qt5 yeilds no audio

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1756]
This ticket is here to serve as a reminder for phonon + Qt5 is broken, the only working sound system is qt provided by qtmultimedia5 (qtmultimedia5-dev)

 After we compile with these libraries installed https://github.com/kvirc/KVIrc/blob/6357c4cc07277d3fe690cc3161aa41667eba06cf/doc/INSTALL.txt#L125-L127 phonon support is compiled in and fully detected, and it appears as an option in KVIrc

However issue is, that after selecting **phonon** as under preferences -> sound systems and running tests and audio support doesn't work and only is supported via qtmultimedia5 which appears as **qt** in sound system.

Since I could never make this work I have removed `libphonon4qt5-dev libphonon4qt5experimental-dev libphonon4qt5experimental-dev libqt5svg5-dev libqt5webkit5-dev` from readme in https://github.com/kvirc/KVIrc/commit/0faa84288edec7f9fd2904dcbdc1404a7034558c

We should fix it or remove it entirely and if its fixed. reading the dependencies is easy picking.

**Comment by un1versal** [comment]
solved it.

needs phonon4qt5-backend-gstreamer

**Comment by ctrlaltca** [comment]
Adding support for qt5multimedia (it's called qtmobility in qt4) is probably a nice idea.

**Comment by un1versal** [comment]
atm you need to specify WANT_PHONON=0 with Qt5 if you only want qt5multimedia (for those who follow the INSTALL.txt to handle the audio for you, it would also be nice if phonon libs aren't installed but qt5multimedia is that you dindt have to suffer all the errors in the world about phonon being missing while configuring or something more gracious.
