### ISSUE TITLE
Add a dedicated output window for the script tester

### ISSUE THREAD

**Issue by staticfox** [kvirc/KVIrc#1758]
AFAIK, if you run anything such as `echo "whatever"`, `whatever` will be printed to the first(?) console window. Perhaps maybe we should add a dedicated output window within the script tester itself?

EDIT: By window I mean something in the same pane. Like, maybe a buffer where my wonderfully drawn red box is:  

![](http://staticfox.net/screenshots/1449731259.png)

**Comment by un1versal** [comment]
+1

the editors in general need bringing up-to-date and being consistent (they look somewhat consistent but they are not)

as a workaround you can undock this window and put it at bottom of the main program window with an active context showing.

**Comment by IceN9ne** [comment]
I use "/echo -d" and just dump it to the debug window when testing scripts.  Not what you asked for, but a potential workaround.
