### ISSUE TITLE
Status bar incorrectly shows snomasks as user modes.

### ISSUE THREAD

**Issue by AndrioCelos** [kvirc/KVIrc#1759]
I'm on an InspIRCd network, and the status bar ended up looking like this:
**[redacted]** Andrio (+orsAGKLOagklt)
in response to this:

```
:redacted 221 Andrio :+ors
:redacted 008 Andrio +AGKLOagklot :Server notice mask
```

on 64-bit Windows 10 build git:git-5743-g698e0d1.

**Comment by un1versal** [comment]
Try a recent build, this was fixed already I think in https://github.com/kvirc/KVIrc/commit/514d9135afdae7b6c3ca8f6bdf0ec1b6231db620

As a side note, before reporting issues, please try to always use latest version available, sometimes these things get fixed without notice.

please report back.

**Comment by AndrioCelos** [comment]
It is indeed fixed; sorry about that.

**Comment by un1versal** [comment]
no problem, it happens.
