### ISSUE TITLE
Fix AppVeyor build

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1769]
For some reason 64 bit build started to try to link with 32 bit OpenSSL

https://ci.appveyor.com/project/DarthGandalf/kvirc/build/0.0.0.0.1-branch-master-build-953/job/o7y22nlqdkalmamq#L1581

**Comment by un1versal** [comment]
64-bit builds are now broken as a result so d00p builds have ben misaligned for a while now I suspect.
