### ISSUE TITLE
Appveyor: StrawberryPerl 5.20.2.1 broken and approved. causes mayhem in our lovely bug free project.

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1773]
This ticket is here only in order to track progress on package version chocolatey side,

I wonder why this was so sudden as its been working until now. but blame lies with **StrawberryPerl 5.20.2.1** packages.

workaround merged in master by Dessa in https://github.com/kvirc/KVIrc/commit/4640e16b5ae30e707b66c12193bb118cdc97b280

```
c:\cygwin\bin\bash : /usr/bin/bash: /cygdrive/c/Strawberry/perl/lib/core/config.h: No such file or directory
At line:6 char:5
+     c:\cygwin\bin\bash -c "/bin/cat .appveyor.perl >> /cygdrive/c/Strawberry/per ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (/usr/bin/bash: ...le or directory:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

c:\cygwin\bin\touch : /usr/bin/touch: cannot touch '/cygdrive/c/Strawberry/kvirc_workaround': No such file or directory
At line:7 char:5
+     c:\cygwin\bin\touch /cygdrive/c/Strawberry/kvirc_workaround
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (/usr/bin/touch:...le or directory:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Command executed with exception: /usr/bin/touch: cannot touch '/cygdrive/c/Strawberry/kvirc_workaround': No such file or directory
```

https://github.com/kvirc/KVIrc/blob/fbe86a9d3cbc3e36f3d4a0b2a49bfef4f1abb479/.appveyor.yml#L69-L71

No windows builds :(

**Comment by DarthGandalf** [comment]
Cygwin builds? o_O
KVIrc doesn't really build in Cygwin...
Just some tools of it are used instead of PowerShell tools.

2015-12-15 15:47 GMT+00:00 un1versal notifications@github.com:

**Comment by un1versal** [comment]
https://chocolatey.org/packages/StrawberryPerl thx Dessa.

We look with some sad frown and wonkey eyed at @gep13 for accepting a knowing broken package and hope  @alanstevens and https://chocolatey.org/profiles/railmeat to update strawberry perl packages in chocolatey to a non broken version :D 

@dessa fixed it by forcing a non broken version in https://github.com/kvirc/KVIrc/commit/4640e16b5ae30e707b66c12193bb118cdc97b280, but that's just not ideal.

**Comment by DarthGandalf** [comment]
Why do you think it's "knowing broken package"?

2015-12-15 17:02 GMT+00:00 un1versal notifications@github.com:

**Comment by un1versal** [comment]
read the comments in https://chocolatey.org/packages/StrawberryPerl and Dessa said so in IRC.

**Comment by un1versal** [comment]
See https://github.com/alanstevens/ChocoPackages/issues/72 if anything happens there Ill update here in order to try an track progress on this.

**Comment by gep13** [comment]
@un1versal please accept my apologies.  That package version should not have been approved.  I have removed the listed version from Chocolatey.org, and it will no longer be installed by default.  Instead, you will get the previous version, which was working for you.

Should the package be updated, based on your issue that you opened, the new package version will again be added to chocolatey.org, assuming it is proven to work correctly.

Apologies again.

**Comment by un1versal** [comment]
@gep13 welcome and thank you for quick reply ;) things like this are bound to happen. :wink:  I sure hope it wasn't coming off too harsh. Sense of humour is a bit funky also... So excuse the oddities. :grin: 

Im not sure how chocolatey,org works exactly but Ive opened a PR to test the next version out and see if that's working better. See https://github.com/alanstevens/ChocoPackages/pull/73, if you have any suggestion how to best proceed the advice and insight will surely be welcome.

Thanks for removing that broken package, Im sure more people will sleep easier tonight knowing that. :

Regards and thanks again.

**Comment by un1versal** [comment]
fixed upstream closing here...

**Comment by gep13** [comment]
In all honesty, I am not sure when, if at all, that PR will get accepted :cry: Alan has sort of stepped away from maintaining his packages due to other committments, so unless the other maintainer picks up this request, it might go unanswered.  Since we rely on community contributions, if this application is one that you use a lot, we would welcome any contributions that you could make.  For instance, I could add you as a maintainer for the application.

In terms of keeping things working as part of your CI, it probably makes sense to take a fixed version, that you know works, rather than automatically installing every new version.  Only do that once you have tested the application elsewhere and you know it works.

**Comment by un1versal** [comment]
Ideally we would test a version before it gets accepted as a replacement in chocolatey but we/I cant do that until its already in there (either as a beta or something) that would be a semi-sane and easy way to go without disturbing anything too much and maybe it would benefit others as well...

If thats possible I wont mind giving it a wirl and see how that goes. The other team members are quite happy with the version that works but to me personally given the info about the current maintainer that version will soon get old quick. So Ill make a small effort there.

**Comment by un1versal** [comment]
maybe its better if I push that pacjage to an active maintainer who already has an account setup and chocolatey stuff setup.

**Comment by gep13** [comment]
@un1versal that "might" work, but the ideal would be for you to take ownership of the package.  Getting an account set up on Chocolatey is very simple, and I can get you added as a maintainer.  @ferventcoder already has a LOT of packages, and I don't think he will be in a position to take on more.  His main focus, like mine, is to add features/fix bugs within Chocolatey itself.  A better option if you are not in a position to maintain, would be to reach out to @dtgm who "might" be able to help out.

**Comment by un1versal** [comment]
well lest see what he says, Ive put my name on package and made a PR https://github.com/ferventcoder/chocolatey-packages/pull/104. if he declines as is his right, then open an account and we try that... Is that OK?

Is it possible btw to put package in pre-release so we can force that version on our CI and test it out before you give it final blessing?

btw thanks for help so far ;)

**Comment by gep13** [comment]
> @un1versal said...
> Is it possible btw to put package in pre-release so we can force that version on our CI and test it out before you give it final blessing?

Again, the ideal would be that the package is tested somewhere else, before pushing to Chocolatey.org.  For instance, you can push package to a MyGet.org feed, test them as part of your CI process, and once you are happy that they work, you can push them to Chocolatey.org.

**Comment by un1versal** [comment]
Thats what I thought, sadly...
