### ISSUE TITLE
popup error when right-clicking active channel

### ISSUE THREAD

**Issue by LW-archlinux** [kvirc/KVIrc#1775]
Aria 4.3.2 , git-5836-g4640e16  
GCC 5.3.0 , QT 5.5.1 , phonon, no KDE
$ uname -a 
Linux obelix 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux

[15:41:56] [KVS] Runtime error: A popup menu cannot be popped up twice
[15:41:56] [KVS]   In script context "OnWindowPopupRequest::default", line 1, near character 1

Everytime i right-click the active channel i get these 2 lines.
Most of the time the right-click menu does show, but not always.

**Comment by LW-archlinux** [comment]
GCC 5.3.0 , QT 5.5.1 ,  x86_64

**Comment by ghost** [comment]
Confirmed.  Bug appeared for me after de-selecting the "Use tree window list" theme setting.  Using default scripts only.
