### ISSUE TITLE
RFC: enable friendly commandline mode by default

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#1786]
What do you think? I think 99% of the users find the default to be confusing.

I can't think of a good reason to have KVS mode by default.

**Comment by un1versal** [comment]
+1

99% of all statistics are made up on the spot.

**Comment by Heufneutje** [comment]
:+1:

**Comment by DarthGandalf** [comment]
Yes!

**Comment by wodim** [comment]
I made the change with 044a3da but I wrote the wrong bug #. Anyway, case closed.
