### ISSUE TITLE
kvs boolean error false is not false?

### ISSUE THREAD

**Issue by craftwar** [kvirc/KVIrc#1789]
echo $str.cmp("aBC", "abc", false)
echo $str.cmp("aBC", "abc", 0)

output is
-32
0

Build Info:
Build Date: 2015-08-01 20:02:52 UTC
Sources Date: 20141230
Revision Number: 30289
System Name: Windows-6.2
CPU Name: AMD64
Build Command: C:/CMake64/bin/cmake.exe
Build Flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/Users/d00p/KVIRC/git/build/release
   Threads=Win32
Compiler Name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler Flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc

**Comment by un1versal** [comment]
Can you please update your build and retest and let us know the outcome? 

see https://github.com/kvirc/KVIrc/wiki/Downloading-KVIrc's-nightly-source-or-binaries

**Comment by craftwar** [comment]
same
I use d00p's 64bit nightly build

**Comment by pragmaware** [comment]
You must use $false. "false" is interpreted as a (non empty) string which
in boolean context evaluates to true.
Il 27 dic 2015 4:50 AM, "un1versal" notifications@github.com ha scritto:

**Comment by craftwar** [comment]
Thanks

I think this should be added into document, every1 will think false is what they want.

**Comment by un1versal** [comment]
@craftwar documentation sure needs improving some, if you can submit a PR that would also be great and fastest way t get this done.

**Comment by wodim** [comment]
That's how the language is and how programming overall works... Where to put this doc change?

**Comment by ctrlaltca** [comment]
Documentation already exists for both `$true` and `$false`.
They could be also documented around here: https://github.com/kvirc/KVIrc/blob/c2c21e466be8929a6bb91fcbf258dd36b1922322/src/kvirc/kvs/parser/KviKvsParser.cpp#L2163
