### ISSUE TITLE
labels in edit/set text fields

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1790]
Its should be obvious which field does what but only by typing in each one you find out what they are for.
Left is Channel
Right is Password

![capture](https://cloud.githubusercontent.com/assets/3521959/12008944/81b581b4-ac59-11e5-83c3-1db812e968d7.PNG)

We should design dialogs that are consistent and follow same standards applied in other dialogs.
FYI I tried deciphering how to do this myself, but After banging my head against https://github.com/kvirc/KVIrc/blob/ad7de10f2e041f0368afac5ab60257761df6b5cf/src/kvirc/ui/KviSelectors.cpp#L891-L898 I gave up.

**Comment by wodim** [comment]
I already told you about it yesterday:

```
m_pChanLineEdit->setPlaceholderText(__tr2qs("Channel Name"));
```

Anyway the layout of that dialog is awful...

**Comment by un1versal** [comment]
No, setPlaceholderText is not how other dialogs do this.

in this case it should be like Join channels dialog for consistency sake.

![capture](https://cloud.githubusercontent.com/assets/3521959/12008968/0f26f166-ac5c-11e5-9539-3a07acdf074d.PNG)

> Anyway the layout of that dialog is awful...

Many of our dialogs are awful so I agree with that assessment, whoever is doing drugs while doing these should stop. :p

**Comment by un1versal** [comment]
@pragmaware I could have done same as in 5e0a1cb17b7f9eb2fec3f62bdb7fe1aea8d7c84e but as I noted above and in c6d1b9fe595f0bc3393eef8591cc83aa76cf69e2 we already have too much dialog consistency problems, your workaround is but a temporary stop gap hiding the problem.

I dont mean to sound ungrateful :) but that dialog is simply awful. 

So Im reopening this until a later date, where I can figure out how to fix the problem properly or someone else who hates this as much as I helps out in doing it right..
