### ISSUE TITLE
Code is using the "register" storage class

### ISSUE THREAD

**Issue by ctrlaltca** [kvirc/KVIrc#1793]
C++11 deprecates the "register" storage class: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4193.html#809
C++17 will probably remove it definitively: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4340

Since e98d60a32fe1648b8694f82ba1da489eaa828e42 KVIrc compiles following c++11 so, at best, the "register" declarations are ignored.
I propose to just remove them.

**Comment by wodim** [comment]
I think I found them all... So I'll leave this open by now. (Except `ppport.h` which seems to be generated automatically)

**Comment by wodim** [comment]
Let's say this is fixed now.
