### ISSUE TITLE
fix default position on enable for classic window list ~~Drop Classic Window List option.~~

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1797]
It looks awful with more than one network, its all over the place.

With one network is sort of passable...
![capture](https://cloud.githubusercontent.com/assets/3521959/12046182/b082583e-aeaa-11e5-9e9b-e02050a80f3f.PNG)

Pragma says that this is suppose to be at the bottom, so its also broken.

**Comment by Heufneutje** [comment]
When everything is right underneath each other it looks passable with multiple networks as well, but at that point it looks very similar to the tree list. So I agree that this doesn't really have a reason to exist anymore.

**Comment by un1versal** [comment]
That said I would never use this, I like some sanity, so neither here nor there to my personal usage + like I said according to pragma this is supposed to be at the bottom, not the side, so its also broken as is.

**Comment by Heufneutje** [comment]
You mean it's supposed to be docked at the bottom of the window by default when you choose to use the classic list? Cause you can drag it there yourself just fine.

**Comment by un1versal** [comment]
I cannot drag this anywhere, Linux side.

**Comment by un1versal** [comment]
It makes even less sense when its at the bottom with say 2 networks and more channels than the width... :-1: this view is insane mode.

And also the alert colors, because the background is light you cant have the same format as the tree window list if the theme is dark. I doubt many themes out there actually take this into account, but havent checked and wont check.

**Comment by wodim** [comment]
We have it because mIRC had it. I don't understand what's wrong with it all of the sudden.

![daytime](https://cloud.githubusercontent.com/assets/1001553/12050110/881c5bec-aef0-11e5-8547-1f1fc8b9e430.jpg)

![mirc](https://cloud.githubusercontent.com/assets/1001553/12050111/89dac64e-aef0-11e5-9567-3ea903b1231b.gif)

**Comment by un1versal** [comment]
> We have it because mIRC had it. I don't understand what's wrong with it all of the sudden.

Im not sure if youre being sarcastic or what.

**Comment by wodim** [comment]
I am not being sarcastic. A lot of features of KVIrc (and other IRC clients) were taken from mIRC.

And again, I don't understand what's wrong with that feature in particular. It works perfectly well, whether you like it or not is not relevant... Just don't use it.

**Comment by AndrioCelos** [comment]
You can click the space at the top of the list and drag it to any edge.
Also, you can set the minimum width of the buttons, in the theme configuration, wide enough to allow only one column.

**Comment by ghost** [comment]
Works fine. This mode also allows you to move it to the top for a "tab like" list.  Try using a narrower window list to make it look better.

I see nothing wrong with keeping it.

**Comment by un1versal** [comment]
While have a conversation with pragma it was mentioned this could be dropped, this issue is to gain feedback on that.

So, while everyone is up fro keeping it (thats fine), but then the default positioning should be fixed, again I say this because pragma said this is supposed to be at the bottom per default not at the side (at least when you first turn it on) so I assume something has gone wrong somewhere.

**Comment by wodim** [comment]
You mean it should be moved to the bottom when it's activated?

**Comment by un1versal** [comment]
That's what pragma said when I showed him a screenshot, his words were, "lol thats suppose to be at bottom." Only as you can test yourself, when first activated its default position is where screenshot shows. Even when I drag it to bottom, and turn it off, when I turn it back on, it wont remember that it was in bottom. (I wonder if the settings aren't being saved bug has anything to do with that last part.)

make sense?

**Comment by un1versal** [comment]
So drop this as a feature request for removal and just leave it to get the default initial position handled...
