### ISSUE TITLE
Console window doesn't render on KDE5 while using default KDE theme (Breeze)

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1799]
As reported by Fleck.

I was going to look at it, and reproduced on fresh Kubuntu VM, but then learnt that Fleck worked it around by changing KDE theme.

Sometimes it renders last shown channel, sometimes not.

![gkxmqsr](https://cloud.githubusercontent.com/assets/325092/12048969/7768a63c-aed9-11e5-952b-6a67daedb592.png)
![anz6ufy](https://cloud.githubusercontent.com/assets/325092/12048971/7a630f3a-aed9-11e5-8fcb-543b007d0db2.png)

**Comment by wodim** [comment]
All console windows are affected by this and I could reproduce it with Plastique on Qt 5.

```
kvirc -style plastique
```

**Comment by wodim** [comment]
Oh, that was not Plastique but Breeze. Well, the problem here is that we can't give a background to a QComboBox with Breeze using a stylesheet.
