### ISSUE TITLE
Remove splash screen

### ISSUE THREAD

**Issue by pragmaware** [kvirc/KVIrc#1808]
With modern CPUs and SSDs the KVIrc startup time is negligible.
The splash screen stays on screen less than a second and one can't even see what's in it.
I propose to remove it and keep the image only in the about dialog.
This will save yet more startup time and few bytes in the executable.
Votes open :)

**Comment by un1versal** [comment]
not everyone has ssds and modern computers, but Im fine with --nosplash for a trial

> I propose to remove it and keep the image only in the about dialog.

Im fine with that too

**Comment by Stanzilla** [comment]
:+1:

**Comment by wodim** [comment]
I vote for its complete removal. I don't have an SSD and I only get to see it when it's half transparent.

**Comment by ghost** [comment]
Sounds good.

My attempt at removing it: 6bbcc26c

Edit:
_sigh_ Not sure how that . got deleted from data/man/kvirc.de.1

oh well, pragma said he'd do it anyways. I'll see how close I got to pragma's removal. ;)
