### ISSUE TITLE
broken spellchecker correction in c6d1b9fe

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1809]
type a word wrong for e.g. I picked `coalecence` to mis-type

![capture](https://cloud.githubusercontent.com/assets/3521959/12078084/ab4e4158-b1fb-11e5-9a78-ee31fe7f8a61.PNG)

Then right click and select correct spelling from list, and you end up with extra e (in this case added to word (other words add other letters)
![capture1](https://cloud.githubusercontent.com/assets/3521959/12078083/ab48e4c4-b1fb-11e5-9149-7e1d14a8c9be.PNG)

If you correct that second word again by picking `coalescence e` you end up with a further added letter.

![capture](https://cloud.githubusercontent.com/assets/3521959/12078087/12e47738-b1fc-11e5-9439-f5f3edeb40e0.PNG)

```
KVIrc 4.9.1 'Aria'

Runtime Info:
System name: Linux 3.13.0-71-generic
System version: #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015
Architecture: x86_64
Qt version: 5.2.1
Qt theme: fusion

Build Info:
Build date: 2016-01-03 08:03:29 UTC
Sources date: 20160102
Revision number: git-6017-gc6d1b9f
System name: Linux-3.13.0-71-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.2.1
```

I think the recent input box fixes broke this...

**Comment by DarthGandalf** [comment]
> I think the recent input box fixes broke this...

That's why unit tests are useful... which KVIrc doesn't have.

**Comment by un1versal** [comment]
Then it should:D (easier said than done)... a feature request for those unit tests would probably help.. no?

**Comment by pragmaware** [comment]
Writing unit tests for everything in such a big program is hard.
It would require more code than the program itself.
It's also very hard to test UI features: one would need to clearly separate "data model"
code from the "view code". Almost impossible :D

**Comment by DarthGandalf** [comment]
I'm pretty sure there is some way to test GUI even without clear
separation, even though it's not as nice.
This is not very easy task, but benefits would be huge.

2016-01-04 0:07 GMT+00:00 Szymon Tomasz Stefanek notifications@github.com:

**Comment by pragmaware** [comment]
Heh...I agree that benefits would be huge, but unfortunately also the costs...
