### ISSUE TITLE
System information is incorrect on Windows 10

### ISSUE THREAD

**Issue by Heufneutje** [kvirc/KVIrc#1810]
Both the runtime info in the about dialog and the OS information in the CTCP VERSION reply state Windows 8, despite the fact that I'm running Windows 10.

**Comment by un1versal** [comment]
please post more information, like copy and paste the executable information tab contents and paste it here or provide screenshots, not everyone uses windows or windows 10

**Comment by Heufneutje** [comment]
I figured that wasn't really necessary since it should be easy to reproduce, but here you are:

```
KVIrc 4.9.1 'Aria'

Runtime Info:
System name: Windows Release : 6.2.9200
System version: Windows 8 (x64) (Build 9200)
Architecture: Intel64 Family 6 Model 42 Stepping 7
Qt version: 5.5.1
Qt theme: windowsvista

Build Info:
Build date: 2016-01-03 07:54:21 UTC
Sources date: 20160102
Revision number: git-6017-gc6d1b9f
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.5.1
```

**Comment by un1versal** [comment]
Yea, not everyone uses windows or windows 10 even ;), but in any case a issue report should come with this as minimum information see https://github.com/kvirc/KVIrc/wiki/Submitting-a-bug-report#information-required-when-making-a-bug-report-via-github-issues

I think @Dessa added these Win10 bits in https://github.com/kvirc/KVIrc/commit/5cede3476e1dc62814a3c078a4caf9cd2813dcd5 a while back.

**Comment by Heufneutje** [comment]
Alright. I'll also add my Windows version string for reference here.

```
Microsoft Windows [Version 10.0.10586]
```

**Comment by un1versal** [comment]
@Heufneutje if you read the comment in https://github.com/kvirc/KVIrc/commit/5cede3476e1dc62814a3c078a4caf9cd2813dcd5

```
- fix #1601
- fix msvc14 build
- add Windows 10 identifier to KviOsInfo, even though it will not work until we will actually *target* win10 (which will probably never happen)
```

seems that this is intentional and known

**Comment by Dessa** [comment]
this actually existed since win 8.1 see https://msdn.microsoft.com/en-us/library/windows/desktop/ms724834%28v=vs.85%29.aspx right below the OS table.
as at least vista changed some network api (i have seen warnings when targetting win7 a while back; which were later fixed) i don't think bumping the value in the CMakeLists makes sense for everyone, unless we drop xp support at some point.
if someone wants to do it anyway for a local build (like i do it so i catch issues eventually) please see here: https://msdn.microsoft.com/en-us/library/6sehtctf.aspx

**Comment by DarthGandalf** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/dn481241(v=vs.85).aspx

> Manifesting the .exe for Windows 8.1 or Windows 10 will not have any impact when run on previous operating systems. You can also add this to your .rc file if you already have it defined.

Looks like it's fine to _target_ Win 8/10 while still _supporting_ Win XP

**Comment by wodim** [comment]
We could change this so it says "Windows 8 or higher", because I can see many people complaining.

**Comment by un1versal** [comment]
> We could change this so it says "Windows 8 or higher", because I can see many people complaining.

Or do what DarthGandalf suggests

**Comment by Heufneutje** [comment]
Personally I'm more a fan of @DarthGandalf's suggestion. "Windows 8 or higher" just looks kinda bad because it's very vague.

**Comment by DarthGandalf** [comment]
Moving discussion from unrelated #1819 

@un1versal wrote:

> > I would hardly consider displaying the wrong OS information to NOT be a bug...
> 
> It was done with reason, so since its intentional its not a bug. Its turned into a feature request as its up to whoever understands all the implications and reasons for deciding on how best proceed to make a decision.

@DarthGandalf wrote:

> It's obviously a bug, as the shown information is wrong.
> There are some technical reasons behind it, but it's the case for every bug - there is some reason behind it. That doesn't mean that it can't and it
> shouldn't be fixed.

@un1versal wrote:

> bugs are not intentional in my book, but I suppose it can be a bug, a feature request is enough for that since its only some cosmetic issue that affects no functionality as far as I know or stop people from doing something some work properly where kvirc is concerned, but sure, it "should" be fixed by who understand how best to handle it.
> 
> We love splitting hairs :wink: :grinning:

**Comment by un1versal** [comment]
So much noise for something like this that affects nothing and more serious issues relegated to silence ;)

**Comment by wodim** [comment]
Because more serious issues require a lot of time and work.

**Comment by un1versal** [comment]
> Because more serious issues require a lot of time and work.

You mean like the time wasted babbling away? not all issue require that much time, just the right expertise.

like this one... would been fixed already 5 times over :D :grinning:

**Comment by wodim** [comment]
This workaround looks good enough (the one with the hardcoded table) if we cannot alter the manifest file. I don't have a Windows environment ready though. http://www.codeproject.com/Articles/678606/Part-Overcoming-Windows-s-deprecation-of-GetVe

**Comment by staticfox** [comment]
Closed via https://github.com/kvirc/KVIrc/commit/b79e1f031849a82dfaa69c10e01697b9a8f866bf
