### ISSUE TITLE
Compose key stops working

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1811]
If to switch to another channel, compose key doesn't work.
To restore it working, switching to another window (e.g. with Alt-Tab) and back helps.
Using KDE4, if that matters.

KVIrc 4.9.1 'Aria'

Информация времени выполнения:
System name: Linux 4.0.5-zen+
System version: #1 ZEN SMP Thu Jun 18 22:29:11 IST 2015
Архитектура: x86_64
Qt version: 5.4.2
Qt theme: fusion

Информация о сборке:
Build date: 2016-01-03 12:15:02 UTC
Sources date: 20160102
Revision number: a90d8193157947eb1ee6b4a7a0b5a0c8801c0cb6
System name: Linux-4.0.5-zen+
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   VERBOSE
   LIB_SUFFIX=64
   Threads=POSIX
Compiler name: /usr/bin/x86_64-pc-linux-gnu-g++
Compiler flags: -O2 -pipe -march=bdver2 -ggdb3 -fno-strict-aliasing 
Qt version: 5.4.2

**Comment by un1versal** [comment]
Sounds a lot like https://github.com/kvirc/KVIrc/issues/1749

**Comment by DarthGandalf** [comment]
Yeh, looks similar.

**Comment by wodim** [comment]
Looks like it's the same, actually.
