### ISSUE TITLE
Option to lock toolbars and hide grip

### ISSUE THREAD

**Issue by Stanzilla** [kvirc/KVIrc#1812]
An option to prevent toolbars from being moved and hide the grip and/or the area the grip should be (hi Windows) so the channel list and topic box borders line up.
![2016-01-03_19-01-00](https://cloud.githubusercontent.com/assets/75278/12080100/ddb597f4-b250-11e5-8c23-f1e2d0a99d2b.png)

**Comment by un1versal** [comment]
Some programs have a lock toolbar option.

**Comment by wodim** [comment]
In this case, you mean the tree list, and not the toolbars.

**Comment by un1versal** [comment]
all of it? (tm)
