### ISSUE TITLE
[ueserlist] selecting away users nick, doesnt follow color selction rules.

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1814]
This is probably intended by design, but just looks wrong, 

These are my normal `#232323` / selected `#c8c8c8` colors
![capture1](https://cloud.githubusercontent.com/assets/3521959/12084830/5c255dae-b2b0-11e5-85f0-100fb4b22630.PNG)

The color `#e6e6e6` for the nick away is:
![capture5](https://cloud.githubusercontent.com/assets/3521959/12084863/c1fefcfc-b2b0-11e5-95ba-38bd232d2066.PNG)

This is what happens when I select a normal user:
![capture](https://cloud.githubusercontent.com/assets/3521959/12084878/fc760d44-b2b0-11e5-82da-d84459cf4165.PNG)

And this happens when selecting an away user:
![capture0](https://cloud.githubusercontent.com/assets/3521959/12084882/0c0374ae-b2b1-11e5-9433-85175b667b10.PNG)

That to me looks odd and feels wrong.

**Comment by TheReign** [comment]
Try this: 3bcc660

**Comment by ghost** [comment]
Right now it blends foreground of "away" and whatever the foreground is supposed to be normally.

Would you prefer it to not blend at all and just use foreground of "selected" when you select a user?

**Comment by un1versal** [comment]
I would prefer that there's always some significant contrast, enough to moot this issue, else if thats not possible, use same foreground...

One consideration would be, what if you have a user selected that was not away and in meanwhile went away, and how could you visually tell there's a status change, and is that important?

atm I have set prefs>irc>channel/advanced `[x] Enable keep away list updated` but thats not default, so theres also that.

Make sense?

**Comment by un1versal** [comment]
It just occurred to me... what about adding a  settable color to 
![capture1](https://cloud.githubusercontent.com/assets/3521959/12084830/5c255dae-b2b0-11e5-85f0-100fb4b22630.PNG)

so we can configure the away when selected color?

Not even an idea how to word that, so its probably a bad idea :D

**Comment by ghost** [comment]
I guess that's an option, since I can't figure out how to de-select the user in the list so you'd lose all ability to determine by color whether the selected user was away or not.

But, with the added setting, you'd lose all other color indicators as well, since it currently is a "dimming" of sorts for away status.

Also, "Enable keep away list updated." is enabled by default.  I find that dangerous when you sit in multiple channels with 2k+ users in them, since it lags out the connection periodically, but that's another issue.

**Comment by ghost** [comment]
Programmatically determining if two colors are "too similar" probably wouldn't be the easiest heuristic to create. So, I'm not really seeing a _good_ option that will solve this in all cases besides just using a specific foreground color.

**Comment by un1versal** [comment]
> But, with the added setting, you'd lose all other color indicators as well, since it currently is a "dimming" of sorts for away status.

mm really? thats not any better then.

> Also, "Enable keep away list updated." is enabled by default. I find that dangerous when you sit in multiple channels with 2k+ users in them, since it lags out the connection periodically, but that's another issue.

I can see that being a problem, but we also have that with other options like running ctpc avatar in a large channel like #freenode the staffers will kick your butt.

**Comment by un1versal** [comment]
how about storing the selected color and the nick away color and using some other color other than that to blend when away? Thats way when selected the bled would more likely offer some better contrast....

You know this smells a bit like the smart nickname colors issue.

**Comment by un1versal** [comment]
I realize what you mean by blend now, duurh...

![capture5](https://cloud.githubusercontent.com/assets/3521959/12084863/c1fefcfc-b2b0-11e5-95ba-38bd232d2066.PNG)

So the rank user color uses that color to blend to when user goes away.... so if I used a much darker color (tested this) this issue reported on the theme side is resolved.

this is setting blend color to #232323
![capture1](https://cloud.githubusercontent.com/assets/3521959/12094837/dfdcfca4-b302-11e5-856f-db27a823f1f6.PNG)
![capture](https://cloud.githubusercontent.com/assets/3521959/12094838/dffce596-b302-11e5-9e2a-828a43f79fce.PNG)

So technically that Away: label is pure nonsense, I expect that the color there is the color used for the away status but instead its used for blending nonsense.

I suggest we rename that from Away to Away (blend color): to close this issue and Ill fix all the internal themes.

**Comment by un1versal** [comment]
see https://github.com/kvirc/KVIrc/pull/1817

I would add a tootip txt to it tbh as well as the proposed addition. thoughts?

**Comment by un1versal** [comment]
@TheReign this is the code that this option triggers https://github.com/kvirc/KVIrc/blob/master/src/kvirc/ui/KviUserListView.cpp#L1863-L1873

Im adding a tooltip that reads.

`The away color selected, will be blended with the user rank foreground color. You should also consider your theme's style / color and the userlist background selected color for optimum visibility.`

thoughts?
