### ISSUE TITLE
Search tools: proposal and request for resorting flyout options

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1816]
Regarding the menu flyout over the output/split view called Search tools... this ticket has two parts...

Part 1:)

![capture1](https://cloud.githubusercontent.com/assets/3521959/12093764/b52cdf98-b2fc-11e5-93f7-a394e6327582.PNG)

It makes little sense to me why this is called search tools when it has more functionality that is not related to searching than to it.

I suppose the simplest, is to rename it to something that probably more suitable, Perhaps:
- Output tools
- Search and output tools
- Output view tools

So please either say which name you prefer or suggest some alternative to rename that to..

---

Part 2) 

But then thats a short term solution to me, because I dont think many people realize you have all those other options available there, so it occurs to me that we could move such options like zoom/font and background options either to:

A) to the top right, as first option before encoding tools

**or**

B) to the bottom again as first option.

Then the current button would only toggle search directly and the other options would have their own dialog that could also handle the split view scenario.

I dont have any mocks at this time but I can make something up eventually.

In the meanwhile some thoughts and feedback on both part 1 and part 2 would be nice.

**Comment by ghost** [comment]
2) Neither, since it applies separately to each of the split windows and wouldn't make sense if it was only a single button.  But, definitely not B as it's not an input option list.

**Comment by un1versal** [comment]
well the applies separately could be handled in dialog... but it would require some more work...

So rename option then... now to what? Im ok with any of the 3 but prefer the 3rd option.

**Comment by un1versal** [comment]
see https://github.com/kvirc/KVIrc/pull/1817 that should be something towards this...
