### ISSUE TITLE
Can't connect to Quakenet using default server (it doesn't exist)

### ISSUE THREAD

**Issue by ekolis** [kvirc/KVIrc#1819]
kvirc always tries to connect to irc.quakenet.eu.org, which doesn't exist; is this a typo for irc.eu.quakenet.org? (That would be consistent with the other global servers.) Have we been DDOSing the European Union this whole time? ;)

Steps:
1. Attempt to connect to the Quakenet network without specifying a server
2. kvirc attempts to connect to the false EU server and fails with a DNS error

(Not sure why it always attempts to connect to the EU server - it's not the first server in the list, and I'm not in the EU...)

I can work around this bug by deleting the EU server from the server list, or by manually connecting to a different server (not to the network as a whole). Oddly setting a different server as a favorite has no effect; do favorites do something else?

```
Executable Information

KVIrc 4.9.1 'Aria'

Runtime Info:
System name: Windows Release : 6.2.9200
System version: Windows 8 (x64) (Build 9200)
Architecture: Intel64 Family 6 Model 58 Stepping 9
Qt version: 5.5.1
Qt theme: windowsvista

Build Info:
Build date: 2016-01-05 10:20:26 UTC
Sources date: 20160102
Revision number: git-6040-gb7fa661
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.5.1
```

**Comment by ekolis** [comment]
BTW, I think something might be wrong with the executable information dialog because I'm definitely running Windows 10, not Windows 8...

**Comment by un1versal** [comment]
> BTW, I think something might be wrong with the executable information dialog because I'm definitely running Windows 10, not Windows 8...

Cant see how thats related to your main report so -> See https://github.com/kvirc/KVIrc/issues/1810 its not a bug though.

as for your other issue... if the server is permanently down or temporarily down it would be nice to find out so that way you can submit a server update pull request or something.

Regarding your main issue: it would be related at best to https://github.com/kvirc/KVIrc/issues/1706

**Comment by Heufneutje** [comment]
> See #1810 its not a bug though.

I would hardly consider displaying the wrong OS information to NOT be a bug...

**Comment by un1versal** [comment]
> I would hardly consider displaying the wrong OS information to NOT be a bug...

It was done with reason, so since its intentional its not a bug.

**Comment by DarthGandalf** [comment]
It's obviously a bug, as the shown information is wrong.
There are some technical reasons behind it, but it's the case for every bug
- there is some reason behind it. That doesn't mean that it can't and it
shouldn't be fixed.

**Comment by un1versal** [comment]
bugs are not intentinal in my book, but I suppose it can be a bug, but as is a feature request is enough since its only some cosmetic issue, but sure, it "should" be fixed.

**Comment by DarthGandalf** [comment]
Why do you think that one is intentional?

2016-01-05 18:41 GMT+00:00 un1versal <notifications@github.com>:

**Comment by DarthGandalf** [comment]
I'll move this to that bug...

**Comment by un1versal** [comment]
@ekolis 

Would you mind copying and pasting your main report into #1706 and your second comment about os info into #1810
