### ISSUE TITLE
Can't build on OS X with Perl support on

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#1825]
I'm not in front of my OS X machine right now, but one of the Perl headers (for the Perl version that comes with El Capitan) does not compile with C++11. Anything that can be done?

**Comment by DarthGandalf** [comment]
It's already fixed
by -Wno-literal-suffix -Wno-reserved-user-defined-literal in
https://github.com/kvirc/KVIrc/blob/master/src/modules/perlcore/CMakeLists.txt

2016-01-07 12:46 GMT+00:00 wodim notifications@github.com:
