### ISSUE TITLE
WHeres the code block for the right click toolbar context.

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1833]
Trying to find this window
![capture](https://cloud.githubusercontent.com/assets/3521959/12220490/11d2da40-b76c-11e5-8464-e3b2d947be04.PNG)

Trying to find the option labeled as Show Scripting, more specifically where Icon is defined.

Looked at `KviMainWindow.cpp`` but cant make head or tails of that.

thx

**Comment by ghost** [comment]
`src/kvirc/ui/KviToolBar.cpp`

Tip: `grep src -r -e "Button Style"` since that appears to be a unique string in the menu.

**Comment by un1versal** [comment]
ya just opened my eyes its in toolbars.kvs what Im looking for actually

thx
