### ISSUE TITLE
Treeview not displayed correctly in 4.9.1

### ISSUE THREAD

**Issue by UKMechanic** [kvirc/KVIrc#1834]
First run:

Normal Run via icon in launcher:

![kvirc1 screenshot](https://cloud.githubusercontent.com/assets/16625070/12220817/77534df2-b779-11e5-9a23-dcc9a6e3c6ba.png)

KVIrc 4.9.1 'Aria'

Runtime Info:
System name: Linux 3.19.0-43-generic
System version: #49~14.04.1-Ubuntu SMP Thu Dec 31 15:44:49 UTC 2015
Architecture: x86_64
Qt version: 5.2.1
Qt theme: gtk+

Build Info:
Build date: 2016-01-07 19:16:23 UTC
Sources date: 20160102
Revision number: git-6064-g221bd96
System name: Linux-3.13.0-74-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/x86_64-linux-gnu-g++
Compiler flags: -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 
Qt version: 5.2.1

Second run:

cmdline=kvirc -m -p %u -style=windows

![kvirc2 screenshot](https://cloud.githubusercontent.com/assets/16625070/12220819/897cd17e-b779-11e5-96f3-533301abed50.png)

KVIrc 4.9.1 'Aria'

Runtime Info:
System name: Linux 3.19.0-43-generic
System version: #49~14.04.1-Ubuntu SMP Thu Dec 31 15:44:49 UTC 2015
Architecture: x86_64
Qt version: 5.2.1
Qt theme: windows

Build Info:
Build date: 2016-01-07 19:16:23 UTC
Sources date: 20160102
Revision number: git-6064-g221bd96
System name: Linux-3.13.0-74-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/x86_64-linux-gnu-g++
Compiler flags: -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 
Qt version: 5.2.1

Third run:

cmdline=kvirc -m -p %u -style=fusion

![kvirc3 screenshot](https://cloud.githubusercontent.com/assets/16625070/12220820/9476de76-b779-11e5-83d3-92d7a2a44ddd.png)

KVIrc 4.9.1 'Aria'

Runtime Info:
System name: Linux 3.19.0-43-generic
System version: #49~14.04.1-Ubuntu SMP Thu Dec 31 15:44:49 UTC 2015
Architecture: x86_64
Qt version: 5.2.1
Qt theme: fusion

Build Info:
Build date: 2016-01-07 19:16:23 UTC
Sources date: 20160102
Revision number: git-6064-g221bd96
System name: Linux-3.13.0-74-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/x86_64-linux-gnu-g++
Compiler flags: -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 
Qt version: 5.2.1

**Comment by un1versal** [comment]
Thanks for report, so gtk+ style is naffed :grinning: , and using windows/fusion fixes it... glad to know.

I think these style issues are Qt issues as opposed to KVIrc issues directly, (need someone to confirm what exactly causes these and whats the best way to proceed)

But yes, it happens none-the-less and Im glad that specifying a theme at least works.

Please continue using `-style=fusion` (you can add it to shortcut icon in launcher if you like) or some other style you like in meanwhile.

Lets see what others have to say about this.

**Comment by wodim** [comment]
Should be fixed with 7144d5c, let's wait until AlexanderP uploads a new build so the reporter can test it.

**Comment by un1versal** [comment]
@AlexanderP would you mind kicking in a few new builds please?

**Comment by UKMechanic** [comment]
KVIrc 4.9.1 'Aria' Runtime Info: System name: Linux 3.19.0-43-generic 
System version: #49~14.04.1-Ubuntu SMP Thu Dec 31 15:44:49 UTC 2015 
Architecture: x86_64 Qt version: 5.2.1 Qt theme: fusion Build Info: 
Build date: 2016-01-16 12:44:58 UTC Sources date: 20160102 Revision 
number: git-6142-g33eca33 System name: Linux-3.19.0-43-generic CPU name: 
x86_64 Build command: /usr/bin/cmake Build flags:    MANDIR=share/man 
    CMAKE_INSTALL_PREFIX=/usr    LIB_SUFFIX=/x86_64-linux-gnu 
    Threads=POSIX Compiler name: /usr/bin/x86_64-linux-gnu-g++ Compiler 
flags: -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat 
-Werror=format-security -D_FORTIFY_SOURCE=2 Qt version: 5.2.1

**Comment by AlexanderP** [comment]
@un1versal  I didn't understand :)

**Comment by un1versal** [comment]
@AlexanderP Debian builds seemed a bit behind we need newer ones ;) please (Im looking at http://notesalexp.org/ for what version are available, is that correct up-to-date?

@UKMechanic can you try now without the -style=fusion and see if this is fixed?

**Comment by AlexanderP** [comment]
@un1versal Now debian revision for 6135
http://notesalexp.org/kvirc/sid/pool/main/k/kvirc/kvirc-dbg_4.9.1~git-6135-g5e29e49-1_amd64.deb
Today will be a new revision for debian.

**Comment by un1versal** [comment]
thx.. Ill let one of our users know so he can text if this is also fixed for sure now....

**Comment by AlexanderP** [comment]
@un1versal updated 
http://notesalexp.org/kvirc/sid/pool/main/k/kvirc/kvirc_4.9.1~git-6154-gd3b9a60-1_amd64.deb

**Comment by un1versal** [comment]
thx

**Comment by UKMechanic** [comment]
I broke the charger for my laptop earlier so I won't be able to try it out until tomorrow when I get my hands on a soldering iron.

**Comment by un1versal** [comment]
I broke the whatsit-ma-jigglywig that goes up and down round and round, but now wheels come off and Im waiting for a flippin flip-on-wobler to fix the whole lot.

**Comment by UKMechanic** [comment]
I hate it when that happens!
