### ISSUE TITLE
Tray Icons - redesign...

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1840]
Our current tray icons neither fit in any OS nor do they fit anywhere immho. I dislike them all and I rather look at a pile of puke at least I know what Im looking at!

The rub here is the multiplatform jig, designing anything for multiplatform its not the same as designing for a single OS.
However... in order to do the job we need to look how all OS's tray icons look so we can design things that fit everywhere.
# @ EVERYONE

Please post screenshots of all the OS tray icons with KVIrcs tray icons enabled (so we can also see how they stand out)  so I can start looking how to tackle the issue asap.

Thanks.

**Comment by wodim** [comment]
Easy there, fella. Windows icon is OK. And we don't need "things that fit everywhere". We need different designs for different OSes that integrate well with the system.

![2016-01-13_13-28-48](https://cloud.githubusercontent.com/assets/1001553/12294311/af0e8450-b9f9-11e5-8f24-bed912ce64bf.png)

**Comment by un1versal** [comment]
that was before the tray icon has 20 elements in one and flashes...

none of those actually fit with the windows style fyi

Linux mint cinnamon (fits like a glove to prove my point) you cant see the icon you cant really see what ontop or what it means and doesnt fit style)
![capture](https://cloud.githubusercontent.com/assets/3521959/12295351/820cf190-b9f8-11e5-9f1a-557584320c8f.PNG)
![capture](https://cloud.githubusercontent.com/assets/3521959/12320599/6b0b71c0-baa1-11e5-968a-ad9d7dda7d3d.PNG)

perfect example of what not to do with any icons design.

**Comment by wodim** [comment]
I think it's done on purpose. System icons have a recognisable white colour with a black border. Rest of icons are colourful. Not the case on OS X though.

**Comment by un1versal** [comment]
well KVIrc icons are too colorful and too busy, no application i know does this.. I have a simple solution but code wise its not going to be so simple, idk no idea about that side

cant we instead of having all these overlays over the icon in tray have notices instead....

Needs simplifying the idea being transmitted. Too may ideas at same time in this icons size is a bad idea. The icon + more than one overlay in several positions at same time and with color states is a no go and will die.

**Comment by un1versal** [comment]
I see no one else is being vocal and posting screenshots... I know everyone has a real life but consider the time Im wasting if I do work with no feedback and that results in complaints or me having to fix stuff after the fact.

**Comment by DarthGandalf** [comment]
Now it works fine for me on KDE4.

![selection_233](https://cloud.githubusercontent.com/assets/325092/12350512/659d005e-bb6f-11e5-8ef7-117f70cc37f6.png)

**Comment by ctrlaltca** [comment]
![schermata 2016-01-15 alle 11 27 57](https://cloud.githubusercontent.com/assets/1631111/12351023/19b69162-bb7b-11e5-97d7-adc8580948d9.png)
OSX 10.11. All the system icons on the right are black (except of the keyboard layout with the italian flag). Other apps have black or gray icons (only owncloud is blue and green). KVIrc icon looks like an indefinite things.

**Comment by wodim** [comment]
![screen shot 2016-01-15 at 20 10 35](https://cloud.githubusercontent.com/assets/1001553/12362519/11578398-bbc4-11e5-9373-bddd4b885be2.png)

This is what my icons look like.

**Comment by un1versal** [comment]
> This is what my icons look like.

wheres kvirc, same as ctrlaltca I guess

**Comment by wodim** [comment]
![screen shot 2016-01-16 at 01 08 44](https://cloud.githubusercontent.com/assets/1001553/12368662/ce3f6c36-bbed-11e5-916c-057e784e3b89.png)

This is even uglier than @un1versal, and that's a lot to say.

**Comment by un1versal** [comment]
> This is even uglier than @un1versal, and that's a lot to say.

Youre hilarious, like a toothache. :grinning:

**Comment by johndoe71rus** [comment]
Lubuntu 14.04.4 
Openbox (ver. 3.5.2)
GNU libc ver. 2.19 (stable), Glib ver. 2.40.2, GTK+ ver. 2.24.23
Kvirc Revision number: git-6407-ge47f18e
![2016-04-20-174957_1280x800_scrot](https://cloud.githubusercontent.com/assets/7861172/14678976/f9db2b88-0728-11e6-987e-220de610a3cd.png)

**Comment by Glossow** [comment]
Debian 8.4
Openbox 3.5.2
KVIrc 4.9.2~git-6502-g0c15101-1
![screen](https://cloud.githubusercontent.com/assets/11541179/14852759/69e23d98-0c99-11e6-8be9-51ef54017aae.png)

**Comment by un1versal** [comment]
thx guys

**Comment by DarthGandalf** [comment]
The last two screenshots look perfectly fine, IMHO, except the strange
black background, which should be transparent.

2016-04-27 14:19 GMT+01:00 un1versal notifications@github.com:

**Comment by un1versal** [comment]
You can see a small black border around the US flag, so my guess its specific issue not related to KVIrc

once theres only one icon and one activity overlay and the OSX type icon is actually black this should be semi sane.

**Comment by johndoe71rus** [comment]
un1versal 
previous 4.2 was without black icon background. 
small black border around the US flag this gxneur 
![us](https://cloud.githubusercontent.com/assets/7861172/14858554/896d104e-0cb1-11e6-8eae-bf4c91a5007a.png)

**Comment by johndoe71rus** [comment]
![2016-04-27-185713_1280x800_scrot](https://cloud.githubusercontent.com/assets/7861172/14858824/a1bdf3ce-0cb2-11e6-892c-bf1891ede72d.png)

**Comment by un1versal** [comment]
@johndoe71rus so OK did you chnage OS in meanwhile or was it just KVIrc you upgraded?

One difference is we now use Qt5

out of curiosity can you post these details

Type /about.kvircon KVIrc and copy & paste the details from the Executable Information tab into here..
if you using KDE what OS it is etc.

Ah I see you have other icons with black background, are they also Qt based?

**Comment by DarthGandalf** [comment]
Only KVIrc has this black background on screenshots above. Other icons,
including the flag, appear correctly.

**Comment by johndoe71rus** [comment]
I only add new kvirc ppa and update.
I use Lubuntu 14.04.4
Openbox (ver. 3.5.2)

[KVS] Runtime error: Module command call failed: 'about' unit can not provide the team with the name 'kvircon'
[20:27:23] [KVS] In script context "commandline :: kvs", line 1, about 1 character

sorry some russian 
KVIrc 4.9.2 'Aria'

Информация времени выполнения:
System name: Linux 4.5.0-040500-generic
System version: #201603140130 SMP Mon Mar 14 05:32:22 UTC 2016
Архитектура: x86_64
Qt version: 5.2.1
Qt theme: fusion

Информация о сборке:
Build date: 2016-04-16 18:32:52 UTC
Sources date: 20160102
Revision number: git-6407-ge47f18e
System name: Linux-3.13.0-85-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/x86_64-linux-gnu-g++
Compiler flags: -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 
Qt version: 5.2.1
Features: IRC, IPv6, Crypt, SSL, IfAddr, IPC, Transparency, Phonon, Webkit, DCCVoice, Perl, Python, Enchant, Qt5, KVS

**Comment by un1versal** [comment]
@johndoe71rus 

we have a experimental ppa that ships nighly kvirc compiled against qt 5.5.1 and also ships updated Qt packages, if you are willing to test and make a backup of current system state (just in case) or test on a Virtual machine have a try https://github.com/kvirc/KVIrc/issues/1949 ppa details in there, I wonder if this is a qt issue or something else.

**Comment by un1versal** [comment]
Form IRC @johndoe71rus confirms that
![2016-04-27-185713_1280x800_scrot](https://cloud.githubusercontent.com/assets/7861172/14858824/a1bdf3ce-0cb2-11e6-892c-bf1891ede72d.png)

Is fixed by KVIrc compiled against Qt5.5.1 + updated Qt packages from https://github.com/kvirc/KVIrc/issues/1949 

![fixed](http://s32.postimg.org/ile8s9ej9/2016_04_29_202415_1920x1080_scrot.png)

**Comment by un1versal** [comment]
**Its a long way off**, but I started toying with the idea for the black/dark tray area icons

It wont look like this but you can see a glimpse of what it could look like

https://github.com/kvirc/KVIrc/blob/master/README.md

Its temporarily on main readme as a sort of teaser as I refine the image I can upload it to wiki and it automatically refreshes the readme image for a quick preview.

Eventually all icons of all sizes and colors will be redone one by one in the target sizes so they all match and at same time we can get rid of the status overlays and keep only one.

**Comment by un1versal** [comment]
![kvirc-logo-light](https://cloud.githubusercontent.com/assets/3521959/16358184/7a4761e2-3b04-11e6-9da7-eccc69383204.png)
![kvirc-logo-dark](https://cloud.githubusercontent.com/assets/3521959/16358185/7a4c9518-3b04-11e6-9bc6-d326d42035ec.png)

So these are more or less ideas to replace the mono icons and have account for dark/light tray with using same image to work on both scenarios...

its not perfect the idea is to do one inverted image in white for black trays like steam done type thing.
this is only 2 vectors one for V one for gear
