### ISSUE TITLE
We need new activity meter indicators

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#1843]
![](https://raw.githubusercontent.com/kvirc/KVIrc/721401b6665093414d2b474648c2065b5677c402/data/pics/kvi_activitymeter.png)

@un1versal pls

**Comment by un1versal** [comment]
Not my most top priority, but its on the todo list. thers two of those btw.

**Comment by un1versal** [comment]
Those work just fine as is, the userlist ones are the ones which annoy me most tbh
