### ISSUE TITLE
Declaring war on most large blocks of centered text

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1847]
But not all centered text, for instance, tooltip header text and other centered header text is perfectly acceptable, Also acceptable in the Honor and Glory dialog type.

But large blocks of text like tooltips and similar, should be left aligned. **This enhances readability** since we are trained to read RTL since an early age (unless youre LTR but these things dont apply there and if they did they should be handled automatically not forced to center, also cant see many programs who use centered text for these things.

Aside from the fact not every tooltip is actually centered some are not.

In next few days I will be testing local chnages with view of proposing final changes via PR.

thoughts?

**Comment by un1versal** [comment]
There's this book I recommend people should buy and read, its titled **DON'T MAKE ME THINK" By Steve Krug. Its about Web design/usability but the principles discussed apply to anything that involves user interaction with an interface.

**Comment by wodim** [comment]
I completely agree.
