### ISSUE TITLE
We don't support custom input methods on Qt 4

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#1850]
After 39a9e33 we do not support custom input methods, so it needs to be reimplemented or...

**Comment by un1versal** [comment]
...drop Qt4

**Comment by wodim** [comment]
I need a "Make America Great Again" cap that says "Drop Qt4" instead.

**Comment by un1versal** [comment]
![capture](https://cloud.githubusercontent.com/assets/3521959/12379755/1b3faaa8-bd58-11e5-8f3f-e703ceb306ad.PNG)

**Comment by un1versal** [comment]
![capture](https://cloud.githubusercontent.com/assets/3521959/12379767/942a0ac6-bd58-11e5-9994-ed61cd8229d9.PNG)

**Comment by wodim** [comment]
That could be our temporary splash screen if only we still had a splash screen :sob:

**Comment by un1versal** [comment]
Better yet

![capture](https://cloud.githubusercontent.com/assets/3521959/12379796/589f394e-bd59-11e5-90c1-986378b27532.PNG)

alternative design
![capture](https://cloud.githubusercontent.com/assets/3521959/12379833/5c23851a-bd5a-11e5-86f4-b854b145c6cd.PNG)

**Comment by un1versal** [comment]
Qt4 gone this is now invalid/fixed
