### ISSUE TITLE
place cursor at end of text when pressing arrow up

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1851]
press arrow up to input last input text, cursor is at begining of input box before all the text instad of at the right hand side.
If you wanted to type something else for instance after that you need to move cursor all the way to right hand side, of click it there.

**Comment by wodim** [comment]
wtf does this mean

**Comment by un1versal** [comment]
press arrow up on keyboard and see

**Comment by wodim** [comment]
It works properly.

**Comment by wodim** [comment]
Ah I think I understand what you mean but I cannot reproduce it.

**Comment by un1versal** [comment]
![capture](https://cloud.githubusercontent.com/assets/3521959/12379703/284f15f4-bd57-11e5-904c-8de32c6be597.PNG) purple where it should be

my cursor is ALWAYS on the left whenever up arrow is pressed and buffer something comes up

**Comment by DarthGandalf** [comment]
> It works properly.

+1

**Comment by Heufneutje** [comment]
Works fine for me too.

**Comment by un1versal** [comment]
well Im not inventing this

**Comment by staticfox** [comment]
Works fine here

**Comment by un1versal** [comment]
Still doesnt work here at all.

**Comment by wodim** [comment]
Confirmed troll.

**Comment by wodim** [comment]
Ehm, okay?

**Comment by un1versal** [comment]
works for everyone but reporter close it, thats the trend now.

we also have this https://github.com/kvirc/KVIrc/wiki/Submitting-a-bug-report#ticket-validity
