### ISSUE TITLE
can't switch IME mode

### ISSUE THREAD

**Issue by craftwar** [kvirc/KVIrc#1857]
Under Chinese language, press "shift" can't switch between alphanumeric and Chinese.
Under Japanese language, press "alt+caps lock" to Katakana and press "ctrl + caps lock" to Hiragana doesn't work.

Sometimes switch works, sometimes not.
I don't know correct steps to reproduce it, it happens every day.

Switching mode works fine in kvirc 4.2.0

kvirc.d00p.de 64bit nightly

/say /$version
 /KVIrc Aria 4.9.1, revision: git-6156-g3eef8a1, sources date: 20160102, built on: 2016-01-27 12:56:31 UTC

/about.config
[KVS] Runtime error: Module command call failed: the module 'about' doesn't export a command named 'config'
[KVS]   In script context "commandline::kvs", line 1, near character 1

**Comment by un1versal** [comment]
Please read https://github.com/kvirc/KVIrc/wiki/Submitting-a-bug-report#information-required-when-making-a-bug-report-via-github-issues

**Comment by wodim** [comment]
The support for custom input methods has been removed from the Qt 4 version. Try to compile using Qt 5.

**Comment by craftwar** [comment]
It is compiled with qt5.5.1. I don't know what is custom input methods but my testing IMEs are all shipping with windows.

**Comment by wodim** [comment]
Looks like a case of cad079d but no clue

**Comment by craftwar** [comment]
confirmed, same issue as  #1749

I can reproduce it in the same way.

**Comment by un1versal** [comment]
> confirmed, same issue as #1749
> 
> I can reproduce it in the same way.

Yes but #1749 has been fixed apparently.

@craftwar

/about.config
[KVS] Runtime error: Module command call failed: the module 'about' doesn't export a command named 'config'
[KVS] In script context "commandline::kvs", line 1, near character 1

mm I probably meant `/about.kvirc` Ill fix that on wiki... that works.

**Comment by craftwar** [comment]
I mean I do the same thing and error happens.
I switch to different channel, IME switch to alphanumeric mode.
looks like same issue

**Comment by Kaens** [comment]
Confirmed on a nightly 2016-04-04 with Japanese on Win10x64, Japanese locale. Reproduceable by simply changing the current channel. Alt-tabbing out and back in fixes it.

**Comment by craftwar** [comment]
fixed in [https://github.com/kvirc/KVIrc/commit/32c9b9ce86f6fbacce5cd14f1b1948cca2f8db77](https://github.com/kvirc/KVIrc/commit/32c9b9ce86f6fbacce5cd14f1b1948cca2f8db77)

same issue as I think.
