### ISSUE TITLE
Command /DIE

### ISSUE THREAD

**Issue by Glossow** [kvirc/KVIrc#1863]
If enter a command /DIE in KVIrc, which is necessary to stop unrealircd server, we get the error:
[KVS] Runtime Error: 
[KVS]   in script context "commandline::kvs", line 1, near character 1

**Comment by wodim** [comment]
`die` is a scripting command. Use `/raw die` instead.

**Comment by AndrioCelos** [comment]
You can also just type `DIE` into the server window.
