### ISSUE TITLE
Crash when Python module is loaded on Windows

### ISSUE THREAD

**Issue by TheCycoONE** [kvirc/KVIrc#1866]
Version: KVIrc-4.9.1-dev-git-6215-gd1d891a-x86_64 (Downloaded from nightly builds)
OS: Windows 7 x64

The Servers and Configuration window pops up, I click freenode, then Advanced...
After a period of time (about 20 seconds) with that dialog up regardless of whether I've entered anything or even touched the mouse or keyboard, KVirc terminates.

I have not seen any error or log that indicates there was an issue.

Edit to include Executable Information:

```
KVIrc 4.9.1 'Aria'

Runtime Info:
System name: Windows Release : 6.1.7601
System version: Windows 7 Professional (x64) Service Pack 1 (Build 7601)
Architecture: Intel64 Family 6 Model 42 Stepping 7
Qt version: 5.5.1
Qt theme: windowsvista

Build Info:
Build date: 2016-02-05 03:12:34 UTC
Sources date: 20160102
Revision number: git-6215-gd1d891a
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.5.1
```

**Comment by wodim** [comment]
The only thing I can think of is UPnP.

**Comment by un1versal** [comment]
![capture](https://cloud.githubusercontent.com/assets/3521959/12848146/f1f618a0-cc0f-11e5-90c8-2af8c23692ab.PNG)
![capture1](https://cloud.githubusercontent.com/assets/3521959/12848147/f1f701f2-cc0f-11e5-9490-132ef7af0cb1.PNG)

5 minutes on each screen left to its devices, tried also connected to a network also then cleared settings just for a test... took those screenshots and posted, its still up and running.

Works fine here

Only _issues_ I found is one tooltip is HUGE long (Server Encoding / Text Encoding) and that help button on title bar does nothing.

![capture](https://cloud.githubusercontent.com/assets/3521959/12848338/29407f0c-cc11-11e5-8391-36ffb2f7aa1c.PNG)

**Comment by TheCycoONE** [comment]
Is there anything I can do on my side that would help? Obviously the best thing would be to compile it myself and if it still happens trace exactly what is happening, which I may do if I find the time. On the other hand if there's anything I could check quickly I would be happy to help.

**Comment by wodim** [comment]
As soon as you launch kvirc, close the servers window and write the following command: `/upnp.refresh`. See if it crashes immediately.

**Comment by TheCycoONE** [comment]
Does not crash

**Comment by un1versal** [comment]
If you have a way to test in a virtual machine where you dont have other softwares installed, you can rule out 3rd party influence.

also if you have any KVIrc addons/scripts installed try with a clean config.

Cant think of anything else except. do you have a theme? if so try a default theme. In my case its a VM it has tons of other crap installed but Ive no kvirc addons or scripts in that one and was both with internal theme or no theme at all.

**Comment by TheCycoONE** [comment]
I don't have a clean windows VM sadly. I am using the minimal theme that ships with KVirc and don't have any addons or scripts. It was a fresh profile.

I changed the theme from Minimal to Aria and it is still terminating on the Network Details dialog, as well as the Server Details dialog.

There is no windows crash dialog, so it appears to be exiting cleanly.

**Comment by un1versal** [comment]
is this a laptop? is it plugged into main power/battery?

**Comment by TheCycoONE** [comment]
It is a laptop and it is plugged in.

**Comment by un1versal** [comment]
A friend of mine reported a while back to me that when he disconnects his laptop from main power, KVIrc dies... I cant test because I have no laptop here. But hes not using windows just occurred to me it could be related to the platform.

Im not really experienced enough to make a educated guess, but its crossed my mind Qt maybe doing something in a laptop environment that affects KVIrc. Its probably a silly idea and Ive no way to even test or know what if anything is going on there.

Lets see what smarter people say.

**Comment by TheCycoONE** [comment]
As an update from IRC, the terminate does not happen with kvipython.dll and kvipythoncore.dll are removed from the module folder.

**Comment by TheCycoONE** [comment]
When python 2.7.11 is removed from my system then kvirc doesn't crash. If I install it again and remove kvscompleter.idx then the crash happens again.

Having python 3 installed on my system does not interfere with kvirc, nor does having python 2.7.11 x86_32 installed.

**Comment by un1versal** [comment]
yep thx for hunting this down and having the patience to do it.

IMO KVIrc shouldn't crash and handle whatever the issue is in a more graceful manner. But thats above my paygrade. :smiling_imp:

**Comment by un1versal** [comment]
To add more prominent information 

## Python disabled in Windows in https://github.com/kvirc/KVIrc/commit/d186462e594120f186dcae6b9fac125c05d938d8
