### ISSUE TITLE
Push API for avatars and userinfo

### ISSUE THREAD

**Issue by SoniEx2** [kvirc/KVIrc#1870]
There should be a Push API for avatars and userinfo by setting a realname flag. For backwards compatibility this should be set at the end of the realname, while also setting the previous flags.

Such a push API would allow the avatar holder(?) to decide when to send their avatar, thus preventing (rare, but possible) flood kills. It would also allow genders other than bot, male, female and unspecified to be used.

[(Too bad KVIrc 4.2 only lets you use 0-9 for the first flag, otherwise we would've been able to set it to 12 (8+4) and things like that. Please parse this one correctly.)](https://github.com/kvirc/KVIrc/blob/07867e9/src/kvilib/irc/KviIrcUserEntry.cpp#L57)

**Comment by SoniEx2** [comment]
About the bitfield encoding: It should use all 13 bits (yes, there are 13 bits), and it should be little-endian.

First let's talk about the 13 bits part. Color codes are of the format `^K99,99`. Now if you treat each field separately you get the highest power of two as `^K64,64`, but if you treat the fields together you can use it as `^K81,92`, which has a single set of 13 bits instead of 2 sets of 6 bits.

Now, why little-endian? Let's start at `^K1`. This is `1` in the first field. Then let's go increasing it, `^K16`, is `16` in the first field. Now what happens if we try to use 99? `^K99`. Compare this to the little-endian versions: `^K00,01` `^K00,16`, `^K00,99`. Now what if we start to go higher? `^K00,01` is 100 in little-endian format. This ends up using less bytes for lower values while still allowing 13 bits of data.

Note that this is both from an efficiency point of view (little-endian so it uses less space, and has 1 extra bit), and from a convenience point of view (you can fit 13 flags instead of 12 (or worse, 3), so you add bitfields less often).

**Comment by un1versal** [comment]
PR's welcome ;)

**Comment by SoniEx2** [comment]
Well, how can I learn C++?

**Comment by ctrlaltca** [comment]
> There should be a Push API for avatars and userinfo by setting a realname flag.

Do you mean something like this: https://github.com/kvirc/KVIrc/blob/master/src/kvirc/kernel/KviIrcConnection.cpp#L1585 ?

We currently handle:
`1` as male, `2` as female, `3 (1 bitwise or 2)` as bot, `4` as "has avatar".

Your idea of using up to 13 bits for publishing informations in the realname is nice, do you have an idea on what informations we could publish on those extra bits?
My only worry is on how other clients could misinterpret color codes over the canonical max of 15.

**Comment by SoniEx2** [comment]
> Do you mean something like this: https://github.com/kvirc/KVIrc/blob/master/src/kvirc/kernel/KviIrcConnection.cpp#L1585 ?

That's a Pull API. (Other clients see that and REQUEST avatars etc)

> My only worry is on how other clients could misinterpret color codes over the canonical max of 15.

mIRC accepts all of them (but due to the reset that follows, it doesn't matter), HexChat also doesn't care (0-15 for normal colors, 16-31 for internal colors, everything else ignored). 

See also http://www.mirc.com/colors.html

So, it should be safe.

KVIrc also uses some color codes in special ways, but it shouldn't be an issue.

We should add CTCP GENDER, and then 1 = accepts GENDER 2 = accepts AVATAR. If someone has 1 set on their realname, KVIrc should send a GENDER CTCP, through a NOTICE, to that person. If they have 2 set, KVIrc should send a CTCP AVATAR.

The GENDER CTCP is useful because it allows people like me to use their gender, instead of using one of male, female or bot. The icon for unrecognized options should be the transgender symbol, U+26A7. When parsing, you should first trim the input, then match case-insensitively one of MALE (to use male icon), FEMALE (to use female icon), BOT (to use bot icon), UNSPECIFIED (alternatively UNDEFINED, to use no icon), and everything else should use the transgender icon.

**Comment by DarthGandalf** [comment]
There is an issue with having something in end of real name: some IRC servers limit number of characters in real name, and drop the rest. So part of that extra info will be lost.

**Comment by SoniEx2** [comment]
Hmm good point...

This is what we currently have: `<legacy fields><nick color field><real name>`. For backwards compatibility, we need to put it after nick color, but there might be interactions with it. Maybe we should put an extra reset between nick color and push fields? (i.e. `<legacy fields><nick color field><RESET><push fields><real name>`)

`<legacy fields>` would be handled until KVIrc 7, and set until KVIrc 6. This would allow a reasonable transition period. (KVIrc 4: no push. KVIrc 5: push+legacy. KVIrc 6: push-only, but parse legacy. KVIrc 7: push-only, drop legacy)

**Comment by DarthGandalf** [comment]
Uh, you're already planning for KVIrc 7? Please don't; that will be in soooooo many years, that all your predictions will be false by that time.

**Comment by SoniEx2** [comment]
How many years, 10? sounds reasonable. Either way there needs to be a transition period.

**Comment by un1versal** [comment]
10 for v7? if thats Dog years sure ;D

**Comment by SoniEx2** [comment]
Hmm... Ok so, let's plan a transition period in terms of years. In 5 years we would stop setting legacy flags, in 10 years we would stop parsing legacy flags. Sounds reasonable?

**Comment by un1versal** [comment]
Reality check, you understand that to implement feature x,y,z requires a (any) developer (internal to team or outside developer) that has interest in that feature x,y,z, that further has the time to do that in his/hers spare time after dealing with their real life. it a roll of the :game_die: :smile: 

Since not not everyone who makes a feature request is a developer, you will notice by looking at our **[135](https://github.com/kvirc/KVIrc/labels/Feature%20Request)** open feature requests many been there for 10//9/7 and so on years like the first one (or last in this list). :sob: 

As a fellow KVIrc user, I dream of the day 6 active developers in a regular fashion work on the things they want and maybe are kind enough to implement one of these features and maybe fix a bug. :+1: 

My _advice_ is dont try to schedule other peoples spare time, their skills and interests and avoid some disappointments, you're lucky though, this ticket has attracted some interest so who knows when it will happen could be 5 minutes or 5 years or never.

Dreaming is nice though but reality is a swift kick in the butt. :dancer: 

If I could I would have done those 135 feature request + bug fixes + website + all the stuff I want to do myself, but like you Im also not a C++ developer or a web developer :disappointed:  but hey whos gonna let little things like that stop them from contributing to a project they feel passionate about?

**Comment by SoniEx2** [comment]
Note that as it currently stands, ignoring users doesn't stop them from sending automated AVATAR requests. Switching to a Push API allows for more fine-grained ignores.

**Comment by un1versal** [comment]
Can I ask why do you care if you dont even use KVIrc? :pig2: 

Sorry about being the devils advocate, someone has to. :imp:

**Comment by SoniEx2** [comment]
@un1versal Talk to me on IRC about it.
