### ISSUE TITLE
Support for #rrggbb colors

### ISSUE THREAD

**Issue by SoniEx2** [kvirc/KVIrc#1871]
There's a little-known color format, supported by IRCII and a few other uncommon clients, which is triggered by `^K#rrggbb,#rrggbb`. Support for it would be much appreciated, especially for, say, IRC games.

Note that, due to the lack of widespread support, we can't use this for #1870.

**Comment by un1versal** [comment]
The law of diminishing returns should apply here. Sorry -1 waste of man hours if you ask me.

**Comment by staticfox** [comment]
:-1: I'd rather get relatively standard things in to kvirc first like _italics_ rather then add even more super client specific things that can also effect the output of other clients in unintended ways.

**Comment by SoniEx2** [comment]
> then add even more super client specific things that can also effect the output of other clients in unintended ways.

How's parsing something gonna affect the output of other clients in unintended ways? You wouldn't be emitting anything...

**Comment by DarthGandalf** [comment]
So, user can see some color, but can't use the same color?

2016-02-11 21:04 GMT+00:00 Soni L. notifications@github.com:

**Comment by SoniEx2** [comment]
They can. You just aren't gonna provide a whole color picker. The user can input it themself.

**Comment by un1versal** [comment]
> They can. You just aren't gonna provide a whole color picker. The user can input it themself.

what a pain in the backside that would be, as a user idle like an easy way to do this, this means adding a picker of sorts.

Then theres also the issue of themes, many people like darker themes, some like lighter themes and then thers the cases where they have colored bg themes.

imo its already bad enough the standard IRC colors become pretty much unreadable in some cases.

So my question is, how useful is this? and How many readability and usability issues will we create?

here is my second :-1: to this and pending another -1 will close this.

**Comment by SoniEx2** [comment]
It's great for encoding hidden data in messages. Given that it's hidden, it won't cause any readability issues.

**Comment by un1versal** [comment]
> It's great for encoding hidden data in messages. Given that it's hidden, it won't cause any readability issues.

Er what... thers a better request for that.https://github.com/kvirc/KVIrc/issues/1877

this one sorry.  I stand by my first comment.

We have far too many feature requests that actually more helpful than this given the problems it may introduce and the ultimate desired end a transparent color would be better.

Also we dont have Devs implementing any previous older more valid requests never mind 0.01% user features.

Ill close this for now as wont fix, if anyone who feels like deving this, please reopen...

**Comment by SoniEx2** [comment]
#1877 isn't about hidden color, it's about transparent color. For background color, it would just show the background image or w/e. For foreground color, same thing, but it'd show text if the background color was solid and there was a background image, if you get what I mean.

This thing however, combined with some reset formatting keystrokes, can send lots more invisible (truly invisible, that does't even change the message length) data (e.g. metadata).

**Comment by un1versal** [comment]
Then its not invisible if under certain conditions some random users may see the message stick out like a sore thumb and proceed to investigate. makes this feature even more useless.

as transparent color would be perfect, if both bg/fg are transparent no matter what other persons sets as theme or bg image or not, they will trully see nothing.

**Comment by SoniEx2** [comment]
Current method is `^K01,23^K45,67^K89,01^K<normal shit here>`. New method would just use hex instead of decimal, which is a lot more compact.

Transparent color still shows a message. It's an empty message but it still shows up, and may take up multiple lines depending on length.

The `^K` trick is zero-width and universally supported. Heck, you even do it yourself (`AVATAR` sync mechanism).

**Comment by un1versal** [comment]
@staticfox already said no, and hes the most likely person to invest time in adding such features.

Ill tell you what if staticfox open this again Ill let it stay open, but I see no point no matter how much you try to sell this. You dont even use KVIrc and whos gonna use this feature? Santa? How many people (dont pull numbers out of thin air), 1 or 2.

I vote no.
