### ISSUE TITLE
data: URIs in avatars

### ISSUE THREAD

**Issue by SoniEx2** [kvirc/KVIrc#1872]
KVIrc currently doesn't support data: URI avatars, e.g. `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAC0lEQVQI12NgQAcAABIAAe+JVKQAAAAASUVORK5CYII=`. See [data: URIs on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/data_URIs)

**Comment by wodim** [comment]
This is absolutely unrealistic.

**Comment by SoniEx2** [comment]
@wodim You said avatars are a bad idea because they fetch remote content, thus potentially leaking IP. By putting the data in the reply itself you remove that attack vector.

**Comment by SoniEx2** [comment]
This might be more useful for SVGs tho, which can actually fit in the message.

**Comment by wodim** [comment]
You do realise you can't put anything meaningful in a base64-encoded IRC line, right? For example a 40x40 version of my current avatar:

```
curl 'https://avatars2.githubusercontent.com/u/1001553?v=3&s=40' | base64 -w0 | wc -c
```

That's 1772 bytes already.

**Comment by SoniEx2** [comment]
Try SVG! (without base64)

**Comment by un1versal** [comment]
Ill goto -1 thers no benefit for this now KVIrc supports Https for avatars.

**Comment by staticfox** [comment]
:-1:

**Comment by wodim** [comment]
I'm going to close this because it's unrealistic.
