### ISSUE TITLE
Url 

### ISSUE THREAD

**Issue by Indavoid** [kvirc/KVIrc#1876]
Hi !
When I click on a link, no windows open. I try run firefox $0 but it doesn't work. Please help me.
When will be a new version of KVIRC ?

**Comment by wodim** [comment]
Try this and see if it fixes it.

https://github.com/kvirc/KVIrc/wiki/FAQ#clicking-urls-doesnt-work-anymore-after-upgrading-whats-up

And we haven't got a clue of when we'll release a new version. This year, hopefully.

**Comment by Indavoid** [comment]
It does'nt work.

**Comment by Indavoid** [comment]
It's ok now, thanks ! Hope a new version soon ! :)

**Comment by un1versal** [comment]
> Indavoid commented
> When will be a new version of KVIRC ?

@Indavoid see https://github.com/kvirc/KVIrc/wiki/Downloading-KVIrc's-nightly-source-or-binaries

Best you get used to that for the meanwhile.

> wodim commented
> And we haven't got a clue of when we'll release a new version. This year, hopefully.

If it comes out this year with the fixes that should be in it, I'll come up with cold fusion reactor technology. :grinning:

**Comment by un1versal** [comment]
> And we haven't got a clue of when we'll release a new version. This year, hopefully.

If it comes out this year with the fixes that should be in it, I'll come up with cold fusion reactor technology. :grinning:
