### ISSUE TITLE
Windows: Opening KVIrc via IRC URL or shortcut opens a new instance every time

### ISSUE THREAD

**Issue by kidmar** [kvirc/KVIrc#1885]
I use Firefox browser to open irc:// links.
When I click on those links, kvirc open itself and connects to the server correctly.
The second time I click on the same link, a new copy of kvirc opens and connects to the same server again (or to another server if it was a different link).

In previous versions (<= 4.3.1) I only had 1 copy of kvirc open. Clicking the second time on the same link, didn't do anything (as I was already connected).
I think this is a regression (and can't find a way to workaroud this)

```
KVIrc 4.9.1 'Aria'

Infomazioni Runtime:
System name: Windows Release : 6.2.9200
System version: Windows 8 Professional (x64) (Build 9200)
Architettura: Intel64 Family 6 Model 60 Stepping 3
Qt version: 5.5.1
Qt theme: windowsvista

Informazioni Compilazione:
Build date: 2016-02-23 10:07:03 UTC
Sources date: 20160102
Revision number: git-6246-g8ff3bff
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.5.1
```

**Comment by un1versal** [comment]
I had a glace at appveyor config and the cmake configuration at https://github.com/kvirc/KVIrc/blob/master/.appveyor.yml#L118

I can see anything in there that would imply allow multiple sessions or instances, are you sure your links aren't passing `-f` flag to the KVIrc executable?

**Comment by un1versal** [comment]
mmm odd, Just fired up a Windows VM and If you clcik the KVIrc shortcut each time you click a new instance/session opens, and Im 100% sure that thers no `-f` flags anywhere there.

My Linux instance is self compiled KVIRc version and without `-f` it will not open a new instance and throws a warning message. Marking this as a Windows bug for now.

**Comment by kidmar** [comment]
No -f flag in links.
Also on my machine running kvirc.exe (or a shortcut) multiple times opens multiple instances.

**Comment by un1versal** [comment]
Yea Ive confirmed it also, now we wait...

**Comment by ctrlaltca** [comment]
Bug introduced here: https://github.com/un1versal/KVIrc/commit/f41c1f2868ee7d318b29e4c076db45a8b0346b3d#diff-bb6b2b0631283944011aa0ef4ca449d8L220

**Comment by un1versal** [comment]
> Bug introduced here: un1versal@f41c1f2#diff-bb6b2b0631283944011aa0ef4ca449d8L220

thats incorrect see conversation in https://github.com/kvirc/KVIrc/pull/1892#issuecomment-191643773
