### ISSUE TITLE
Icon remains highlighted when no longer pointed to by cursor

### ISSUE THREAD

**Issue by Arfrever** [kvirc/KVIrc#1896]
If I press any icon (marked with triangle) which opens its menu (e.g. `IRC Actions` or `User Mode` icon) and press in (almost) any place, then this icon will remain highlighted even when not pointed to by cursor.

Highlighting of icon disappears after moving cursor over icon and next to other place.

![kvirc_icons](https://cloud.githubusercontent.com/assets/656294/13500534/4976bcfc-e163-11e5-82c0-ab359456c0cc.png)

```
Executable Information

KVIrc 4.9.1 'Aria'

Runtime Info:
System name: Linux
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-02-25 03:59:53 UTC
Sources date: 20160102
Revision number: fb3d7d44b0a90afea71c1775d4511e3807ab2c63
System name: Linux
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   VERBOSE
   LIB_SUFFIX=64
   Threads=POSIX
Compiler name: /usr/bin/x86_64-pc-linux-gnu-g++
Compiler flags: -march=native -O2 -fno-ident -frecord-gcc-switches -pipe -Wall -fno-strict-aliasing 
Qt version: 5.5.1
```

**Comment by wodim** [comment]
Qt bug I guess... Maybe the theme.

**Comment by un1versal** [comment]
nope, not theme bug... it happens here also (even with no theme) so maybe Linux only maybe

you can tell his theme has icons and looks crap though mixed styles everywhere.

**Comment by wodim** [comment]
With no theme? I meant the Qt theme, I assume you use fusion too

**Comment by un1versal** [comment]
I do. So yes it maybe that idk... have not tested that.

@Arfrever test please with satrting kvirc from terminal with:

`kvirc -style=windows`

**Comment by Arfrever** [comment]
Problem is present with `kvirc -style=windows`.

**Comment by un1versal** [comment]
You will find that this problem is only with specific toolbar buttons, not all

![capture](https://cloud.githubusercontent.com/assets/3521959/14587547/bd32419a-04ac-11e6-8297-6af14a666fd6.PNG)

Only buttons that open a side menu cause this as screenshot shows above, I just selected the side menu on each and took a screenshot, result 3 buttons selected all at same time.

**Comment by un1versal** [comment]
@Arfrever 

slightly offtopic, but looking at your toolbar you have mixed really old icons and new ones,
I would recommend you go into your current theme directory and remove all the icons you have in there.

This will force the default core ones to be used instead.

**Comment by un1versal** [comment]
@Arfrever I think this issue is related to Qt if thats true we cant do jack about that
see https://github.com/kvirc/KVIrc/issues/2117

**Comment by IceN9ne** [comment]
I ran one of the examples that came with Qt5 (`diagramscene` to be specific) and it exhibits this same buggy behavior.

**Comment by IceN9ne** [comment]
This is an issue with Qt, not KVIrc, so nothing we can do.
