### ISSUE TITLE
Provide OS X installer

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1903]
.dmg, I guess

Using travis

**Comment by un1versal** [comment]
+1 e.g. ppl complain there's no nightlies

**Comment by ctrlaltca** [comment]
@DarthGandalf you may want to copy/paste from here: https://github.com/Cockatrice/Cockatrice/blob/master/CMakeLists.txt#L185
and then modify travis.yml to run `make package`

**Comment by un1versal** [comment]
No more advances on this?

**Comment by staticfox** [comment]
I tried setting up a qemu + kvm hackintosh instance, maybe ill mess around with it more today.

**Comment by un1versal** [comment]
I was thinking about what @ctrlaltca suggested, that way travis does everything

**Comment by DarthGandalf** [comment]
I tried the cpack way on real mac, but didn't succeed.

2016-04-03 19:11 GMT+01:00 un1versal notifications@github.com:

**Comment by un1versal** [comment]
would this help? (Chinese to me)
http://stackoverflow.com/questions/29587581/how-to-build-macosx-executables-on-travis-ci

**Comment by staticfox** [comment]
Added: https://kvirc.staticfox.net/

**Comment by un1versal** [comment]
> Added: https://kvirc.staticfox.net/

Nice, you should have used Comic Sans font `</sarcasm>`
