### ISSUE TITLE
hostpopup: telnet - ping - traceroute just make terminal blink open/closed

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1905]
As part of functionality test I run once in while, this time I came to the hostpopup popups.

located at https://github.com/kvirc/KVIrc/blob/master/data/defscript/popups.kvs#L683-L725

What has some effect: **Look up** **ftp** has some (desired) effect even if goes nowhere due to lack of supporting services on that end (as expected).

```
[15:13:52]  DNS Lookup result for query "username-48FE303E.dsl.telecom.blah"
[15:13:52]  Error: Unknown node (host not found)
```

The FTP one opens the brwoser to nowhere but thats OK I wouldnt expect this to work unless that had and ftp working on that host.

**What doesnt work:**
Its things like **ping** and **traceroute** and **telnet** commands that rely on the a OS Terminal that have the issue.

> **Note:** Windows apparently doesnt suffer from this and not sure if this is a specific Distro issue or what.

**traceroute, ping, telnet etc. are installed**

```

    item($tr("Telnet to ","defscript")$0,9)
    {
        system.runcmd telnet $0
    }

    item($tr("Traceroute to ","defscript")$0,36)
    {
        if("$system.ostype" == "unix") system.runcmd traceroute $0
        else system.runcmd tracert $0
    }

    item($tr("Traceroute6 to ","defscript")$0,36)
    {
        if("$system.ostype" == "unix") system.runcmd traceroute6 $0
        else system.runcmd tracert6 $0
    }

    item("Ping "$0,36)
    {
        system.runcmd ping $0
    }

    item("Ping6 "$0,36)
    {
        system.runcmd ping6 $0
    }

```

What happens instead is terminal opens/closes extremely fast (blibk and you miss it) and nothing else seems to happen.

Linux Mint 17.3

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 3.13.0-79-generic
System version: #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016
Architecture: x86_64
Qt version: 5.2.1
Qt theme: fusion

Build Info:
Build date: 2016-03-12 14:48:18 UTC
Sources date: 20160102
Revision number: git-6291-g936a854
System name: Linux-3.13.0-79-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.2.1
```

**Comment by wodim** [comment]
I can't reproduce it on Ubuntu Linux with LXDE.

**Comment by un1versal** [comment]
Linux Mint Cinnamon here.

**Comment by wodim** [comment]
What terminal is flashing? GNOME terminal? Cinnamon terminal? xterm?

**Comment by un1versal** [comment]
GNOME Terminal

**Comment by wodim** [comment]
I am unable to reproduce this on Cinnamon, Ubuntu, and GNOME terminal. Are you sure you haven't changed the GNOME terminal defaults in any way that could trigger this?

**Comment by un1versal** [comment]
pretty sure and to test I reset it with

`gconftool --recursive-unset /apps/gnome-terminal`

**Comment by wodim** [comment]
Try to record a vid of your desktop, use those popups, and then advancing frame by frame see what the error is in the terminal. I can't think of anything.

**Comment by wodim** [comment]
????

**Comment by un1versal** [comment]
I dont think you used enough interrogation marks.

Sort of fixed this anyway hence closed and labeled respectively.

**Comment by wodim** [comment]
What was the problem?

**Comment by un1versal** [comment]
Not entirely sure tbh, but holding the terminal open when command exits sort of helped.
Its not something on by default either so not sure how things work without that on your end.
