### ISSUE TITLE
Incorrect formatting of user tip text for users present in large number of channels

### ISSUE THREAD

**Issue by Arfrever** [kvirc/KVIrc#1906]
User tip text for users present in large number of channels (e.g. about 100 channels) has incorrect formatting (large and very wide glyphs).

This regression was introduced during last week.
I use revision 405c5bf69523a60d76ca86c0ae8d1b47e3afbd22.

(Unfortunately user tip text is disappearing quickly if I press PrintScreen button, so I cannot create useful screenshot.)

**Comment by un1versal** [comment]
Can you take a picture with your mobile or make a video perhaps?

Also try to post this https://github.com/kvirc/KVIrc/wiki/Submitting-a-bug-report#information-required-when-making-a-bug-report-via-github-issues info,

What would also be helpful would be what network/channels and user you seeing this issue with so we can test the exact same scenario. 

FYI I dont see this in Linux what I see is this

![capture](https://cloud.githubusercontent.com/assets/3521959/13752361/48c8f63e-ea06-11e5-9c19-75b9f5de0ed1.PNG)

Eventually it cuts off channel and stops adding them

**Comment by Arfrever** [comment]
Maybe requirements of occurrence of this problem were misidentified. Anyway user `Arfrever` in Freenode.

**Comment by un1versal** [comment]
You have to be in 100 channels in order to do this right?

aside from the information requested would you mind also sharing your freenode winproperties.kvc so at least can join the same channels...

**Comment by un1versal** [comment]
I removed the wrapping in the table which is probably partly responsible for the screenshot above
Before code was     

```
    buffer = "<table width=\"100%\">" \
            "<tr><td bgcolor=\"#303030\">" \
            "<center><font color=\"#FFFFFF\"><b>";
```

This is the code after https://github.com/kvirc/KVIrc/blob/master/src/kvirc/ui/KviConsoleWindow.cpp#L259-L261

The code responsible for the part I think your talking about and up in screenshot was:

```
    if(connection())
    {
        QString chans;
        if(connection()->getCommonChannels(nick,chans,false))
        {
            buffer += "<tr><td bgcolor=\"#F0F0F0\"><font color=\"#000000\">";
            buffer += __tr2qs("On <b>");
            buffer += KviQString::toHtmlEscaped(chans);
            buffer += "</b></font></td></tr>";
        }
    }
```

and now https://github.com/kvirc/KVIrc/blob/master/src/kvirc/ui/KviConsoleWindow.cpp#L325-L336

I dont think any of those changes would cause the issue you describe, though it may explain my screenshot issue which ideally would break after around 10 channels.

**Comment by Arfrever** [comment]
Probably sufficient list of channels:

```
#apr,#asf,#bottlepy,#bpython,#buildbot,#buildout,#cryptography-dev,#distutils,#divmod,#django-dev,#dulwich,#eric-ide,#eventlet,#fabric,#fcitx,#funtoo,#gentoo-amd64-dev,#gentoo-apache,#gentoo-base,#gentoo-bugs,#gentoo-commits,#gentoo-comrel,#gentoo-council,#gentoo-cpp,#gentoo-crypto,#gentoo-db,#gentoo-dev,#gentoo-doc,#gentoo-docs-pl,#gentoo-elections,#gentoo-forums,#gentoo-groupcontacts,#gentoo-hardened,#gentoo-java,#gentoo-kde,#gentoo-kernel,#gentoo-meetings,#gentoo-multilib,#gentoo-office,#gentoo-ops,#gentoo-overlays,#gentoo-perl,#gentoo-portage,#gentoo-pr,#gentoo-python,#gentoo-qa,#gentoo-qt,#gentoo-ruby,#gentoo-science,#gentoo-toolchain,#gentoo-trustees,#gentoo-vim,#gentoo-x86,#gnupg,#grok,#hgsubversion,#httpd-dev,#ipython,#jython,#kss,#kvirc,#libcloud,#matplotlib,#mercurial,#openrc,#paramiko,#pil,#plone,#plone-framework,#plone.org,#pocoo,#pychecker,#pygame,#pylib,#pylons,#pypa,#pypa-dev,#pypy,#pyramid,#python-dev,#python-testing,#pythonpaste,#repoze,#scipy,#serf,#silva,#sphinx-doc,#sqlalchemy,#sqlalchemy-devel,#sqlite,#subclipse,#twisted,#twisted-dev,#viewvc,#vim,#zope
```

**Comment by un1versal** [comment]
nope, cannot duplicate at all I get a similar tooltip to what I posted above), 

![capture](https://cloud.githubusercontent.com/assets/3521959/13755041/3e8a7d68-ea11-11e5-996f-f9c7bea25a72.PNG)

Can you provide the information requested in https://github.com/kvirc/KVIrc/issues/1906#issuecomment-196406518 please

**Comment by Arfrever** [comment]
kvirc-9999 from Gentoo

```
Executable Information

KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-03-14 13:00:20 UTC
Sources date: 20160102
Revision number: 405c5bf69523a60d76ca86c0ae8d1b47e3afbd22
System name: Linux
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   VERBOSE
   LIB_SUFFIX=64
   Threads=POSIX
Compiler name: /usr/bin/x86_64-pc-linux-gnu-g++
Compiler flags: -march=native -O2 -fno-ident -frecord-gcc-switches -pipe -Wall -fno-strict-aliasing 
Qt version: 5.5.1
```

**Comment by un1versal** [comment]
can you compile with https://github.com/un1versal/KVIrc/commit/d72002946c287e011b5dff997e3ea66ba58e1b6c

with `<table style=\"white-space: pre-line\">`

![capture](https://cloud.githubusercontent.com/assets/3521959/13757544/fa79a5d4-ea1c-11e5-869e-8b0616905fde.PNG)

with `<table style=\"white-space: pre-line\">`
![capture](https://cloud.githubusercontent.com/assets/3521959/13757662/7eba8386-ea1d-11e5-99e3-9d53be1896c0.PNG)

with `<table>`
![capture](https://cloud.githubusercontent.com/assets/3521959/13759030/44d4a744-ea24-11e5-9d2e-a74b661d6ca2.PNG)

**Comment by Arfrever** [comment]
un1versal's patch (`<table style=\"white-space: pre-wrap\">`) fixed problem.

I have no opinion about whether `<table style=\"white-space: pre-wrap\">` or `<table>` is better.

**Comment by un1versal** [comment]
for me its which makes the lot more easily readable, hence why I tested all solutions
I looking where the breaks occur and if its more or less readable with said break in each solution...

I know, I know, Im OCD about these things... :nut_and_bolt:

**Comment by Arfrever** [comment]
Screenshot showing original problem:
![kvirc-user_tip_text-table-white-space_pre](https://cloud.githubusercontent.com/assets/656294/13761159/3a08ed12-ea37-11e5-90d3-9cbe51f614c9.png)

**Comment by un1versal** [comment]
nice... thats interesting. I wonder if KDE contributed to that aberration. No idea what would cause it for sure.
