### ISSUE TITLE
charybdis and ircd-seven mode mappings are wrong

### ISSUE THREAD

**Issue by kaniini** [kvirc/KVIrc#1908]
tl;dr: All modes are available on charybdis that are in ircd-seven.

https://github.com/kvirc/KVIrc/blob/e5db866836f2172a6556aba111e9437435e20751/src/kvirc/kernel/KviIrcConnectionServerInfo.cpp#L951-L982

Of special note, `+pqFS` are available on charybdis.

`+R` does not exist on seven, and `+M` is available in charybdis as an extension.

The descriptions for `+F` and `+S` are wrong, they should be:
- `+F`: allow anyone to forward users to this channel
- `+S`: SSL only

**Comment by wodim** [comment]
now that's a cute bunny

**Comment by kaniini** [comment]
Also missing is `+c` (strip colours).  I think that's all the ones that are not right.

Looks like someone just copypasta'd the hyperion structs or something.
