### ISSUE TITLE
Features: MPRIS v2.2

### ISSUE THREAD

**Issue by rasdark** [kvirc/KVIrc#1912]
Hi! 
KVIrc currently supports the MPRIS 1 API but is not MPRIS 2 capable.

More desktop applets (MPRIS Applet in GNOME and Xfce, xfce4-soundmenu-plugin in Xfce, Ayatana Sound Menu) are able to control only players supporting the latest version of the MPRIS standard (like Amarok, Banshee, Clementine, Guayadeque, Pragha, Rhythmbox, Spotify, VLC, xnoise, etc) and are not able to control MPRIS 1 capable players like Audacious.

I think it would make sense to implement an MPRIS 2 interface in KVIrc.

References:
https://specifications.freedesktop.org/mpris-spec/latest/

**Comment by rasdark** [comment]
Sorry, Audacious already supports the  MPRIS 2 standard :) But KVIrc doesn't!

**Comment by un1versal** [comment]
KVirc doesnt even support spotify currently so theres that also.

**Comment by wodim** [comment]
He means Spotify over MPRIS, which only works on Linux. What we had on Windows was a hack that read the Spotify window title.

**Comment by rasdark** [comment]
Congratulations! Very grateful!
