### ISSUE TITLE
right click has to be done with mouse to use spell checker

### ISSUE THREAD

**Issue by dennisroczek** [kvirc/KVIrc#1914]
### Expected behavior

hitting shift+f10 or the "right click key" on the keyboard when the text curser is in the wrong spelled word should open the right-click-menu like moving the mouse there and hit right-click

Be aware that MS Windows has two events: one for thee mouse right-click and one for the keyboard courser...
### System information

KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Windows Release : 6.2.9200
System version: Windows 8 Enterprise (x64) (Build 9200)
Architecture: Intel64 Family 6 Model 69 Stepping 1
Qt version: 5.5.1
Qt theme: windowsvista

Build Info:
Build date: 2016-03-27 12:36:32 UTC
Sources date: 20160102
Revision number: git-6331-g2137554
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.5.1
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Webkit, Perl, Qt5, KVS

oh I missed: 
This behavior was already incorrectly in nightly:
[17:43:04] <DennisRoczek> Erstellungsdatum: 2015-10-31 00:57:26 UTC
[17:43:04] <DennisRoczek> Datum der Quelldateien: 20151002
[17:43:04] <DennisRoczek> Revisionsnummer: git-5613-gb8c034d

**Comment by wodim** [comment]
I'm not sure this will work with Shift+F10, though, can you check it? (Wait one hour or so until the new nightly is built, check the number)

**Comment by un1versal** [comment]
This has always annoyed me however the patch https://github.com/kvirc/KVIrc/commit/a559c50d8ff1ba2c265d22cb45ce0b79b26584d9 doest make this behavior change, still need to click on the word or move the cursor there else cursor wont move there just by right clicking the word to be corrected.

**Comment by un1versal** [comment]
@dennisroczek can you try a nightly build with https://github.com/kvirc/KVIrc/commit/a559c50d8ff1ba2c265d22cb45ce0b79b26584d9 and see if your issue is fixed and report back please

**Comment by DarthGandalf** [comment]
Ctrl-G opens the spellcheck menu directly.

**Comment by un1versal** [comment]
in 2 days will close this as fixed for lack of user feedback

**Comment by wodim** [comment]
Well, to answer myself: this works only with the Menu key, not Shift+F10, but since Shift+F10 is an usable shortcut for the `OnAccelKeyPressed` event, I won't implement it.

**Comment by dennisroczek** [comment]
"but since Shift+F10 is an usable shortcut for the OnAccelKeyPressed event, I won't implement it."

Nope it is not. At least very much fast than searching where the mouse is and take first the mouse in the hand.

Moreover this laptop doesn't have a right-click-keyboard-key.  :-(

Sry, I was very busy as I had to work some extra hours at work...

**Comment by un1versal** [comment]
if you read what wodim said, shift+f10 is an already used shortcut for something else + you already have two available key combos ctrl+g (open spellchecker directly) and menu key)opens context menu) if thats not enough idk.
