### ISSUE TITLE
Right click menu => Part

### ISSUE THREAD

**Issue by Stanzilla** [kvirc/KVIrc#1921]
### Expected behavior

Should part the channel
### Actual behavior

Errors with `[15:27:08] [KVS] Warning: You don't appear to be on channel No
[15:27:08] [KVS]   In script context "click callback for windowpopup.item5", line 1, near character 67`
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Windows Release : 6.2.9200
System version: Windows 8 Professional with Media Center (x64) (Build 9200)
Architecture: Intel64 Family 6 Model 58 Stepping 9
Qt version: 5.5.1
Qt theme: windowsvista

Build Info:
Build date: 2016-04-02 21:03:51 UTC
Sources date: 20160102
Revision number: git-6353-g0515b22
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.5.1
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Webkit, Perl, Enchant, Qt5, KVS
```

**Comment by wodim** [comment]
Try to restore your default script, at least popups.

**Comment by Stanzilla** [comment]
I did, same error.

**Comment by ctrlaltca** [comment]
> You don't appear to be on channel No

what's the name of the channel / name shown on the window you are right clicking on?

**Comment by Stanzilla** [comment]
`#paragon`

**Comment by wodim** [comment]
Ah, got it.

**Comment by un1versal** [comment]
We recently added a issue report template to make it easy for everyone to report issue properly with necessary info **so we dont have to guess or beg for the info**, like **Steps to reproduce** which were ignored here.

If its on the issue template please complete it.
