### ISSUE TITLE
Feature request: Add DCC I/O traffic graph support

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1931]
Like title says.

Current IRC IO graph doesnt do this.

@staticfox there you go.

**Comment by un1versal** [comment]
its DCC IO graph support, we dont have that.

**Comment by staticfox** [comment]
o

**Comment by ghost** [comment]
The main I/O graph already includes both IRC traffic and DCC traffic.  Is this feature request asking for it to be split into 2 graphs (1 for each), 3 graphs (1 for each plus a total graph), or asking for it to be bug fixed for some bug you're experiencing?

The I/O graph on my client is verified to work with both IRC traffic and DCC traffic in latest trunk.

**Comment by un1versal** [comment]
> he main I/O graph already includes both IRC traffic and DCC traffic

not according to the pragma

> or asking for it to be bug fixed for some bug you're experiencing?

The bug I reported was closed so it doesnt exist.

**Comment by ghost** [comment]
> The bug I reported was closed so it doesnt exist.

Hmm, did you follow the guidelines for reporting bugs and include version dumps and compile settings?  I think we have a template for that.  I think that would help.

**Comment by un1versal** [comment]
The bug report https://github.com/kvirc/KVIrc/issues/1619 precedes such template but includes all basic information, if theres more required information ask for it.

Anyway Im closing this, beginning to hate Qt even more and starting to wonder towards the negative.

**Comment by un1versal** [comment]
> The main I/O graph already includes both IRC traffic and DCC traffic. Is this feature request asking for it to be split into 2 graphs (1 for each), 3 graphs (1 for each plus a total graph), or asking for it to be bug fixed for some bug you're experiencing?
> 
> The I/O graph on my client is verified to work with both IRC traffic and DCC traffic in latest trunk.

Sorry qt 5.5.1 and dcc doesnt even make anything budge, so really idk what to make of your verification if your build has some special code that upstream doesnt. Ive tested this with qt 5.5.1 and it makes no difference.

> pragmaware commented on 27 Sep 2015 in #1619
> 
> You mean the one you open with /iograph.open?
> That one shows IRC traffic only...
