### ISSUE TITLE
Broken appveyor builds since 14-04-2016

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1934]
Apparently its failing since I tried bumping openssl version in https://github.com/kvirc/KVIrc/commit/5044017daf0ebb30191807f666d1936048e43e83

Without reading logs fully I thought chnage had somehow triggered something to die and reverted change in https://github.com/kvirc/KVIrc/commit/0250dab97159263c25a4adfbd0b4a4dae68c0d4b but to no avail

However reading the build logs the error more seems related to a corrupt or incomplete download of jom

```
jom v1.1.0
 Downloading jom 32 bit
   from 'https://download.qt.io/official_releases/jom/jom_1_1_0.zip'
 Chocolatey expected a file at 
 'C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\jom\1.1.0\jomInstall.zip' 
 to be of length '1116638' but the length was '526575'.
 At C:\ProgramData\chocolatey\helpers\functions\Get-ChocolateyWebFile.ps1:162 
 char:101
 +     if ($headers.ContainsKey("Content-Length") -and ($fi.Length -ne 
 $headers["Co ...

     + CategoryInfo          : OperationStopped: (Chocolatey expe...h was '5265 
    75'.:String) [], RuntimeException
     + FullyQualifiedErrorId : Chocolatey expected a file at 'C:\Users\appveyor 
    \AppData\Local\Temp\1\chocolatey\jom\1.1.0\jomInstall.zip' to be of length  
    '1116638' but the length was '526575'.
The install of jom was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\jom\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures:
 - jom
Command exited with code 1

```

**Comment by DarthGandalf** [comment]
For some reason only 64 bit build is affected, though both are using the same jom

**Comment by DarthGandalf** [comment]
Or probably jom choco maintainer fixed it already...
I've started new build.

**Comment by un1versal** [comment]
64-bit still broken.

Downloading manually you get the correct size file in any case.https://download.qt.io/official_releases/jom/

That doesnt come from choco :/

**Comment by DarthGandalf** [comment]
It doesn't matter. It's only run during build instead of nmake.

2016-04-15 9:29 GMT+01:00 un1versal notifications@github.com:

**Comment by un1versal** [comment]
Yea as much as I try this is clearly wooshing over my head.

It probably means nothing but in my feeble attempts to further understand the process here is https://github.com/kvirc/KVIrc/pull/1935, The choco package looking at the date is newer than the fix so lets see what happens.

**Comment by un1versal** [comment]
Sorry to whos concerned, clearly must been me touching appveyor.yml that broke the dammed thing. It shouldn't happen but Ive learned my lesson, steer clear from appveyor.yml direct merges. fondling over PR is much safer tbh.

**Comment by un1versal** [comment]
interesting https://ci.appveyor.com/project/DarthGandalf/kvirc/branch/master both 32-bit 64-bit built ok just choked with some protocol violation at the end...

```
Deploying using FTP provider
Uploading artifact "KVIrc-4.9.2-dev-git-6401-g96d9144-x86.exe" to FTP server "ftp://ftp.nutime.de" as "KVIrc-4.9.2-dev-git-6401-g96d9144-x86.exe"
The underlying connection was closed: The server committed a protocol violation.
```

**Comment by un1versal** [comment]
Another different error
https://ci.appveyor.com/project/DarthGandalf/kvirc/build/0.0.0.0.1-branch-master-build-1476

```
Deploying using FTP provider
Uploading artifact "KVIrc-4.9.2-dev-git-6406-g281e60e-x86_64.exe" to FTP server "ftp://ftp.nutime.de" as "KVIrc-4.9.2-dev-git-6406-g281e60e-x86_64.exe"
The remote server returned an error: (500) Syntax error, command unrecognized.
```

Now travis also seems to be going nuts randomly

https://travis-ci.org/kvirc/KVIrc/builds/123545611
https://travis-ci.org/kvirc/KVIrc/jobs/123377349

**Comment by un1versal** [comment]
Magic, seems to have cured itself, if this holds for next 3 commits to master, then this can be closed.

**Comment by DarthGandalf** [comment]
@un1versal FTP was issue on d00p's side, and d00p fixed it.

**Comment by un1versal** [comment]
yes but it wasnt failing just because of that, now was it?
