### ISSUE TITLE
URLs don't open in Mac OS X

### ISSUE THREAD

**Issue by kartagis** [kvirc/KVIrc#1936]
### Expected behavior

I expect the URLs to open by double/single clicking on Mac OS X
### Actual behavior

They don't
### Steps to reproduce the issue
1. Click on any URL
   2.
   3.
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: MacOS X
System version: Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64
Architecture: x86_64
Qt version: 5.6.0
Qt theme: macintosh

Build Info:
Build date: 2016-04-15 07:25:45 UTC
Sources date: 20160102
Revision number: 
System name: Darwin-13.4.0
CPU name: x86_64
Build command: /usr/local/Cellar/cmake/3.5.1/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/Users/travis/build/kvirc/KVIrc/build/KVIrc.app
   Threads=POSIX
Compiler name: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
Compiler flags: N/A
Qt version: 5.6.0
Features: IRC, IPv6, Crypt, SSL, IfAddr, IPC, Transparency, Perl, Python, Enchant, Qt5, KVS

[//]: # (Also Enter any OS information the "Executable Information" tab doesn't contain, e.g. KDE, Gentoo, Linux Mint, etc.)

Mac OS X El Capitan
```

**Comment by un1versal** [comment]
### Expected behavior

read and try this https://github.com/kvirc/KVIrc/wiki/FAQ#clicking-urls-doesnt-work-anymore-after-upgrading-whats-up

**Comment by kartagis** [comment]
I've already got ![screenshot 2016-04-15 10 15 33](https://cloud.githubusercontent.com/assets/1607518/14558962/4656ae16-030e-11e6-8589-8f245b7125ac.png)

**Comment by kartagis** [comment]
Sorry, without ,

**Comment by un1versal** [comment]
its should be

`openurl $0;`

including the semicolon at the end

**Comment by kartagis** [comment]
No, it's still the same.

**Comment by un1versal** [comment]
For my curiosity only, can you show a screenshot of this settings page: **ignore what mine says its Linux**
![capture](https://cloud.githubusercontent.com/assets/3521959/14559103/70c4e902-02fe-11e6-8a7b-b3455d25362e.PNG)

Also set KVIrc aside, try

Open a terminal and type: `open https://github.com`

**Comment by kartagis** [comment]
![screenshot 2016-04-15 14 01 47](https://cloud.githubusercontent.com/assets/1607518/14559613/b8444818-0312-11e6-90c4-d9fa38333aac.png)

**Comment by un1versal** [comment]
ah no, that cant say xdg-open in OS X

it must say `run open $0`

1) change them all to read `run open $0` 
2) click apply
3) close kvirc
4) reopen kvirc

retry

Reason for closing KVIrc is that setting only written to disk when you close kvirc (clicking apply writes them to memory)
