### ISSUE TITLE
Tree window list scrolling dies on OS X 

### ISSUE THREAD

**Issue by Cpuroast** [kvirc/KVIrc#1940]
### Expected behavior

Tree window list scrolling on OS X works when "Mouse wheel changes the active window instead of scrolling the scrollbar" is unchecked.
### Actual behavior

Tree window list scrolling on OS X dies when "Mouse wheel changes the active window instead of scrolling the scrollbar" is unchecked.
### Steps to reproduce the issue
1. Uncheck "Mouse wheel changes the active window instead of scrolling the scrollbar"
2. Try to scroll the Tree window list
### System information

```
OS X 10.10.5

KVIrc 4.9.2 'Aria'

Runtime Info:
System name: MacOS X
System version: Darwin Kernel Version 14.5.0: Mon Jan 11 18:48:35 PST 2016; root:xnu-2782.50.2~1/RELEASE_X86_64
Architecture: x86_64
Qt version: 5.6.0
Qt theme: macintosh

Build Info:
Build date: 2016-04-16 03:28:45 UTC
Sources date: 20160102
Revision number: 
System name: Darwin-13.4.0
CPU name: x86_64
Build command: /usr/local/Cellar/cmake/3.5.1/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/Users/travis/build/kvirc/KVIrc/build/KVIrc.app
   Threads=POSIX
Compiler name: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
Compiler flags: N/A
Qt version: 5.6.0
Features: IRC, IPv6, Crypt, SSL, IfAddr, IPC, Transparency, Perl, Python, Enchant, Qt5, KVS
```

**Comment by un1versal** [comment]
What I get in Linux is another bug something old thats never been fixed when trying to duplicate this https://github.com/kvirc/KVIrc/issues/1301 so the reason may or may not be somewhat related.

**Comment by un1versal** [comment]
this issue should be retested after https://github.com/kvirc/KVIrc/pull/2047 is merged
