### ISSUE TITLE
Tray icon state frozen

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#1941]
I wrote this script, to be used just after I connect to clear highlights from all windows:

```
foreach (%w, $window.list(all, all)) {
    window.highlight 0 %w
}
```

And when I use it the tray icon gets stuck forever in this state:

![2016-04-17_16-01-37](https://cloud.githubusercontent.com/assets/1001553/14587589/b4c3a2f2-04b5-11e6-89fe-d4b610bea1a7.png)

**Comment by un1versal** [comment]
This report reminds me of that joke, A guy goes to the doctor's and says "Doctor it hurts when I move my arm" The Doctor replies, "Then stop moving your arm".

**Comment by wodim** [comment]
As discussed on IRC: even though all entries in the window list are dehighlighted by that script, it looks like the tray icon keeps a separate record of the highlight level of each window, and so the way to fix the tray icon is to switch to all channels, one by one.

**Comment by un1versal** [comment]
Cant you script that also in that for loop?

**Comment by wodim** [comment]
What?

**Comment by wodim** [comment]
Ah, no. The tray icon and the highlight level of each window must always be in sync. Therefore there isn't even is a scripting function to edit the highlight level of a window on the tray icon.

**Comment by un1versal** [comment]
you can disable the tray icon anyway before running that for loop... if you do and minimize kvirc, the icon tray is automatically re-enabled.

**Comment by wodim** [comment]
I know. I can also use mIRC.

**Comment by un1versal** [comment]
that was a genuine workaround suggestion, but if you want to use mirc instead, go ahead.

**Comment by un1versal** [comment]
This 100% works

```
foreach (%w, $window.list(all, all)) {
    trayicon.hide
    window.highlight 0 %w
    trayicon.show
}
```

**Comment by wodim** [comment]
Not a bug.
