### ISSUE TITLE
broken server link right-click to view other options

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1946]
### Expected behavior

You should get some popup with options
### Actual behavior

You get nothing

![capture](https://cloud.githubusercontent.com/assets/3521959/14649037/30ddb92e-065d-11e6-8b39-6aa7d66bf0b0.PNG)
### Steps to reproduce the issue
1. right click a server link
### System information

Any, this never worked afaik

**Comment by staticfox** [comment]
Fixed
