### ISSUE TITLE
Ubuntu 14.04LTS and Variants Test Builds for Qt 5.5.1 Are Now Available 

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1949]
### Intro

Thanks to @AlexanderP's hard work and a couple of emails, Im happy to announce that test builds for Qt 5.5.1 for Ubuntu 14.04LTS and variants based distros are now available for testing.

All going well with these tests which should hopefully resolve any issues that default 5.2.1 builds currently exhibit and then packages will be managed via our PPA
### Warning

By using this ppa you understand that any system or app breakages due to some unforeseen reason may occur due to factors outside our control for however likely or unlikely this maybe in practice,
### `sudo apt-get dist-upgrade`

I presume you can handle the rest from here but if you cant just ask or use a search engine.
### Why are you building Qt packages?

We are building them because the old 5.2.1 Ubuntu Trusty version is clearly buggy it affects KVIrc and other apps and unlikely ever be fixed.
Also we have control over these packages and if anything is wrong with packaging we (AlexanderP in fact) have some control over.

**_Known issues are:**_
- https://github.com/kvirc/KVIrc/pull/1932#issuecomment-210049026
- https://github.com/kvirc/KVIrc/commit/99925aa796ad1319f6f374fedc9a6d5907294b36#commitcomment-17079776
- https://github.com/kvirc/KVIrc/issues/1882 **Fixed by Qt 5.5.1 self compiled version**

Please report any issues you find due to new Qt as well (though not as important as we cant do anything about Qt bugs)
### I Installed Qt 5.5.1, now what?

Report any problems **that have been solved** by new Qt 5.5.1
Report any issue(s) caused by these Qt packages in KVIrc and elsewhere, so that this can be improved.
### Who should report back?

Anyone who uses KVIrc from our PPA or self Compiles..
#### Include system information with your replies here/

`(Type "/about.kvirc" (or click "Help → About KVIrc") and copy&paste the details from the "Executable Information" tab below between`````marks)`
`(Also Enter any OS information the "Executable Information" tab doesn't contain, e.g. KDE, Gentoo, Linux Mint, etc.)`

```

```

**Comment by un1versal** [comment]
@ctrlaltca any possibility you can text this since you noticed other issues?

Also as a general question to everyone, what are your thoughts on providing this Qt build as a fix for these Qt issues with Trusty?

**Comment by ctrlaltca** [comment]
The build installs and works just fine. It's incompatible with `appmenu-qt5`, since that package depends on the old qt5 version provided by ubuntu itself.

**Comment by DarthGandalf** [comment]
I didn't check where this ppa installs its qt, but /usr is too disruptive for the rest of system which relies on qt version.

There is ppa:beineri/opt-qt551-trusty with qt 5 already available, which installs to /opt
We can use that one, I think, as dependency for KVIrc ppa, and build it using that version.
I don't know how it would work with `appmenu`.

If it won't, it won't provide any benefit.

**Comment by un1versal** [comment]
> The build installs and works just fine. It's incompatible with appmenu-qt5, since that package depends on the old qt5 version provided by ubuntu itself.

Didn't check yet, this doesnt have appmenu-qt5 package? So if it did would be OK, right?

> There is ppa:beineri/opt-qt551-trusty with qt 5 already available, which installs to /opt
> We can use that one, I think, as dependency for KVIrc ppa, and build it using that version.
> I don't know how it would work with appmenu.

Why would we want to use random 3rd party ppa's  and packages that we have no control over whatsoever? 

Especially if you want to build KVIrc against it, if anything is wrong we can ask @AlexanderP if it can be fixed like these comments right here from you and ctrlaltca.
3rd party ppa we are at the mercy of whatever these random people, if they dont reply to emails we stuffed, with Alex this isnt even a consideration. 

> I didn't check where this ppa installs its qt, but /usr is too disruptive for the rest of system which relies on qt version.

We definitely dont want to break anything system or otherwise of anything that relies on Qt, **we want to fix** not break.

@AlexanderP can anything be done about appmenu-qt5?

**Comment by ctrlaltca** [comment]
> Didn't check yet, this doesnt have appmenu-qt5 package? So if it did would be OK, right?

No `appmenu-qt5` package is available from the PPA, and the ubuntu's provided package requires ubuntu's qtbase 5.2.1 package in order to be installed. To be clear, `apt-get` won't let me install the package for failed dependencies.

I understand the problem raised by @DarthGandalf: the Qt packages from this PPA replace ubuntu's packages, and they could potentially break any other installed package that depends on qt5. I've said "could" because Qt minor versions should be [ABI compatible](https://wiki.qt.io/Qt-Version-Compatibility#Binary_Compatibility_Guidelines), but i don't know how heavily the ubuntu package is patched and how much compatibility is guaranteed.

I'm using `ppa:beineri/opt-qt551-trusty` on another project. This PPA installs Qt5 in another separated directory (/opt/qt551), so it won't break anything else. It has some major drawbacks:
- ask the user to install another PPA and download another copy of a different qt version 
- if you put /opt/qt551 in PATH, you'll have problems with other software. If you don't, you'll have problem with KVIrc (at least compiling, think about qmake/moc/etc..)
- if you put /opt/qt551 in ldconfig's paths, you'll have problems with other software. If you don't, you won't be able to run KVIrc (unless we mess with CMake and RPATH)

So, there's no perfect solution other than upgrading to a more recent distro version or (sadly) stick with the unsupported Qt4. I saw at least a dozen projects having the same exact problem, this is all ubuntu's fault, and they don't give a fuck. Just look at the appmenu-qt5' issues on their bugtracker, marked as "critical" but still open after 2 years with no patch whatsoever.

**Comment by un1versal** [comment]
There is also an alternative (like you said upgrade). Today 16.04LTS is released, other variants based on this are soon following, in a few months we could potentially say that to use nightlies we should have a minimum Qt5.5.1 and in Ubuntu OS bases 16.04LTS or better.

For other distros whichever provides minimum known working Qt versions whatver theire OS versions are

So in a couple of months we can make such announcement and already require this in KVIrc.

Then we can ditch anything else,

> I understand the problem raised by @DarthGandalf: the Qt packages from this PPA replace ubuntu's packages, and they could potentially break any other installed package that depends on qt5.

I dont disagree with his concerns, they are valid.
Using 3rd party ppa's (ppa:beineri/opt-qt551-trusty) packages/packaging process we dont have control over, absolutely none is silly imo.

**Comment by AlexanderP** [comment]
@un1versal  Today I added package ppa appmenu-qt5 with Ubuntu 16.04 and is now uploaded kvirc 4: 4.9.2 ~ git-6469-g7954653-1ppa1 ~ trusty1 in https://launchpad.net/~alex-p/+archive/ubuntu/test/+packages

**Comment by staticfox** [comment]
Alex, slightly off topic, but does your Travis change automatically unshadow git history?

**Comment by un1versal** [comment]
> @un1versal Today I added package ppa appmenu-qt5 with Ubuntu 16.04 and is now uploaded kvirc 4: 4.9.2 ~ git-6469-g7954653-1ppa1 ~ trusty1 in https://launchpad.net/~alex-p/+archive/ubuntu/test/+packages

Thx lets see if it solves @ctrlalca install he said apt-get wont let him install it due to dependency issues?

AlexanderP there's some concern, that this will break Ubuntu and other apps, I dont understand the implications fully. what do you think (please read https://github.com/kvirc/KVIrc/issues/1949#issuecomment-212850506)

**Comment by AlexanderP** [comment]
@staticfox I did not quite understand the question :(

**Comment by AlexanderP** [comment]
@un1versal Theoretically, this can cause damage to other applications, in practice, I do not know. 
You can make 2 ppa.
1 With the system qt
2 With the compiled qt-5.5.1

**Comment by un1versal** [comment]
@AlexanderP kvirc's ppa is already with systeme Qt currently. right?

You mean another ppa with Qt-5.5.1 packages + kvirc compiled against it?

**Comment by AlexanderP** [comment]
@un1versal All right

**Comment by un1versal** [comment]
> @un1versal All right

Im confused :D

@AlexanderP  That was a question wasnt asking for a new ppa as idk what everyone else wants

**Comment by AlexanderP** [comment]
@un1versal Possible to create second ppa with qt-5.5.1 compiled and kvirc to 14.04 and 15.10. This is my idea of an alternative.

**Comment by DarthGandalf** [comment]
Or... just don't give a shit about broken Ubuntu version.

2016-04-21 16:38 GMT+01:00 Alexander Pozdnyakov notifications@github.com:

**Comment by un1versal** [comment]
Ive been testing a self compiled build with this on a secondary VM, now and I think Im about ready to start using it daily for a while.
@ctrlaltca didn't find any issues installing appmenu-qt5 it was straight forward all the way.

As for system breakages have seen no issues with other apps that use Qt as well.
Ill consider a good test around two weeks of daily use for both OS/KVIrc and other apps wise, Ill update here soon after.
IMO we can slap a warning on this potential PPA and clearly also tell them we prefer newer distro. so no support necessary imo...

> Or... just don't give a shit about broken Ubuntu version.

That goes without saying really and also save on toilet paper ;)

**Comment by un1versal** [comment]
OK bugs fixed so far by using Qt 5.5.1 (will update as I go)

https://github.com/kvirc/KVIrc/issues/1882

However during initial setup my VM lost mouse pointer, which was solved by reinstalling virtual-box additions and a reboot.

**Comment by un1versal** [comment]
@AlexanderP added a ppa to our launchpad page with I presume KVIrc compiled against Qt 5.5.1 which also contains Qt 5.5.1 that will update and replace your Ubuntu installed Qt.

Added instructions to main post

**Comment by un1versal** [comment]
Well this build is paying off on helping to identify issues that are Qt related

https://github.com/kvirc/KVIrc/issues/1840#issuecomment-215961659 another one fixed by newer Qt.
