### ISSUE TITLE
Sources date: no longer updated or exported to the about dialog

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1954]
Its not very important and already knows, but here it is just in case
### Expected behavior

Open about dialog > Executable information tab

```
Build Info:
Build date: 2016-04-22 16:39:42 UTC
Sources date: 20160422
```
### Actual behavior

```
Build Info:
Build date: 2016-04-22 16:39:42 UTC
Sources date: 20160102
```
### Steps to reproduce the issue
1. Compile KVIrc and watch as sources date is reflected correctly.
2. Open about dialog > Executable information tab Sources date is stuck in 20160102
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 3.13.0-85-generic
System version: #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-04-22 16:39:42 UTC
Sources date: 20160102
Revision number: git-6482-g2435391
System name: Linux-3.13.0-85-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.5.1
Features: IRC, Debug, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

**Comment by Stanzilla** [comment]
Pretty sure we already talked about sourcesdate being useless and it should be removed? The git hash is the only interesting thing about it. What is sourcesdate used for anyway? Docs?

**Comment by un1versal** [comment]
It wasnt removed despite that discussion, it was instead implemented and worked very well until recently, why do you care either way?

**Comment by staticfox** [comment]
It was intentionally disabled or something https://github.com/kvirc/KVIrc/commit/14f39c4297bfe232d0bfcbe13a97bd22e5769a11 _not a CMake ninja_

**Comment by un1versal** [comment]
its probably something to do with tarball BS.

**Comment by staticfox** [comment]
lolwut

**Comment by un1versal** [comment]
if you look at that commit it coincides with the first alpha release and prgman compiled the tarball to check, and I wonder if this change was so it works from the tarball related,.., and by doing that screwed this part when compiling from non tarball...
jeez thats a mouth full,

**Comment by HelLViS69** [comment]
Il 23/apr/2016 12:34, "staticfox" notifications@github.com ha scritto:

> It was intentionally disabled or something 14f39c4 not a CMake ninja

Sources date, as the name say, I contains the date where something great
has changed. In the file it's contained, there's another define which is
used when we have to force users to create a fresh new profile, for example
when a new needed feature isn't compatible with something already exists.

So, imho, it's a bad idea to remove them and rely on git.. Moreover, git
hashes aren't readable, compared to a plain date..

HelLViS69

**Comment by un1versal** [comment]
> Sources date, as the name say, I contains the date where something great has changed. In the file it's contained, 

And have to be bumped manually everytime  which is pointless hence why it was automated in https://github.com/kvirc/KVIrc/commit/1324ddf24834ab89df2dfbe9bf2198962d88d454 as that makes sense and worked perfectly fine, else these values have no reason to exist about box. (this already has been discussed to death in https://github.com/kvirc/KVIrc/issues/1566) lets not discuss that anymore,

> there's another define which is used when we have to force users to create a fresh new profile, for example when a new needed feature isn't compatible with something already exists.

#define KVI_SOURCES_DATE_NUMERIC_FORCE_SETUP has nothing to do with the other sources date and is irrelevant here. Also dont seem to have the desired effect as far as I could test.

**Comment by un1versal** [comment]
fixed by https://github.com/kvirc/KVIrc/commit/6c0ae4cb7163bf26a6121b4d860f86b455797e48
