### ISSUE TITLE
Event handler names with spaces in name are mishandled depending on how they are added.

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1959]
### Expected behavior

event handler names added via script/command or manually via GUI, with or without space in name) should be handled and display in event editor in a consistent and non buggy manner 
### Actual behavior

[know trigger] The GUI event editor strips spaces form the handlers names under some conditions
[know trigger] adding handlers via GUI event editor strips spaces form the handlers names

Handler names with spaces in name can behave and cause **eventctl** commands to behave erratically especially when such events names with spaces are _magically_ gone

Reference: https://github.com/kvirc/kvirc-scripts/issues/14
### Steps to reproduce the issue
- Add a handler manually via GUI event editor **notice** does not allow spaces in handler name once click **apply**
  ![capture](https://cloud.githubusercontent.com/assets/3521959/14913062/349da6da-0df8-11e6-9200-252a31d5c168.PNG)
- **Close event editor**
- add a event handler via command line in any input line with:
  `/event(OnURLLinkPopupRequest,added via command in input line) { popup.show urlpopup $0; }`
  **notice** the handler manually via command allows spaces in handler name
  ![capture](https://cloud.githubusercontent.com/assets/3521959/14913199/3b8ca9ea-0df9-11e6-9f21-9d78d8f682d0.PNG)
- Selecting via event editor (via GUI) **OnURLLinkPopupRequest** then selecting the handler named **`added via command in input line`** then selecting **OnURLLinkPopupRequest** again causes spaces in event name to disappear. 
  ![capture](https://cloud.githubusercontent.com/assets/3521959/14913298/f777372e-0df9-11e6-9bf0-76e6faeae219.PNG)
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 3.13.0-85-generic
System version: #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-04-29 06:51:37 UTC
Sources date: 20160428
Revision number: git-6544-gfa33e18
System name: Linux-3.13.0-85-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.5.1
Features: IRC, Debug, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

System:    Kernel 3.13.0-85-generic x86_64 (64 bit) Desktop Cinnamon 2.8.8  Distro Linux Mint 17.3 Rosa

**Comment by AndrioCelos** [comment]
The only quirk I've actually noticed is the event editor stripping spaces from handler names.

`/event` and `/eventctl` seem to work correctly with handler names containing spaces.

Still best not to use spaces though, I think.

**Comment by un1versal** [comment]
but what happens if you set a handler with spaces in name and then the space is stripped, will your /eventctl still work if you trying to enable or disable the name with spaces that no longer has one?

**Comment by AndrioCelos** [comment]
Well, the name no longer has spaces, so `/eventctl -d OnURLLinkPopupRequest "URL popup"` will throw a warning and do nothing.
It seems to work just as if you renamed it deliberately.

**Comment by un1versal** [comment]
> Well, the name no longer has spaces, so /eventctl -d OnURLLinkPopupRequest "URL popup" will throw a warning and do nothing.

yep such is described on main post, which is a side effect of the stripping issue.

> Still best not to use spaces though, I think.

I agree, but that's really up to whom will fix this or what the original design intended.

**Comment by un1versal** [comment]
This bug was probably related or caused by the fix to https://github.com/kvirc/KVIrc/issues/218

**Comment by DarthGandalf** [comment]
@un1versal do you realize that with your "workaround" every restoration of default script causes this warning about double popup? #2140

**Comment by un1versal** [comment]
> @un1versal do you realize that with your "workaround" every restoration of default script causes this warning about double popup? #2140

@DarthGandalf my `workaround` was reverted in https://github.com/kvirc/KVIrc/commit/03772457ac61619c971b5ba9abf953af4cd43e01

and your fix well, it will fix nothing either as the issue is not the name of the handler but the fact theres two handlers calling same popup.

the real cause for what you noticed is fixing this bug.

**Comment by DarthGandalf** [comment]
Well, the space in the name _is_ the reason why there are two handlers.

**Comment by un1versal** [comment]
er no it is not.

there has always been a space in this event handler name, fact!
this bug is the reason why the space is removed and when restoring events you get two handlers.

due to discovering this bug I removed that space in https://github.com/kvirc/KVIrc/commit/ac1e4d82c9daa040af03330507ff6ee7eb77b654 because I already had experienced #2149 but iI reported #1959, because it was the cause and #2149 the symptom.

due to Dessa coming across #2149 months ago I reverted the fix/workaround as agreed on IRC discussion with Dessa in https://github.com/kvirc/KVIrc/commit/03772457ac61619c971b5ba9abf953af4cd43e01

anyway pointless to argue the original cause of the issue is this bug and your fix will fix nothing since anyone upgrading and restoring events will have the original named `URL popup` + the new one named `default` = #2149

**Comment by the-j0k3r** [comment]
I see pr up, it hopefully does the trick Ive suffered from this just because one day I added a custom event handler and space was eaten, then later when restoring popups due to some update, error galore.

easy to temp fix but annoying to have to deal with it.

the problem was that no matter the handler name if contents of handler are the same it errored out.

**Comment by pragmaware** [comment]
Event handler names can't contain spaces nor weird characters. Should be OK now.
