### ISSUE TITLE
Apply clang format caused MUTABLE_PTR warning at compile

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1965]
Its just a warning but... here it is just to record the happening ;) @DarthGandalf

Get some warning that wasn't there before

**local compile**

```
KVIrc/src/modules/perlcore/libkviperlcore.cpp:72:0:
KVIrc/src/modules/perlcore/ppport.h:2166:0: warning: "MUTABLE_PTR" redefined [enabled by default]
 #define MUTABLE_PTR(p) ( \
 ^
In file included from /usr/lib/perl/5.18/CORE/perl.h:2513:0,
                 from KVIrc/src/modules/perlcore/libkviperlcore.cpp:68:
/usr/lib/perl/5.18/CORE/handy.h:60:0: note: this is the location of the previous definition
 #  define MUTABLE_PTR(p) ({ void *_p = (p); _p; })
 ^
```

First build with warning https://travis-ci.org/kvirc/KVIrc/jobs/126836495

**Comment by DarthGandalf** [comment]
Oops, I tried to exclude external/generated files, but failed.

2016-05-04 5:27 GMT+01:00 un1versal notifications@github.com:

**Comment by un1versal** [comment]
np. this one seems to be only one that moaned.
