### ISSUE TITLE
Jumpy behaviour when scrolling the irc view

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#1969]
I think it's because of the tall lines in there. I've always seen stuff like this but this is just too much. Beware, 18MB GIF

https://lh3.googleusercontent.com/-UOa3C-yCSRA/VyzqlCNPlnI/AAAAAAAA_K8/HszIoEzlMLw/s0/2016-05-06_20-59-33.gif

**Comment by un1versal** [comment]
yes, its really not smooth its probably wrong but https://github.com/kvirc/KVIrc/commit/222d59fdc7ffd931b2a0aebfddcdbbae3f1bbdda touched some mouse code.

**Comment by un1versal** [comment]
And another thing, scroll all the way to bottom and keep scrolling and it jumps up to middle and back down again, really ugly and not user friendly.

**Comment by un1versal** [comment]
https://bugreports.qt.io/browse/QTBUG-38274

something in there about a possible workaround, not sure if it applies, but this is seemingly a Qt issue.

**Comment by wodim** [comment]
Unrelated.

**Comment by un1versal** [comment]
Another one for the ages then...

**Comment by un1versal** [comment]
Is this still a problem? Cant duplicate it anymore.

**Comment by un1versal** [comment]
Since no reply and I cant duplicate it anymore, Ill close it as worksforme, reopen and relabel if its not.

**Comment by un1versal** [comment]
damm thing started doing it again after last upgrade :/ :-1:

**Comment by un1versal** [comment]
Since the person who reported this wont reply to update ANYTHING or provide further feedback
and because I cant duplicate this anymore now for a few weeks solid after many many upgrades, Im closing it as works for me.

if it comes back, feel free to reopen.
