### ISSUE TITLE
Travis: implementing docker support - adds support for KDE built against Ubuntu 16.04LTS

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1975]
## Travis WILL NOT implement 16.04LTS support into buildworlkers reference https://github.com/travis-ci/travis-ci/issues/5821

If we want Travis to build against KDE we then need Docker support.
KDE builds have been removed see  https://github.com/kvirc/KVIrc/pull/1939

Reference for implementation https://github.com/geerlingguy/ansible-role-mysql/issues/109

thoughts?

**Comment by un1versal** [comment]
> staticfox commented 2 days ago 
> 
> # Re-add KDE builds to travis #2095

---

merged duplicate on:

Wed 10 Aug 17:08:57 BST 2016

**Comment by DarthGandalf** [comment]
With Docker, it doesn't even need to be Ubuntu. Any distro would work.

**Comment by ctrlaltca** [comment]
Travis is no more; closing
