### ISSUE TITLE
Commandline friendly mode - settings vs toolbutton

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1980]
### Expected behavior

Essentially when you enable or disable the commandline friendly mode in one side its should reflect the proper state in the other and vice versa.
### Actual behavior
- running /option boolCommandlineInUserFriendlyModeByDefault 1 or 0 has no effect on the toolbutton by input bar

Checking/unchecking the preferences > interface > input bar [ ] commandline in user-friendly mode by default,  also has 0 effect on toolbutton by input bar.

Checking/unchecking the toolbutton also has no effect in preferences settings.
- bonus issue if the preferences setting is enabled and you also enable the toolbutton it actually disables the friendly mode but with no visible effect on any checkboxes. only when you try typing something.

![capture](https://cloud.githubusercontent.com/assets/3521959/15207147/11b9190a-181c-11e6-9837-092b48792274.PNG)
### Steps to reproduce the issue
1. enable/disable the general ui setting, look at toolbutton -> no change
2. enable/disable the toolbutton, look at the general ui checkbox -> no effect.
3. enable both general setting and toolbutton, see how they cancel each other out/
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 3.13.0-86-generic
System version: #130-Ubuntu SMP Mon Apr 18 18:27:15 UTC 2016
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-05-12 05:12:42 UTC
Sources date: 20160511
Revision number: git-6624-g50f5925-dirty
System name: Linux-3.13.0-86-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.5.1
Features: IRC, Debug, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

**Comment by un1versal** [comment]
I tried a few things none seem to have any effect whatsoever in the end I gave up. If you want to have a laugh look at https://github.com/un1versal/KVIrc/commit/febe7ada16534d12d05735ff0be75ff867dbdb5c

**Comment by un1versal** [comment]
Can anyone confirm?

**Comment by wodim** [comment]
I think it works fine. "by default" means "for new windows"

**Comment by un1versal** [comment]
these nuances neither mean same thing or are same as this is reporting that doesnt even matter its a non issue.

**Comment by Heufneutje** [comment]
I always assumed what @wodim just described was the intended way for it to work. What would be the point in having separate buttons for each window while also being controlled by a checkbox in the settings at the same time?

**Comment by un1versal** [comment]
Ive no idea, but there we have it... there are two settings a global and a toolbox button and **the problem is that the toolbutton breaks the global setting when used together** since there's zero sanity checking and both are unware of each other which is wrong

Im assuming global is for everything and toolbutton is per window. 

I feel inclined to remove the toolbutton even though its wrong way to solve this.

**Comment by staticfox** [comment]
sounds more like it overrides it.. which is what it's supposed to do?

**Comment by un1versal** [comment]
there is no override... it breaks it

**Comment by un1versal** [comment]
this is how it works...

global setting OFF > toolbutton works enable/disable per window,

global setting ON > toobutton ON == broken or disables feature completely.

**Comment by IceN9ne** [comment]
> global setting ON > toobutton ON == broken or disables feature completely.

I cannot reproduce this claim.  I even went through all of the code references and changing the default value in main settings for new windows does not affect existing windows.  As the option describes, it only affects the default value used when new windows are created.

I see no reason for the current workings to change and the setting should remain independent and changeable on a per-window basis.
