### ISSUE TITLE
Wrong Cursor Position

### ISSUE THREAD

**Issue by SuperMarioFan** [kvirc/KVIrc#1983]
### Expected behavior

For the cursor in the input window to stay at the end of a line when I am typing.
### Actual behavior

When I am typing long lines in KVirc 4.2.0, especially when adding a lot of spaces, the cursor slowly gets off center. It will become several spaces off of the end of the line, where it actually should be.

I don't have any screenshots that will show the issue. Sorry.
### Steps to reproduce the issue
1.  Type a sentence.
2. hit space
3. rinse and repeat until you notice the cursor is way off course
### System information

My computer upgraded itself to Windows 10 recently despite the fact that I kept telling it I didn't want to. haha. But anyway, i hadn't noticed any issues before that.

**Comment by AndrioCelos** [comment]
Try the latest KVIrc 4.9.2 build from https://kvirc.d00p.de/. A lot of issues have been fixed there.
Though in that, I've noticed similar things when editing my channel topic, which has colour codes in it. It also seems to depend on your font.

**Comment by SuperMarioFan** [comment]
Thank you. I will try that.

**Comment by un1versal** [comment]
> SuperMarioFan commented 3 days ago 
> 
> My computer upgraded itself to Windows 10 recently despite the fact that I kept telling it I didn't want to. haha. **But anyway, i hadn't noticed any issues before that.**

since theres no user feedback after 3 days and because user specifically said that prior to OS upgrade there were no noticeably issues regarding this, Im closing this ticket.

Can be reopened later pending more information
