### ISSUE TITLE
Add a KVS interface to QTextEdit's toHtml method

### ISSUE THREAD

**Issue by AndrioCelos** [kvirc/KVIrc#1985]
There doesn't seem to be any way to get the text entered in a [`multilineedit`](http://www.kvirc.net/doc/class_multilineedit.html) widget as a HTML document. You can only get it as plain text.

In terms of Qt, you can get the text as a HTML document using the [toHtml()](https://doc.qt.io/qt-4.8/qtextedit.html#html-prop) method.

Also, it may be a good idea to expand the `$loadFile` KVS function, to allow the user to specify whether the file is a HTML or plain text document, and/or add a `$saveFile` function.

**Comment by un1versal** [comment]
So it worked before that commit?

Sorry Im half brain dead, you are saying that after that commit its broken?

**Comment by wodim** [comment]
https://github.com/kvirc/KVIrc/commit/37d17999ff5bb1718da63f3d0b5dffae521f02ed#diff-74ea6ed9cd45f1b8a3e799a66f5cfc4cR262

mfw

**Comment by un1versal** [comment]
and that means?

**Comment by AndrioCelos** [comment]
...there wasn't a way before commit 37d17999ff5bb1718da63f3d0b5dffae521f02ed either.
This is a request for a new feature.

**Comment by un1versal** [comment]
and what does your cryptic comment mean about https://github.com/kvirc/KVIrc/commit/37d17999ff5bb1718da63f3d0b5dffae521f02ed#diff-74ea6ed9cd45f1b8a3e799a66f5cfc4cR262 

andrio thx for making it your ticket clearer

**Comment by AndrioCelos** [comment]
I assume you're referring to @wodim, as I never mentioned that line specifically.

**Comment by un1versal** [comment]
I am.
