### ISSUE TITLE
Release preparation for 5.x.x stable

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#2002]
## *\* RELEASE BLOCKERS

Should be fixed before release but depends on how many more years you want to wait for a release.

https://github.com/kvirc/KVIrc/milestone/6
### Intro

Since there's no documentation on release procedures anywhere and not many people seem in any rush to release 5.x any time in any foreseeable future I decided to post this here to stimulate discussion and gather information on previous procedures, after a few discussions with Pragma (who wants to release 5.x warts and all) on IRC.

Im also personally now actively seeking to push a next release out.

Nothing is set in stone.
### Suggested procedure
- [ ] Branch Master branch into 5.x branch on GitHub
- [ ] Feature freeze set for major features and new language strings (3 months minimum prior to release)
- [ ] Merge only fixes/bug fixes via cherry picking them from master
- [ ] Tag on GitHub
- [ ] Possibly force reconfiguration to user on 5.x due to most changes not being available via upgrade
- [ ] Make releases and post website news

Soon as pragma is available to discuss and fine tune these details and after feedback is provided by team members interested in releasing next 5.x we can organise these things better..

**Comment by pragmaware** [comment]
The procedure looks fine to me.
As long as there are no major crashes I'd say to push it out.

**Comment by heinrich5991** [comment]
The latest release is (a little over) 5 years old, according to [Wikipedia](https://en.wikipedia.org/w/index.php?title=KVIrc&oldid=747530917). I think you're missing out on a lot of users that install KVIrc via the packet manager.

**Comment by heinrich5991** [comment]
5.0.0 has been released 4 years ago, I guess this issue could be closed. A next release would still be cool. ;)
