### ISSUE TITLE
Multi-line input requires first command to include / "forward slash" to output formatted text

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#2011]
### Expected behavior

Typing both lines or just the first line would output 
1) `echo $b"this is bold"$o $i"this is italic"$o $u"this is underlined"$o`
2) `echo $b"this is bold"$o $i"this is italic"$o $u"this is underlined"$o`
![capture](https://cloud.githubusercontent.com/assets/3521959/15998050/d6e48d0c-3132-11e6-87ba-2960271996fe.PNG)
### Actual behavior

Typing with no fwd slash in first command.
1) `echo $b"this is bold"$o $i"this is italic"$o $u"this is underlined"$o`
2) `echo $b"this is bold"$o $i"this is italic"$o $u"this is underlined"$o`
![capture](https://cloud.githubusercontent.com/assets/3521959/15997962/dc0c0d2e-3131-11e6-928e-2e17c17b2077.PNG)
Need to add forward slash to first command
1) `/echo $b"this is bold"$o $i"this is italic"$o $u"this is underlined"$o`
2) `echo $b"this is bold"$o $i"this is italic"$o $u"this is underlined"$o`
![capture](https://cloud.githubusercontent.com/assets/3521959/15998025/951e0100-3132-11e6-986c-fba820a2b3fc.PNG)
### Steps to reproduce the issue
1. **Copy and paste and enter the following into multi-line observe results.**  
   `echo $b"this is bold"$o $i"this is italic"$o $u"this is underlined"$o`  
   `echo $b"this is bold"$o $i"this is italic"$o $u"this is underlined"$o`  
2. **Copy and paste and enter the following into multi-line observe results**.  
   `/echo $b"this is bold"$o $i"this is italic"$o $u"this is underlined"$o`  
   `echo $b"this is bold"$o $i"this is italic"$o $u"this is underlined"$o`

> #### NOTE: Command-line in friendly mode has No effect on results
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 3.13.0-88-generic
System version: #135-Ubuntu SMP Wed Jun 8 21:10:42 UTC 2016
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-06-13 05:14:25 UTC
Sources date: 20160612
Revision number: git-6725-g44f90a2
System name: Linux-3.13.0-88-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.5.1
Features: IRC, Debug, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

**Comment by wodim** [comment]
The fact that the multiline editor is a code editor (with highlighting, etc) does not mean it is a place meant to write code so evidently you have to use / to tell the client you're writing code instead of regular text.

I agree it's confusing that the editor has highlighting if it's not meant to be used to write code, but...
