### ISSUE TITLE
Setting output font as Italic will not work

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#2017]
Reported by DarthGandalf over in IRC, confirmed by myself after a few tests
### Expected behavior

That any output font is set to italic in output when selected.
### Actual behavior

Font stays with its normal glyph type
### Steps to reproduce the issue
1. Open Theme Editor 
2. Select output
3. Click the font button and select Italic
4. Click Apply
### Other things tried

Saving a Theme with all italic fonts everywhere and restarting Kvirc and even re-applying theme.
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 3.13.0-88-generic
System version: #135-Ubuntu SMP Wed Jun 8 21:10:42 UTC 2016
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-06-20 17:52:43 UTC
Sources date: 20160620
Revision number: git-6745-g0377245
System name: Linux-3.13.0-88-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.5.1
Features: IRC, Debug, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

**Comment by AndrioCelos** [comment]
What should happen, then, if the font is set to italic and italic codes are used in the message? You can't make it doubly italic...

**Comment by un1versal** [comment]
No change then, I would imagine.

**Comment by AndrioCelos** [comment]
That's what HexChat does... it's at odds with what I see in literature though.

**Comment by un1versal** [comment]
eh...

**Comment by wodim** [comment]
What I've seen in literature is that two italics cancel each other :camel: 

Camel unrelated
