### ISSUE TITLE
Scrolling Channel Treelist skips one channel per scroll tick

### ISSUE THREAD

**Issue by gizmore** [kvirc/KVIrc#2019]
### Expected behavior

Using the mouse wheel on channel tree list should move one channel/context per scroll tick.
### Actual behavior

Since a few weeks it is skipping one channel/context, marking the context read but skipping it.
### Steps to reproduce the issue
1. Have more than 2 channels
2. Use the mouse wheel to scroll through the channels
3. One channel is skipped per mouse wheel tick, moving 2 channels at once.
### System information

net-irc/kvirc-5.0_pre20160401144043::gentoo
KVIrc 4.9.2 'Aria'

Laufzeitinformationen:
System name: Linux 4.6.2-gentoo-gizmo-462e
System version: #2 SMP PREEMPT Fri Jun 24 02:15:40 CEST 2016
Architektur: x86_64
Qt version: 5.6.1
Qt theme: fusion

Erstellungsinfo:
Build date: 2016-05-28 00:56:57 UTC
Sources date: 20160102
Revision number: a559c50d8ff1ba2c265d22cb45ce0b79b26584d9
System name: Linux-4.5.2-gentoo-gizmo-452b
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   VERBOSE
   LIB_SUFFIX=64
   Threads=POSIX
Compiler name: /usr/bin/x86_64-pc-linux-gnu-g++
Compiler flags: -O2 -pipe -march=native -fomit-frame-pointer -fno-strict-aliasing 
Qt version: 5.6.0
Features: IRC, IPv6, Crypt, SSL, IfAddr, IPC, Transparency, Phonon, DCCVideo, DCCVoice, Perl, Python, Qt5, KVS

```
Thanks for kvirc!
```

**Comment by un1versal** [comment]
Its not mouse related, Im able to duplicate with `Ctrl+Tab` or `Ctrl+Shift+Tab``

**Comment by gizmore** [comment]
Fun Fact: Ctrl+Tab works correct here, one channel per tab

**Comment by un1versal** [comment]
Not if you press and hold here, eventually it goes nuts

**Comment by alisonken1** [comment]
Hmm - Having this issue on Fedora 24 as well as of 2016-08-08
KVirc 4.9.1 'Aria'
Fedora 24 x86_64 (fresh install)

Maybe the fedora 24 repo hasn't gotten the fix yet?

**Comment by un1versal** [comment]
Not if you have KVirc 4.9.1 'Aria' for sure

Compile a newer build else get your Fedora ppl to grab and package a master build.
