### ISSUE TITLE
Ugly rendering of bold text when using bitmap X core fonts

### ISSUE THREAD

**Issue by CyberShadow** [kvirc/KVIrc#2022]
### Steps to reproduce the issue
1. On Linux, open Theme Preferences, and in Output -> Look -> Font, set the font to "Fixed [Misc]", "Regular" style, with size 10.
2. Send some bold text (with Ctrl+B) to a channel.
### Expected behavior

KVirc should be using the bold variant of the font.
### Actual behavior

The font KVirc uses appears to be an algorithmically "boldened" version of the regular style, with each glyph rendered twice with a 1-pixel horizontal offset.

This causes bold text to have a much lower readability (many letters are conjoined, and glyphs such as "m" and "w" become difficult to recognize.

Example screenshot - above is correct, below is KVirc rendering:

![](https://dump.thecybershadow.net/4795cb2d93ea99a06892179968675cb1/screenshot.png)

Worth noting that the problem does not manifest in Quassel, also a Qt application, which leads me to believe that it's KVirc-specific (as opposed to being a problem in Qt or TrueType).
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.6.2-1-ARCH
System version: #1 SMP PREEMPT Wed Jun 8 08:40:59 CEST 2016
Architecture: x86_64
Qt version: 5.6.1
Qt theme: fusion

Build Info:
Build date: 2016-06-24 14:41:56 UTC
Sources date: 20160624
Revision number: git-6749-g08a66ad
System name: Linux-4.6.2-1-ARCH
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong 
Qt version: 5.6.1
Features: IRC, IPv6, Crypt, SSL, IfAddr, IPC, KDE, OSS, Audiofile, Transparency, Phonon, Webkit, DCCVoice, Perl, Python, Enchant, Qt5, KVS
```

**Comment by wodim** [comment]
https://github.com/kvirc/KVIrc/blob/master/src/kvirc/ui/KviIrcView.cpp#L1362-L1363

**Comment by wodim** [comment]
This is half-way done, as the input text editor hasn't been fixed. It needs work since the font metrics of each block must be recalculated.

**Comment by CyberShadow** [comment]
Thanks. The width changing might explain the current algorithm I guess. I noticed the same ugly font rendering when hovering over usernames/links - I imagine it would be worse if doing that changed the width of the font and caused a relayout, but perhaps this could be done only for variable-width fonts, or exposed as an option?

**Comment by wodim** [comment]
It's a pretty complicated matter I'm afraid, the irc view code is already brittle and slow enough... That part has to be revisited for sure, maybe it was not such a good idea to commit it, but we'll see what happens

**Comment by un1versal** [comment]
much better with https://github.com/kvirc/KVIrc/commit/b612e36ce2581fdf1f0df5e4bee99bcc70cc548c

**Comment by Dessa** [comment]
![clipboard08](https://cloud.githubusercontent.com/assets/110693/16361821/6c145a38-3b9c-11e6-885a-0e10d36fbdcd.jpg)

note the actually _is_ a space between the bold, and the non-bold text part
