### ISSUE TITLE
UserListView: add bold and italic nickname style

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#2026]
Currently themes, you can define bold and italic style to FontUserListView but only via editing theme directly probably depending on fonts set (some fonts dont support italic/bold must be set artificially)? not sure how that worked before but it works when doing it in theme data.

> ##### Note you can already set Boldnick in Message Style via **boolBoldedNicks**
> 
> ![capture](https://cloud.githubusercontent.com/assets/3521959/16361959/62c6693e-3b98-11e6-979b-9395dde464f0.PNG)

Aria -> fontUserListView=DejaVu%20Sans%20Mono,10,5,75,**b**
I/O -> fontUserListView=Monospace,9,5,75,**bi**
MinimalDark -> fontUserListView=DejaVu%20Sans%20Mono,9,5,50,**i**

Essentially there's no way to add this currently via UI... If you change the font to try something else, only way to get it back is reapplying theme and loose any other changes that may have been done and are desired.

Somewhere at bottom of list or at top (dealers choice)
![capture](https://cloud.githubusercontent.com/assets/3521959/16361952/1073a1b0-3b98-11e6-834d-71b2225331dd.PNG)

**Comment by wodim** [comment]
On Linux and on Windows I can pick italic and bold fonts just fine. Your system might use a font picker dialog that does not support italic/bold, but the ones I tried are fine. We can't do much about this.
