### ISSUE TITLE
RPL_NOWAWAY and RPL_UNAWAY do not update the user list.

### ISSUE THREAD

**Issue by AndrioCelos** [kvirc/KVIrc#2053]
### Expected behavior

When `RPL_NOWAWAY` or `RPL_UNAWAY` is received, the user list should update to reflect the user's true away status.
### Actual behavior

The user list (including tooltips) does not update until a `RPL_WHOREPLY` is received.
### Steps to reproduce the issue
1. Disable the 'Keep away list updated' option _or_ enable `CAP` negotiation and ensure that the network you are connected to supports [`away-notify`](http://ircv3.net/specs/extensions/away-notify-3.1.html). This stops `WHO` requests.
2. Go `AWAY`. Notice that you are not shown as away in the user list.
3. Perform a `WHO` request and notice that this updates the user list.
### System information

```
*KVIrc 4.9.2 'Aria'*

*Runtime Info:*
System name: Windows Release : 6.2.9200
System version: Windows 8 (x64) (Build 9200) [Really Windows 10]
Architecture: Intel64 Family 6 Model 58 Stepping 9
Qt version: 5.5.1
Qt theme: 

*Build Info:*
Build date: 2016-07-06 23:43:33 UTC
Sources date: 20160706
Revision number: git-6780-gce2284f
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.5.1
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

**Comment by Heufneutje** [comment]
This happens for me as well.

**Comment by staticfox** [comment]
By user, do you mean specifically the KVIrc user, or any user going away does not trigger a userlist update?

**Comment by AndrioCelos** [comment]
Only the local user.

**Comment by wodim** [comment]
check this one out fam :triumph: :joy: :100: :ok_hand:
