### ISSUE TITLE
Feature request: add support for SASL ECDSA-NIST256p-CHALLENGE

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#2056]
This would probably be a good alternative to have.. other using PLAIN or PLAIN `</sarcasm>`

Irssi supports it in cap_sasl.pl script and the atheme/atheme or atheme/ecdsatool repos support it.
Though you likely need [ecdsatool](https://github.com/kaniini/ecdsatool) as well. https://wdtz.org/freenode-sasl-upgrade-irssi-howto.html

I doubt theres many KVIrc scripters out there able to do that kind of thing so here goes nothing.

**Comment by ctrlaltca** [comment]
I encountered this issue about one year ago, when support for DH-BLOWFISH has been removed.
At that time, freenode started using an atheme version that removed support for all the existing methods except "plain" (for a good reason).
Unfortunately, the atheme developers decided to implement only one secure method, trying to force everyone into implementing and using nenolod's own wrapper library around openssl, that had a few problems:
- afaik it has never been audited by anyone
- no distro was packaging it

Background links:
http://kaniini.dereferenced.org/2014/12/26/do-not-use-DH-AES-or-DH-BLOWFISH.html
https://nullroute.eu.org/~grawity/irc-sasl-dh.html

**Comment by un1versal** [comment]
I cant speak to other points you raised, but seems like its unlikely then if its not audited to be taken up by mainstream.

Packaging wise I feel confident that Alexander_P would be able to package `<insertyourpackage>` and it shouldn't be an issue for us(KVIrc) to provide at [KVIrc's PPA](https://launchpad.net/~kvirc) to start with, at least Debian/Ubuntu side would have some prepackaged something.
That is if the only reason for blocking, would be packaging.

**Comment by IceN9ne** [comment]
Is there any network that supports this? I'm not sure if this would be useful to implement.

**Comment by DarthGandalf** [comment]
It's not a standard SASL mechanism. nenolod (aka kaniini) who was pushing for it, also stopped doing so: https://github.com/znc/znc/issues/746#issuecomment-119274435
