### ISSUE TITLE
Feature request: Default CTCP replies and CTCP echo message (replied, ignored) scripted into Events

### ISSUE THREAD

**Issue by sloanonlinux** [kvirc/KVIrc#2062]
### Intro

Easily adding silly CTCP replies from a menu like in Hexchat
### Request

KVIrc has a concrete set of CTCP replies, and I have still not figured out how to create a custom CTCP reply via the OnCTCPRequest event.

I would like to see a menu where it is possible to configure the existing CTCP replies, and add more, which also adds more CTCP request options in the right click menu.

```

```

**Comment by wodim** [comment]
I don't think this is a useful feature and it's easily scriptable ("I don't know how to do it" is not enough...)

**Comment by un1versal** [comment]
This can be achieved several ways, one of which is popups, or toolbar button or even just scripting your own conditionals into the desired events.

Ive no interest in doing any of these though, but its possible to do,

**Comment by sloanonlinux** [comment]
@wodim If it's not useful, then why is it featured in Hexchat?

**Comment by staticfox** [comment]
Because it can easily be scripted within KVS so for it to be a core component seems unnecessary. If anything, it could just be added to defscripts or made a third party script added to the scripting repository.

**Comment by staticfox** [comment]
(For the record, I'm not :-1:ing the idea, just :-1:ing it as a core component at the C++ level)

**Comment by un1versal** [comment]
> @wodim If it's not useful, then why is it featured in Hexchat?

You actually have a UI already

![capture](https://cloud.githubusercontent.com/assets/3521959/16716696/1b806b64-46fc-11e6-8cbc-a4c7b5186c71.PNG)

Its not comprehensive but should do you started, it could even be extended since it already exists, but like i did say earlier, Ive no interest on this myself at this time, and to add something you need some personal motivation to get you going.

**Comment by sloanonlinux** [comment]
Ok I've figured out how to script it, but I don't like scripting it, and I'll tell you why when I have the time.

**Comment by sloanonlinux** [comment]
So this is why I don't like scripting my custom CTCP replies. This is my script for a custom CTCP response:
`if (($4 == FOO) || ($4 == foo))
{
ctcp -n $0 FOO bar; echo Sending custom FOO reply to $0
}`

It took me a while to figure this out. I just added the brackets.
And the response to /ctcp sloanonlinux foo is:
`[20:26:21] Sending custom FOO reply to SloanOnLinux
[20:26:21] CTCP foo request from SloanOnLinux [~sloan@dat.cloak] (foo), ignored (unrecognized)
[20:26:22] CTCP FOO reply from SloanOnLinux [~sloan@dat.cloak]: bar`

I would like to see something more like this:

`[20:26:21] CTCP foo request from SloanOnLinux [~sloan@dat.cloak] (foo), replied (custom)
[20:26:22] CTCP FOO reply from SloanOnLinux [~sloan@dat.cloak]: bar`

**Comment by sloanonlinux** [comment]
Let's make CTCP completely scriptable, and have the default replies all written in KVS.

**Comment by un1versal** [comment]
You already can do that.

**Comment by sloanonlinux** [comment]
@un1versal Well come back to #KVIrc and teach me how to edit one of the default ctcp replies

**Comment by un1versal** [comment]
Theres nothing to teach, you script the replies the way you done it, thats it.

or Use the UI for the ones that can be done via UI, again theres nothing to teach.

**Comment by un1versal** [comment]
> Let's make CTCP completely scriptable, and have the default replies all written in KVS.

Well this feature wont happen UI side anytime soon, I lack interest in this, staticfox already said he wont support any UI side implementation and the reply above expresses you want this all scriptable,

I'll open a request in https://github.com/kvirc/kvirc-scripts/issues/new for this ticket on scripts repo.

As for this ticket it will be closed

**Comment by un1versal** [comment]
closed in favor of https://github.com/kvirc/kvirc-scripts/issues/21
