### ISSUE TITLE
Strange spacing on input bar with default settings, Windows 10

### ISSUE THREAD

**Issue by lexialexis** [kvirc/KVIrc#2063]
### Expected behavior

Spacing between words should appear normally.
### Actual behavior

The spacing is much too large between words.

<img width="778" alt="kvi input bug" src="https://cloud.githubusercontent.com/assets/20416661/16761825/28b64482-47df-11e6-9e28-548762dc1177.png">

This is an install of KVirc with 0 changes to the configuration except for the nickname. Changing the Input font to Consolas resolved the issue. 
### Steps to reproduce the issue
1. Install kvirc on windows 10, using a brand new configuration directory
2. Type into the input bar
### System information

```

KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Windows Release : 6.2.9200
System version: Windows 8 (x64) (Build 9200)
Architecture: Intel64 Family 6 Model 62 Stepping 4
Qt version: 5.5.1
Qt theme: windowsvista

Build Info:
Build date: 2016-07-10 21:42:42 UTC
Sources date: 20160710
Revision number: git-6806-g5113bcd
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.5.1
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS

```

**Comment by un1versal** [comment]
A little background: This was reported over IRC, but its seems no one else reported this using Windows 10,

Andrio tested this on his setup, couldn't duplicate.

Ill label this as a bug/3rd party for now, perhaps with some feedback we can maybe help user find the cause.

**Comment by wodim** [comment]
I can't reproduce this, no matter what I set my dpi setting to.

**Comment by wodim** [comment]
A little insight anyway: user has high dpi, fonts on some widgets are painted the wrong size, but their metrics are calculated properly.

**Comment by un1versal** [comment]
I wonder... Im not familiar with Windows apps that could override fonts in applications, maybe user has something installed that could cause this?

**Comment by lexialexis** [comment]
I hadn't thought of that. The screenshot was taken on a triple head setup, 2x 1080p and one 4k. but the KVI window is located on one of the 1080p screens. I don't have any software installed that I know of that would mess with fonts of other programs.

**Comment by wodim** [comment]
This screams Qt bug

**Comment by ctrlaltca** [comment]
> This screams Qt bug

Not really; the bug is only present in the ircview and the inputline, the only two widgets in KVirc where font sizes and pacing are calculated manually and not inherited by Qt.

**Comment by wodim** [comment]
> Not really; the bug is only present in the ircview and the inputline, the only two widgets in KVirc where font sizes and pacing are calculated manually and not inherited by Qt.

Size calculation works ok, the bug is that fonts aren't being painted the correct size, no? They should be as big as the title bar or the status bar.

**Comment by lexialexis** [comment]
> Size calculation works ok, the bug is that fonts aren't being painted the correct size, no? They should be as big as the title bar or the status bar.

No.. it's enormous already. But out of curiosity I checked the title bar size on the 4k screen and it's fine. I took screenshots to compare it.

1080p:

<img width="778" alt="1080p title bar comparison" src="https://cloud.githubusercontent.com/assets/20416661/16778579/dac2f5ca-482b-11e6-8ec7-218d13f060f7.png">

4k:

<img width="809" alt="4k after move" src="https://cloud.githubusercontent.com/assets/20416661/16778676/4a4f8ab6-482c-11e6-88a9-4e6815416cd5.png">

As you can see, the title bar font is normal now.. but after dragging the window a rather interesting effect happened to the contents of the channel.

**Comment by wodim** [comment]
That second one is the other way around: fonts are being painted big but their size is calculated small. Funny things.

**Comment by un1versal** [comment]
> I hadn't thought of that. The screenshot was taken on a triple head setup, 2x 1080p and one 4k. but the KVI window is located on one of the 1080p screens. I don't have any software installed that I know of that would mess with fonts of other programs.

Multi monitor, Ive still to see one app that can actually handle that properly, never mind that weird mix...

I would be doing a setup with one 1080p screen only, test, then with 2x1080p and test and then add 4k and test, then see where the issue happens.

**Comment by ctrlaltca** [comment]
We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix and report if this issue is still present. Thank you
