### ISSUE TITLE
Unwanted "black color code" in Realname

### ISSUE THREAD

**Issue by gizmore** [kvirc/KVIrc#2064]
### Expected behavior

I want to choose my Realname exclusively on my own.
### Actual behavior

KVIrc sends a "black color code" before the Realname, which messes with certain IRC clients like IRC2.0.
My coworker is using some oldschool terminal client which displays black on black when he does a whois on me.
### Steps to reproduce the issue
1. Do a /who or /whois on a kvirc client
2. There is a "black color code" as prefix in the Realname, which cannot be removed in configuration.
### System information

KVIrc 4.9.2 'Aria'

Laufzeitinformationen:
System name: Linux 4.6.3-gentoo-gizmo-463
System version: #1 SMP PREEMPT Sun Jun 26 03:05:36 CEST 2016
Architektur: x86_64
Qt version: 5.6.1
Qt theme: fusion

Erstellungsinfo:
Build date: 2016-05-28 00:56:57 UTC
Sources date: 20160102
Revision number: a559c50d8ff1ba2c265d22cb45ce0b79b26584d9
System name: Linux-4.5.2-gentoo-gizmo-452b
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   VERBOSE
   LIB_SUFFIX=64
   Threads=POSIX
Compiler name: /usr/bin/x86_64-pc-linux-gnu-g++
Compiler flags: -O2 -pipe -march=native -fomit-frame-pointer -fno-strict-aliasing 
Qt version: 5.6.0
Features: IRC, IPv6, Crypt, SSL, IfAddr, IPC, Transparency, Phonon, DCCVideo, DCCVoice, Perl, Python, Qt5, KVS

**Comment by wodim** [comment]
See if disabling these three options helps.

![2016-07-14_19-28-43](https://cloud.githubusercontent.com/assets/1001553/16849096/372a33e0-49f9-11e6-9232-d3d4525515a8.png)

**Comment by staticfox** [comment]
@gizmore have you tried the above?

**Comment by un1versal** [comment]
17 days is enough... I doubt this is a bug anywho but rather whats been said already.

Closing as works for me, if @gizmore should grace us with presence again please compalin and we shall reopen issue if it turns out its not.

**Comment by un1versal** [comment]
aye I forgot to actually close so 21 days is enough for user feedback
