### ISSUE TITLE
input line focus changes adds random spaces into input line

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#2065]
### Expected behavior

That no matter if you **click** away from input line when returning to input line to complete the remainder of nick, or message you are typing, that this is done so without weird features like random size spaces being added..
### Actual behavior

If you type 3 letters of a nickname and select the user on userlist, when returning to input line to tab complete the remainder of nick when pressing tab, some spaces are added between half completed nick and the new nick is then completed.

if you type something on input line click on desktop or any other area that makes input line loose focus when returning to complete what you were typing a random ammount of  spaces may be added in between what you are typing.
### Steps to reproduce the issue
1. You must type some alias (doesnt matter if its fake) e.g `/something`
2. type first 3 characters of a nick then goto userlist select another nick and then the target nick you maybe want to complete (its important the cursor is no longer flashing on input line)
3. return to input line click near the 3 letters of nick and press tab

![sling](https://cloud.githubusercontent.com/assets/3521959/16859296/bc707ea2-4a25-11e6-9961-2f921aa60475.gif)
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.4.0-31-generic
System version: #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-07-14 07:44:59 UTC
Sources date: 20160710
Revision number: git-6806-g5113bcd-dirty
System name: Linux-4.4.0-30-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.5.1
Features: IRC, Debug, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

**Comment by wodim** [comment]
I can't repro this. When I click on a nickname it's not written in the input field. Maybe my default script is screwed?

**Comment by Stanzilla** [comment]
I can repro, when you click the name nothing happens but you have to click into the input field again and then hit tab

**Comment by wodim** [comment]
oh yes

**Comment by un1versal** [comment]
there's a better one of these.

1) Type a letter (a),
2) select a different nick on nicklist
3) repeat 1 and 2 a few times up and down nick list

![demo-a](https://cloud.githubusercontent.com/assets/3521959/17571668/14a90a66-5f49-11e6-9887-158cc9c391bc.gif)

it varies of course but mostly you get a magical space added because fairies like adding spaces

**Comment by un1versal** [comment]
should the main issue be separated from the issue described above?

cant believe more people not moaning about this, it happens to me for other reasons not yet reported spaces being added for whatever reason.

**Comment by un1versal** [comment]
OK Ive updated description, this cleary affects any manner of clicking away from input line while youre typing anything.

OK the nick one is werider but they all seem related.

1) type something on input line
2) click on desktop or go to your browser and look up something.
3) come back to paste or type something in kvirc.

![demo-ab](https://cloud.githubusercontent.com/assets/3521959/17803149/788742ec-65ec-11e6-9092-2e8981cb8d3e.gif)

**Comment by IceN9ne** [comment]
Well, I've narrowed it down to a discrepancy between `m_iCursorPosition` and `m_szTextBuffer.length()`.  Somewhere `m_iCursorPosition` is getting set to beyond the length of the buffer.

In the nick completion situation, `m_iCursorPosition` is set off the end of `m_szTextBuffer`, so when it goes to replace, it's removing characters not in the buffer, thus leaving behind the characters that should have been replaced.

In the "extra whitespace" issue that @un1versal last mentioned, the `m_iCursorPosition` is again set beyond the length of `m_szTextBuffer`, so when it does an `insert` for the typed letter, it fills in the missing positions in the buffer with spaces.  I've only gotten this to happen when clicking into the text field beyond the current cursor position from a state where KVIrc wasn't in focus (terminal window had focus for example).

`QString("").insert('a',5) == "     a"`

I'm going to guess that there needs to be a `std::max` added somewhere, just have to find it.

**Comment by IceN9ne** [comment]
I was able to consistently reproduce it after I stopped using the touchpad on my laptop.  Once I was using a real click, I noticed that long clicks would work properly, but really fast clicks to the right of the cursor would cause the position to be stored incorrectly.  It seems that with a long click, some other part of the code would "fix" the issue by clamping the cursor position to the end of the buffer, but this wasn't triggered after a really fast click.

The problem ultimately comes from incorrect values being returned from `KviInputEditor::charIndexFromXPosition()` (it can return up to 2x the current size of the text buffer), but that code is so much of a hack I didn't want to touch it in fear of breaking it, so the second best option was to just clamp it in the mouse event.

**Comment by un1versal** [comment]
I can confirm that https://github.com/kvirc/KVIrc/pull/2129/commits/cceae369e707573ecf5450d394ef1f8b594b2935 fixes this.

There is a small however, when completing nicks you can only complete **one** nick per line, if you complete one nick and straight after that try completing another it wont work.

**Comment by IceN9ne** [comment]
I can't reproduce that issue, but I'm running with all of #2129 patched, which includes many fixes for nick completion.

**Comment by un1versal** [comment]
So am I, full patch.

**Comment by un1versal** [comment]
![gif](https://cloud.githubusercontent.com/assets/3521959/18273930/c7385fb2-7437-11e6-8017-005646c98efc.gif)

you cant tell but Im pressing tab for completion there

**Comment by IceN9ne** [comment]
Well, I can't help you as with both #2129 and master + cceae36 doesn't have this issue for me.  I'm thinking you have something unrelated going on.

**Comment by un1versal** [comment]
~~Seems my nick postfix  completion string may have had a non breaking space after colon.~~

Or not, resaved my nick completion postfix and it works now... all is well
