### ISSUE TITLE
Feature request: add way to find out if event handlers are enabled or disabled

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#2067]
Ive looked around and even asked, but cant find it, hence request.

It would be useful to know if an event handler is on or off in order to be able to control enabling or disabling accordingly via script or popups.

An example of what I had in mind was to add a dedicated popup to enable or disable suppressing of part/quit etc.

See https://github.com/kvirc/KVIrc/wiki/FAQ#how-do-i-suppress-join-part-and-quit-messages

The idea is to add those events to KVIrc by default **(disabled)** and control the enabling or disabling them via a popup. I would ideally like to keep this whole proposition confined to scripting as much as possible.

**Comment by slaboff** [comment]
Hi un1versal,
Unless I'm mistaken we already have that feature built-in. In the form of:   $isEventEnabled
Which can be used to check if event handlers are enabled or disabled.

**Comment by un1versal** [comment]
Excellent, didnt actually know, let me see if I can make that work for intended. thx slaboff.

**Comment by un1versal** [comment]
if($isEventEnabled(eventname,handlername))

and 

if(!$isEventEnabled(eventname,handlername))

and using as a conditional work just as I wanted, thx again for that.

closing as works for me
