### ISSUE TITLE
KVIrc freezes after long use

### ISSUE THREAD

**Issue by blur1** [kvirc/KVIrc#2074]
### Expected behavior

Should not freeze after leaving open for a long time.
### Actual behavior

After leaving KVIrc open for more then 8 hours on inactivity, KVIrc freezes.
### Steps to reproduce the issue
1. Leave KVIrc open for more then 8 hours with inactivity. 
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.6.0-1-amd64
System version: #1 SMP Debian 4.6.4-1 (2016-07-18)
Architecture: x86_64
Qt version: 5.6.1
Qt theme: fusion

Build Info:
Build date: 2016-07-21 18:45:37 UTC
Sources date: 20160102
Revision number: git-6812-gc3471bb
System name: Linux-4.5.0-pf4
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 
Qt version: 5.6.1
Features: IRC, IPv6, Crypt, SSL, IfAddr, IPC, Transparency, Phonon, Webkit, DCCVoice, Perl, Python, Enchant, Qt5, KVS
```

**Comment by un1versal** [comment]
Hi there, welcome.

I think this maybe a Debian issue only, not sure, but Ubuntu and friends I cant duplicate that personally.

Do you get your binaries from @AlexanderP  repos?

Is there anyone out there running Debian builds from our download pages? https://github.com/kvirc/KVIrc/wiki/Downloading-KVIrc's-nightly-source-or-binaries#pre-compiled-nightly-32-bit-or-64-bit-binaries-for

**Comment by AlexanderP** [comment]
Hi.
Yes it is my build.

25 июля 2016 г. 11:06 PM пользователь "un1versal" notifications@github.com
написал:

**Comment by un1versal** [comment]
Hi, @AlexanderP how are you? Thx for dropping by, must be great weather for riding eh?

you wouldnt happen to run kvirc on Debian for this 8+ hours?

I would normally ask the user to put binary through a debugger, but I dont think these builds have debug symbols in... do they?

@blur1 would you be able to compile a debug build and try this?

**Comment by blur1** [comment]
Hi @un1versal, yes I can compile a debug build and try it out.

**Comment by blur1** [comment]
Odd, I compiled the latest build with debug so far it has not freeze. my build config:

KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.6.0-1-amd64
System version: #1 SMP Debian 4.6.4-1 (2016-07-18)
Architecture: x86_64
Qt version: 5.6.1
Qt theme: fusion

Build Info:
Build date: 2016-07-26 03:58:07 UTC
Sources date: 20160102
Revision number: 
System name: Linux-4.6.0-1-amd64
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr/local
   LIB_SUFFIX=
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.6.1
Features: IRC, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS

**Comment by un1versal** [comment]
Why is it that your build info doesn't even say its has debug on?

my features part...

Features: IRC, **Debug**, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS

Ive long suspected precompiled binaries from Ubuntu repos at least, suffer from more instability. for this reason I started compiling long before I was involved in project.

In your case only time will tell.

My uneducated guess is that **maybe** one of, or multiple `Compiler flags: -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2` flags may contribute to this, but idk for sure.
This is only a personal guess based on experience and reorts from other users that after compiling some of the issues went away.

@blur1 only time will tell, please keep an eye on it and do update ticket with more info when you have it.

@AlexanderP what do you think maybe happening? Is there any reason why pre-compiled binaries do actually seem more unstable?

**Comment by AlexanderP** [comment]
Hi.
The weather is beautiful;)

My PC does not work more than 8 hours :(

Honestly, I do not know why this might be, in the assembly of different modules and compiler flags. It should be checked.

The package repository has kvirc-dbg: https://wiki.debian.org/HowToGetABacktrace

**Comment by un1versal** [comment]
@AlexanderP thanks for reply, if you look into https://scan.coverity.com/projects/kvirc-coverity/view_defects you will see that there are many possible defects that may not like the restriction that some compiler flags may require, (but this is a guess) if this assumption is true, then could explain a few things where precompiled binaries are concerned.

Alex, would you please also add dbg packages for KVIrc ppa? thx in advance.

**Comment by CyberShadow** [comment]
> The package repository has kvirc-dbg: https://wiki.debian.org/HowToGetABacktrace

If your distro provides debug packages, perhaps you could try to reproduce the freeze with your distro's binary + debug packages and try getting a stack trace out of that.

**Comment by un1versal** [comment]
@CyberShadow no, Distro doesnt, we do (AlexanderP is our packager) hes said it above if you noticed thers dbg packages in debian ppa now.

**Comment by AlexanderP** [comment]
Hi.
Today I will try to do extra. repository.
Where will kvirc compiled with CMAKE_BUILD_TYPE = Debug

**Comment by blur1** [comment]
Last night my version of KVIrc froze too. After I recompiled KVIrc I got the debug feature. I will try what @CyberShadow said and get a backtrace.

**Comment by AlexanderP** [comment]
Hi.
extra. repository:

```
deb http://notesalexp.org/kvirc-debug/jessie/ jessie main
deb http://notesalexp.org/kvirc-debug/stretch/ stretch main
deb http://notesalexp.org/kvirc-debug/sid/ sid main
```

**System information**

```
KVIrc 4.9.2 'Aria'

Информация времени выполнения:
System name: Linux 4.6.0-pf1+
System version: #1 SMP Mon Jul 25 22:04:53 MSK 2016
Архитектура: x86_64
Qt version: 5.3.2
Qt theme: fusion

Информация о сборке:
Build date: 2016-07-27 17:53:33 UTC
Sources date: 20160102
Revision number: git-6818-gd7d7992
System name: Linux-4.6.0-pf1+
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 
Qt version: 5.3.2
Features: IRC, Debug, IPv6, Crypt, SSL, IfAddr, IPC, Transparency, Phonon, Webkit, DCCVoice, Perl, Python, Enchant, Qt5, KVS
```

**Comment by blur1** [comment]
Here is the backtrace that I got after KVIrc froze. 

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from kvirc...done.
(gdb) set pagination 0
(gdb) run
Starting program: /usr/local/bin/kvirc 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe3447700 (LWP 22256)]
[New Thread 0x7fffd9944700 (LWP 22257)]
libpng warning: iCCP: known incorrect sRGB profile
[New Thread 0x7fffd2de1700 (LWP 22259)]
[Thread 0x7fffd2de1700 (LWP 22259) exited]
[New Thread 0x7fffd2de1700 (LWP 22261)]
[Thread 0x7fffd2de1700 (LWP 22261) exited]
^C
Thread 1 "kvirc" received signal SIGINT, Interrupt.
pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185 ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S: No such file or directory.
(gdb) thread apply all bt full 10

Thread 3 (Thread 0x7fffd9944700 (LWP 22257)):
#0  0x00007ffff197519d in poll () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x00007ffff0b9e39c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007ffff0b9e4ac in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007ffff27aa1cb in QEventDispatcherGlib::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#4  0x00007ffff2752e4a in QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#5  0x00007ffff257b9e4 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#6  0x00007ffff7e6b515 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
No symbol table info available.
#7  0x00007ffff2580808 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
BFD: reopening /usr/lib/debug/.build-id/51/798d00dbee2f9e1eb56ca8a50f9f1187df19b1.debug: No such file or directory

BFD: reopening /usr/lib/debug/.build-id/51/798d00dbee2f9e1eb56ca8a50f9f1187df19b1.debug: No such file or directory

BFD: reopening /usr/lib/debug/.build-id/51/798d00dbee2f9e1eb56ca8a50f9f1187df19b1.debug: No such file or directory

Can't read data for section '.debug_loc' in file '/usr/lib/debug/.build-id/51/798d00dbee2f9e1eb56ca8a50f9f1187df19b1.debug'
(gdb) thread apply all bt full 

Thread 3 (Thread 0x7fffd9944700 (LWP 22257)):
#0  0x00007ffff197519d in poll () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x00007ffff0b9e39c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007ffff0b9e4ac in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007ffff27aa1cb in QEventDispatcherGlib::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#4  0x00007ffff2752e4a in QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#5  0x00007ffff257b9e4 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#6  0x00007ffff7e6b515 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
No symbol table info available.
#7  0x00007ffff2580808 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
Segmentation fault

It says no symbol table, so should I install the debugging symbols for Qt?

**Comment by un1versal** [comment]
Lets see what others say, that output doesnt say much tbh.

You sure you have a KVIrc Debug build?

**Comment by wodim** [comment]
That backtrace says nothing, as far as I understand it. There's no kvirc code running in those threads.

**Comment by wodim** [comment]
Closing because of lack of feedback. If this keeps happening, please feel free to reopen it.
