### ISSUE TITLE
Right clicking on unknown nicks does not produce the right popup

### ISSUE THREAD

**Issue by staticfox** [kvirc/KVIrc#2075]
### Expected behavior

Right clicking on a nick name who parts all common channels would produce a context menu with menus such as `WHOWAS`.
### Actual behavior

The only menu option is `Clear Buffer`.
### Steps to reproduce the issue
1. Find a nick that has joined a channel you are in, then parted.
2. Right click their nick name
3. `WHOWAS` dialogues are not an option.
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Windows Release : 6.2.9200
System version: Windows 8 Professional (x64) (Build 9200)
Architecture: Intel64 Family 6 Model 60 Stepping 3
Qt version: 5.5.1
Qt theme: windowsvista

Build Info:
Build date: 2016-07-14 10:29:35 UTC
Sources date: 20160714
Revision number: git-6807-g2fa46d9
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.5.1
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

(note: this also exists in `HEAD`)

---

I know this was a thing at some point, unless I'm crazy?

**Comment by un1versal** [comment]
this has been fixed update your default popups

reference https://github.com/kvirc/KVIrc/commit/9845c3d4853f34a646656a0355ac32603ffbf75b

**Comment by staticfox** [comment]
Hrm, wasn't there a dedicated `WHOWAS` system though for unknown clients?

**Comment by un1versal** [comment]
there is and that has never changed

![capture](https://cloud.githubusercontent.com/assets/3521959/17267956/c3c8688a-5610-11e6-8831-6ef2e262ac98.PNG)

**Comment by staticfox** [comment]
Ah alright. For some reason I thought there was a system directly for `WHOWAS` and not just part of the normal deal. Closing.

**Comment by un1versal** [comment]
as a back story, the reason why this was hidden, is due to the fact when users leave IRC (not just channel) you are able to execute commands that you shouldnt anymore (theres no point in sending avatar or dcc or query or whois req etc), but alas the mechanism for hiding this conditionally doesnt work as expected.

some commands maybe valid still like whowas but imo we shouldnt see options that return nothing or invalid data
