### ISSUE TITLE
Tabwidget /Textbrowser dialog wont load HTML docs - Windows only issue

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#2076]
### Expected behavior

That the specified  HTML docs is displayed inside tab
### Actual behavior

Nothing is displayed

> ### Note in Linux this works fully without issues.
### Steps to reproduce the issue
1. open scriptester and past https://gist.github.com/un1versal/2f1c1c2f2220c6b2401259f61041f2a4
2. execute script

Text files also same result

refrence source https://github.com/kvirc/KVIrc/blob/master/src/modules/objects/KvsObject_textBrowser.cpp#L93-L109
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Windows Release : 6.1.7601
System version: Windows 7 Ultimate (x64) Service Pack 1 (Build 7601)
Architecture: Intel64 Family 6 Model 26 Stepping 5
Qt version: 5.5.1
Qt theme: windowsvista

Build Info:
Build date: 2016-07-30 02:39:55 UTC
Sources date: 20160728
Revision number: git-6819-g3ebbee9
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.5.1
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

here is a Windows Vs Linux e.g.

![demo-a](https://cloud.githubusercontent.com/assets/3521959/17268098/7f276ce8-5616-11e6-8c9d-f42bccaf9e35.gif)

**Comment by un1versal** [comment]
marking as bug, asked in IRC for confirmation and same result came up

@AndrioCelos pointed to https://github.com/kvirc/KVIrc/blob/master/src/modules/objects/KvsObject_textBrowser.cpp#L105-L107

this however works in Linux so am wondering if this is some weird Qt thing.

**Comment by slaboff** [comment]
un1versal, 
I have a suggestion that comes by way of TheReign.
Replace: ((QTextBrowser *)widget())->setSource(url);
With: ((QTextBrowser *)widget())->setSource(QUrl::fromLocalFile(szFile));
Maybe that will fix the issue.
Thanks,
slaboff

**Comment by un1versal** [comment]
@slaboff regarding the forward slashes / backslashes you shouldnt need to do anything as KVS should automatically handle that.

Ill try your workaround, however imo the issue you reported is still valid, should work as is no?

**Comment by slaboff** [comment]
un1versal,
Update on issue. The fix I gave you earlier seems to have cured the problem. We compiled a windows version using the changes mentioned at line 107. Now Windows displays the HTML files.

**Comment by un1versal** [comment]
Good to hear,~~I still think that feels like a workaround, will need some feedback from other to confirm this.~~

Thanks for the update.

**Comment by AndrioCelos** [comment]
I much prefer it to the existing code.

**Comment by un1versal** [comment]
> I much prefer it to the existing code.

? Its not KVS though

**Comment by AndrioCelos** [comment]
...I'm aware.

**Comment by un1versal** [comment]
durh.... lol this needs to be patched in... haha

**Comment by un1versal** [comment]
OK clearly my brain was disengaged from body, see https://github.com/kvirc/KVIrc/pull/2090 should also pump out Windows builds for testing.

**Comment by AndrioCelos** [comment]
There's a redundant local variable in there now, though.

**Comment by un1versal** [comment]
Its too early in the moring for guessing, care to tell me which, line etc..
