### ISSUE TITLE
KVIrc licencing

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#2078]
KVIrc same source code should not be incensed under GPLv2+ and GPLv3 simultaneously

its beyond silly and its not why GPLv2+ exists
https://www.gnu.org/licenses/gpl-faq.html.en#v2v3Compatibility

there was a discussion at http://lists.omnikron.net/pipermail/kvirc/2009-September/subject.html following to which GPLv3 was added to the repo... I can see no good reason on that discussion to changing license...

There was also no agreement there in that mailing list discussion and pending conversation with pragma **my motion is to remove GPLv3 from the repo** and keep KVIrc soley as GPLv2+

Edit: Wed 10 Aug 17:18:11 UTC 2016 (pragma hasnt shown his face in: **7w 4d 19h** and none else in 11 days had anything else to say (so here goes nothing) since I doubt due diligence was ever done on half baked upgrade. 

Its is 100% stupid to carry two licenses for same software.

And BTW upgrading to GPLv3 requires consent from all the people who [contributed to the software to agree to this, so please lets see those agreements](http://lists.omnikron.net/pipermail/kvirc/2009-September/003342.html). This was mentioned on the mailing list but nothing ever was said about this status.

**Comment by staticfox** [comment]
:+1:

**Comment by ctrlaltca** [comment]
@un1versal  Check https://github.com/kvirc/KVIrc/blob/master/doc/COPYING

**Comment by un1versal** [comment]
@ctrlaltca thx

ill remove the reference from there but aside from thatI dont see anything that makes the transition complete or agreed up by all.

**Comment by un1versal** [comment]
Ive clarified and updated  the https://github.com/kvirc/KVIrc/blob/master/doc/COPYING.

For future reference of a full and complete upgrade to GPLv3 these are some valid/legal points
- Have in place a Contributor Licence Agreement
- Obtain and provide proof from previous contributors to KVIrc of this CLA to be applied retroactively.
- Make clear the reason for making upgrading to GPLv3 and why it applies to KVIrc
- then finally when upgrade is complete change all source Headers to reflect GPLv3 and re-add GPLv3 text and remove GPLv2 lic from source.

there are various CLA standard agreements out there we should consider using one ASAP.

further reading http://oss-watch.ac.uk/resources/cla
