### ISSUE TITLE
KVIrc lists channel mode "q" as "quiet" and "a" as "anonymous messages" for unknown IRCds

### ISSUE THREAD

**Issue by Heufneutje** [kvirc/KVIrc#2082]
### Expected behavior

The channel modes should be listed as "unknown".
### Actual behavior

KVIrc lists cmode "q" as being "quiet" and "a" as "anonymous messages" which due to the fact that KVIrc doesn't know the IRCd, is incorrect. Various other assumptions with regards to basic mode information are being made [here](https://github.com/kvirc/KVIrc/blob/master/src/kvirc/kernel/KviIrcConnectionServerInfo.cpp#L1560) that are not listed in RFC1459 and therefore not standardized.
### Steps to reproduce the issue
1. Connect to a network that runs an IRCd that is not known to KVIrc. If you want a test case, I happen to run one over at heufneutje.net, port 6670.
2. Look at the mode listing in your console window and notice "a" and "q" having a description when they really should not have.
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.4.0-21-generic
System version: #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-08-02 07:04:50 UTC
Sources date: 20160102
Revision number: git-6833-g3f64dc0
System name: Linux-3.13.0-92-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/x86_64-linux-gnu-g++
Compiler flags: -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 
Qt version: 5.5.1
Features: IRC, IPv6, Crypt, SSL, IfAddr, IPC, Transparency, Phonon, Webkit, DCCVoice, Perl, Python, Enchant, Qt5, KVS
```

**Comment by un1versal** [comment]
Whats the IRCd exactly and version? isnt it easier to ask for it to be added than this song and dance?

FYI I dont consider unknown IRCd a bug, at best is a feature request, and for that you need to actually provide details about that IRCd.

**Comment by Heufneutje** [comment]
The IRCd is [txircd](https://github.com/ElementalAlchemist/txircd). It's a small project that I contribute to. Also, adding it doesn't fix the issue I'm trying to point out. Information for unknown IRCds will still be incorrect.

**Comment by Heufneutje** [comment]
Also, yes it clearly is a bug. Because the information it shows is incorrect. What's the point in setting some to "Unknown" and assuming other non-standardized ones.

**Comment by Heufneutje** [comment]
My point is not that I want an IRCd to be added, my point is that if there's no standardization for a mode, its description should not be assumed. Otherwise you're only dancing around the issue.

**Comment by wodim** [comment]
Standardisation of IRC stuff, the bane of our existence.

I am not really sure of what would be correct. We rely on many custom channel and user modes.

**Comment by Heufneutje** [comment]
It's also rather inconsistent this way, because while these descriptions are assumed, the control option when right clicking a user shows options to admin/deadmin and owner/deowner. So it's assuming 2 entirely different things at the same time.

**Comment by staticfox** [comment]
+q is pretty consistent for quiet bans, I'm not sure there is anything else using +q as a ban mask?

**Comment by Heufneutje** [comment]
Not if it's a status mode though, which it is in this case.

**Comment by staticfox** [comment]
status mode.. meaning ban flag?

**Comment by Heufneutje** [comment]
Meaning a channel status. `This server supports: PREFIX=(qaohv)~&@%+  :are supported by this server`. KVIrc seems to recognize this token as it's showing options for them in the control menu, yet also at the same time assumes they're something else.

**Comment by staticfox** [comment]
if +q is a prefix, it won't show up in the ban list editor

**Comment by Heufneutje** [comment]
It's not showing up in that editor. That is correct. The description shows up in the available channel modes that are listed in your console window when you connect.

```
[15:57] Available channel modes:
[15:57] b: Ban masks
[15:57] W: 
[15:57] k: Key
[15:57] l: Limited number of users
[15:57] f: 
[15:57] C: 
[15:57] G: 
[15:57] i: Invite only
[15:57] c: 
[15:57] K: 
[15:57] m: Moderated
[15:57] S: 
[15:57] n: No external messages
[15:57] p: Private
[15:57] s: Secret
[15:57] t: Topic change restricted
[15:57] a: Anonymous messages
[15:57] h: 
[15:57] q: Quiet
[15:57] o: Channel operators
[15:57] v: Voiced users
```

**Comment by staticfox** [comment]
oh, you're talking about the description after the client parses the login stuff

**Comment by un1versal** [comment]
> The IRCd is txircd. It's a small project that I contribute to. Also, adding it doesn't fix the issue I'm trying to point out. Information for unknown IRCds will still be incorrect.

The only way to solve that is add support for all unknown IRCds to KVIrc, the way it behaves now with unknown IRCDds is pretty much by design, just look at the source code https://github.com/kvirc/KVIrc/blob/master/src/kvirc/kernel/KviIrcConnectionServerInfo.cpp

Contributions welcome I guess...

Ill leave this to people who understand this stuff better than I. good luck.

**Comment by Heufneutje** [comment]
Awesome. Thanks!

**Comment by staticfox** [comment]
np
