### ISSUE TITLE
Ubuntu 16.04 + SSL DCC Error (Unsupported Protocol) + [SSL ERROR]: shutdown while in init

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#2089]
Ive been investigating a report from another user on IRC for a while now and I feel Im not getting anywhere. So here is a report.
## where will this bug not happen?
-  **Current master + Ubuntu 14.04 LTS neither of the problems described will be present, SDCC works smoothly and as expected.**
- Windows Nightly Builds from d00p also works as expected.

Im really trying to get to bottom of this so am looking for tips on how to debug this and find cause at least.
## where will this issue happen
-  With Current master + Ubuntu 16.04LTS and OpenSSL 1.0.2g both these issues are present
-  With Current master + Ubuntu 16.04LTS and OpenSSL 1.0.1t  both these issues are present
### Expected behavior

Grabbing a SDCC (DCC over  SSL) transfer from another user/bot should work OK smoothly like in 14.04LTS
### Actual behavior

Ubuntu 16.04 outputs on transfer window

```
[14:30:45] [TRANSFER 11]: Low-level transport connection established
[14:30:45] [TRANSFER 11]: Starting Secure Socket Layer handshake
[14:30:45] [TRANSFER 11]: [SSL ERROR]: unsupported protocol
```

then shortly after this the IRC context /server connection this happens

```
[14:31:26] [SSL ERROR]: shutdown while in init
[14:31:26] [SOCKET ERROR]: Secure Socket Layer error
[14:31:26] Connection terminated [irc.server.net (:7070)]
[14:31:26] The connection terminated unexpectedly. Trying to reconnect...
```

The above is error (**shutdown while in init**) comes from openssl

https://github.com/openssl/openssl/blob/master/ssl/ssl_err.c#L511
https://github.com/openssl/openssl/blob/master/ssl/ssl_lib.c#L1639
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.4.0-31-generic
System version: #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-08-04 11:00:38 UTC
Sources date: 20160804
Revision number: git-6853-g96a891d
System name: Linux-4.4.0-31-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.5.1
Features: IRC, Debug, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

**Comment by un1versal** [comment]
I can confirm that this is an issue in Linux only (not sure about OS X), Our AV Windows + latest OpenSSL 1.0.2h which should be equivalent to the Ubuntu version works just fine

Also, in Ubuntu 16.04 I compiled openssl 1.0.1 stable tree with defaults (Im assuming its equivalent to openssl version in Ubuntu 14.04) and compiled KVirc against that openssl version, both these issues are still present in there. (So Ill assume this isnt openssl related and stop barking up that tree)

So its a Linux issue (maybe even just Ubuntu? No idea) or some stupid Qt issue,  I tried running KVIrc through debugger while this is going on, but output is pretty useless.

any ideas where to look or what to try?

**Comment by IceN9ne** [comment]
My **guess** is that the client you're trying to connect to is trying to use/force SSLv3, but Ubuntu 16.04 just rejects all SSLv3 as unsupported protocol since it is disabled in the OpenSSL source.

When using `openssl s_client` to check what's going on while on my Ubuntu 16.04 box I get this:

`SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol:s23_clnt.c:735`

And when I'm on an older Ubuntu 14.04 box I get this:

```
CONNECTED(00000003)
---
Certificate chain
 0 s:<removed>
   i:<removed>
---
Server certificate
-----BEGIN CERTIFICATE-----
<removed>
-----END CERTIFICATE-----
subject=<removed>
issuer=<removed>
---
No client certificate CA names sent
---
SSL handshake has read <removed> bytes and written <removed> bytes
---
New, TLSv1/SSLv3, Cipher is AES256-SHA
Server public key is 1024 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : SSLv3
    Cipher    : AES256-SHA
    Session-ID: <removed>
    Session-ID-ctx:
    Master-Key: <removed>
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1473302050
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)
---
```

I'm not sure there's anything that KVIrc can do.  I'm not an SSL expert, but does anyone know if we can force TLS (v1.2?) to be used from our side?

**Comment by wodim** [comment]
SSL (all versions) is indeed deprecated and Ubuntu rightfully chose not to compile OpenSSL with support for it. We use OpenSSL to connect to secure servers so if a server tells us it wants us to use SSLv3, we cannot connect as we don't know that protocol.

That said, I can't find a server that only supports SSLv3...

**Comment by un1versal** [comment]
its not sslv3 related

**Comment by IceN9ne** [comment]
@wodim I doubt you'll find an IRCd server that only supports SSLv3.  This problem will likely only exist in the SDCC realm when dealing with ancient servers.  IMO, this isn't really something that can be fixed, nor should we really care as SSLv3 should go away anyways (similar to ECB).

**Comment by IceN9ne** [comment]
@un1versal While I do think the SSLv3 issue of this issue isn't of concern, what leaves me concerned is why would the IRCd server connection die with an SDCC error.  That should probably be the focus of this issue.

**Comment by wodim** [comment]
This smells bad, do we default to SSLv2? https://github.com/kvirc/KVIrc/blob/master/src/kvilib/net/KviSSL.cpp#L351-L372

**Comment by IceN9ne** [comment]
> [20:52:27] [TRANSFER 7]: Attempting an active DCC SRECV connection
> [20:52:27] [TRANSFER 7]: Contacting host x.x.x.x on port xxx
> [20:52:27] [TRANSFER 7]: Low-level transport connection established
> [20:52:27] [TRANSFER 7]: Starting Secure Socket Layer handshake
> [20:52:27] [TRANSFER 7]: Transfer failed: Remote end has closed the connection
> [20:54:14] [SSL ERROR]: shutdown while in init
> [20:54:14] [SOCKET ERROR]: Secure Socket Layer error
> [20:54:14] Connection terminated [irc.xxx.net (x.x.x.x:xxx)]
> [20:54:14] The connection terminated unexpectedly. Trying to reconnect...
> 
> KVIrc Aria 4.9.2, revision: git-6958-g901914e-dirty, build type: release, sources date: 20160825, built on: 2016-08-27 11:38:48 UTC

Had that happen to someone in a channel I hang out in.  They're on Windows.  A few seconds longer duration between the DCC SSL close socket and the server SSL error and also isn't the unsupported protocol error either.  But, it's suspiciously similar.

**Comment by un1versal** [comment]
> I'm not sure there's anything that KVIrc can do. I'm not an SSL expert, but does anyone know if we can force TLS (v1.2?) to be used from our side?

Cant KVIrc switch to TLS like its _supposedly_ does when _`Switch to SSL/TLS by using the STARTTLS extension`_ is enabled?
If that works for server connections then what you ask would be possible if implemented for DCC no?

![capture](https://cloud.githubusercontent.com/assets/3521959/18581734/c4d390b0-7bf9-11e6-9bb8-51a9284ef7eb.PNG)

> Had that happen to...

Sometimes the network disconnected isn't the network where _this_ happens... dont ask me how to duplicate that either.

**Comment by IceN9ne** [comment]
This issue is due to Ubuntu, and anyone else who does it, removing the older protocols from their OpenSSL installation.

The solution is to either only interact with targets who are also using a modern protocol system, or build your own local copy of OpenSSL and link KVIrc to that.
