### ISSUE TITLE
Re-add KDE builds to travis (duplicate #1975)

### ISSUE THREAD

**Issue by staticfox** [kvirc/KVIrc#2095]

**Comment by un1versal** [comment]
Well I already did add a ticket about this... https://github.com/kvirc/KVIrc/issues/1975

**Comment by staticfox** [comment]
Oh, I searched for the ticket since I thought we had it and all I saw was something about docker support

**Comment by un1versal** [comment]
Thats it, without docker theres no 16.04 in Travis and without that theres no KDE

**Comment by un1versal** [comment]
merged with #1975
