### ISSUE TITLE
KVIrc crashed under unknow circumstances after #2093

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#2097]
This is a placeholder for a random crash report after #2093
### Expected behavior

A happily running KVIrc
### Actual behavior

KVIrc decided to crash just because.
### Steps to reproduce the issue

There were no steps, cliked on another window and when came back KVIrc wasnt running
shortly after apport popped up

![demo-a](https://cloud.githubusercontent.com/assets/3521959/17475112/4762ac68-5d51-11e6-83c6-fd9eff2a5737.gif)
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.4.0-31-generic
System version: #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-08-08 07:15:36 UTC
Sources date: 20160807
Revision number: git-6873-g642ec84-dirty
System name: Linux-4.4.0-31-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.5.1
Features: IRC, Debug, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVSKVIrc 4.9.2 'Aria'
```

**Comment by un1versal** [comment]
and theres goes two crashes while elsewhere except in KVIrc

**Comment by un1versal** [comment]
3rd crash

![demo-a](https://cloud.githubusercontent.com/assets/3521959/17573398/06c8fbe6-5f52-11e6-8e8e-ff7b5297ebe6.gif)

**Comment by un1versal** [comment]
![capture](https://cloud.githubusercontent.com/assets/3521959/17573556/26eee11e-5f53-11e6-9858-f3e032134de5.PNG)

**Comment by un1versal** [comment]
I can repro this almost at will now... just had another crash

essentially starting it, then attached process to gdb (thread apply all bt get it moving and press c to continue) and killing gdb straight after and leaving kvirc running on #kvirc and go do something else on a diffrent window, two minutes later KVIrc will be gone crashed into oblivion.

edit, I quit GDB and detached process previous to killing GDB.

**Comment by staticfox** [comment]
Tried on OS X, Windows, and Linux. Can't reproduce :< core dumps welcome.

**Comment by Fylwind** [comment]
> killing gdb straight after

I don't think you're supposed to kill GDB while it is attached to a live process. I did the steps and got a SIGTRAP, which suggests it's trying to signal the (now-dead) debugger.

**Comment by staticfox** [comment]
> I don't think you're supposed to kill GDB while it is attached to a live process. I did the steps and got a SIGTRAP, which suggests it's trying to signal the (now-dead) debugger.

+1, from what I can recall, users have been saying they have been crashing and I doubt they attached gdb then called sigterm on it.

That said, I'm now unsure which back traces you posted are from the actual bug and you killing gdb

**Comment by un1versal** [comment]
> That said, I'm now unsure which back traces you posted are from the actual bug and you killing gdb

None, I meant I detached process from gdb and killed it, nothing wrong there.,

Im not the only one crashing randomly, it just hapens here after I ran KVIrc though the debugger and removed it.

Ive gone back to previous #2093 and I cant duplicate this anymore,

> Tried on OS X, Windows, and Linux. Can't reproduce :< core dumps welcome.

Ive said this now several times the gifs up here are from apport, Ill try to get stacks from them but kvirc only crashes when it not attached to GDB and I cant copy and paste anything from the apport report boxes.

**Comment by staticfox** [comment]
Do you use a proxy?

**Comment by un1versal** [comment]
> Do you use a proxy?

One of my private networks requires a proxy to be able to connect to it. so yes.

**Comment by un1versal** [comment]
FYI the first and second crash KVIrc crashed (spontaneously) and it had never been attached to GDB, I started attaching KVIrc's PID to GDB ever since  trying to catch this crash, but while KVIrc **IS** attached to GDB it wont crash.

The 3rd crash (and 4th happened last night before bed) after I detached PID from GDB etc.

the 3rd crash I was on a channel window (#kvirc to be precise) apport detected the crash as usual.
the 4th crash I left the window on freenodes console kvirc crashed and apport never even flinched.

Im not sure if the 1st crash KVirc was on the network using proxy. (now proxy has been mentioned)

in all instances KVIrc crashes while I leave the VM window and go else where on host. 2 minutes or so later its gone.

interesting.

**Comment by Fylwind** [comment]
P.S. It would be nice if you can post the backtrace as plain text instead of GIF/PNG.

Please try to post as many backtraces as you can. There's a good chance these are multiple different bugs.

**Comment by un1versal** [comment]
> P.S. It would be nice if you can post the backtrace as plain text instead of GIF/PNG.

maybe you missed it.

> Ive said this now several times the gifs up here are from apport, Ill try to get stacks from them but kvirc only crashes when it not attached to GDB and I cant copy and paste anything from the apport report boxes.

also Kvirc doesnt seem to crash when attached to GDB...

suggestions for magic welcome.

**Comment by staticfox** [comment]
I wonder if this is even related to #2093... There were minor things changed between now and that PR that _may_ (unlikely) affect things. Did the crashes happen at the last commit of the PR?

**Comment by staticfox** [comment]
Extreme shot in the dark, try from master now ( https://github.com/kvirc/KVIrc/commit/e988cdae48df9ea6eef6635add52f7aa43eed2a4 )

**Comment by un1versal** [comment]
I also wondered that, and Ive said it once, but Il say it again.

Straight after #2093 was compiled in (what was tip of master then 642ec84f26dbf7cb86039ddd650afff247c17f00) KVIRc crashed (1st crash)

[earlier this morning](https://github.com/kvirc/KVIrc/issues/2097#issuecomment-239099871), I went back pre #2093 and did the GDB thing which seems to hasten KVIrcs crash and it never crashed.

> Extreme shot in the dark, try from master now ( e988cda )

yep sure let me compile again.

**Comment by Fylwind** [comment]
Could try running `ulimit -c 4000000` before `kvirc` and see if a core dump file gets created in either the current directory or `/var/crash`.

**Comment by staticfox** [comment]
Hmm... If that doesn't work, maybe could you try looking at that PR and try ever n commits in that PR and see where you crash? It would really really help find where the issue is, since this is a really elusive bug. (And hey, looks like it worked out to commit more frequently ^^)

**Comment by un1versal** [comment]
Im in current master currently no crash so far, I have kvirc stacktraces in /var/crash but their for https://github.com/kvirc/KVIrc/issues/2084 and  https://github.com/kvirc/KVIrc/issues/2083 and https://github.com/kvirc/KVIrc/issues/2012

apport doesnt create anything there its in /tmp and its ~92MB bin files, so far, my attempts to get a stacktrace from that all open in apport thing that doest let me copy anything, Im sure theres ways around that, if I want to waste hours on this or not its another matter

**Comment by staticfox** [comment]
I'm 10 hours in, still no crash. How about you, @un1versal ?

**Comment by un1versal** [comment]
so far looks solid... idk what to tell ya

**Comment by staticfox** [comment]
That's so weird. If after a certain amount of time you need to turn off your computer or close KVIrc for whatever reason, can you try the commit before the one I mentioned above and see if you re-crash? This may be the fix but I honestly don't know why. I don't want to do forensics on it until either 1) we know it solves the issue or 2) we randomly have that giant "A HA" moment and the bug in the previous diff hits us like a ton of bricks.

**Comment by un1versal** [comment]
I can try reverting that commit to see if it makes crashes return. would that do or do you want me to specifically go back pre that commit?

**Comment by staticfox** [comment]
Basically just go back one commit before the proxy one (https://github.com/kvirc/KVIrc/commit/e988cdae48df9ea6eef6635add52f7aa43eed2a4) so https://github.com/kvirc/KVIrc/commit/a358e2ef10b569a83e5a1090261c691055713fa1 and see what happens

**Comment by staticfox** [comment]
![](http://24.media.tumblr.com/b8cc70098d2e40fd2c2c01a58415b9f3/tumblr_mn7t0rEOHn1ssppvlo1_500.gif)

**Comment by un1versal** [comment]
![](https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fimages.rapgenius.com%2F26b37ef63c2e62683951e5b19f9a26e1.500x296x18.gif&f=1)

What is there to understand, when life gives you lemons and youre dislexic it could be melons for all you know.

The gif was for added effect.
