### ISSUE TITLE
Run WHOIS nick nick on Query when a user doesnt exist console outputs wrong message

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#2098]
https://github.com/kvirc/KVIrc/blob/master/src/kvirc/sparser/KviIrcServerParser_numericHandlers.cpp#L2031-L2036

https://github.com/kvirc/KVIrc/blob/master/src/kvirc/sparser/KviIrcServerParser_numericHandlers.cpp#L2712-L2713

this seems intentional but makes no sense, much like almost everything KVIrc.
### Expected behavior

It should reply something like `nick: No such nick` or something.

[401 ERR_NOSUCHNICK](https://github.com/kvirc/KVIrc/blob/master/src/kvirc/sparser/KviIrcServerParser_tables.cpp#L483)
### Actual behavior

console outputs `nick: no such server`

[402 ERR_NOSUCHSERVER](https://github.com/kvirc/KVIrc/blob/master/src/kvirc/sparser/KviIrcServerParser_tables.cpp#L484)
### Steps to reproduce the issue
1. Open a query to some unknown (made up or real nick)
2. Make sure it is not online
3. Right click Query window or nick and perform a WHOIS.

![demo-a](https://cloud.githubusercontent.com/assets/3521959/17572075/c0e19c70-5f4a-11e6-94dd-0d3fd0a43da6.gif)
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.4.0-34-generic
System version: #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-08-10 20:36:49 UTC
Sources date: 20160810
Revision number: git-6893-ge37f31d
System name: Linux-4.4.0-34-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.5.1
Features: IRC, Debug, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

**Comment by staticfox** [comment]
This is correct, actually.

**Comment by un1versal** [comment]
yea, because that makes sense, nick and server are same thing obviously.

erm if its so right then ... close it.

**Comment by staticfox** [comment]
[5:50:36 pm] <staticfox> because the ircd attempts to hunt the server with the nick
[5:50:46 pm] <staticfox> and if the ircd cant find the server, it returns server not found

See more:
https://github.com/charybdis-ircd/charybdis/blob/8fed90ba8a221642ae1f0fd450e8e580a79061fb/modules/m_whois.cc#L138

**Comment by un1versal** [comment]
I see I see... In some languages parv pronounced parvo means stoopid

**Comment by staticfox** [comment]
parv = parameter vector

**Comment by un1versal** [comment]
:grin: I like http://dictionary.reverso.net/portuguese-english/parvo better
