### ISSUE TITLE
Away controller in tray icon is broken.

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#2102]
discussed in IRC and https://github.com/kvirc/KVIrc/pull/2100#discussion_r74549403

> ### Note: Somewhat related to https://github.com/kvirc/KVIrc/issues/2101
### Expected behavior

that when setting  away via tray icon, this is set as specified.
### Actual behavior

Setting away via tray icon is broken, the only thing that works is unsetting away if away is already set.
### Steps to reproduce the issue
1. enable tray icon
2. open tray icon and select 'Away on <networkname`or if youre connected to multiple networks`Away on All`
3. you see `[07:59:01] [Leaving away status]: You are no longer marked as being away`

![capture](https://cloud.githubusercontent.com/assets/3521959/17616145/bce0c5da-606a-11e6-903b-ea804d38c053.PNG)
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.4.0-34-generic
System version: #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-08-12 07:37:08 UTC
Sources date: 20160812
Revision number: git-6918-g5f84c46
System name: Linux-4.4.0-34-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.5.1
Features: IRC, Debug, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

**Comment by staticfox** [comment]
https://github.com/kvirc/KVIrc/issues/2101#issuecomment-239527456
