### ISSUE TITLE
Hover over effect on treeview channels

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#2108]
Windows OS works as expected, even with a Windows style (`kvirc -style=windows`) this  has never worked in Linux.

this is part 1 of 2 report on window selection and controlling when in treeview.
### Expected behavior

![demo-a](https://cloud.githubusercontent.com/assets/3521959/17652957/a1b51f4e-6282-11e6-86bb-b9f4915918f6.gif)
### Actual behavior

![demo-ab](https://cloud.githubusercontent.com/assets/3521959/17652972/24f4cd14-6283-11e6-9ce7-ee4dd42c23fb.gif)
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.4.0-34-generic
System version: #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016
Architecture: x86_64
Qt version: 5.5.1
Qt theme: windows or fusion

Build Info:
Build date: 2016-08-14 23:59:34 UTC
Sources date: 20160813
Revision number: git-5428-g197fcef
System name: Linux-4.4.0-34-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.5.1
Features: IRC, Debug, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

**Comment by IceN9ne** [comment]
I believe that this is a difference in style defaults between Windows and Linux in Qt and not a KVIrc bug.

However, if you want to add this property on all OS variants, then add the following line to the `KviTreeWindowListTreeWidget` constructor:

    setStyleSheet("QTreeView::item:hover{ background-color: #FFFFFF; }");

Adjust `#FFFFFF` to the background color of your choice.

**Comment by ctrlaltca** [comment]
As @IceN9ne says, it's the style that decides is the currently hovered item gets highlighted.
