### ISSUE TITLE
feature request: make window.close ignore boolKeepChannelOpenOnPart

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#2111]
I made this into a feature request because part and window.close should be distinct functions.
Modern popups have part/join in there that why part exists

and also made it into a feature request and not a bug so that @staticfox isnt upset and @IceN9ne dont argue in favor of this madness.
### Expected behavior

when you right click a channel i.e. `window.close` and `boolKeepChannelOpenOnPart` = true channel should close.
### Actual behavior

when you right click a channel i.e. `window.close` and `boolKeepChannelOpenOnPart` = true you dont part the channel as sane logic dictates. you need to perform 2x close to get the desired behavior.
### Steps to reproduce the issue

1) enable  `/option boolKeepChannelOpenOnPart 1`
2) join a network and any channel
3) select the channel on treeview, right clik and select close. 
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.4.0-34-generic
System version: #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-08-15 00:07:05 UTC
Sources date: 20160814
Revision number: git-6933-g65f77c7
System name: Linux-4.4.0-34-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.5.1
Features: IRC, Debug, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

**Comment by IceN9ne** [comment]
Implemented in b55570d
