### ISSUE TITLE
Status bar clock shows "12:xx:xx AM" for 12 PM.

### ISSUE THREAD

**Issue by GerbilSoft** [kvirc/KVIrc#2119]
The status bar clock shows "12:xx:xx AM" when it's actually 12 PM. This is caused by an error in the 12hr code.

https://github.com/kvirc/KVIrc/blob/755ea16867c402f9d205686d6d432d09ed9a7bc1/src/kvirc/ui/KviStatusBarApplet.cpp#L414

The "> 12" should be ">= 12".
### Expected behavior

Status bar clock shows "12:xx:xx PM" when it's 12 PM.
### Actual behavior

Status bar clock shows "12:xx:xx AM" when it's 12 PM.
### Steps to reproduce the issue
1. Add status bar clock in 12hr mode.
### System information

Distribution: Gentoo Linux
KVIrc executable information:

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.7.2-DEK-X230
System version: #10 SMP PREEMPT Tue Aug 23 02:47:49 EDT 2016
Architecture: x86_64
Qt version: 5.7.0
Qt theme: oxygen

Build Info:
Build date: 2016-08-20 22:40:18 UTC
Sources date: 20160102
Revision number: 755ea16867c402f9d205686d6d432d09ed9a7bc1
System name: Linux-4.7.1-DEK-X230
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   VERBOSE
   LIB_SUFFIX=64
   Threads=POSIX
Compiler name: /usr/bin/x86_64-pc-linux-gnu-g++
Compiler flags: -flto -O2 -pipe -g0 -march=native -floop-interchange -ftree-loop-distribution -floop-strip-mine -floop-block -fno-strict-aliasing 
Qt version: 5.7.0
Features: IRC, IPv6, Crypt, SSL, IfAddr, IPC, KDE, Transparency, Phonon, DCCVoice, Perl, Python, Enchant, Qt5, KVS
```

**Comment by DarthGandalf** [comment]
I think instead of doing this it should ask the system to render the time according to the current locale.
