### ISSUE TITLE
kvirc crash shortly after removing some DCC transfers

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#2125]
Ive just received this and was able to duplicate the crash by having several dcc active transfers and removing some completed while trying to select other transfers in progress.

Not exacty simple but there you are @staticfox 

However stacktraces in text format are another matter.

I have obtained the crash file from /var/crash and this can be opened with apport for inspection 
it contains all details.
### https://dl.dropboxusercontent.com/u/4325533/_usr_bin_kvirc.1000.crash.tar.gz

here is how to get the report in readable form form a Ubuntu or Variant 16.04 based
- sudo apt install apport-retrace
- Download _usr_bin_kvirc.1000.crash.tar.gz from link above
- untar archive and right click file
- select the stacktrace portion or any others to see what caused crash

see gif
![demo-ab](https://cloud.githubusercontent.com/assets/3521959/18090997/099bb8e6-6ebf-11e6-804b-2d42caff333c.gif)
### Expected behavior

Not a crash
### Actual behavior

Crash
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.4.0-34-generic
System version: #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-08-27 07:43:09 UTC
Sources date: 20160825
Revision number: git-6958-g901914e
System name: Linux-4.4.0-34-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.5.1
Features: IRC, Debug, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

**Comment by IceN9ne** [comment]
This part confuses me:

> removing some completed while trying to select other transfers in progress

Could you elaborate on the exact procedure you did?  I'm not understanding how you can remove some completed while at the exact same time selecting another.

Also, are you running "Clear Terminated" or "Clear All"?

**Comment by un1versal** [comment]
Obviously not at same time, thats not possible, what happened here was issue a clear terminated (via right click) about 3 or 4 (to clear) of them and while that was processing or immediately after it finished (hard to tell which was first) I tried selecting an ongoing transfer (some another 2 going) and poof shortly after no more kvirc...

On any case loading the crash file will give a stacktrace which Im sure points to right places, if it makes sense or not idk.

**Comment by IceN9ne** [comment]
I read the stacktrace (which you don't need to install anything to read, just edit it with any editor), and it seems to point to a timer event that ran a `window.close`.  I see nothing pointing to anything DCC related.

I also couldn't reproduce it, which is why I asked for a clarification.

**Comment by un1versal** [comment]
Ya, I dont understand it either, but thats what was going on. not sure what could send a window.close in that context.

there was  a crash bug related to window.close not long ago but thats was fixed

/me shrugs

**Comment by pragmaware** [comment]
Can't reproduce with current git. Stack trace no longer available.
