### ISSUE TITLE
broken ssl certificate or key file messages

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#2134]
### Expected behavior

A complete message
### Actual behavior

incomplete message
### Steps to reproduce the issue
1. load a key/pem file
   https://cloud.githubusercontent.com/assets/3521959/18159108/0adb976a-701f-11e6-8d31-6b711e770e75.PNG
2. connect to any server
3. look at messages in console

`[05:52:46] []: [SSL]: Using certificate file ....`
`[05:52:46] []: [SSL]: Using private key file ....`

![capture](https://cloud.githubusercontent.com/assets/3521959/18305247/8fff6ac0-74de-11e6-8255-c2124e51b0f2.PNG)

https://github.com/kvirc/KVIrc/blob/master/src/kvirc/kernel/KviSSLMaster.cpp#L135
https://github.com/kvirc/KVIrc/blob/master/src/kvirc/kernel/KviSSLMaster.cpp#L161

the other messages are also likely broken as the `[%s]:` isnt being populated.

notice the blank `[ ]` at beginning of message
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.4.0-36-generic
System version: #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-09-06 22:15:46 UTC
Sources date: 20160906
Revision number: git-6965-gc8a2f6f
System name: Linux-4.4.0-36-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.5.1
Features: IRC, Debug, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

**Comment by wodim** [comment]
They are not broken, they are empty: https://github.com/kvirc/KVIrc/blob/master/src/kvirc/kernel/KviSSLMaster.cpp#L124-L125

**Comment by un1versal** [comment]
they are never filled under any circumstances I come across.

**Comment by wodim** [comment]
From a quick look at the code, the only circumstance that fills that spot is a secure DCC connection, and it works:

![2016-09-07_12-17-52](https://cloud.githubusercontent.com/assets/1001553/18308512/200fb384-74f5-11e6-953e-6463187e2b6d.png)

**Comment by un1versal** [comment]
populated once out of six possible ways, yea makes sense to leave all five others empty, of course, what was I thinking, KVIrc flawless logic.

**Comment by wodim** [comment]
Things would be better for you if you stopped being a little bitter thing.

**Comment by un1versal** [comment]
keep them coming, its always good to get your personal attacks on the record.
