### ISSUE TITLE
Add option to get notified about messages in a certain channel

### ISSUE THREAD

**Issue by holzingk** [kvirc/KVIrc#2137]
### Expected behavior

Add an option to allow permanent or temporary notifications on new messages in a channel, like it is already possible when rightclicking a nickname. Maybe by rightclicking a channelname.

**Comment by wodim** [comment]
Isn't that this option?

![2016-09-09_19-12-39](https://cloud.githubusercontent.com/assets/1001553/18395971/6de91ffa-76c1-11e6-8fd5-72b6f9d44073.png)

**Comment by holzingk** [comment]
Yes there is, was asking in IRC. Always thought it applies to a nickname.
