### ISSUE TITLE
DCC video?

### ISSUE THREAD

**Issue by SoniEx2** [kvirc/KVIrc#2149]
It appears that DCC video is unfinished. Can it be finished?

This is for a friend who's looking for a video call software that works between windows and gnu.

**Comment by wodim** [comment]
Yes, it can be finished.

**Comment by SoniEx2** [comment]
Uh. Well what's missing?

**Comment by wodim** [comment]
I don't remember. I think it worked well but it was Linux only (v4l2) or something like that.

**Comment by wodim** [comment]
Anyway, being honest: DCC VIDEO is rubbish; it's some experiment that was done, credit where credit is due, but sending video over the internet is very complicated to get right, and if you're serious about needing this, I suggest you try Skype or something similar.

**Comment by Stanzilla** [comment]
You want something that uses https://en.wikipedia.org/wiki/WebRTC probably

**Comment by SoniEx2** [comment]
They said they couldn't get WebRTC to work reliably. Same for skype. Same for jitsi. Same for hangouts. [And so on....]

**Comment by wodim** [comment]
Millions of people use those technologies every day. I'd say pebcak

**Comment by SoniEx2** [comment]
Can we get working DCC video yet? Now I want it for personal reasons (promoting DCC) rather than to help someone.

**Comment by wodim** [comment]
Compile KVIrc on Linux with video support. I'm pretty sure it works.

**Comment by ctrlaltca** [comment]
When i wrote the DCC video code Qt had no facility to access webcams yet, so the only implemented backend was based on v4l2 and working only under linux.
Still now, Qt doesn't support video capture on Windows (source: http://doc.qt.io/qt-5/qtmultimedia-windows.html)

**Comment by ctrlaltca** [comment]
https://github.com/kvirc/KVIrc/pull/2628 ports dcc video to qt6, now OSes other than linux are supported.
Still, no way it's going to be enabled by default or publicized as a working video chat solution.
