### ISSUE TITLE
Feature request: Command for killing all global variables, a way to identify variable names from values

### ISSUE THREAD

**Issue by titaniachkt** [kvirc/KVIrc#2156]
no.1
`killglobals`?

Does something like this already exist? (sans maybe via Objects)
The online [command list](http://www.kvirc.net/doc/doc_command_index_all.html) returns no solutions

no.2
`global` and `$globals` are fine for creation and identification respectively,
but there's no way TMK to get the variable **name** itself from possible values
(sans maybe via Objects: `$objects.variables`)

eg. if the value of `%v1`  is "10", then some function, maybe, `$getvarname(<value>,[type],[local|global])` would search for declared variables and return an array of possible matches

Would such a thing be feasible?

**Comment by un1versal** [comment]
http://www.kvirc.net/doc/cmd_unset.html

**Comment by wodim** [comment]
I don't understand how any of these would be necessary... how can you even lose a variable name?

**Comment by alexzulu** [comment]
foreach(%y,$keys($globals)){
   unset %y
}

and no problem

**Comment by titaniachkt** [comment]
@un1versal:  wow, not sure how I missed unset, thanks
tried something like

`%a = $globals ;
unset %a ;`

..but that just unsets %a

@wodim: Haha,  it's a bit odd, yeah
it happens when you're modifying an open file while parsing it to kvirc, and you somehow...forget the old variable name

it's still in kvirc memory, but you can't unset it without quitting since there's no builtin command to kill all globals

@alexzulu: ohh,  really thought that would work, 
tried something similar actually [this is the exact code block]
`$n` is an alias for `$nothing`

```
foreach(%i2, $globals){
    if(%i2 == $n){
        echo "killing %i2\...";
        %i2 = $n ;
        echo "getting next gvar";
    }
}
```

but there's still one global that doesn't unset for whatever reason. Still investigating why
(it's the last line here, `%V00out1`)
(the global var. value is `echo -w=1` by the way)

```
%V00trg =1 ; //target wid/csid, global
%V00oute = "echo -w=%V00trg "; //output cmd, global
%V00out1 = "%V00oute" ; //global
```

**Comment by un1versal** [comment]
try not to use capitalized letter variable names and unseting them should be fine.

I have a low tech way to resolve your "I forgot the variable name" problem, its called pencil and paper.

> it happens when you're modifying an open file while parsing it to kvirc, and you somehow...forget the old variable name

in any case you just echo the full list of variables and if you know the current variables youre working with, all others must be old and therefore you can unset them without issue.

**Comment by titaniachkt** [comment]
OK, just tried 

```
%V00out1 = $n;
%V00out1 = "";

echo '%V00out1';
```

`%V00out1 = "";` worked

~90% sure I read somewhere that the above were equivalent when unsetting variables, but that seems to be my mistake :c 

Anyway just modified the above `foreach()` block as such:

```
foreach(%i2, $globals){
    if(%i2 == ""){
        echo "killing %i2\...";
        %i2 = "" ;
        echo "getting next gvar";
    }
}
```

and it still throws the same error, and the same global var. is set

@un1versal do you mean stick to lowercase variables, and declare globals via `global` instead?

**Comment by un1versal** [comment]
> do you mean stick to lowercase variables, and declare globals via global instead?

have you tried?

we dont know what the error is, you havent posted any errors yet. maybe you ant to post a fulll sample of what your trying to achieve so we can try to duplicate the issue. Not that I see any issue at all with setting or unsetting any variables.

**Comment by titaniachkt** [comment]
pfftahahah never mind everyone about the error, it was a simple `if` check mistake

```
foreach(%i2, $globals){
    if(%i2 == ""){
[..]
```

should've been

```
foreach(%i2, $globals){
    if(%i2 != ""){
 [...]
```

`==` -> `!=`
also, `if(%i2 == $nothing)`  works just fine as a comparison check, but unsetting a global variable with $nothing doesn't work
(minor, but worth nothing I guess)

**Comment by un1versal** [comment]
solved then

also try unsetting variables last e.g. https://github.com/kvirc/KVIrc/blob/master/data/defscript/actions.kvs#L377-L387

I cant remember anymore but using unset before delete caused one variable to be stuck, but using unset after delete solved that,

**Comment by titaniachkt** [comment]
Ok, sure thing
Regarding the topic feature requests:

@alexzulu 's  excellent suggestion allowed me to figure out the variable name,
and the `foreach()` block i posted works for unsetting global variables, even without a builtin command,

Though, I feel it should be noted somewhere in the 'Local and global variables' section of  [Variable documentation](http://www.kvirc.net/doc/doc_kvs_datatypes.html) that unsetting global variables via `%V = $nothing`
doesn't seem to work
(unsetting regular variables that way does work though, at least for integers and strings)

In any case, thanks to everyone who helped!

**Comment by un1versal** [comment]
feel free to submit [pull requests](https://github.com/kvirc/KVIrc/wiki/Contributing-code-to-KVIrc's-repositories) with any documentation improvements.

Its common knowledge that the internal documentation for many parts could use rewording or clarification and in many many cases needs examples. See https://github.com/kvirc/KVIrc/issues/1890
