### ISSUE TITLE
KVIRC nigthly build 'Server and Configuration' screen not centered in middle of screen.

### ISSUE THREAD

**Issue by lbalbalba** [kvirc/KVIrc#2158]
The 'Server and Configuration' screen displayed on startup, or through 'Settings->Configure Servers' does not get displayed in the center of the screen for me, but rather on the right bottom of the screen. It used to be in the center of the screen in kvirc 4.2.0. Running kvirc 64-bit version git-7028-g392d211 on Windows 10 Home 64 bit (Version 1607 [OS Build 14393.447]), with a screen resolution of 2560 x 1440.

### Expected behavior
'Server and Configuration' screen displayed at center of screen.

### Actual behavior
'Server and Configuration' screen displayed at right hand bottom of screen.

### Screenshot
![kvirc](https://cloud.githubusercontent.com/assets/2118014/20607124/1ad953ca-b276-11e6-96f1-d9103372c948.jpg)

### Steps to reproduce the issue
1. Start kvirc
2. Optionally go to 'Settings->Configure Servers' if the 'Server and Configuration' screen does not display on start-up.

### System information
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Windows Release : 10.0.14393
System version: Windows 10 (x64) (Build 14393)
Architecture: Intel64 Family 6 Model 60 Stepping 3
Qt version: 5.5.1
Qt theme: windowsvista

Build Info:
Build date: 2016-11-20 23:24:53 UTC
Sources date: 20161120
Revision number: git-7028-g392d211
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.5.1
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

**Comment by ltc-data** [comment]
+1 This also happens here

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Windows Release : 6.1.7601
System version: Windows 7 Ultimate (x64) Service Pack 1 (Build 7601)
Architecture: Intel64 Family 6 Model 158 Stepping 9
Qt version: 5.8.0
Qt theme: 

Build Info:
Build date: 2017-06-19 05:18:28 UTC
Sources date: 20170618
Revision number: git-7118-g6d68da09d
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.8.0
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Perl, Python, Enchant, Qt5, KVS
```
