### ISSUE TITLE
CTCP ignore options are unusable on Windows with high DPI settings

### ISSUE THREAD

**Issue by Heufneutje** [kvirc/KVIrc#2159]
### Expected behavior

Options should be properly spaced apart.

### Actual behavior

All of the options overlap each other.
![image](https://cloud.githubusercontent.com/assets/1357231/20649632/fd271d62-b4c3-11e6-99f3-cae3a6928f61.png)

### Steps to reproduce the issue
1. Right click any channel and hit Option Controllers

### System information
[//]: # (Type "/about.kvirc" (or click "Help → About KVIrc") and copy&paste the details from the "Executable Information" tab below between ``` marks)
[//]: # (Also Enter any OS information the "Executable Information" tab doesn't contain, e.g. KDE, Gentoo, Linux Mint, etc.
```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Windows Release : 10.0.14393
System version: Windows 10 Professional (x64) (Build 14393)
Architecture: Intel64 Family 6 Model 78 Stepping 3
Qt version: 5.5.1
Qt theme: windowsvista

Build Info:
Build date: 2016-11-15 05:17:21 UTC
Sources date: 20161115
Revision number: git-7023-gfa9a5d3
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.5.1
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```
[//]: # (If you experienced crashes, segfaults please also include a stacktrace below, For how-to read: https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace.)

**Comment by IceN9ne** [comment]
It looks like the window has a fixed pixel size enforced from the script.  This should probably be changed to allow for natural sizing of the dialog, but disable resizing.

**Comment by un1versal** [comment]
Thats not going to work as you think, I had a huge problem with this issue and other issues developing this in pre https://github.com/kvirc/KVIrc/pull/2070 , iirc I had one version previous to committing the PR that specified a gap between the items to solve this issue and no fixed size anywhere, and ended up being what is is now with no such issue reported.

I can say for sure, removing fixed dialog sizes will not do what you think and very likely bring back all the other issues. 

**However I dont care what is done here to solve this**, I have a terminal illness that will kill me before the year is out, at best!
So as you can imagine, no shits are given here for KVirc or the assholes remaining on this planet pre and post the fact.

**Comment by Heufneutje** [comment]
That sucks to hear but without trying to be rude here, this is an issue tracker. Can we please stick to the issue at hand?

**Comment by slaboff** [comment]
@Heufneutje 
I was wondering what monitor and resolution you are using. I have a script that uses the same type of GUI. Heard from a user that is running a 4K monitor with zoom, was having the same type of issue. So I'm redesigning my GUI to be more horizontal and adding an option for a resizing factor. Just allowing full resize doesn't always work, since it covers the whole screen.

Something that may help and I haven't found it in the docs for KVIrc, is a way to read the screen resolution.

**Comment by AndrioCelos** [comment]
This is what I got when I tried opening the dialog:
![screenshot 2016-11-29 17 42 56](https://cloud.githubusercontent.com/assets/6897624/20699627/606e1454-b65c-11e6-81c2-6f7a84ca86a9.png)
Can you explain how to set the display resolution such that this issue occurs?

## System Information
**KVIrc 4.9.2 'Aria'**

**Runtime Info:**
System name: Windows Release : 10.0.14393
System version: Windows 10 (x64) (Build 14393)
Architecture: Intel64 Family 6 Model 58 Stepping 9
Qt version: 5.5.1
Qt theme:  [actually a style sheet specified by a command line parameter]

**Build Info:**
Build date: 2016-11-28 19:14:42 UTC
Sources date: 20161128
Revision number: git-7030-gbc81991
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.5.1
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS

**Comment by Heufneutje** [comment]
@slaboff @AndrioCelos It's a Surface Pro 4. I believe the resolution is 2736x1824. It uses 200% zoom by default.

**Comment by IceN9ne** [comment]
Out of curiosity, since I don't have a machine that I can test this on, could you try the latest build that includes 9a2cb9a and make the following modifications to the optionctrlr action?

Comment out these lines (add a `#` to the beginning of the lines):

    %widget->$setMinimumHeight(450)
    %widget->$setMaximumHeight(450)
    %widget->$setMinimumWidth(330)
    %widget->$setMaximumWidth(555)
    %widget->$resize(330,450)

And add this line at the very end (after `%widget->$show()`)

    %widget->$setFixedSize(%widget->$width(),%widget->$height())

**Comment by Heufneutje** [comment]
I have never used any scripting in KVIrc before so I have no idea where you want me to add that.

**Comment by AndrioCelos** [comment]
Go to **Scripting** → **Action Editor**. **optionctrlr** is there.

**Comment by slaboff** [comment]
@IceN9ne  I tried the line you suggested, sorry to say it didn't work. I got the following error instead.

Runtime error: Can't find object function $setFixedSize for object named '' of class 'dialog'

I also got the same error when testing some of my own GUI panels.

**Comment by IceN9ne** [comment]
@slaboff I said in my comment

> could you try the latest build that includes 9a2cb9a

I just commited that an hour ago, so unless you compile KVIrc yourself, you'll have to wait for the next KVIrc nightly to be built.

**Comment by slaboff** [comment]
@IceN9ne  My apologies, should have finished my coffee first, didn't fully read your comment. Guess that's a problem with old age.

**Comment by Heufneutje** [comment]
@IceN9ne That does indeed solve the issue.
