### ISSUE TITLE
Punycoded Unicode nicks

### ISSUE THREAD

**Issue by SoniEx2** [kvirc/KVIrc#2161]
SoniEx2/CTCP-S#5

Messages with a `PUNY` CTCP should cause the user's nick to show up as unicode in a compatible client, if the feature is enabled.

TODO find a valid nick syntax for punycoded nicks.

(Alternatively, we could add yet another fucking bitfield to the fucking realname...)

**Comment by wodim** [comment]
![](http://imgur.com/r8xsmTC.gif)

**Comment by Heufneutje** [comment]
Maybe you should try actually defining your toy specifications before proposing them.

**Comment by SoniEx2** [comment]
Anyone wants unicode nicks and is willing to help me with their encoding?

**Comment by Heufneutje** [comment]
I won't, but I will give you some things to consider and reasons why this is a bad idea.

- Seeing as your messages will turn into a channel CTCP, there are channels that block those altogether. You would need to parse what IRCd you're using and for every single one take into account what their anti channel CTCP mode is (mode letter conflicts are fun). And then you just end up with a unicode nick that only sometimes shows up.
- You _**will**_ break compatibility with at least a few old clients, which an extension should never do. Have you considered what an unsupported client might do when it receives a CTCP message it doesn't understand? Will it drop the message altogether? Will it spam them at the user in a window not related to the channel? You have to take into account that there are many old abandoned clients out there that people still use and losing messages is a serious issue.

**Comment by SoniEx2** [comment]
1. You put the CTCP at the end of the message. Only 1 IRCd is known to block end-of-message CTCPs.
2. I have yet to see a broken client that parses end-of-message CTCPs.
