### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by amittel** [kvirc/KVIrc#2164]
Just saw that travis is failing.
Looks like this [line](https://github.com/kvirc/KVIrc/blob/master/.travis.yml#L76) is the problem.
`after_success:
    - test -r .travis_after_all.py && python .travis_after_all.py || echo No .travis_after_all.py found`

A solution may be found [here](https://github.com/semantic-release/semantic-release/issues/274).

**Comment by IceN9ne** [comment]
The solution you posted doesn't seem to match what we're experiencing.  From what I can see, the said solution is in regards to multiple processes both thinking themselves as the leader.  It also seems to apply to travis users that use semantic-release as they include a similar thing themselves.  I don't see anywhere indicating that we are using semantic-release.

For us, it appears that the Mac OSX build isn't reporting that it is done.  I know very little about travis-ci, but if you look at the last line of the Mac build, you'll see this line that might also be causing the issue (which appears to be a travis issue, not our issue):

    /Users/travis/build.sh: line 148: shell_session_update: command not found

**Comment by amittel** [comment]
Ah ok, sorry. I overlooked that one.

**Comment by staticfox** [comment]
@DarthGandalf would probably know, he's the one that set up our Travis-CI service initially (that and I believe a lot of the code is borrowed from ZNC)

**Comment by IceN9ne** [comment]
Possibly fixed with d300312

**Comment by wodim** [comment]
It is.
