### ISSUE TITLE
Typo in KVIrc Documentation - Help Index - $chan.invitelist

### ISSUE THREAD

**Issue by Donat76** [kvirc/KVIrc#2168]
### Expected behavior

$chan.invitelist
Returns an array of channel invite masks
Usage
<array> $chan.invitelist([window_id])
Description
Returns an array of invite masks set on the channel identified by [window_id].
If [window_id] is empty, the current window is used.
If the window designated by [window_id] is not a channel a warning is printed and an empty array is returned.

### Actual behavior

$chan.invitelist
Returns an array of channel invite masks
Usage
<array> $chan.banexceptionlist([window_id])
Description
Returns an array of invite masks set on the channel identified by [window_id].
If [window_id] is empty, the current window is used.
If the window designated by [window_id] is not a channel a warning is printed and an empty array is returned.

[//]: # (Besides the text description, include any screenshot(s) that help us visualize the issue you're facing)

Under the Usage heading, rather then "<array> $chan.invitelist([window_id])" there is "<array> $chan.banexceptionlist([window_id])".

### Steps to reproduce the issue
1. Help Index
2. $chan.invitelist
3.

### System information

KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Windows Release : 10.0.14393
System version: Windows 10 (x64) (Build 14393)
Architecture: AMD64 Family 20 Model 2 Stepping 0
Qt version: 5.5.1
Qt theme: windowsvista

Build Info:
Build date: 2016-12-30 01:29:46 UTC
Sources date: 20161229
Revision number: git-7043-g907dca6
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.5.1
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS

[//]: # (If you experienced crashes, segfaults please also include a stacktrace below, For how-to read: https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace.)

**Comment by staticfox** [comment]
Thanks!
