### ISSUE TITLE
Feature request: webcam functionality

### ISSUE THREAD

**Issue by Sharrisii** [kvirc/KVIrc#2169]
I wanted to request webcam functionality for KVIrc, either using FFmpeg or MJPGstreamer.
Perhaps RTMP might be needed (https://obsproject.com/forum/resources/how-to-set-up-your-own-private-rtmp-server-using-nginx.50/ )

You could allow to have a channel OP stream his webcam footage, and make it available (only in the current chatroom), to all people in the chatroom (guests). If there is more than 1 OP in the chatroom, the person that was OP the first would get the streaming privilege, but upon leaving the room or de-opping himself, the person that then becomes OP will get the streaming privilege.

This feature should make the software usable as a (light-weight) videoconferencing software (which are in short supply for linux, and are often quite heavy on resources (see http://openmeetings.apache.org/installation.html ). IRC also all ready has the ability to make chatrooms private (see https://botbot.me/how-to-setup-irc-channel/ ), so that would be an additional advantage (then usable for say company meetings, ...).

PS: If there's interest in making a version of KVIrc for slitaz (or TAZ: https://sourceforge.net/projects/taz/ ), then perhaps you might also wish to make a kvirc.profile for firejail (firejail package).

**Comment by wodim** [comment]
There is already such feature but it only works on Linux.

**Comment by Sharrisii** [comment]
I only have slitaz (and no other linux distro's) installed, and since there's not yet a package for slitaz, I didn't know the function was all ready available. Still, reading about the webcam feature now (https://github.com/kvirc/KVIrc/issues/2149 ) it seems it's client-to-client based, so I'm assuming its only available between 2 users (direct, private connection), and not any more (so not for the entire chatroom). I'm thinking that a multicast webcam functionality as discussed in my previous post (1 user -the OP- sending video to all guests in the chat room). For some things, like corporate meetings or even classes for school, having just 1 videocam where someone can present something and the others just watch and ask questions, this would be perfect. It's this feature that most other software (like gajim, pidgin, ...) doesn't have. Videoconferencing software probably does have it, but its less convenient to use and heavy. So market-wise, there's a need that isn't being fulfilled by other software which KVirc could potentially address.

**Comment by IceN9ne** [comment]
> You could allow to have a channel OP stream his webcam footage, and make it available (only in the current chatroom), to all people in the chatroom (guests). If there is more than 1 OP in the chatroom, the person that was OP the first would get the streaming privilege, but upon leaving the room or de-opping himself, the person that then becomes OP will get the streaming privilege.

> I'm thinking that a multicast webcam functionality as discussed in my previous post (1 user -the OP- sending video to all guests in the chat room). For some things, like corporate meetings or even classes for school, having just 1 videocam where someone can present something and the others just watch and ask questions, this would be perfect.

There is no way to add this functionality as IRC was never designed for something like this.  You're trying to force a protocol to do something it shouldn't.

The webcam ability we do have over DCC is as good as it gets.
