### ISSUE TITLE
Fix INSTALL-Macos.txt

### ISSUE THREAD

**Issue by kartagis** [kvirc/KVIrc#2174]
There are some typos in the INSTALL-Macos.txt, which needs to be fixed. A PR is on the way.

**Comment by DarthGandalf** [comment]
Most of these dependencies (Qt, etc) are easier installable via homebrew. There should be a KVIrc formula in brew itself, to make installation even easier. I guess I should open a separate ticket here for that.

**Comment by wodim** [comment]
I wrote this some time ago https://github.com/kvirc/KVIrc/wiki/Compiling-KVIrc-from-git-on-macOS-Sierra
