### ISSUE TITLE
Alpha releases

### ISSUE THREAD

**Issue by ShalokShalom** [kvirc/KVIrc#2176]
Alpha 2 is not released on Github - i found it only in the - imho confusing - news archive.
Is Alpha 3, or even a Beta near?
Stable release?

Thanks a lot in advance

**Comment by staticfox** [comment]
Hi! Currently we have a set of tickets open that need to be completed before a release is finalized. Once those issues are resolved in one way or another, we should be good to go straight to release as we've had a batch of users run nightly for a good while and everything appears to be stable. If you're curious, the list of issues can be found here https://github.com/kvirc/KVIrc/milestone/6. Thanks for your interest in the KVIrc project!

**Comment by ShalokShalom** [comment]
Its running for me stable as well, thats why i am asking. 

Thanks a lot

**Comment by wodim** [comment]
@ShalokShalom There are still a few things we'd like to see fixed before a stable release is made.
