### ISSUE TITLE
Drop QtWebKit support

### ISSUE THREAD

**Issue by staticfox** [kvirc/KVIrc#2178]
It's deprecated and should be replaced with something like QtWebEngine or a text viewer for now. Regardless, once that's implemented it should make porting KVIrc to MSVC2015 a breeze.

**Comment by IceN9ne** [comment]
This seems related to #1854

**Comment by SolarAquarion** [comment]
debian sid and stretch has qtwebengine

**Comment by wodim** [comment]
msys2 on the other hand does not.

I'm thinking about this change because it seems fairly simple, but is qtwebengine available in the version of qt that resides in appveyor?

**Comment by Dessa** [comment]
it should be, we could try a few versions if we are not sure

**Comment by a17r** [comment]
Any update here?

**Comment by ctrlaltca** [comment]
Closing as dup #1854
