### ISSUE TITLE
German Version 4.9.2 - EventHandler doesnt execute

### ISSUE THREAD

**Issue by h1ght** [kvirc/KVIrc#2188]
### Expected behavior
on default, eventhandler "OnChannelMessage" should execute handler "Standart"

### Actual behavior
on default, eventhandler "OnChannelMessage" doenst execute "Standart" (default), it just executes "Standart_1"
http://i.imgur.com/RId0Xig.png
[//]: # (Besides the text description, include any screenshot(s) that help us visualize the issue you're facing)

### Steps to reproduce the issue
1.go to eventeditor
2.select "OnChannelMessage" right click, add new handler.
3. paste somescript into it and press "anwenden" and nothing happens like usual. 

### System information
[//]: # (Type "/about.kvirc" (or click "Help → About KVIrc") and copy&paste the details from the "Executable Information" tab below between ``` marks)
KVIrc 4.9.2 'Aria'

Laufzeitinformationen:
System-Name: Windows Release : 6.1.7601
System-Version: Windows 7 Enterprise (x64) Service Pack 1 (Build 7601)
Architektur: Intel64 Family 6 Model 23 Stepping 7
Qt-Version: 5.5.1
Qt-Theme: windowsvista

Erstellungsinfo:
Build-Datum: 2017-02-04 17:32:32 UTC
Quellcode-Datum: 20170204
Revisionsnummer: git-7063-g9e8a9d9e0
System-Name: Windows-6.3.9600
CPU-Name: AMD64
Build-Kommando: C:/Program Files (x86)/CMake/bin/cmake.exe
Buildflags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler-Name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compilerflags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt-Version: 5.5.1
Funktionen: IRC, IPv6, Crypt, SSL, IPC, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
[//]: # (Also Enter any OS information the "Executable Information" tab doesn't contain, e.g. KDE, Gentoo, Linux Mint, etc.)
win 7 x64 enterprise german. 
```

```
[//]: # (If you experienced crashes, segfaults please also include a stacktrace below, For how-to read: https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace.)

**Comment by IceN9ne** [comment]
If you look at the color of the symbols to the left of the event handler name in the list, you'll notice that one is darker than the other.  This lighter colored one is indicating the event handler "Standard" is disabled whereas "Standard_1" is enabled.  Right click the "Standard" event in the list and click "Enable Handler".

Usually, when an event handler becomes disabled, it's indicative of an error in the code for said handler.

**Comment by h1ght** [comment]
it doens't work. not on my rig with that version. 
i can hit "awenden" (apply) as many times as i want. but it doenst activate.

**Comment by IceN9ne** [comment]
>  Right click the "Standard" event in the list and click "Enable Handler".

Clicking apply only saves the event handler, not enables it.

**Comment by h1ght** [comment]
i only got the buttons "ok" (closing the editor) "anwenden" (which would apply it) and "abort" (gues what, closing it too)
and i only can delete them to deactivate them.

**Comment by IceN9ne** [comment]
To the left of the script editor are is a list of all of the handlers.  Right-click the event handler name in the list and click "Enable Handler" (or whatever it is in German).

**Comment by h1ght** [comment]
ive seen it now, but now im figuring out how i activated that script ô.O

**Comment by wodim** [comment]
If there's a problem with a handler (syntax error, or whatever) the handler is disabled, and you have to enable it manually if you want it to work again.
