### ISSUE TITLE
have Appveyor build standard and debug builds for windows?

### ISSUE THREAD

**Issue by wchristian** [kvirc/KVIrc#2191]
In order to get useful backtraces debug builds are necessary. However the Windows build process is not automated for a general case, and right now is done so only for Appveyor. Short of automating the build process for users with scripting in the repo, a useful idea would probably have Appveyor generate normal AND debug builds.

As far as i can tell this should be doable by way of adding to the cmake line in appveyor.yml: https://github.com/kvirc/KVIrc/blob/master/.appveyor.yml#L109

As per https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace -DDEBUG=1 should probably be added; and DarthGandalf suspects -DCMAKE_BUILD_TYPE=Debug as well.

**Comment by wchristian** [comment]
@DarthGandalf This build lacks the *.pdb files containing the actual symbols. Do you think you can get those added?

    D:\KVIrc\Qt5Cored.pdb: Cannot find or open the PDB file.
    D:\KVIrc\Qt5Cored.pdb: Cannot find or open the PDB file.
    c:\work\build\qt5_workdir\w\s\qtbase\lib\Qt5Cored.pdb: Cannot find or open the PDB file.
    C:\WINDOWS\Qt5Cored.pdb: Cannot find or open the PDB file.
    C:\WINDOWS\symbols\dll\Qt5Cored.pdb: Cannot find or open the PDB file.
    C:\WINDOWS\dll\Qt5Cored.pdb: Cannot find or open the PDB file.
    SYMSRV:  c:\Symbols\Qt5Cored.pdb\41560C78A04540CABA4EFFC868CE75BD4\Qt5Cored.pdb - file not found
    *** ERROR: HTTP_STATUS_NOT_FOUND
    *** ERROR: HTTP_STATUS_NOT_FOUND
    *** ERROR: HTTP_STATUS_NOT_FOUND
    SYMSRV:  c:\Symbols\Qt5Cored.pdb\41560C78A04540CABA4EFFC868CE75BD4\Qt5Cored.pdb not found
    SYMSRV:  http://msdl.microsoft.com/download/symbols/Qt5Cored.pdb/41560C78A04540CABA4EFFC868CE75BD4/Qt5Cored.pdb not found
    srv*c:\Symbols*http://msdl.microsoft.com/download/symbols: Symbols not found on symbol server.

---

    D:\KVIrc\kvirc.pdb: Cannot find or open the PDB file.
    D:\KVIrc\kvirc.pdb: Cannot find or open the PDB file.
    C:\projects\kvirc\build\src\kvirc\kvirc.pdb: Cannot find or open the PDB file.
    C:\WINDOWS\kvirc.pdb: Cannot find or open the PDB file.
    C:\WINDOWS\symbols\exe\kvirc.pdb: Cannot find or open the PDB file.
    C:\WINDOWS\exe\kvirc.pdb: Cannot find or open the PDB file.
    SYMSRV:  c:\Symbols\kvirc.pdb\54182D19394140E4887D13E019AF7DFD2\kvirc.pdb - file not found
    *** ERROR: HTTP_STATUS_NOT_FOUND
    *** ERROR: HTTP_STATUS_NOT_FOUND
    *** ERROR: HTTP_STATUS_NOT_FOUND
    *** ERROR: HTTP_STATUS_NOT_FOUND
    SYMSRV:  c:\Symbols\kvirc.pdb\54182D19394140E4887D13E019AF7DFD2\kvirc.pdb not found
    SYMSRV:  http://msdl.microsoft.com/download/symbols/kvirc.pdb/54182D19394140E4887D13E019AF7DFD2/kvirc.pdb not found
    srv*c:\Symbols*http://msdl.microsoft.com/download/symbols: Symbols not found on symbol server.

**Comment by staticfox** [comment]
Is there a reason to build release at all? If it's easier, maybe we should only do debug builds and not release builds, since they're nightlies and that's more or less the point.

**Comment by wchristian** [comment]
Technically debug builds are slower, but i've been running debug kvirc for a while now and not noticed any reason to be concerned about performance.

**Comment by DarthGandalf** [comment]
* There's an ugly black window (console), and currently nightly is the recommended way to run on windows, because 4.2.0 is so old and unsupported. That ugly black window will just scare people away.
* It makes sure KVIrc is buildable in release mode, which will be important for KVIrc 5.0

**Comment by wchristian** [comment]
I think you can get rid of the console window by changing the debug configuration to be a normal window-only program.

**Comment by wchristian** [comment]
Oh, and of course:

- debug builds are much bigger, usually 2 x release build

**Comment by wchristian** [comment]
Note for later, #2071 contains a script to easily cause crashes and thus test symbols.

**Comment by wchristian** [comment]
Managed to get this output from a manually enforced crash. I think that makes the debug builds a great success.

![image](https://cloud.githubusercontent.com/assets/175467/23192379/638435ae-f8a3-11e6-8e08-c65c90ca8e51.png)

Stuff i had to do:

- have ms visual studio 2015 installed
- download & install the debug build of kvirc
- download and unpack pdb.tgz
  - delete all the vc120.pdb files
  - copy all remaining *.pdb files directly into the same dir as kvirc.exe
- download and install the appropiately bitted msvc2013 build from https://download.qt.io/archive/qt/5.5/5.5.1/
  - copy all the qt *.pdb files into the same dir as kvirc.exe

That allowed me to click a "debug" button on crash, which dropped me into msvc which found the pdb files on its own.

**Comment by Jan02** [comment]
@wchristian where did you get ms visual studio 2015 ? the official download is for the 2017 community version from https://www.visualstudio.com/downloads/

**Comment by wodim** [comment]
Is this supposed to be fixed now, then?

**Comment by wchristian** [comment]
I see debug builds here: https://ci.appveyor.com/project/DarthGandalf/kvirc/branch/master

So that should be fine now, yes. Thank you. :)
