### ISSUE TITLE
kvirc first run wizard should store even partial settings

### ISSUE THREAD

**Issue by wchristian** [kvirc/KVIrc#2197]
### Expected behavior

If i have partial progress in configuring kvirc via the wizard, cancel the wizard, then start it again later, it should offer me to load the settings i chose last time i ran it.

### Actual behavior

On every run the kvirc wizard starts off completely fresh.

### Steps to reproduce the issue

1. install kvirc fresh
2. run it to get first run wizard, make some settings
3. cancel
4. restart kvirc to get first run wizard

**Comment by ctrlaltca** [comment]
Imho when you "cancel" the wizard you declare you want to drop all changes made to the settings using the wizard. Where are they supposed to be stored? In a last-cancelled-wizard-settings file?

**Comment by wchristian** [comment]
Something like that, yea. In this case i'm only canceling because i'm inspecting file system/registry activity of the wizard with procmon. Other use cases would be "suddenly need to do something else, but would like to continue later".

**Comment by Heufneutje** [comment]
That's not how a cancel button works. In any software. If that option were to be added it should be called something else in my opinion rather than using the cancel option.

**Comment by wchristian** [comment]
Fair enough, i have no particular beef with whether this functionality is in "cancel" or a "later" button.

**Comment by IceN9ne** [comment]
There's less than 10 settings that you can set during the wizard and they're simple settings so saving them for later is a waste of effort and not worth it.
