### ISSUE TITLE
ability to close windows by middle-clicking button in classic window list

### ISSUE THREAD

**Issue by wchristian** [kvirc/KVIrc#2199]
In most tabbed UIs (browsers, editors, etc.) it is possible to close a tab by middle-clicking it. KVIrc doesn't seem to have that, and it would be nice to see that added.

**Comment by IceN9ne** [comment]
We already have <kbd>shift</kbd>+<mouse>left-click</mouse> as window close when clicking on the window list button.  Is it important to add <mouse>middle-click</mouse> as well?

**Comment by wchristian** [comment]
It's the difference between being able to manipulate the ui quickly with one hand or not, which is also an accessibility issue.

**Comment by IceN9ne** [comment]
Ok, apparently middle-click works on the tree list, so I suppose it can be added to the classic list as well.
