### ISSUE TITLE
smart nickname colors option should be more strict in checking fg/bg contrast

### ISSUE THREAD

**Issue by wchristian** [kvirc/KVIrc#2201]
The option is here:

![image](https://cloud.githubusercontent.com/assets/175467/23122319/080b6d4a-f764-11e6-9e2e-afe88196ae5b.png)

And sometimes it generates colors like this:

![image](https://cloud.githubusercontent.com/assets/175467/23122351/23c0f334-f764-11e6-890d-db1c3dfeee62.png)

The contrast between fg and bg is much too low there.

**Comment by IceN9ne** [comment]
Duplicate #353
