### ISSUE TITLE
option controller window does not clarify it changes global options

### ISSUE THREAD

**Issue by wchristian** [kvirc/KVIrc#2202]
The option controller window is opened by clicking a button in the channel option toolbar, which implies it works per channel, when in reality it works for all windows.

The window should have a note stating that changes there apply globally.

![image](https://cloud.githubusercontent.com/assets/175467/23122436/802899a6-f764-11e6-80a6-1ac36a55501b.png)

**Comment by ltc-data** [comment]
hey, I had a go at trying to fix this in a simple way in https://github.com/kvirc/KVIrc/pull/2237
if that gets merged you will need to update your KVIRC and restore default scripts EXACTLY like this screenshot shows.
goto Scripting Menu -> Restore Default Script

edit changed screengrab
![capture](https://user-images.githubusercontent.com/25669462/27670152-efa8e672-5c82-11e7-80a1-d0edc71c9a6f.PNG)

that will bring up the changes without overwriting any of your own scripts that you may have.

To make any of this per network, you need a total rewrite maybe even c++ changes too.
