### ISSUE TITLE
message decorations don't differentiate between user action and *own* user action

### ISSUE THREAD

**Issue by wchristian** [kvirc/KVIrc#2204]
There's only this:

![image](https://cloud.githubusercontent.com/assets/175467/23124732/c39c6f82-f76e-11e6-818c-153d161bd36a.png)

In contrast to:

![image](https://cloud.githubusercontent.com/assets/175467/23124838/4e38ac78-f76f-11e6-9b78-0db2978b4b27.png)

**Comment by wchristian** [comment]
13:31:50 (IceN9ne) If someone does #2204, then it should probably be KVI_OUT_OWNACTION and KVI_OUT_OWNACTIONCRYPTED... and slip in KVI_OUT_TOPICCRYPTED as well so the theme defaults only need updating once

**Comment by ltc-data** [comment]
Im curious now, which any other clients do you know that distinguish own action vs someone elses action?

**Comment by wodim** [comment]
HexChat?

**Comment by ltc-data** [comment]
the correct answer is, there are no other clients but kvirc and kvirc is near perfect as is.

**Comment by ltc-data** [comment]
I had to re-install Hexchat to test that 😄  in fact the difference is the text color of message between own action text vs someone else action text. Own is lighter grey text vs someone else is darker text.

The only advantage (if you can call it that)  I see in hexchat is that you can customize that output text and make each word a different color or bold etc if you want.

In the end I ended up in kvirc and dumped hexchat, so my previous comment applies.

That said, if the same distinction of text color one vs the other is made in KVirc that would be enough.

**Comment by wchristian** [comment]
@positr0nic mIRC also makes the difference, and my personal use case is to make my own lines dimmer to make it easier to skim conversation. That doesn't work well if i can't dim my own `/me` actions.

**Comment by wodim** [comment]
e4ef82f
