### ISSUE TITLE
The example code for the event OnQuit is wrong.

### ISSUE THREAD

**Issue by Kejiaigojiomannah** [kvirc/KVIrc#2209]
The error is present in stable as well as the online version of the help (which, I hope, is current). The presented code is this:
`foreach(%cname,$4)echo -r=$channel(%cname) User $0 is quitting...`
In conjunction with the event’s description, one might be led to believe that $4 is an array. However, inspection with the function $typeof shows that it is not; instead, it’s a comma-separated list in a single string.
Furthermore, the code, as shown, won’t work if multiple channels are left: The foreach loop would do exactly one iteration, during which the entire contents of $4 are assigned to %cname (it doesn’t split the string automatically). This will lead to the echo failing because the switch '-r' is receiving invalid input.

In order to fix it, I suggest adding a hint to the description (or to the scripting introduction) that states that $4 (and indeed all numbered parameters, according to IceN9ne) is a string and that multiple elements are packed into it separated with a comma.
In addition, the code could be changed to this line instead, which ought to work*:
`foreach(%cname, $str.split(",", $4)) echo -r=$channel(%cname) User $0 has quit. (Channels left: $4)`

*During testing, I noticed that it’s astonishingly uncommon for people to quit with more than one channel active (and probably even more uncommon to part). It’s also very quiet on IRC right now, so I can’t really tell whether it works or not. ;)

**Comment by IceN9ne** [comment]
Fixed in ca80ee6
