### ISSUE TITLE
Debug builds git-7115-g2c89201e3: Missing ucrtbased.dll Kivirc fails to launch

### ISSUE THREAD

**Issue by ltc-data** [kvirc/KVIrc#2227]
### Expected behavior
That the program would launch

### Actual behavior
Fails to Launch with error

```
The program cant start because ucrtbased.dll is missing from your computer, Try reinstalling the program
to fix this problem.
```

Tried reinstalling kvirc/msvc no joy

![capture](https://user-images.githubusercontent.com/25669462/26970592-de553f64-4d01-11e7-8f2c-724578fa71b8.PNG)

[//]:# (Besides the text description, include any screenshots that help us visualize the issue you're facing)

### Steps to reproduce the issue
1. upgrade Kvirc from  git-7103-g48fd3bc45 to  git-7115-g2c89201e3 on Windows 7
2. Start Kvirc post upgrade
3.

EDIT: I suspect https://github.com/kvirc/KVIrc/commit/5b14c711675aa807ccf27ea2f67cf5116872f210 broke this for Windows 7

### System information
[//]:# (Type ```/about.kvirc``` or click "Help → About KVIrc" and copy & paste the details from the "Executable Information" tab below between ``` marks)  
[//]:# (Also Enter any OS information the "Executable Information" tab doesn't contain, e.g. KDE, Gentoo, Linux Mint, etc.)

```
Program doesnt start
```
[//]:# (If you experienced crashes or segfaults please also include a stacktrace below, For how-to read: https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace.)

**Comment by wodim** [comment]
I guess we need to update the msvc redistributable @Dessa

**Comment by ltc-data** [comment]
I just noticed this happens with the debug builds only, release are OK. Somehow I grabbed a debug build instead.

Edit: Heres some info that may help setup your Windows 7 compatible debug builds https://qualapps.blogspot.co.uk/2016/05/remote-debugging-visual-c-2015.html

**Comment by Stanzilla** [comment]
I haven't been following anything lately but if nothing was changed since we discovered it, the release builds on d00p's website get overwritten by debug builds since they build afterwards and have the same name.

**Comment by ltc-data** [comment]
Yes thats a separate issue, release names would be more informative with release/debug labels added,

From what I have investigated, this issue only affects debug builds on Windows 7.

**Comment by IceN9ne** [comment]
@Stanzilla The debug builds are built first, then the release builds. Also, the debug builds are not uploaded to d00p's website.  If you look at the bottom of the appveyor logs you'll see this line highlighted in yellow:

> "FTP" deployment has been skipped as environment variable has not matched ("cmake_build_type" is "Debug", should be "Release")

**Comment by Stanzilla** [comment]
Oh! Nvm then!

**Comment by IceN9ne** [comment]
@positr0nic 
> Somehow I grabbed a debug build instead.

How did you acquire a debug build without purposely grabbing it from appveyor artifacts?

**Comment by wodim** [comment]
He probably downloaded it just after the debug build finished, but before the release build finished.

Does this count as a race condition?

**Comment by ltc-data** [comment]
> How did you acquire a debug build without purposely grabbing it from appveyor artifacts?

It wasnt on purpose, I cant stress that enough, but having noticed the issue was with the debug builds the observation is, no debug builds recent or old, work on windows 7 all fail with this error.

**Comment by IceN9ne** [comment]
@positr0nic Where did you get the install you are using?  d00p doesn't host a debug build, which is why I asked how you acquired it.  If you got it from d00p, then the issue is with our release builds, not debug builds.

**Comment by ltc-data** [comment]
It was like you say, but it wasnt on purpose, but does it matter? They still dont work.

It doesnt matter either way, release builds work, close it f you like.

**Comment by wodim** [comment]
It matters because debug builds shouldn't be in the ftp at all.
