### ISSUE TITLE
[Privacy] Use tor for avatar requests

### ISSUE THREAD

**Issue by SoniEx2** [kvirc/KVIrc#2235]
You have separate proxy settings for avatars (or at least you should have/I assume you do), so why not use tor by default?

This would make avatars much safer. Only DCC-based avatars would leak the avatar **_owner_**'s IP. (Add a warning for this, recommend imgur or something for privacy protection. Which is a good idea anyway unless you're stripping EXIF before DCCing the avatars.)

**Comment by AndrioCelos** [comment]
HTTP could also leaks the owner's IP if I host my avatar on my own website.

**Comment by wodim** [comment]
You want to talk shit, go to the irc channel. You know we have essentially no rules. But please don't pollute the bug tracker, because this is where the work is done.
