### ISSUE TITLE
After installing from source on macOS Sierra, I do not have SSL available

### ISSUE THREAD

**Issue by SystemDisc** [kvirc/KVIrc#2236]
This isn't a bug. I'm pretty certain I just don't know what I'm doing. I didn't see anything mentioned about SSL in [INSTALL-MacOS.txt](https://github.com/kvirc/KVIrc/blob/master/doc/INSTALL-MacOS.txt)

### Expected behavior
Since I have openssl installed, I expected cmake and make to link in any appropriate SSL libs, and to be able to use SSL in KVIrc.

### Actual behavior
The SSL chekbox for servers is greyed out

<img src="https://i.imgur.com/fUT4PiO.png">

### System information
<img src="https://i.imgur.com/IktP9Xc.png">
<img src="https://i.imgur.com/clXowU9.png">

[console output while building/installing](https://pastebin.com/Xn1ZqJuz)

**Comment by wodim** [comment]
Please try my guide.

https://github.com/kvirc/KVIrc/wiki/Compiling-KVIrc-from-git-on-macOS-Sierra

**Comment by wodim** [comment]
Re-open if, after using that guide, you still can't get SSL support on macOS.
