### ISSUE TITLE
DCC accept/reject dialog shows on center of primary monitor regardless of where the main KVIrc window is located

### ISSUE THREAD

**Issue by LeRaldo** [kvirc/KVIrc#2240]
### Expected behavior
The DCC accept/reject dialog should show in the center of the main KVIrc window, OR at the very least in the center of the monitor that the main KVIrc window is on.

### Actual behavior
The DCC accept/reject dialog currently shows in the center of my primary monitor, while I have the main KVIrc window situated on my secondary monitor. So in essence, the DCC accept/reject dialog shows on monitor 1 while I have KVIrc on monitor 2.

[//]:# (Besides the text description, include any screenshots that help us visualize the issue you're facing)
![gvtbtuo](https://user-images.githubusercontent.com/3815475/31053824-9f670b90-a65a-11e7-8b59-6b767a179561.png)

### Steps to reproduce the issue
1. Have KVIrc on a secondary monitor
2. Have someone attempt to send you a file
3. DCC accept/reject dialog subsequently appears on primary monitor

### System information
[//]:# (Type ```/about.kvirc``` or click "Help → About KVIrc" and copy & paste the details from the "Executable Information" tab below between ``` marks)  
[//]:# (Also Enter any OS information the "Executable Information" tab doesn't contain, e.g. KDE, Gentoo, Linux Mint, etc.)

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Windows Release : 10.0.15063
System version: Windows 10 (x64) (Build 15063)
Architecture: Intel64 Family 6 Model 23 Stepping 6
Qt version: 5.8.0
Qt theme: windowsvista

Build Info:
Build date: 2017-06-26 13:58:58 UTC
Sources date: 20170626
Revision number: git-7124-gd3d9de816
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.8.0
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Perl, Python, Enchant, Qt5, KVS
```
[//]:# (If you experienced crashes or segfaults please also include a stacktrace below, For how-to read: https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace.)

**Comment by IceN9ne** [comment]
To test if this is related to something else I've seen, could you move the KVIrc window to the other monitor (the left monitor), maximize the window (in the left monitor), then move it back to where it originally was (in the right monitor) and let me know if the issue persists?

**Comment by LeRaldo** [comment]
The issue persists after following your directions.

**Comment by LeRaldo** [comment]
qBittorrent just fixed an issue similar to this with a sub window in version 4.0.0 of their application. I don't know if this is of any use/help: 
https://github.com/qbittorrent/qBittorrent/pull/3858 
https://github.com/qbittorrent/qBittorrent/commit/7eaa5987c88eac05a2fdace62952cd9ec008070f
