### ISSUE TITLE
weird output when an active dcc fails from sourcehost or when aborting an active dcc

### ISSUE THREAD

**Issue by ltc-data** [kvirc/KVIrc#2245]
Im not sure what these values are printed ( **```r:i<1```** and **```w<0```** )or what they mean, it happens in several servers I have tried and from various people. Im not sure if it is a bug either, but would like to find out and if its a problem maybe someone can fix it?

### Expected behavior

Get someone to send you DCC that will fail to connect
```[06:33:37] *sourcehost* ** Closing Connection: Connection Lost```

Abort any active DCC
```[06:33:44] *sourcehost* ** Received: 576 kb - Closing Connection: Connection Lost (Broken pipe)```

### Actual behavior
Get someone to send you DCC that will fail to connect
```[06:33:37] *sourcehost* ** Closing Connection: Connection Lost r:i<1```

Abort any active DCC
```[06:33:44] *sourcehost* ** Received: 576 kb - Closing Connection: Connection Lost w<0 (Broken pipe)```

[//]:# (Besides the text description, include any screenshots that help us visualize the issue you're facing)

### System information
[//]:# (Type ```/about.kvirc``` or click "Help → About KVIrc" and copy & paste the details from the "Executable Information" tab below between ``` marks)  
[//]:# (Also Enter any OS information the "Executable Information" tab doesn't contain, e.g. KDE, Gentoo, Linux Mint, etc.)

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Windows Release : 6.1.7601
System version: Windows 7 Ultimate (x64) Service Pack 1 (Build 7601)
Architecture: Intel64 Family 6 Model 158 Stepping 9
Qt version: 5.8.0
Qt theme: 

Build Info:
Build date: 2017-07-09 07:45:06 UTC
Sources date: 20170709
Revision number: git-7129-g64f05096b
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.8.0
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Perl, Python, Enchant, Qt5, KVS
```
[//]:# (If you experienced crashes or segfaults please also include a stacktrace below, For how-to read: https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace.)

**Comment by ctrlaltca** [comment]
Are you sure that output is not created from a script? From a quick look I can't find any reference to those strings in the code.

**Comment by wodim** [comment]
That's a notice sent to you by a certain XDCC bot. Example: https://github.com/lformella/xdcc-grabscher/issues/62
