### ISSUE TITLE
Some pages in the built-in help lack word wrapping

### ISSUE THREAD

**Issue by darkred** [kvirc/KVIrc#2246]
Using KVirc 4.9.2 x64 (latest Git Nightly) in win10.

Currently, for some pages you have to constantly use the horizontal scrolling bar in order to read each text line.

[Screenshot of my 1920x1200 monitor](https://user-images.githubusercontent.com/723651/28285318-f964ea8a-6b3c-11e7-8cfc-7541ca5fc001.jpg)

So, my suggestion is to add [word wrapping](https://en.wikipedia.org/wiki/Line_wrap_and_word_wrap) to such pages in the built-in help.

**Comment by wodim** [comment]
This looks like a problem in that particular help page.

**Comment by darkred** [comment]
_(I edited the issue post)._
The pages linked in the [help index](https://user-images.githubusercontent.com/723651/28289487-7a2779a4-6b4b-11e7-8d19-f82e96bb7d62.jpg) that I found that lack word wrapping are the following :
(all from the `Scripting Concepts: The KVS Manual` group) :

- Basic KVS Concepts
- Aliases and Functions
- Variables
- Events
- Objects
- Addons 

(Maybe there are more pages inside help that lack word wrapping).

**Comment by IceN9ne** [comment]
Looks like it might be an issue with removing WebKit from the recent builds.  Might need to adjust the `QTextBrowser` a bit.

**Comment by ltc-data** [comment]
the [br] on that page on screenshot are all over the place and missing in many places. same goes for all other pages.

https://github.com/kvirc/KVIrc/blob/90e1ffeefb2405f71095dd3529b4c0ec2fe2b906/src/kvirc/kvs/parser/KviKvsParser.cpp#L304-L613

all it needs is adding [br] at sensible intervals.

**Comment by wodim** [comment]
No, we need to find another solution. We can't just change hundreds of pages.

**Comment by wodim** [comment]
I consider this fixed with e05d3393daf39f92e3f4a3e3757082d4753e8d2f, bff6c4d1d3b34e5c4c3fb83f9439b4427f75a363 and a8c8e0bd686ce3793c8a8584a056899886c1fbb5.

**Comment by ltc-data** [comment]
no wrap webview page no wrap.

broken in page examples.

widget class example
workspace class examples
eval page example
switch page examples
wrapper class page
Standard rebinding switch page

And probably more code example
