### ISSUE TITLE
The file types that KVIrc creates during installation (.kva, .kvc, .kvs, .kvt) have type names with chinese characters

### ISSUE THREAD

**Issue by darkred** [kvirc/KVIrc#2249]
Using KVIrc 4.9.2 x64 (latest Git Nightly) in win10.

I chose `English` language during installation.

After installation, the file types that KVIrc creates during installation `.kva, .kvc, .kvs, .kvt` have type names with chinese characters.

Such files are inside 'C:\Users\user\AppData\Roaming\KVIrc4' and 'C:\Program Files\KVIrc'.
Here is a [screenshot in File Explorer](https://user-images.githubusercontent.com/723651/28473790-c268a804-6e4e-11e7-98e0-3e87ac6f0aa1.jpg) inside the former, where I noticed this.

And, here is a screenshot from windows 'Settings | Apps | Default apps | Choose default apps by file name' :
![2017-07-21_192955](https://user-images.githubusercontent.com/723651/28473063-f0252ca2-6e4b-11e7-99ad-32ffd71772f7.jpg)
and an additional screenshot, from [NirSoft's FileTypeMan](http://www.nirsoft.net/utils/file_types_manager.html):
![2017-07-21_193014](https://user-images.githubusercontent.com/723651/28473084-0144bd9a-6e4c-11e7-8f47-edc75e9fed86.jpg)

**Comment by wodim** [comment]
My fault

**Comment by wodim** [comment]
See if it's alright now. It should remove the old associations and add a few new ones.

**Comment by darkred** [comment]
Yes, it's alright. Thank you
