### ISSUE TITLE
Garbage being added to exported classes function when none added to parameter reminders.

### ISSUE THREAD

**Issue by the-j0k3r** [kvirc/KVIrc#2281]
### Expected behavior
Ide expct no quotes or single quotes only example of expected below is quoteless ;)
```c++
class("somename::setup","widget")
{
	function saveSetUp()
	{
		some code here
	}

	function loadSetUp()
	{
		some code here
	}

	function destructor()
	{
		some code here
	}

	function constructor()
	{
		some code here
	}
}

class("somenale::something","object")
{
	function closePMWin($0 = nick)
	{
		some code here
	}
}

class("somename::main","widget")
{
	function saveList($0 = flag)
	{
		some code here
	}

	function loadList()
	{
		some code here
	}

	function destructor()
	{
		some code here
	}

	function constructor()
	{
		some code here
	}

	function somename($0 = nick)
	{
		some code here
	}
}
```

### Actual behavior
```c++
class("somename::setup","widget")
{
	function saveSetUp("\"\"")
	{
		some code here
	}

	function loadSetUp("\"\"")
	{
		some code here
	}

	function destructor("\"\"")
	{
		some code here
	}

	function constructor("\"\"")
	{
		some code here
	}
}

class("somenale::something","object")
{
	function closePMWin("\"\\\"\\\\\\\$0 = nick\\\"\"")
	{
		some code here
	}
}

class("somename::main","widget")
{
	function saveList("\"\\\$0 = flag\"")
	{
		some code here
	}

	function loadList("\"\"")
	{
		some code here
	}

	function destructor("\"\"")
	{
		some code here
	}

	function constructor("\"\"")
	{
		some code here
	}

	function somename("\"\\\$0 = nick\"")
	{
		some code here
	}
}
```

[//]:# (Besides the text description, include any screenshots that help us visualize the issue you're facing)

### Steps to reproduce the issue
1. import the clean classes file ([download from here](https://gist.github.com/the-j0k3r/85bb43513bd36342cf269414ddb9be93/archive/83e07e3223ced26f884462e6bb99816e35cf08f4.zip)
2. open classes editor look around the treeview 
3. make some changes (optional)
4. export for sharing testing etc and see garbage added.

Notes: apparently it doesnt happen Linux side but the person testing has some much older version of KVIrc that way. And Ive lacked time to test it myself.

### System information
[//]:# (Type ```/about.kvirc``` or click "Help → About KVIrc" and copy & paste the details from the "Executable Information" tab below between ``` marks)  
[//]:# (Also Enter any OS information the "Executable Information" tab doesn't contain, e.g. KDE, Gentoo, Linux Mint, etc.)

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Windows Release : 6.1.7601
System version: Windows 7 Ultimate (x64) Service Pack 1 (Build 7601)
Architecture: Intel64 Family 6 Model 158 Stepping 9
Qt version: 5.8.0
Qt theme: Windows

Build Info:
Build date: 2017-08-27 22:38:01 UTC
Sources date: 20170827
Revision number: git-7161-gc3dc09c62
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.8.0
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Perl, Python, Enchant, Qt5, KVS
```
[//]:# (If you experienced crashes or segfaults please also include a stacktrace below, For how-to read: https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace.)

**Comment by the-j0k3r** [comment]
below this comes for the class editor Installer that is shipped with KVirc by default.

I can do that everytime I use KVIrc, but after closing KVIrc down and re-opening the garbage is back
and if I clean and export the garbage is back.

![bummed](https://user-images.githubusercontent.com/31389848/29784601-80b874a2-8c1c-11e7-8cd8-ad9c0f611eeb.gif)

![bummed fixingineditor](https://user-images.githubusercontent.com/31389848/29784602-80ba59e8-8c1c-11e7-942a-e8108d4321a4.gif)

**Comment by the-j0k3r** [comment]
todays export 

```
class("somename::setup","widget")
{
	function saveSetUp("\"\\\"\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\"\\\"\"")
	{
		somecode
	}
	
	function loadSetUp("\"\\\"\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\"\\\"\"")
	{
		somecode
	}
	
	function destructor("\"\\\"\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\"\\\"\"")
	{
		somecode
	}
	
	function constructor("\"\\\"\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\"\\\"\"")
	{
		somecode
	}
}

class("somename::somename","object")
{
	function closePMWin("\"\\\"\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\$0 = nick\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\"\\\"\"")
	{
	{
		somecode
	}
	}
	
}

class("somename::main","widget")
{
	function saveList("\"\\\"\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\$0 = flag\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\"\\\"\"")
	{
	{
		somecode
	}
	}
	
	function loadList("\"\\\"\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\"\\\"\"")
	{
		somecode
	}
	
	function destructor("\"\\\"\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\"\\\"\"")
	{
		somecode
	}
	
	function constructor("\"\\\"\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\"\\\"\"")
	{
		somecode
	}	
	
	function somename("\"\\\"\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\$0 = nick\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\"\\\"\"")
	{
		somecode
	}
}
```

**Comment by ltc-data** [comment]
Just had a look at the classes installer class, it is full of those slashes too

**Comment by the-j0k3r** [comment]
@positr0nic thanks, ill try to test this in a Linux box.

**Comment by IceN9ne** [comment]
So, there was an issue opened for an issue of parentheses failing in reminder text #2211. There was a patch that was applied as an attempted fix to just escape everything in the reminder text.  Unfortunately, this didn't fix the original issue as it still fails to build with a closing `)` in the text.

If you look into the KVS parser, when it gets to the reminder text, it just blindly grabs everything after the opening `(` and puts everything up to the `)` into the reminder text `QString` without doing any analysis on what is in it (so you can't do any KVS tricks like variable expansion, etc).

This is why the original patch caused this issue.

I've debated on how to address this issue.  We can either revert the previous patch, or attempt to change the parser.  The question is... "How do we change the parser without breaking all existing classes?"

We could check if the first character after the `(` is a `"` and do a string parsing up to the closing `"`, but we would have to take into account escaped `"` within the `"` so we don't close it too early.  I can't find an existing function in the parser that will let us do this (and where it doesn't do variable expansion because we have `$0 = stuff` inside reminder text).

So, we'll probably have to build our own parser extension to de-escape the quoted text as we read it.

**Comment by wodim** [comment]
Can't you grab everything from `(` up to the last `)` of the line? The reminder text should not do variable expansion or anything fancy after all, it's just a string.

Or even better, from `(` up to the last `)` that is before a `{`.

**Comment by IceN9ne** [comment]
No, because the `)` doesn't have to be the last character in the line.

**Comment by wodim** [comment]
>Or even better, from `(` up to the last `)` that is before a `{`.

**Comment by the-j0k3r** [comment]
Tested this in Linux, the installer.kvs was 100% clean,  when exporting it added a single `\"` windows adds two `"\"\`

Windows the installer classes, after importing a clean one, and checking theres nothing added, the act of restarting kvirc adds two ```"\"\```
Linux does same.

both tests with git-7176-g9defac5

**Comment by the-j0k3r** [comment]
Theres an issue with single slashes in paths in Windows with custom icons in popup entries. The slash is stripped when parsed for reading.

```popup.addExtPopup querytextview popupname "Menu Entry" $file.localdir("pics/icon_small.png") popupnames```

In linux that adds OK to the popup icon field

```home /username/.config/KVIrc/pics/icon_small.png```

but in Windows it adds as 

```E:\Portable\KVIrc\Settings\pics\icon_small.png``` the issue is that when bringing up the popup it shows a warning,

```[21:32:33] Can't find the icon 'E:PortableKVIrcSettingspicsicon_small.png': ignoring```

manually adding a second slash to the icon entry in popups like ```E:\\Portable\\KVIrc\\Settings\\pics\\icon_small.png``` makes the issue go away.

I would like to know if that is related to this problem reported here or is another problem entirely.

**Comment by IceN9ne** [comment]
Different issue entirely.  The one you just stated is that it needs to be escaped.

This issue is entirely due to the funky way parsing is done specifically for the reminder text, as it goes against the normal KVS parsing routine.

**Comment by the-j0k3r** [comment]
Ill open a separate issue for that last one then.

**Comment by the-j0k3r** [comment]
this revert https://github.com/kvirc/KVIrc/commit/e7e2f4048920ca2da10ccb5c1b00781fcd895d39 seems to have made this issue go away.

**Comment by ltc-data** [comment]
well i dont know whats going on but when I exported the popups today I got this rubbish slashes everywhere. This did not happen before.

but the classes I can confirm are now clean. crazy!

```
defpopup(ctcp)
{
	item(PING, \$icon\(\"serverping\"\))
	{
		ctcp $0 PING
		echo -w=$active -i=$msgtype(GenericStatus) $tr("Sent CTCP PING to","defscript") $b$0$b
	}

	item(FINGER,\$icon\(\"finger\"\))
	{
		ctcp $0 FINGER
		echo -w=$active -i=$msgtype(GenericStatus) $tr("Sent CTCP FINGER to","defscript") $b$0$b
	}

	item(VERSION,\$icon\(\"kvirc\"\))
	{
		ctcp $0 VERSION
		echo -w=$active -i=$msgtype(GenericStatus) $tr("Sent CTCP VERSION to","defscript") $b$0$b
	}

	item(USERINFO,\$icon\(\"user\"\))
	{
		ctcp $0 USERINFO
		echo -w=$active -i=$msgtype(GenericStatus) $tr("Sent CTCP USERINFO to","defscript") $b$0$b
	}

	item(CLIENTINFO,\$icon\(\"serverinfo\"\))
	{
		ctcp $0 CLIENTINFO
		echo -w=$active -i=$msgtype(GenericStatus) $tr("Sent CTCP CLIENTINFO to","defscript") $b$0$b
	}

	item(SOURCE,\$icon\(\"ctcprequestunknown\"\))
	{
		ctcp $0 SOURCE
		echo -w=$active -i=$msgtype(GenericStatus) $tr("Sent CTCP SOURCE to","defscript") $b$0$b
	}

	item(TIME,\$icon\(\"time\"\))
	{
		ctcp $0 TIME
		echo -w=$active -i=$msgtype(GenericStatus) $tr("Sent CTCP TIME to","defscript") $b$0$b
	}

	item(PAGE...,\$icon\(\"messages\"\))
	{
		#dialog.textinput -d=$tr("Wakeup!","defscript") ($tr("CTCP Page to","defscript") $0,$tr("Enter the message text","defscript"),$tr("OK","defscript"),$tr("Cancel","defscript"))
		dialog.textinput(CTCP Page $0,$tr("Enter the message text","defscript"),$tr("&Page","defscript"),$tr("&Cancel","defscript"),"",$0)
		{
			if($0 == 0)
				ctcp $2 PAGE $1
			echo -w=$active -i=$msgtype(GenericStatus) $tr("Sent CTCP PAGE to","defscript") $b$2$b
		}
	}

	item(AVATAR,\$icon\(\"avatar\"\))
	{
		ctcp $0 AVATAR
		echo -w=$active -i=$msgtype(GenericStatus) $tr("Sent CTCP AVATAR to","defscript") $b$0$b
	}
}
```

**Comment by pragmaware** [comment]
I can't reproduce this with the latest git.
Also the escaped icon code in popups is correct.
