### ISSUE TITLE
reguser.add <nickname> $mask(<nickname>) makes kvirc die

### ISSUE THREAD

**Issue by ltc-data** [kvirc/KVIrc#2289]
### Expected behavior
just adds user to registered users

### Actual behavior
kvirc dies

There is no debug info it just dies

there is a terminal up for debug build but just says 
`
** (kvirc.exe:8156): CRITICAL **: enchant_broker_request_dict: assertion 'tag && strlen(tag)' failed
Can't load spellchecker dictionary :
`

[//]:# (Besides the text description, include any screenshots that help us visualize the issue you're facing)

### Steps to reproduce the issue
1. type /reguser.add <nickname> $mask(<nickname>)

### System information
[//]:# (Type ```/about.kvirc``` or click "Help → About KVIrc" and copy & paste the details from the "Executable Information" tab below between ``` marks)  
[//]:# (Also Enter any OS information the "Executable Information" tab doesn't contain, e.g. KDE, Gentoo, Linux Mint, etc.)

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Windows Release : 10.0.14393
System version: Windows 10 Enterprise (x64) (Build 14393)
Architecture: Intel64 Family 6 Model 158 Stepping 9
Qt version: 5.8.0
Qt theme: 

Build Info:
Build date: 2017-08-30 01:14:53 UTC
Sources date: 20170829
Revision number: git-7173-gd09814dd9
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.8.0
Features: IRC, Debug, IPv6, Crypt, SSL, IPC, Transparency, Perl, Python, Enchant, Qt5, KVS
```
[//]:# (If you experienced crashes or segfaults please also include a stacktrace below, For how-to read: https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace.)

**Comment by ltc-data** [comment]
should have added code brackets ``` to the command.

### Steps to reproduce the issue
1. type ```/reguser.add <nickname> $mask(<nickname>)```

**Comment by ltc-data** [comment]
thx

**Comment by the-j0k3r** [comment]
I came across this a while back too, thank you for the fix.
