### ISSUE TITLE
Broken css in Qt or something else

### ISSUE THREAD

**Issue by the-j0k3r** [kvirc/KVIrc#2292]
I have been helping out and testing a kvirc addon, while writing some help file and fit to kvirc help style I noticed that the ```border-top-left-radius:``` and  ```border-top-right-radius: ``` doesnt seem to work anymore.

Looking at screengrabs I see the white shadow is also broken in KVIrc.

Looking at the internal help file HTML and it seems its broken too. is this because of recent changes in kvirc docs or is it Qt?

### Expected behavior
```border-top-left-radius:``` +  ```border-top-right-radius: ```  + ```text-shadow:``` to work and probably other css to work

![works-in browser](https://user-images.githubusercontent.com/31389848/29927914-9a029e34-8e5f-11e7-8ab5-7ed62d02f508.PNG)

### Actual behavior
seems much of css is broken everywhere. except normal browser.

![broken](https://user-images.githubusercontent.com/31389848/29927925-a1481084-8e5f-11e7-9c94-43722d859010.PNG)

[//]:# (Besides the text description, include any screenshots that help us visualize the issue you're facing)

### Steps to reproduce the issue
1. load a internal kvirc help file in kvirc help browser ```$action.exists```
2. load the same html file in your preferred browser, like Google Chrome ```/KVIrc/help/en/fnc_action.exists.html```

### System information
[//]:# (Type ```/about.kvirc``` or click "Help → About KVIrc" and copy & paste the details from the "Executable Information" tab below between ``` marks)  
[//]:# (Also Enter any OS information the "Executable Information" tab doesn't contain, e.g. KDE, Gentoo, Linux Mint, etc.)

```

```
[//]:# (If you experienced crashes or segfaults please also include a stacktrace below, For how-to read: https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace.)

**Comment by wodim** [comment]
While the situation with QWebKit is solved (#1854 etc) we are using a QTextBrowser instead of an embedded webkit view to display the help. Unfortunately QTextBrowser is barebones and buggy, which is why I've had to make lots of modifications to the docs to make some things, like word wrapping, work again.

`border-radius` is not supported on QTextBrowser.

**Comment by the-j0k3r** [comment]
No problem, wasn't aware. Thanks.
