### ISSUE TITLE
Addon saving: arg(m_szSavePath) is not shown in dialog

### ISSUE THREAD

**Issue by the-j0k3r** [kvirc/KVIrc#2293]
bug line https://github.com/kvirc/KVIrc/blob/f8f50bd6a787fdae7ce03cc36f97068399700d66/src/modules/addon/PackAddonDialog.cpp#L185

### Expected behavior
```The Package was saved successfully in C:\path\directory\cherryontop```

### Actual behavior

[//]:# (Besides the text description, include any screenshots that help us visualize the issue you're facing)

### Steps to reproduce the issue
1. create a kva package via addon manage addons ```ctrl+shift+n```

### System information
[//]:# (Type ```/about.kvirc``` or click "Help → About KVIrc" and copy & paste the details from the "Executable Information" tab below between ``` marks)  
[//]:# (Also Enter any OS information the "Executable Information" tab doesn't contain, e.g. KDE, Gentoo, Linux Mint, etc.)

```
Revision number: git-7181-g692d10d9d
```
[//]:# (If you experienced crashes or segfaults please also include a stacktrace below, For how-to read: https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace.)

**Comment by ltc-data** [comment]
You told me to report this now you did it? make up your mind

**Comment by the-j0k3r** [comment]
Relax I had a minute :) Im duplicating issue myself, btw positronic, we're looking into the other issue with the custom icon paths in popups since its stripping the single slash. no need to report that until we know what to report.

thanks for your help.

**Comment by the-j0k3r** [comment]
confirmed in both Win and Lnux

I had to double check since the icon path slashes are being stripped in Windows but not linux (the other issue)

![win](https://user-images.githubusercontent.com/31389848/29949186-edc79bc8-8eaa-11e7-919b-fc07cc01e869.PNG)

![linux](https://user-images.githubusercontent.com/31389848/29949187-edc8eef6-8eaa-11e7-9383-882367eedeb0.PNG)
