### ISSUE TITLE
Windows: Path to custom icon popup entry with single slash OK until context menu called.

### ISSUE THREAD

**Issue by the-j0k3r** [kvirc/KVIrc#2295]
theres an issue with single slashes in paths in Windows with custom icons in popup entries. The slash is stripped when you trigger the popup

so the act of calling the context menu is the issue?

e.g.
```popup.addExtPopup querytextview popupname "Menu Entry" $file.localdir("pics/icon_small.png") popupnames```

In linux that adds OK to the popup icon field

home /username/.config/KVIrc/pics/icon_small.png

but in Windows it adds as

E:\Portable\KVIrc\Settings\pics\icon_small.png the issue is that when bringing up the popup it shows a warning,

#### It is important to make the stressed point that if you open the popup editor the image is shown just fine with the path containing a single slash, the slash is stripped only when you call the relevant context menu in that case **querytextview**

manually adding a second slash to the icon entry ipath in popups like E:\\Portable\\KVIrc\\Settings\\pics\\icon_small.png makes the issue go away. but you cant insert it automatically.

even 

```
popup.addExtPopup querytextview popupname  "Menu Item Label" $file.fixpath($file.localdir("//pics//icon_small.png")) popupname
```

[21:32:33] Can't find the icon 'E:PortableKVIrcSettingspicsicon_small.png': ignoring
```
### Expected behavior
this to work without fuss?

### Actual behavior
[21:32:33] Can't find the icon 'E:PortableKVIrcSettingspicsicon_small.png': ignoring

[//]:# (Besides the text description, include any screenshots that help us visualize the issue you're facing)

### Steps to reproduce the issue
1. as above
2.
3.

### System information
[//]:# (Type ```/about.kvirc``` or click "Help → About KVIrc" and copy & paste the details from the "Executable Information" tab below between ``` marks)  
[//]:# (Also Enter any OS information the "Executable Information" tab doesn't contain, e.g. KDE, Gentoo, Linux Mint, etc.)

```

```
[//]:# (If you experienced crashes or segfaults please also include a stacktrace below, For how-to read: https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace.)

**Comment by the-j0k3r** [comment]
Thanks, will test asap and have alerted the parties concerned to this update. Once again  thanks.

**Comment by the-j0k3r** [comment]
Im sorry but its still broken.

So I run this..

```popup.addExtPopup channeltextview somepop.name "Menu Entry" $file.localdir(pics/icon_small.png) somepop.name```

Result.
![capture](https://user-images.githubusercontent.com/31389848/30002847-25d99a5a-90ab-11e7-87b1-33b474f843f1.PNG)
So as you can see, the single slash is OK here, the icon shows fine on editor.

BUT: Then on ANY Channel I call the context menu...

Result
```[12:19:26] Can't find the icon 'C:PortableKVIrcSettingspicspmmanager_small.png': ignoring```

So the act of calling the popup/displaying the context menu, strips the single slash which results in a context menu entry without the icon. AND thats the issue here.

EDIT  + context menu screenshot.
![capture](https://user-images.githubusercontent.com/31389848/30002933-966d6402-90ad-11e7-9f75-50d8f9c3e04a.PNG)


```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Windows Release : 6.1.7601
System version: Windows 7 Ultimate (x64) Service Pack 1 (Build 7601)
Architecture: Intel64 Family 6 Model 42 Stepping 7
Qt version: 5.8.0
Qt theme: windowsvista

Build Info:
Build date: 2017-09-03 00:12:14 UTC
Sources date: 20170902
Revision number: git-7185-g20efc5d86
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.8.0
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Perl, Python, Enchant, Qt5, KVS
```

**Comment by wodim** [comment]
Does it work if you add the icon with the popup editor instead of using `popup.addExtPopup`?

**Comment by the-j0k3r** [comment]
I dont understand that question exactly.

If I create the entry manually IT ONLY WORKS if I add double slashes to path.

![capture](https://user-images.githubusercontent.com/31389848/30005691-06f49bfa-90e0-11e7-8d48-6dd48758acb8.PNG)

```popup.addExtPopup``` doesnt allow (normally without hacking around the bug)  adding double slashes via ```$file.localdir(pics/icon_small.png)``` that is interpreted as single slashes and works fine for all other images everywhere except here.

What I dont understand is ALL other images in addon manager, help images etc are all fine with single slashes. WHY does the slash get stripped from path when calling the context menu only?

**Comment by wodim** [comment]
Not a bug: use `$escape` around the file name.

**Comment by the-j0k3r** [comment]
Where is this method documented?

**Comment by wodim** [comment]
While it's true that no mention of `$escape` is made in the documentation page of `popup.addExtPopup`, it's obvious that it's necessary to use it, since whatever is written in the icon field of a popup is executed as a KVS script. And backslashes in KVS scripts must be escaped.

![image](https://user-images.githubusercontent.com/1001553/30005839-970d4aec-90eb-11e7-8f10-a9864a9b171f.png)

**Comment by the-j0k3r** [comment]
can you give an example pls.

**Comment by wodim** [comment]
popup.addExtPopup querytextview popupname "Menu Entry" $escape($file.localdir("pics/icon_small.png")) popupnames

**Comment by the-j0k3r** [comment]
Thats weird, doesnt KVS automatically handle OS path translation?

**Comment by wodim** [comment]
The fourth parameter of `popup.addExtPopup` is added, as it is, to the "icon" field of that menu entry. But that icon field is later also interpreted by the KVS parser. For example, all icons in the default popups are KVS scripts, like `$icon("kick")`. Those functions return a number, and KVIrc loads the icon with that number. 

If you add a Windows path to the icon field of a popup menu, that will also be parsed by the KVS parser, which won't find the file because all the backslashes are removed.

In your example, you have `$file.localdir("pics/icon_small.png")`. That is parsed immediately and added as `C:\Users\User\AppData\Roaming\KVIrc4\pics\icon_small.png`, which breaks.

An option is to use `$escape($file.localdir("pics/icon_small.png"))`. That means `C:\\Users\\User\\AppData\\Roaming\\KVIrc4\\pics\\icon_small.png` is added, which doesn't break.

Yet another option would be to use `\$file.localdir("pics/icon_small.png")`, escaping the first `$`, which would mean `$file.localdir("pics/icon_small.png")` would be written into the icon field, which when interpreted would yield the correct path (I haven't tried it though but it should work).

**Comment by the-j0k3r** [comment]
We did this as a workaround, clearly some docs are in need. No other addons (I could find) in scripts repo do any of these things you mention (or I missed it).

Option 3
```
if($system.ostype != "UNIX")
{
	%ticon = $file.localdir(\pics\\icon_small.png)
	%ficon = $str.replace(%ticon, $char(92), $char(92)$char(92), 1)
	popup.addExtPopup querytextview popupname  "Menu Entry" %ficon QUPM.popupname
}
else
{
	popup.addExtPopup querytextview popupname  "Menu Entry" $file.localdir(pics/icon_small.png) popupname
}

**Comment by wodim** [comment]
You don't need to check what the OS is. Either of the options I gave you (`$escape` or escaping the first `$` with `\`) will work on Linux and Windows. And I agree the docs should mention it but they don't. Maybe you'd like to send a pull request? :)

**Comment by the-j0k3r** [comment]
Linux doesnt need anything, it just works, hence why for Linux we din nothing special and for lack of examples or docs it was some ugly hack around this issue.

**Comment by wodim** [comment]
`/` is not a special character for KVS, but `\` is. So on Linux it works without using `$escape`, but that doesn't mean it's right, because having other special characters in that path would make it crash on Linux too. You are supposed to simply use `$escape`.

**Comment by the-j0k3r** [comment]
> Yet another option would be to use \$file.localdir("pics/icon_small.png"), escaping the first $, which would mean $file.localdir("pics/icon_small.png") would be written into the icon field, which when interpreted would yield the correct path (I haven't tried it though but it should work).

```\$file.localdir("pics/icon_small.png")``` works but its ugly and breaks showing the icon in editor,

**Comment by wodim** [comment]
Then use `$escape` :)
