### ISSUE TITLE
New script tester Improvemnet  suggestion

### ISSUE THREAD

**Issue by the-j0k3r** [kvirc/KVIrc#2296]
in normal usage you type at input line at bottom and output is displayed above and also KVIrc has a vertical splitview rather than horizontal.

Its a more natural and expected vertically oriented layout.

### Expected behavior
The script tester output ircview to be displayed above the script tester.

### Actual behavior
The script tester output ircview is displayed to right side of the script tester.

[//]:# (Besides the text description, include any screenshots that help us visualize the issue you're facing)

### System information
[//]:# (Type ```/about.kvirc``` or click "Help → About KVIrc" and copy & paste the details from the "Executable Information" tab below between ``` marks)  
[//]:# (Also Enter any OS information the "Executable Information" tab doesn't contain, e.g. KDE, Gentoo, Linux Mint, etc.)

```

```
[//]:# (If you experienced crashes or segfaults please also include a stacktrace below, For how-to read: https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace.)

**Comment by wodim** [comment]
-1

**Comment by the-j0k3r** [comment]
it feels weird seeing on the side when everything else is up or down.

since everyone hated my suggestion Ill close it then and get used to a unfamiliar layout.

**Comment by wodim** [comment]
I think it's a complete waste of space to have two windows stacked horizontally now that everybody has wide screens.

**Comment by the-j0k3r** [comment]
1080p is hardly wide,

also when you are testing a script with long code that outputs longer strings, eventually youre wrapping contents in either one or the other or both.

**Comment by the-j0k3r** [comment]
maybe If it were possible to drag the editor up or down or sideways this would allow for both ppl that have 4k screen and eagle eyes for tiny text and to ppl that still are 1080p or less.

**Comment by the-j0k3r** [comment]
![capture](https://user-images.githubusercontent.com/31389848/30031031-bb480c52-9187-11e7-94bd-97ed560a96f3.PNG)

to avoid output wrapping, the code section gains a lovely scrollbar.
