### ISSUE TITLE
The IrcView can't handle DPI changes

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#2302]
If you have Windows with two monitors with different DPI values and you move the KVIrc window from one monitor to the other, the IrcView gets messed up.

From high DPI to normal DPI:

![image](https://user-images.githubusercontent.com/1001553/30153267-57952f56-93b6-11e7-8cc9-4570044fdf74.png)

From normal DPI to high DPI:

![image](https://user-images.githubusercontent.com/1001553/30153336-8747e554-93b6-11e7-94fe-b5fb98127ecc.png)

The problem solves itself if you change the font size. So I guess we should detect when the DPI value has changed, and do something to repaint the IrcView or whatever.

**Comment by ctrlaltca** [comment]
It should be enough to bind on [QWindow::screenChanged()](http://doc.qt.io/qt-5/qwindow.html#screenChanged) and force a repaint

**Comment by pragmaware** [comment]
See a575f61. Reopen if the issue still persists.
