### ISSUE TITLE
cmake errors with -DWANT_STRIP=TRUE

### ISSUE THREAD

**Issue by ghost** [kvirc/KVIrc#2306]
I'm getting a lot of errors with cmake:
https://gist.github.com/muthaber/1c1a5879572ba61b24509eb92ecd56af
It happens when I add: **-DWANT_STRIP=TRUE**
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.12.0-1-amd64
System version: #1 SMP Debian 4.12.6-1 (2017-08-12)
Architecture: x86_64
Qt version: 5.9.1
Qt theme: breeze
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
cmake version 3.9.0

**Comment by ctrlaltca** [comment]
Problem introduced in https://github.com/kvirc/KVIrc/commit/5db1c7a8e8ed1d36da661b2ed92e3663320b590e
Cmake's CMP0026 policy has been removed to fix Appveyor, but involved code has not been adapted to the policy removal.
The policy is relative to the use of the LOCATION target property: https://cmake.org/cmake/help/v3.0/policy/CMP0026.html

Removing the policy breaks both the WANT_STRIP compilation option and the deployment of Qt plugins in OSX builds.

**Comment by Dessa** [comment]
the former can be probably be fixed by forcing MinSizeRel config on people who want WANT_STRIP, the latter i have no idea and i'll need to look into it.
for mac, can't we tell people to use macdeployqt? (bear in mind that i have *no* idea about OSX... :) )
