### ISSUE TITLE
Option fontUserListView not respected

### ISSUE THREAD

**Issue by SM0TVI** [kvirc/KVIrc#2307]
### Expected behavior

That the font family and size settings in Settings->Configure Theme->Userlist->Foreground is reflected in the actual user list.

### Actual behavior

Isn't.

[//]:# (Besides the text description, include any screenshots that help us visualize the issue you're facing)

### Steps to reproduce the issue
1.
2.
3.

### System information
[//]:# (Type ```/about.kvirc``` or click "Help → About KVIrc" and copy & paste the details from the "Executable Information" tab below between ``` marks)  
[//]:# (Also Enter any OS information the "Executable Information" tab doesn't contain, e.g. KDE, Gentoo, Linux Mint, etc.)
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 3.16.0-4-amd64
System version: #1 SMP Debian 3.16.43-2+deb8u3 (2017-08-15)
Architecture: x86_64
Qt version: 5.3.2
Qt theme: windows

Build Info:
Build date: 2017-09-08 15:27:52 UTC
Sources date: 20160102
Revision number: git-7189-ge7e2f4048
System name: Linux-4.9.0-3-amd64
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 
Qt version: 5.3.2
Features: IRC, Debug, IPv6, Crypt, SSL, IfAddr, IPC, Transparency, Phonon, Webkit, DCCVoice, Perl, Python, Enchant, Qt5, KVS
```

```
[//]:# (If you experienced crashes or segfaults please also include a stacktrace below, For how-to read: https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace.)
![kvircbug1](https://user-images.githubusercontent.com/20062844/30364030-c5ae01a6-9862-11e7-9a45-fe9d7a56a8aa.png)
![kvircbug2](https://user-images.githubusercontent.com/20062844/30364097-113fa2f0-9863-11e7-8ded-bca8c5c71009.png)

**Comment by wodim** [comment]
This was broken at some point in the last months.

**Comment by DarthGandalf** [comment]
There is one line which is affected by the setting: the header, e.g. `[108] b:1`

**Comment by IceN9ne** [comment]
This was broken when style.css was fixed.  When a stylesheet is loaded, it affects things that use the QPalette.

Renaming the style.css file so that it isn't loaded fixes the issue.
