### ISSUE TITLE
UnrealIRCd-4.0.14 user modes

### ISSUE THREAD

**Issue by NicklaTome** [kvirc/KVIrc#2309]
hi, we upgrade server on nets some days now, this missing in modes.

### Expected behavior
https://www.unrealircd.org/docs/User_modes

### Actual behavior
D: : Unknown user mode
Z: : Unknown user mode

[//]:# (Besides the text description, include any screenshots that help us visualize the issue you're facing)

### Steps to reproduce the issue
1.
2.
3.

### System information
[//]:# (Type ```/about.kvirc``` or click "Help → About KVIrc" and copy & paste the details from the "Executable Information" tab below between ``` marks)  
[//]:# (Also Enter any OS information the "Executable Information" tab doesn't contain, e.g. KDE, Gentoo, Linux Mint, etc.)

```

```
[//]:# (If you experienced crashes or segfaults please also include a stacktrace below, For how-to read: https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace.)

**Comment by staticfox** [comment]
Should be good now

**Comment by NicklaTome** [comment]
works good, much thanks.
