### ISSUE TITLE
Double clicking #channel links with control codes joins the wrong channel

### ISSUE THREAD

**Issue by LeRaldo** [kvirc/KVIrc#2313]
### Expected behavior
Double clicking a #channel link (such as in a channel message or topic) joins that channel regardless of control codes used

### Actual behavior
If the #channel has control codes in it, such as to change the color or make it bold, like "2#channel", KVIrc might try to join something like 2#channel instead of #channel (depending on the network). On Rizon, it won't even let you join the channel due to "illegal channel name".

### Steps to reproduce the issue
1. Say text "2#channel" in a channel
2. Double click the "2#channel" link
3. KVIrc tries to join "2#channel" instead of "#channel"

### System information
[//]:# (Type ```/about.kvirc``` or click "Help → About KVIrc" and copy & paste the details from the "Executable Information" tab below between ``` marks)  
[//]:# (Also Enter any OS information the "Executable Information" tab doesn't contain, e.g. KDE, Gentoo, Linux Mint, etc.)

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Windows Release : 10.0.15063
System version: Windows 10 (x64) (Build 15063)
Architecture: Intel64 Family 6 Model 23 Stepping 6
Qt version: 5.8.0
Qt theme: windowsvista

Build Info:
Build date: 2017-06-26 13:58:58 UTC
Sources date: 20170626
Revision number: git-7124-gd3d9de816
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.8.0
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Perl, Python, Enchant, Qt5, KVS
```
[//]:# (If you experienced crashes or segfaults please also include a stacktrace below, For how-to read: https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace.)

**Comment by IceN9ne** [comment]
You're using an old version of KVIrc.  This was fixed in 3ea9f85.
