### ISSUE TITLE
Userlist font size does not increase, only the line height

### ISSUE THREAD

**Issue by Heufneutje** [kvirc/KVIrc#2314]
### Expected behavior

The font size actually increasing.

### Actual behavior

Only the line height changes. Might have something to do with my high DPI settings on Windows 10?

![image](https://user-images.githubusercontent.com/1357231/31052884-6871da3a-a690-11e7-9333-aba2fb1861be.png)

[//]:# (Besides the text description, include any screenshots that help us visualize the issue you're facing)

### Steps to reproduce the issue
1. Go into the userlist foreground options in the theme settings.
2. Increase the font size.

### System information
[//]:# (Type ```/about.kvirc``` or click "Help → About KVIrc" and copy & paste the details from the "Executable Information" tab below between ``` marks)  
[//]:# (Also Enter any OS information the "Executable Information" tab doesn't contain, e.g. KDE, Gentoo, Linux Mint, etc.)

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Windows Release : 10.0.15063
System version: Windows 10 Professional (x64) (Build 15063)
Architecture: Intel64 Family 6 Model 78 Stepping 3
Qt version: 5.8.0
Qt theme: windowsvista

Build Info:
Build date: 2017-09-28 20:51:14 UTC
Sources date: 20170928
Revision number: git-7202-g0f6968307
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.8.0
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Perl, Python, Enchant, Qt5, KVS
```
[//]:# (If you experienced crashes or segfaults please also include a stacktrace below, For how-to read: https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace.)

**Comment by wodim** [comment]
#2307

**Comment by Heufneutje** [comment]
Whoops. I missed that.
