### ISSUE TITLE
big font wont save problems because automatic style.css loadings

### ISSUE THREAD

**Issue by NicklaTome** [kvirc/KVIrc#2318]
Is this a bug report?
==============================
Describe what the problem is. Attach screenshots if you feel like they will help explain the issue better.
If you can, click "Help → About KVIrc", go to the "Executable Information" tab and copy its contents here. That may help us diagnose the issue.
If you're experiencing a crash and you think we might not be able to reproduce it for some reason, a backtrace will be helpful: https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace

Is this a feature request?
==============================
Describe what you'd like to see implemented, and why you think it's a good idea.

Thank you for helping us improve KVIrc!

==============================
Sorry for English is not so good. I try.

I founds 1 bugs in windows KVIrc-4.9.2-dev-git-7206-g4bbda1e58-x86_64.exe
 
My brothers Afredo installs new machine for testings, because kvirc is returns general aplication fonts size to very small size, we try put big size.
My brother Alfredo looks also at this problems and after much hours we finds is problem the css inside file `/config/style.css`.   

If we makes empty file by removings..   
 `/* Make text in message boxes selectable. */
QMessageBox {
    /* LinksAccessibleByMouse | TextSelectableByMouse */
    messagebox-text-interaction-flags: 5;
}
`
Problems is go away. We try, write any css inside for test, all is same problems.  

We reads bugs logs on Github about kvirc and finds Qt loads `kvirc.exe -stylesheet=style.css`, we finds in this problems also goes away with css like normal when we does this. So problems is only in normal  `/config/style.css` automatic loads,

We makes small video

<embed width="440" height="420" type="application/x-shockwave-flash" src="http://v9.tinypic.com/player.swf?file=10xy8uh&s=9"><br><font size="1"><a href="http://tinypic.com/player.php?v=10xy8uh&s=9">Original Video</a> - More videos at <a href="http://tinypic.com">TinyPic</a></font>

downloads video [fontbugs.zip](https://github.com/kvirc/KVIrc/files/1367000/fontbugs.zip)

**Comment by wodim** [comment]
This was fixed.
