### ISSUE TITLE
TextIcons don't work because of unprinted symbol

### ISSUE THREAD

**Issue by Silergo** [kvirc/KVIrc#2319]
When you type text that should convert to image it won't work, because kvirc waiting that you print symbol  before the text. Here the image of what I mean https://i.imgur.com/cZQiI4w.jpg

**Comment by IceN9ne** [comment]
`Alt+E` is what you want to type before the keyword for emojis.

**Comment by Silergo** [comment]
You don't get what I mean. It doesn't matter what I type, but what other people do. If someone in chat type :), I'll see text ":)", but not smile image. If there is other way to add smile or autoreplace words with smile, please tell me.

**Comment by IceN9ne** [comment]
Settings > Configure Theme... > Text > Message Style > Draw some emoticons (smileys) as pictures

**Comment by Silergo** [comment]
This option was on :( If I switch it off, then Texticons stop working ar all.
