### ISSUE TITLE
The multiline editor is so small that it is not a multiline editor

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#2320]
![image](https://user-images.githubusercontent.com/1001553/31713168-a684aca6-b3fd-11e7-955b-ea99eebefdb5.png)

**Comment by wodim** [comment]
Probably related to the fact I have a high dpi screen.

**Comment by Heufneutje** [comment]
Can confirm this happens on my high DPI screen as well.

**Comment by pragmaware** [comment]
See d0ea547.  Please test on a high DPI monitor and eventually close the issue.

**Comment by pragmaware** [comment]
Changed my mind, closing :rofl: 
Reopen if the issue still persists :)

**Comment by Heufneutje** [comment]
Tested on my high DPI screen. This fixed it for me.
