### ISSUE TITLE
Crashing constantly under Windows Server 2016

### ISSUE THREAD

**Issue by tedych** [kvirc/KVIrc#2321]
Testing latest nightlies under two Win2016 servers.
Almost every time, 2-3 minutes after launch Kvirc crashes miserably. I can connect and use the app for 2-3 minutes but it crashes shortly after launched. This happens with all nightlies I tried last two months.
I used to use latest stable 4.2 under Win7 for 5 years with no issues and I was very happy with it.
But now there is no new "stable", nightlies crash constantly, too bad... I don't know if that's the case under Win10 though.
Unfortunately I have to decide what I'll be using, now (I rarely change apps), I just wanted to report the problem for future users. It's too bad I'll have to use different app as Kvirc is the best feature-wise.
Thanks.

**Comment by staticfox** [comment]
This really brings to like that we really need to think about a crash
reporter. Maybe breakpad? cc @DarthGandalf

**Comment by bvn13** [comment]
+1 on Win 10

**Comment by DarthGandalf** [comment]
@staticfox I like the idea of being able to upload crashdumps to be able to debug; but this raises big questions about security of the setup.

**Comment by ctrlaltca** [comment]
We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix and report if this issue is still present. Thank you
