### ISSUE TITLE
kvirc: symbol lookup error: kvirc: undefined symbol: feature_list

### ISSUE THREAD

**Issue by KlaasT** [kvirc/KVIrc#2324]
Hi,

I tried to install 4.9.2~git-7210-g0f76c9b0c-1 from the Debian Stretch repository you are offering. When starting KVIrc I get this error and the application won't run:

kvirc: symbol lookup error: kvirc: undefined symbol: feature_list

**Comment by ctrlaltca** [comment]
We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix and report if this issue is still present. Thank you
