### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by solmon4devx** [kvirc/KVIrc#2326]
In the MindForge net when a user receives an invite to a channel, an bot of the net sends you a notice in this format :

> [04:58:36] *[Minerva]* You have been invited to **#ChannelName**.

the name of de channel is send in bold, and the line is ended with a dot (.) this makes KVIrc interpret the dot as part of the channel name creating a wrong link.

**Comment by IceN9ne** [comment]
A period `.` is a valid character in a channel name, so it is the fault of the ircd writers to return a channel name followed by a `.` and it would be a terrible idea to guess whether the `.` should be included or not.

However, if the channel name is in bold, it should be possible to use the `\x02` as the boundary of the channel name and stop it before the `.`.  Theoretically anyways.

**Comment by solmon4devx** [comment]
Is what I did on the patch referenced above, but I'm not sure it's correctly programmed.

**Comment by IceN9ne** [comment]
I take back my on my "should be possible" comment as formatting should be stripped prior to parsing channel link. If someone were to rainbow color a channel name, it should still link properly, therefore as stated prior, this is an issue with the person writing the text and will not be changed.
