### ISSUE TITLE
Your own nick is excluded from your channel logs when another user mentions it in a message.

### ISSUE THREAD

**Issue by erictinney** [kvirc/KVIrc#2329]
**BUG REPORT:**  With logging enabled (Settings > Configure KVirc... > IRC > Tools > Logging), and "Query Windows" and "Channel Windows" both selected, daily logs for the channel will exclude from the log file (located in the appropriate directory) all entries in which another user in the channel mentions your nick in a message. 

Entries which you initiate using your nick are logged. "/Notice" messages to another user where your nick is mentioned in the message are logged.

The exclusion of your nick (and the text surrounding it) from the channel log only appears to happen when another user says your nick.

**=================================================**

**Help > About KVirc > Executable Information:**
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.4.0-103-generic
System version: #126-Ubuntu SMP Mon Dec 4 16:23:28 UTC 2017
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2017-11-06 01:23:07 UTC
Sources date: 20160102
Revision number: git-7212-g33fcac555
System name: Linux-4.4.0-97-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/x86_64-linux-gnu-g++
Compiler flags: -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 
Qt version: 5.5.1
Features: IRC, Debug, IPv6, Crypt, SSL, IfAddr, IPC, Transparency, Phonon, Webkit, DCCVoice, Perl, Python, Enchant, Qt5, KVS

**Comment by wodim** [comment]
I can't reproduce. Are you sure you haven't unchecked the "Log this" checkbox of the "Highlight" message type?

![2017-12-11-030631_954x684_scrot](https://user-images.githubusercontent.com/1001553/33812831-f1d0a536-de17-11e7-988f-17ed33bff6f2.png)

**Comment by erictinney** [comment]
Wodim,
The option to "log this" with highlighted text in Theme Preferences was indeed unchecked. I have checked it per your example and applied changes. 

 I will come back and close this issue if that was my problem in it's entirety. Thank you for your help.
-ET

UPDATE: This indeed solved the issue I was having. Thanks, Wodim!
