### ISSUE TITLE
AppVeyor nightly build is infected with Azden.A!cl

### ISSUE THREAD

**Issue by sporkwitch** [kvirc/KVIrc#2333]
Windowx x64 Nightly is infected with Azden.Alcl trojan.  Detected immediately by Windows Defender.

Impacted files:
AppData\Local\Mozilla\Firefox\Profiles\7if1zaib.default\cache2\entries\F014C36521A48192748913D553F2DE80E455BCAE

C:\Program Files\KVIrc\modules\kvitoolbareditor.dll

KVIrc-4.9.2-dev-git-7214-g6d28ddb44-x86_64.exe

**Comment by wodim** [comment]
https://www.virustotal.com/#/file/519cf91c614778a65b4d1b919f464852308eb5b24f5736b3c2140ab47f76f5b1/detection :thinking:

**Comment by sporkwitch** [comment]
Possible false positive?  I'd still rebuild from source and try to reproduce.

Windows 10 Home x64, using Windows Defender

**Comment by wodim** [comment]
I uploaded the file to VirusTotal and no antivirus has detected it so I don't know what to say to you.

**Comment by sporkwitch** [comment]
Not some tool trying to badmouth the product, either; i've been using kvirc on both my windows and linux machines for years lol.  Downloaded the nightly via appveyor and windows defender started screaming.

**Comment by sporkwitch** [comment]
I see  it compiling on appveyor; will redownload and retest once it completes.

**Comment by wodim** [comment]
Yeah, I see it now... That's really weird.

![image](https://user-images.githubusercontent.com/1001553/34234697-8a483d0a-e5e4-11e7-9767-8fb9d56a13ee.png)

I'd say it's a false positive but I don't know.

**Comment by sporkwitch** [comment]
New build appears clean.
KVIrc-4.9.2-dev-git-7215-g7ad56c988-x86_64.exe

Given the new one is fine, I honestly don't know what's up.  Might be worth mentioning to appveyor to see if something occurred on their end?

**Comment by HelLViS69** [comment]
Yep, warn AppVeyor if it's the only build affected

**Comment by wodim** [comment]
Closing because it's not our bug.
