### ISSUE TITLE
Last nightly build (x64) crashes in some time after start on Windows 10

### ISSUE THREAD

**Issue by bvn13** [kvirc/KVIrc#2334]
https://i.imgur.com/a7Xsnfm.png - here is a screenshot

**Comment by swarfega** [comment]
I've one had one crash and that was after my router had restarted and assigned a new IP.

**Comment by bvn13** [comment]
crahes into server setup window right after start + crash after joining channel as on screenshot - seems to be enough.

**Comment by senposage** [comment]
confirmed crashes randomly even with the window hidden 

Fault bucket 1964538867552831601, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: kvirc.exe
P2: 4.9.3.0
P3: 5a57efb7
P4: Qt5Core.dll
P5: 5.9.2.0
P6: 59d1f419
P7: c0000005
P8: 00000000001ce27b
P9: 
P10: ****

**Comment by Booster2ooo** [comment]
Same here, random crashes with latest stable version. I tried both x64 and x86 binaries, same result:

```
Faulting application name: kvirc.exe, version: 5.0.0.0, time stamp: 0x5c2c1bd4
Faulting module name: Qt5Core.dll, version: 5.9.7.0, time stamp: 0x5bc4659e
Exception code: 0xc0000005
Fault offset: 0x00172e00
Faulting process ID: 0x8f0
Faulting application start time: 0x01d4d2a87d72a524
Faulting application path: C:\Program Files (x86)\KVirc\kvirc.exe
Faulting module path: C:\Program Files (x86)\KVirc\Qt5Core.dll
Report ID: 52cfad51-6021-42e4-b851-56701cc413e1
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by registered-to-post-this** [comment]
Fixed it. (I think). It appears to be an issue with multithreading. Try starting KVIrc with this batch file that launches KVIrc using only one CPU core.

```
cd "C:\Program Files\KVIrc"
start /affinity 1 kvirc.exe
```

**Comment by AMDphreak** [comment]
upvote

**Comment by lxkurko** [comment]
I had several crashes with 5.0.0 stable and 5.0.0-75 nightly, both 64-bit versions, on Windows 7. Qt5Core.dll was mentioned as the faulting module. Downgraded to 4.2.0 for now.

**Comment by ctrlaltca** [comment]
We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix and report if this issue is still present. Thank you
