### ISSUE TITLE
AppVeyor failing: "Cannot find Visual Studio release redistributable files"

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#2335]
>Command executed with exception: Warning: Cannot find Visual Studio release redistributable files in C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\redist\MSVC\14.12.25810.

https://ci.appveyor.com/project/DarthGandalf/kvirc/branch/master/job/irto9u17d6ce9pa5

**Comment by craftwar** [comment]
WinDeployQt bug

https://bugreports.qt.io/browse/QTBUG-65015
https://i.imgur.com/7sK3Hd6.png

**Comment by DarthGandalf** [comment]
@craftwar any idea why it succeeded on #2325 ?

**Comment by craftwar** [comment]
@DarthGandalf newer VS2017 changes vcredist file name as I write in last reply.

**Comment by DarthGandalf** [comment]
Let's keep this open until the workaround is removed/fixed properly.

**Comment by craftwar** [comment]
![image](https://user-images.githubusercontent.com/16416710/35477669-53d92300-0403-11e8-9b34-b6275a3ac554.png)

VS2017 15.5.4 on my computer. This can be closed.

**Comment by IceN9ne** [comment]
The temporary fixed was reverted yesterday in 8458d1b
