### ISSUE TITLE
Tray icon has no tooltip

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#2339]
This has been broken for years now because XEmbed is history.

I imagine it never worked on Windows either.

**Comment by wodim** [comment]
Elaborating: it stopped working because the tray icon is implemented as a widget and the tooltip is displayed when QEvent::ToolTip happens. With the death of XEmbed, tray icons are no longer embedded windows but, eh, something else.

Elaborating further: some window managers like i3 still use XEmbed and the tooltip works fine there. But on Windows and on Linux desktop environments that use the SNI protocol the tooltip will never appear.

**Comment by leigh123linux** [comment]
Tray icon tooltips works fine on beta1, tested with cinnamon (fedora 28).

**Comment by wodim** [comment]
Cinnamon probably doesn't use SNI
