### ISSUE TITLE
Make KVIrc less scary for new users

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#2340]
Let's open this can of worms.

* Disable avatars by default: it's unacceptable that KVIrc downloads avatars by default. It's a huge privacy issue and it fills the channel output with stuff that nobody understands. Start a new profile and join #KVIrc and you'll see what it's like. It looks like you're being hacked, downloading lots of files you didn't really ask for.

* Output /names and /who to the console window by default: I know it doesn't make much sense but many people are put off when they have znc without having loaded route_replies and all channels are full of WHO replies all day. Other clients send that stuff to the console window. I know the solution is to load route_replies but I guess most people see that and think "kvirc is fucking stupid" and uninstall it.

**Comment by wodim** [comment]
All these suggestions made by @swarfega btw

**Comment by staticfox** [comment]
Agreed with both points.

**Comment by swarfega** [comment]
Actually it was Fuchs that stated the ideas, but I support them.

**Comment by Stanzilla** [comment]
Agreed with both points.

**Comment by IceN9ne** [comment]
The relevant settings I could think of and what the defaults might be to match your request for this issue:

For avatars:
```
boolPrependAvatarInfoToRealname = false
boolIgnoreCtcpAvatar = true
boolRequestMissingAvatars = false
boolAutoAcceptIncomingAvatars = false
boolIgnoreChannelAvatarRequestsWhenNoAvatarSet = true
boolShowAvatarsInUserList = false
boolEnableAnimatedAvatars = false
```

For whois/names:
```
boolWhoRepliesToActiveWindow = false
```

Is this all of them and are they reasonable defaults?

**Comment by wodim** [comment]
Looks ok
