### ISSUE TITLE
Can't interact with "Join Channels" dialogue when "Servers and Configuration" is open

### ISSUE THREAD

**Issue by staticfox** [kvirc/KVIrc#2341]
Steps to repro:

* Ensure "Join Channels" is set to automatically load when joining a server
* Go to Servers
* Click "Connect Now" on a system
* Wait for "Join Channels" to pop up

From there, you'll only be able to hit X on Join Channels, otherwise, you'll need to close Servers and Configurations to interact. Only reason I'm considering this a bug is due to the fact that it's the first dialogue that pops up as soon as you join a server, and it's misleading to present a dialogue that a user cannot interact with (especially when it shows up on top)

**Comment by DarthGandalf** [comment]
Related: #2386
