### ISSUE TITLE
/me command close the client

### ISSUE THREAD

**Issue by Indavoid** [kvirc/KVIrc#2345]
Hi !

/me command close the client. 
I'm running KVIRC 4.9.3 Aria on Ubuntu.

What can I do please ?

**Comment by Cizzle** [comment]
Does it crash with an error? Might be worth to check your aliases: press CTRL+SHIFT+L (or menu Scripting-->Edit Aliases...) and see if you have a "me" entry and what it contains.

**Comment by Indavoid** [comment]
No error, it just close. No "me" entry in aliases. Normal ?

**Comment by wodim** [comment]
Did you compile it yourself? Try to get a backtrace following these steps

https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace

**Comment by Indavoid** [comment]
I've followed this : https://launchpad.net/~kvirc/+archive/ubuntu/kvirc
What can I do for the /me please ?

**Comment by wodim** [comment]
Unless you build it yourself and give us a backtrace...

**Comment by Indavoid** [comment]
cd kvirc-trunk
bash: cd: kvirc-trunk: Aucun fichier ou dossier de ce type

**Comment by Indavoid** [comment]
I use Andaris script with KVIRC.

**Comment by Indavoid** [comment]
What can I do to send some /me commands ?

**Comment by AndrioCelos** [comment]
I was able to reproduce a crash with 0a54a61fe1f0e5ff622d9766c917165f35577ff0 and AndarisScript installed.
See https://paste.ubuntu.com/26448331/ for (part of) the stack trace.

```
KVIrc 4.9.3 'Aria'

Runtime Info:
System name: Linux 4.13.0-25-generic
System version: #29-Ubuntu SMP Mon Jan 8 21:14:41 UTC 2018
Architecture: x86_64
Qt version: 5.9.1
Qt theme: fusion

Build Info:
Build date: 2018-01-24 02:21:51 UTC
Sources date: 20180123
Revision number: git-7252-g0a54a61fe
System name: Linux-4.13.0-25-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr/local
   LIB_SUFFIX=
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.9.1
Features: IRC, Debug, IPv6, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Phonon, DCCVoice, Perl, Python, Enchant, Qt5, KVS
```

**Comment by IceN9ne** [comment]
After reading the reading through AndrioCelos's backtrace and browsing through the code at the below site, it appears that using "/me" with this script installed might cause and infinite recursion of OnMeAction events.

https://svn.tuxfamily.org/viewvc.cgi/andaris_script/trunk/AndarisScript/src/events.kvs?revision=251&view=markup#l1233

Try disabling the "andaris_default" event under OnMeAction in your Event Editor and see if it still crashes.

Or run this with KVS enabled: `/eventctl -d OnMeAction andaris_default`

**Comment by Indavoid** [comment]
"[07:33:38] [KVS] Attention : No handler 'andaris_default' for event 'OnMeAction'
[07:33:38] [KVS]   In script context "commandline::kvs", line 1, near character 1"

**Comment by Indavoid** [comment]
"[07:33:38] [KVS] Attention : No handler 'andaris_default' for event 'OnMeAction'
[07:33:38] [KVS]   In script context "commandline::kvs", line 1, near character 1
[07:33:38] [KVS] Code listing:
[07:33:38] [KVS]   1 eventctl -d OnMeAction andaris_default
[07:33:38] [KVS] Fenêtre :
[07:33:38] [KVS]   CONSOLE [ID: 1]
[07:33:38] [KVS] Call stack:
[07:33:38] [KVS]   #0 Core Simple Command "eventctl" [line 1, near character 1]
[07:33:38] [KVS]"

**Comment by IceN9ne** [comment]
Well, then I'm not sure what it's called in your install of it.  You'll have to manually check the Event Editor and right-click disable it.

**Comment by Indavoid** [comment]
Thanks, it works ! :)

**Comment by IceN9ne** [comment]
Closing as this is not an issue with KVIrc
