### ISSUE TITLE
VirtusTotal False Positive

### ISSUE THREAD

**Issue by raffaeler** [kvirc/KVIrc#2349]
Appveyor artifacts are detected as virus: HW32.Packed.1964
I will not able to install the client until the report is clean.
Thank you

**Comment by ctrlaltca** [comment]
Do you have a link to a virustotal report?
It' usually a false positive due to some crap antivirus detecting NSIS installers as "packed executables".

**Comment by raffaeler** [comment]
Here they are:
[64 bit](https://www.virustotal.com/#/file/ed78204418d2e159cd13cd407d6fb34acc3dc421cbb13de3f295c016489cf954/detection)
[32 bit](https://www.virustotal.com/#/file/635ea7a8855e35fd173ab722102b0df32a99d6a1bfdb03f1748bb74878c03acd/detection)
It would be great if you can get rid of that, thanks

**Comment by IceN9ne** [comment]
Why does this have anything to do with us?  It's just a junk heuristic and can safely be ignored.  We aren't the ones who uploaded it to that company, so we can't clear it anyways.  You are free to install software despite such warnings, there's nothing preventing you from doing it.

**Comment by raffaeler** [comment]
Do you have any other binary channel? I got the ones you suggested here on github ...
Even if I clone the repo and compile it by myself (which I would like to avoid), I would probably obtain the same binaries.

**Comment by Dessa** [comment]
maybe its the installer, maybe not, as long as VT doesn't really try to scan files inside "archives" we can only guess.

**Comment by ctrlaltca** [comment]
Well, it's just a false positive from a single antivirus vendor (on 65):
![schermata 2018-02-14 alle 18 29 45](https://user-images.githubusercontent.com/1631111/36218561-1a3c61d8-11b5-11e8-9c61-58ab63dab6e4.png)
I guess (hope) they'll notice and fix it silently in the next few days. If anyone want to oil the resolution of the problem, here's their contact page: http://www.bkav.com/contact-us , but i guess you'll get in touch with a salesman that barely knows what a false positive is.

**Comment by IceN9ne** [comment]
There's nothing that KVIrc can or should do with this.

**Comment by fisherhu** [comment]
Even tho I agree, nothing to do from the kvirc side, just for the shiplog, yet another file being flagged:

https://www.virustotal.com/gui/file/a098eed981a6a26b50098d0537b628292ae07dbbfc75ba6e331143e8482349f0/details

**Comment by ctrlaltca** [comment]
libkvimy contains windows-specific code to detect the user idle time, including a call to GetLastInputInfo() in user32.dll.
I guess some malware is using that call to implement a keylogger, and some antiviruses are taking the simple way to mark anything using that call as possible spyware.

**Comment by raffaeler** [comment]
Most of the time the detection in current antiviruses is heuristic.
One solution is to contact the vendors and signal a false positive so that they can adjust the detection. It happened to me in the past and they whitelisted the binaries adjusting the detection mechanism.

The fast and efficient solution is to publish the binaries in the GitHub releases. Users typically trusts security scans done by GitHub. I strongly suggest to start with this.

I still didn't install it after all these years, btw. Hope you can find a solution suitable for your needs.

**Comment by ctrlaltca** [comment]
> The fast and efficient solution is to publish the binaries in the GitHub releases. Users typically trusts security scans done by GitHub. I strongly suggest to start with this.

We are already publishing binaries in github releases, or am I misunderstanding your sentence?
https://github.com/kvirc/KVIrc/releases/tag/5.2.4

**Comment by raffaeler** [comment]
> We are already publishing binaries in github releases

This was not the case in 2018 (when I opened this issue) and since I didn't get any notification from this issue, I never came back to check if something changed.
