### ISSUE TITLE
How do I export aliases? Is this function removed?

### ISSUE THREAD

**Issue by craftwar** [kvirc/KVIrc#2355]
There is "Export All to ...." button in Edit Event
![image](https://user-images.githubusercontent.com/16416710/37238951-447dbaae-246c-11e8-843b-6765f9ab6274.png)

But no such button in Edit Alias
![image](https://user-images.githubusercontent.com/16416710/37238957-68ddae04-246c-11e8-9ab7-4143886ba52b.png)

I remember I can export aliases. But I forget how I did it.

**Comment by AndrioCelos** [comment]
Right click the list and select **Export All**.
Unless you're suggesting that the interface be made more consistent, you probably should not use GitHub issues for help. You can ask in our IRC channel (#kvirc on freenode) about that.

**Comment by ctrlaltca** [comment]
Fixed in #2356
