### ISSUE TITLE
File permission problem on win10

### ISSUE THREAD

**Issue by Pan7** [kvirc/KVIrc#2382]
KVirc is trying to write to the folder "Program Files\KVirc\config" when you store your settings which fails, it should write to "ProgramData" on Windows 10.
The same goes for the language setting writing to "Program Files\KVirc\.kvirc_force_locale" but it should be "ProgramData\KVirc\.kvirc_force_locale".

**Comment by Dessa** [comment]
its debatable if it should write the ProgamData though, it should if it really was supposed to write to the program dir, if its a user setting it should write to the user data folder instead (but im not really sure what is true currently)

**Comment by Pan7** [comment]
Right, mixed up the folders. Just not in "Program Files".

**Comment by Heufneutje** [comment]
I believe the proper way right now is to write to ProgramData if it applies to all users and AppData if it's a user specific setting.

**Comment by wodim** [comment]
We should not be writing anything to ProgramData. Everything should go in AppData. And evidently nothing in Program Files.

**Comment by craftwar** [comment]
I am curious why virtual store is not working.

**Comment by IceN9ne** [comment]
Does this affect anyone other than those who choose to install into ProgramFiles and select portable profile?

**Comment by ctrlaltca** [comment]
> Does this affect anyone other than those who choose to install into ProgramFiles and select portable profile?

I think you are right, KVirc has probably been installed to %ProgramFiles% in portable mode, that's why it's trying to write its configs in that folder.
@Pan7 does a `Program Files\KVirc\portable` file exist?

**Comment by Pan7** [comment]
Using KVIrc-4.9.3-dev-git-7277-g98f9af6a1-x86.exe and there is no portable file.

**Comment by Pan7** [comment]
Maybe an old kvirc4.ini is the reason.
