### ISSUE TITLE
Install problem on latest Insider Build 

### ISSUE THREAD

**Issue by swarfega** [kvirc/KVIrc#2383]
I have just tried several times to install the latest build of kvirc (just downloaded from appveyor) on Windows 10 build 17666 (the devil build).

It took longer than usual to install and has several dll errors:

> The code execution cannot proceed because MSVCP140.dll was not found. Reinstalling the program may fix this problem.

Same with VCRUNTIME140.dll which errors 3 times.

The only security I have is Malwarebytes and Defender.

**Comment by craftwar** [comment]
workaround: You can use 7zip to extract installer.

**Comment by swarfega** [comment]
Thank you. I was able then to run the vc redist and it now works. The installer used to prompt for the redist in older builds, perhaps we could have that back.

**Comment by Stanzilla** [comment]
It didn't prompt, it just showed the installer. Can you maybe find logs of what exactly happens during install? I don't know where they would be though. Could just be a insider bug though.

**Comment by swarfega** [comment]
I dont know where they are either. I've checked appdata and the program files location. As you say, it could be the insider build, this one is known to be a bit flaky.

**Comment by Stanzilla** [comment]
Don't worry. was my bad. I broke it in https://github.com/kvirc/KVIrc/commit/8458d1b7a256c95c124d643d41205c600b0f6280
