### ISSUE TITLE
KVS list object -> $sort function, add option to reverse sort order

### ISSUE THREAD

**Issue by Cabji** [kvirc/KVIrc#2384]
The list object in KVS has a sort function (though not found in the documentation). 

It would be really nice if this function had a parameter to optionally reverse the sort order. Currently it sorts the contents alphabetically in descending order (Z-A,9-0), but there's no option to reverse it to ascending order (A-Z) as far as I can determine.

**Comment by slaboff** [comment]
There is already a function for that $rsort

**Comment by Cabji** [comment]
"reverse sort order" in original post was relative to what already exists. 

So a function that will sort a list object alphabetically, not reversed alphabetically.
