### ISSUE TITLE
How to install the dictionaries for enchant-2/hunspell?

### ISSUE THREAD

**Issue by trippleflux** [kvirc/KVIrc#2404]
I have compiled or used the latest KVIrc nightly but seems cannot managed to get the enchant-2/hunspell to works, when going into Settings->Configure KVIrc->General Options->Language, the installed dictionaries which is located on ..\KVIrc\share\hunspell\dicts is not being loaded. 
![dicts](https://user-images.githubusercontent.com/1216215/47146468-4d91f900-d2f6-11e8-8699-7e779befded7.png)

On the spellchecker window it just empty.

![empty](https://user-images.githubusercontent.com/1216215/47146418-30f5c100-d2f6-11e8-89f6-d4dcb4f4fe3c.png)

How to properly installing the dictionaries for the enchant-2 / hunspell ?.

**Comment by DarthGandalf** [comment]
Are libenchant and libhunspell DLLs presented? Builds on Appveyor should work, they have several dictionaries preinstalled.

**Comment by trippleflux** [comment]
Yes they are exist, i have already using dependency walker to check the depended libraries, and they are already in the root folder of KVIrc. As i have mentioned the nightlies on Appveyor also having the same problem.

**Comment by IceN9ne** [comment]
From the latest AppVeyor x64 Release build:

    c:\cygwin\bin\cp : /usr/bin/cp: cannot stat 'c:/msys64/mingw64/lib/enchant-2/libenchant_hunspell.dll': No such file or directory
    At line:19 char:1
    + c:\cygwin\bin\cp -pv $env:mingw_root/lib/enchant-2/libenchant_hunspel ...
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (/usr/bin/cp: ca...le or directory:String) [], RemoteException
        + FullyQualifiedErrorId : NativeCommandError

Could explain a missing dll.  I'd guess the dll name got changed in libenchant-2
