### ISSUE TITLE
libkvisystem.cpp:743:2: error: unknown type name 'QProcess'

### ISSUE THREAD

**Issue by two-dogs** [kvirc/KVIrc#2405]
/Users/xxxxxxx/Downloads/KVIrc-master/src/modules/system/libkvisystem.cpp:743:2: error: unknown type name 'QProcess'
        QProcess oProc;
        ^
is causing build errors on macOS HighSierra, link shows is provided.

https://github.com/kvirc/KVIrc/blob/c7eea2406bf70a77a127b6bf472f422f2dbd9de9/src/modules/system/libkvisystem.cpp#L743
the code is there.

is QProcess permissible on mac HighSierra?

**Comment by IceN9ne** [comment]
There's not much to go on here as you didn't provide much information, but I'm going to guess that you're using KDE on macOS. I'm not sure how much support we have for KDE right now. I'd recommend trying to build with `WANT_KDE=0` in cmake and seeing if that helps. Currently the build process is set to automatically enable KDE if it detects it on the system.

**Comment by two-dogs** [comment]
@IceN9ne , i am trying to install kvirc on mac, i used the instructions for mac, btw, some dependencies are not shown on instructions but become obvious, i can share what ever helps.
https://github.com/kvirc/KVIrc/wiki/Compiling-KVIrc-on-macOS
I tried option WANT_KDE=0 , no joy, same error stops make install at aprox 94%
https://gist.github.com/two-dogs/aa06bbfc6ac29c6b1c717d6e479297ff

**Comment by aspacehspacek** [comment]
try https://kvirc.ru

**Comment by IceN9ne** [comment]
@tow-dogs Could you paste the cmake line you actually used? What I suggested you try is (assuming you modified it from the link you provided):

`ccmake -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/ -DWANT_KDE=0 ..`

You could paste your cmake output as well, which could help.

**Comment by aspacehspacek** [comment]
gegő geci takarodjál

**Comment by two-dogs** [comment]
@IceN9ne  i did as you asked, i also moved the build folder to /usr/local/.. and build completes to creating the app, found two issues with app, no spell check or openssl, fixed spelling with a brew install of enchant, font selection does not work from configuration, not sure what the cause is

**Comment by IceN9ne** [comment]
You would need to install the libs for enchant2 and openssl. I would guess you would do this from brew as well, but I'm not a macOS person and have no way to test it.

**Comment by two-dogs** [comment]
@IceN9ne 'brew install enchant' takes care of the missing dep for spellcheck.
where does one list kvirc-5.x.app for mac in kvirc repos? for testing
the font setting gui is borked, i am not sure where issue is, font setting does not take.
