### ISSUE TITLE
Enchant still failed to load the dictionaries

### ISSUE THREAD

**Issue by trippleflux** [kvirc/KVIrc#2406]
I can see that #2404 already been closed, but i couldn't see the dictionaries being loaded on Settings->Configure KVIrc->General Options->Language and in there the Spellchecker Dictionaries list is listed as 'none' while in the "C:\Program Files\KVIrc\share\hunspell\dicts" there are four installed dictionaries files.

![broken](https://user-images.githubusercontent.com/1216215/47521725-f673c180-d8bd-11e8-9a66-fe47f205170b.png)

From my memories, if the enchant is working, then the dictionaries will be listed in there,

**Comment by DarthGandalf** [comment]
This was fixed in nightly build: 246377354f018aafacf28cb6f117bd1dedf15799
