### ISSUE TITLE
Build fails in libkviabout.h / AboutDialog.cpp on openSUSE Leap 15

### ISSUE THREAD

**Issue by lemmy04** [kvirc/KVIrc#2414]
```
[  933s] [ 58%] Built target kvirc
[  933s] Scanning dependencies of target kviabout_autogen
[  933s] [ 58%] Automatic MOC for target kviabout
[  933s] AutoMoc: /home/abuild/rpmbuild/BUILD/kvirc-5.0.0-beta1/src/modules/about/libkviabout.h:0: Note: No relevant classes found. No output generated.
[  933s] [ 58%] Built target kviabout_autogen
[  933s] Scanning dependencies of target kviabout
[  933s] [ 58%] Building CXX object src/modules/about/CMakeFiles/kviabout.dir/AboutDialog.cpp.o
[  936s] [ 58%] Building CXX object src/modules/about/CMakeFiles/kviabout.dir/libkviabout.cpp.o
[  938s] [ 58%] Building CXX object src/modules/about/CMakeFiles/kviabout.dir/kviabout_autogen/mocs_compilation.cpp.o
[  940s] [ 58%] Linking CXX shared module libkviabout.so
[  941s] /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/kviabout.dir/AboutDialog.cpp.o: in function `AboutDialog::AboutDialog()':
[  941s] AboutDialog.cpp:(.text+0x1c0): undefined reference to `g_pApp'
[  941s] /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: AboutDialog.cpp:(.text+0x1fc): undefined reference to `KviApplication::findImage(QString&, QString const&)'
[  941s] /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: AboutDialog.cpp:(.text+0x19ee): undefined reference to `g_pApp'
[  941s] /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: AboutDialog.cpp:(.text+0x1a1d): undefined reference to `KviApplication::getGlobalKvircDirectory(QString&, KviApplication::KvircSubdir, QString const&)'
[  941s] /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/kviabout.dir/libkviabout.cpp.o: in function `about_module_init(KviModule*)':
[  941s] libkviabout.cpp:(.text+0xee): undefined reference to `KviKvsModuleInterface::kvsRegisterSimpleCommand(QString const&, bool (*)(KviKvsModuleCommandCall*))'
[  941s] collect2: error: ld returned 1 exit status
[  941s] make[2]: *** [src/modules/about/CMakeFiles/kviabout.dir/build.make:155: src/modules/about/libkviabout.so] Error 1
[  941s] make[1]: *** [CMakeFiles/Makefile2:4543: src/modules/about/CMakeFiles/kviabout.dir/all] Error 2
[  941s] make: *** [Makefile:130: all] Error 2
[  941s] error: Bad exit status from /var/tmp/rpm-tmp.YqHpfv (%install)
[  941s] 
```

any ideas, patches or suggestions?

**Comment by ctrlaltca** [comment]
Can you `make VERBOSE=1`?
Looks like the modules are not linking correctly against the main kvirc binary, so the external symbols imported from the main kvirc binary are not resolved.
The code actually defining that linking is here: https://github.com/kvirc/KVIrc/blob/master/cmake/module.rules.txt#L16

**Comment by lemmy04** [comment]
done. the complete log is here:
https://build.opensuse.org/package/live_build_log/home:lemmy04/kvirc/openSUSE_Leap_15.0/x86_64

**Comment by Dessa** [comment]
it appears that -Wl,--no-undefined still breaks things.

**Comment by lemmy04** [comment]
In my opinion that is something that needs to be fixed in kvirc. -Wl,--no-undefined is part of the default build options for qt apps on openSUSE and nothing else breaks like this.

**Comment by IceN9ne** [comment]
You're `cmake`ing from a cmake build directory?

> [  104s] + cd kvirc-5.0.0-beta1
[  104s] + EXTRA_FLAGS='-DWITH_NO_EMBEDDED_CODE=ON -DWANT_OGG_THEORA=ON -DWANT_DCC_VIDEO=ON -DWANT_VERBOSE=ON             -DLIB_SUFFIX=64              -DWANT_COEXISTENCE=OFF'
[  104s] + mkdir build
[  104s] + pushd build
[  104s] + export SUSE_ASNEEDED=0
[  104s] + SUSE_ASNEEDED=0
[  104s] + cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_SKIP_RPATH=true -DCMAKE_SKIP_INSTALL_RPATH=true -DWITH_NO_EMBEDDED_CODE=ON -DWANT_OGG_THEORA=ON -DWANT_DCC_VIDEO=ON -DWANT_VERBOSE=ON -DLIB_SUFFIX=64 -DWANT_COEXISTENCE=OFF
[  119s] + bdir=.
[  119s] + dir=build
[  119s] + mkdir build
[  119s] + cd build
[  119s] + bdir=..
[  119s] + cmake -DCMAKE_BUILD_TYPE=None -DKDE_INSTALL_USE_QT_SYS_PATHS=OFF '-DCMAKE_C_FLAGS=-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -DNDEBUG' '-DCMAKE_CXX_FLAGS=-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -DNDEBUG' '-DCMAKE_EXE_LINKER_FLAGS=-Wl,--as-needed -Wl,--no-undefined -Wl,-Bsymbolic-functions' '-DCMAKE_MODULE_LINKER_FLAGS=-Wl,--as-needed -Wl,--no-undefined -Wl,-Bsymbolic-functions' '-DCMAKE_SHARED_LINKER_FLAGS=-Wl,--as-needed -Wl,--no-undefined -Wl,-Bsymbolic-functions' -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_PREFIX_PATH=/usr -DKDE_INSTALL_LIBDIR=lib64 -DKDE_INSTALL_SYSCONFDIR=/etc -DKDE_INSTALL_QTPLUGINDIR=lib64/qt5/plugins -DKDE_INSTALL_PLUGINDIR=lib64/qt5/plugins -DKDE_INSTALL_QMLDIR=lib64/qt5/qml -DKDE_INSTALL_QTQUICKIMPORTSDIR=lib64/qt5/imports -DECM_MKSPECS_INSTALL_DIR=/usr/lib64/qt5/mkspecs/modules -DKDE_INSTALL_METAINFODIR=/usr/share/metainfo -DBUILD_TESTING=OFF .. -DWITH_NO_EMBEDDED_CODE=ON -DWANT_OGG_THEORA=ON -DWANT_DCC_VIDEO=ON -DWANT_VERBOSE=ON -DLIB_SUFFIX=64 -DWANT_COEXISTENCE=OFF

Looks like you need to fix your build script. Not surprised you're having issues.

**Comment by lemmy04** [comment]
it's not "my" build script, it's the openSUSE default build script for Plasma (KDE 5) apps... and nothing else that's being built on OBS has issues like this.

```
%build
EXTRA_FLAGS="-DWITH_NO_EMBEDDED_CODE=ON -DWANT_OGG_THEORA=ON -DWANT_DCC_VIDEO=ON -DWANT_VERBOSE=ON\
%ifarch x86_64
             -DLIB_SUFFIX=64 \
%endif
             -DWANT_COEXISTENCE=OFF"

mkdir build
pushd build
export SUSE_ASNEEDED=0
cmake .. -DCMAKE_INSTALL_PREFIX=%{_kf5_prefix} -DCMAKE_SKIP_RPATH=true -DCMAKE_SKIP_INSTALL_RPATH=true $EXTRA_FLAGS
%cmake_kf5 -d build -- $EXTRA_FLAGS
```

**Comment by IceN9ne** [comment]
openSUSE still lists 4.2.0 as their official KVIrc version for Leap 15.0, so I'm not sure where this package you're getting is coming from. The issue seems to be the linker flags that your package is adding as KVIrc 5.0 builds just fine on every other Linux distro I've tested so far. Do you have a link to this package you're trying to install?

You're calling it the "default build script for Plasma apps", but you can't just throw the same compile options at every package and expect them to work. Each package needs to be tailored to the software you're installing.

**Comment by lemmy04** [comment]
What I'm calling "the default" is the predefined cmake / rpm macro for building plasma apps. it *should* work,, but obviously it doesnt.

I've forked a KDE:Unstable:Extra/kvirc now, which *successfully* builds from the latest git snapshot, let's see if that works. If so I'll post the differences between the spec files.

**Comment by IceN9ne** [comment]
cmake .. -DCMAKE_INSTALL_PREFIX=%{_kf5_prefix} -DCMAKE_SKIP_RPATH=true -DCMAKE_SKIP_INSTALL_RPATH=true $EXTRA_FLAGS
    %cmake_kf5 -d build -- $EXTRA_FLAGS

It looks like you're running cmake twice here.

**Comment by lemmy04** [comment]
that would explain a lot ... anyway i do have a working package now, and the problem was that i basically built with an old spec file that actually orginated in KDE 4 0.o
