### ISSUE TITLE
kvirc 5 beta openssl is old

### ISSUE THREAD

**Issue by NicklaTome** [kvirc/KVIrc#2418]
Hi kvirc peoples :)

In my pc is instaled KVIrc-5.0.0-beta1-120-g11890eeaa-x86_64 and this openssl with versions 1.0.2o.
we my brother has copied openssl 1.0.2q files and kvirc dont open, but we put old files and kvirc ok. we ask for new openssl please. we thank kvirc peoples and wich a happy crhistmas.

**Comment by Dessa** [comment]
at the time of the report there was no build for a while, openssl was updated on the build host later so this is now done.

**Comment by NicklaTome** [comment]
Hello

We check KVIrc-5.0.0-38-g8a8cb2a00-x86_64.exe is equal openssl versions 1.0.2o, is old.

**Comment by Dessa** [comment]
right.
we don't use the pre-installed openssl anymore, i forgot about that.

**Comment by craftwar** [comment]
To reduce build uncertainty, I don't update vcpkg.
Do you try to build vcpkg openssl? They may be compatible.

**Comment by Dessa** [comment]
nah i didn't try that yet. it might work yeah, maybe i find time tonight.

**Comment by NicklaTome** [comment]
issue is existing current, vcpkg ssl very old, was before easy and current now no good,
