### ISSUE TITLE
Making backup of settings 

### ISSUE THREAD

**Issue by Faq** [kvirc/KVIrc#2420]
**Background story:**
This version of kvirc was installed long time ago and after re-installation windows (with format) kvirc dir was copied over from backup and all settings (defined server/channel, nickname and and password to it) are there.
 
**Problem description:**
A) Using that command, nothing happens.
https://github.com/kvirc/KVIrc/wiki/FAQ#how-can-i-backup-my-settings
B) kvirc4.ini file not found (in C:\*.*).
C) tried also wizard mentioned in https://github.com/kvirc/KVIrc/issues/1712 by pointing to settings "c:\KVIrc4.9.2\Settings\"
D) want to move all configuration to KVIrc5.0 and make it to be used in portable mode, but stuck with described problem A), B), C).
 
Please describe how to get all settings including password (if possible) and use kvirc from one folder

**"Executable Information":**

> KVIrc 4.9.2 'Aria'
> 
> Runtime Info:
> System name: Windows Release : 6.1.7601
> System version: Windows 7 Ultimate (x64) Service Pack 1 (Build 7601)
> Architecture: Intel64 Family 6 Model 30 Stepping 5
> Qt version: 5.9.1
> Qt theme: windowsvista
> 
> Build Info:
> Build date: 2017-11-11 05:16:49 UTC
> Sources date: 20171111
> Revision number: git-7214-g860127e04
> System name: Windows-10.0.14393
> CPU name: AMD64
> Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
> Build flags: 
>    MANDIR=share/man
>    CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
>    Threads=Win32
> Compiler name: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hostx64/x64/cl.exe
> Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
> Qt version: 5.9.1
> Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Perl, Python, Enchant, Qt5, KVS

**Comment by Faq** [comment]
No point to keep it open, no response.

**Comment by majinsnake** [comment]
I took screenshots of my settings.
