### ISSUE TITLE
[Packaging] Ubuntu 19.04 perl dependency unmet

### ISSUE THREAD

**Issue by RogueScholar** [kvirc/KVIrc#2422]
I know we've still got a couple weeks to go until the launch date, but I wanted to point out that the current .deb packages as build for Ubuntu 18.10 "Cosmic" will fail to install on 19.04 "Disco" owing to the shift to perl5.28.1 in the repositories. That breaks kvirc-modules hard dependency on libperl5.26, which breaks kvirc.

Thanks again for a great piece of software. :vulcan_salute:

**Comment by DarthGandalf** [comment]
I think this belongs to https://bugs.launchpad.net/ubuntu/+source/kvirc not here...

**Comment by wodim** [comment]
I understood he means the PPA, but it's not clear. @RogueScholar, where did you get that .deb from?

**Comment by RogueScholar** [comment]
@wodim you're correct, I'm indeed referring to the package available from the [Daily Builds PPA](https://launchpad.net/~kvirc/+archive/ubuntu/kvirc) which I've used for some time. I wasn't implying that something had been overlooked or gone awry, rather that I saw many other projects using Launchpad PPAs for package distribution opening a Disco series and thought a message indicating that some attention to the `DEBIAN/control` file for KvIRC to do the same might be beneficial.

**Comment by RogueScholar** [comment]
Disco builds present and accounted for. Much obliged, all.
