### ISSUE TITLE
[Feature Request] - Allow users to create irc contexts from within the "Servers and Configuration" dialog / window!

### ISSUE THREAD

**Issue by roboirc** [kvirc/KVIrc#2424]
Please allow users to create "New IRC Contexts" from within the "Servers and Configuration" dialog / window so that users can connect to new connections on the fly instead of having to go all the way to the top left corner to create "New IRC Context". Thanks!

**Comment by AndrioCelos** [comment]
KVIrc > New Connection To > Other already does this, as does `/server -n <network name>`. Also note the `Ctrl`+`N` keyboard shortcut to 'New IRC Context'.

**Comment by IceN9ne** [comment]
Also, you can open the Servers and Configuration dialog with `Ctrl+S`.

From the Servers and Configuration dialog, it will first attempt to use any unused open contexts and if none are found, it will automatically open a new context for you. It will never override an already active context.

This is as "on the fly" as you can get, IMO.

**Comment by roboirc** [comment]
Can we change the shortcut key for opening a "New IRC Context" from CTRL+N to something else ?

**Comment by roboirc** [comment]
If so where?

**Comment by roboirc** [comment]
Thanks
