### ISSUE TITLE
Please allow users to be able to delete raw events in the RAW Event Editor!

### ISSUE THREAD

**Issue by roboirc** [kvirc/KVIrc#2427]
Feature Request:

Please allow users to be able to delete raw events in the RAW Event Editor instead of only removing the handler. Right now we can only remove the handler script instead of the entire raw event that we don't want from the tree under: RAW Event.

Thanks!

**Comment by wodim** [comment]
Does an event with no handlers remain even after restarting the client?

**Comment by roboirc** [comment]
Not restarting the client but one should be able to delete the raw event and that includes its handlers. Not sure why we can ONLY delete the handlers?

**Comment by wodim** [comment]
Because that's the way it's programmed I guess? I agree it would be better if the event itself disappeared if there are no more handlers left.

**Comment by roboirc** [comment]
OK

**Comment by roboirc** [comment]
I still want the feature to allow users to remove events

**Comment by wodim** [comment]
I've said I agree the current behaviour is undesirable.

**Comment by roboirc** [comment]
Great

**Comment by roboirc** [comment]
The event itself disappears when there are no more handlers left but not instantly only after we close the Raw Event Editor. Once a person closes an event it should close everything associated with it. Hope this gets fixed in future release.
