### ISSUE TITLE
Panel tint2 icon.

### ISSUE THREAD

**Issue by Glossow** [kvirc/KVIrc#2437]
Hello.
Can not see the application icon.
SS: https://i.imgur.com/bwe0Je7.png

Debian GNU/Linux 10.
KVIrc 5.0.0 'Aria'
Версия Qt: 5.11.3.
Panel: tint2

**Comment by ctrlaltca** [comment]
We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix and report if this issue is still present. Thank you
