### ISSUE TITLE
macOS builds don't support SSL

### ISSUE THREAD

**Issue by stefan1983** [kvirc/KVIrc#2440]
All versions (even nightly) state "This executable has no SSL support". So it is not possible to connect to any server via SSL (nor DCC something via SSL).

**Comment by staticfox** [comment]
I've added a mac build for 5.0.0 to the GitHub release, please give this a go and double check that it works. Thanks! https://github.com/kvirc/KVIrc/releases/download/5.0.0/KVIrc.dmg

**Comment by v-ji** [comment]
I can confirm the linked release is compiled with SSL support and works. However, the “OS X binary package” on the [downloads page](https://www.kvirc.net/?id=releases) has no SSL support, this should probably fixed.

Also, you may want to rename that to “macOS binary package”, as the OS was renamed in 2016.

<img width="652" alt="About KVIrc" src="https://user-images.githubusercontent.com/1476338/78471509-19043e00-7732-11ea-9846-9d6e5af26a6d.png">

**Comment by ctrlaltca** [comment]
Current builds supports ssl.
