### ISSUE TITLE
"[SSL ERROR]: too large" when connecting to ircs servers.

### ISSUE THREAD

**Issue by technic-tec** [kvirc/KVIrc#2442]
SSL error when connect to ircs servers. (kvirc keeps reconnecting, but never suceeded.)
> [19:05:30] End of message of the day.
> [19:05:30] [SSL ERROR]: too large
> [19:05:30] [SOCKET ERROR]: Secure Socket Layer error
> [19:05:30] Connection terminated [ircs.overthewire.org (104.131.10.16:6697)]
> [19:05:30] The connection terminated unexpectedly. Trying to reconnect...

**Servers tested:**
ircs://ircs.overthewire.org:6697/
ircs://irc.hackint.org:6697/

**Environment:**
> KVIrc 4.9.3 'Aria'
> 
> Runtime Info:
> System name: Linux 4.15.0-58-generic
> System version: #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019
> Architecture: x86_64
> Qt version: 5.9.5
> Qt theme: fusion
> 
> Build Info:
> Build date: 2018-02-05 19:12:10 UTC
> Sources date: 20160102
> Revision number: git20180106+dfsg-1buil
> System name: Linux-4.4.0-101-generic
> CPU name: x86_64
> Build command: /usr/bin/cmake
> Build flags: 
>    MANDIR=share/man
>    CMAKE_INSTALL_PREFIX=/usr
>    LIB_SUFFIX=/x86_64-linux-gnu
>    Threads=POSIX
> Compiler name: /usr/bin/c++
> Compiler flags: -g -O2 -fdebug-prefix-map=/build/kvirc-snXz2w/kvirc-4.9.3~git20180106+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2
> Qt version: 5.9.3
> Features: IRC, Debug, IPv6, Crypt, SSL, IfAddr, IPC, KDE, Transparency, Phonon, Webkit, DCCVoice, Perl, Python, Enchant, Qt5, KVS

**Comment by AndrioCelos** [comment]
Can you confirm whether this issue still occurs with the latest build of KVIrc?

**Comment by ghost** [comment]
Doesn't happen on 5.0.1 or 5.0.0. :)
