### ISSUE TITLE
CI: perl module compilation failure on windows

### ISSUE THREAD

**Issue by craftwar** [kvirc/KVIrc#2446]
https://ci.appveyor.com/project/DarthGandalf/kvirc

strawberry version is changed, need new patch.

**Comment by NicklaTome** [comment]
We are with this issue too, compilations of porgram works wit perl 5.28.2.1, https://github.com/kvirc/KVIrc/commits/master much errors

.appveyor.yml change to works
```yml
        choco install strawberryperl -y --version 5.28.2.1 $env:choco_arch
```
