### ISSUE TITLE
KVIrc crashes after suspend to ram - win7

### ISSUE THREAD

**Issue by tojestzart** [kvirc/KVIrc#2447]
> Pakiet błędów 4024013487, typ 516973248
Nazwa zdarzenia: APPCRASH
Odpowiedź: Niedostępny
Identyfikator pliku Cab: 0

Sygnatura problemu:
P1: kvirc.exe
P2: 5.0.0.0
P3: 5c2c154f
P4: StackHash_63e7
P5: 6.1.7601.24520
P6: 5d673de3
P7: c0000374
P8: 00000000000bf302
P9: 
P10: 

Dołączone pliki: 
C:\Users\lsd\AppData\Local\Temp\WERCC98.tmp.WERInternalMetadata.xml

Te pliki mogą być dostępne tutaj:
C:\Users\lsd\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_kvirc.exe_8fd67df8b452be6e336d7ae7fbcdbc24cf46728_09b32948

Symbol analizy: 
Ponowne sprawdzanie rozwiązania: 0
Identyfikator raportu: 473e1cbc-df65-11e9-9a25-681729633106
Stan raportu: 0

> 

> Nazwa aplikacji powodującej błąd: kvirc.exe, wersja: 5.0.0.0, sygnatura czasowa: 0x5c2c154f
Nazwa modułu powodującego błąd: ntdll.dll, wersja: 6.1.7601.24520, sygnatura czasowa: 0x5d673de3
Kod wyjątku: 0xc0000374
Przesunięcie błędu: 0x00000000000bf302
Identyfikator procesu powodującego błąd: 0x1398
Godzina uruchomienia aplikacji powodującej błąd: 0x01d572c785fb5e60
Ścieżka aplikacji powodującej błąd: C:\Program Files\KVIrc\kvirc.exe
Ścieżka modułu powodującego błąd: C:\Windows\SYSTEM32\ntdll.dll
Identyfikator raportu: 473e1cbc-df65-11e9-9a25-681729633106

>

**Comment by ctrlaltca** [comment]
We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix and report if this issue is still present. Thank you
