### ISSUE TITLE
Feature Request: shift-click in input box should select text rather than move the cursor

### ISSUE THREAD

**Issue by poncha** [kvirc/KVIrc#2451]
When entering text in input box, pressing shift on keyboard and then clicking somewhere inside the content should make a selection of text from the original cursor location to the clicked location.

**Comment by ctrlaltca** [comment]
We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix and report if this issue is still present. Thank you
