### ISSUE TITLE
In Windovs 10 Bulgarian language spell checker Dictionary don't load - KVIrc 5.0.0 'Aria'

### ISSUE THREAD

**Issue by filchef** [kvirc/KVIrc#2458]
This is bug report
I change language to English and restart application without result  also I try to write script for reloading dictionaries but give me error see - [https://imgur.com/Nhie7oi](https://imgur.com/Nhie7oi)

![image](https://user-images.githubusercontent.com/6907969/72295730-ce0de980-3660-11ea-8f38-5d50405fc29f.png)

**Comment by ctrlaltca** [comment]
We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix and report if this issue is still present. Thank you
