### ISSUE TITLE
Add OPAQUE-based SASL authentication, separately selectable from SASL PLAIN

### ISSUE THREAD

**Issue by SoniEx2** [kvirc/KVIrc#2459]
There should be an option for [OPAQUE](https://eprint.iacr.org/2018/163.pdf)-based SASL, so that a hacked or misconfigured server doesn't leak the user's password. It should be a separate authentication method so that SASL PLAIN isn't used when SASL OPAQUE is selected. SASL OPAQUE should only be available on TLS-enabled connections.

How many times have we heard of server logs leaking user passwords? How many times have we heard of hacked servers leaking user passwords? This provides *some* level of protection against those.

On the server side, servers should require SASL OPAQUE for new user accounts (i.e. completely prevent the use of SASL PLAIN), and notify old accounts of the risks of SASL PLAIN if that method is being used.

This doesn't affect CertFP or plain nickserv login, altho ideally the latter would be deprecated as well.

See also https://blog.cryptographyengineering.com/2018/10/19/lets-talk-about-pake/

**Comment by wodim** [comment]
What networks support OPAQUE SASL?

**Comment by SoniEx2** [comment]
who cares. push it on them.

**Comment by Dessa** [comment]
patches welcome?

either way, besides of SCRAM-SHA, maybe ECDH-X25519-CHALLENGE is useful, only recent atheme supports this (freenode might? no idea) can't really push something on people that doesn't exist, when there could be some work done on actual things.

we as a client dev are not responsible for "pushing something on people" esp. when the person expressing the need for it could very well do that themselfs

**Comment by SoniEx2** [comment]
upon further research I have decided to close this issue.
