### ISSUE TITLE
[Request] Adjustable Line Spacing in Output

### ISSUE THREAD

**Issue by Gelmo** [kvirc/KVIrc#2464]
It would be excellent if we could adjust the amount of whitespace between lines in the output window. This would be very useful for ascii art communities.

Here's an example:

http://lowtrucks.net/Forums/Pictures/mIRC-IRC-ANSIart1.png

You'll see that full-height characters touch at the full-height characters above and below it since there is not a defined number of pixels separating lines.

**Comment by jaxson5** [comment]
Agree with this. It makes channels with a lot of traffic use the mouse scroll heaps to keep with conversation flows.. better to have no space or adjustable space between rows. I'm using 5.0.0 Aria on Debian Buster.

**Comment by VaporNinja** [comment]
**Totally agree.**
It ruins ASCII art and allows for less text on the screen at one time.
Also would look a LOT better.
Thanks for making this request.

**Comment by Gelmo** [comment]
Nice!!! Thank you!
