### ISSUE TITLE
Crash after long use

### ISSUE THREAD

**Issue by tojestzart** [kvirc/KVIrc#2469]
https://pastebin.com/eVXg9HLX - first time
https://pastebin.com/y0vmB51C - second time

**Comment by pragmaware** [comment]
It seems that SIGPIPE is already ignored...
But there may be some threading issues here as it's unclear if signal management is thread-wide or process-wide.
We should probably just ignore SIGPIPE globally forever without ever reverting to default behaviour.

**Comment by tojestzart** [comment]
Before i didnt set properly kvirc under gdb, exatly same bug with verbose messages
https://pastebin.com/kDvwxuhZ
What i was doing before?
I was connected throught Openvpn to freenode network then openvpn connection was lost, aftermath i tried to recover main window but it wasnt responding.

**Comment by pragmaware** [comment]
Can you try branch ignore-sigpipe to see if it changes anything?

**Comment by tojestzart** [comment]
I will try, for now i can show  https://youtu.be/PBxRQSs5bxk?t=201 i tried to make crash but it doenst work all the time, so could you tell me how to make sure it will crash everytime before i will test branch  ?

**Comment by ctrlaltca** [comment]
We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix and report if this issue is still present. Thank you
