### ISSUE TITLE
Launchpad PPAs need new source package for Ubuntu 20.04 LTS with Perl 5.30

### ISSUE THREAD

**Issue by RogueScholar** [kvirc/KVIrc#2470]
It's me again, sorry to have to bug you guys. Just like my last visit exactly a year ago, another shiny new Ubuntu release has descended from on high and once again it has shipped with a new version of Perl (5.30 this time). So when I ran the upgrade, I had no choice but to acquiesce to its demand to uninstall KVIrc since I install from the Launchpad PPAs.

If I promise to send you guys a cake (hookers and blow is also on the table, I'm a man of many resources :smiling_imp:) could I impose upon one of you to push a build for 20.04 Focal to Launchpad when you get a chance? I know, I know, I should just be patient and deal with the package from the official repos, but I'm somewhat addicted to the splendid aesthetic enhancements that arrived with the last flurry of commits. Call me particular, but after a quarter century on IRC I feel like I've got the perfect client and if it means being called a crybaby to keep it, I can live with that.

Thanks again for the work you've put in. It may not be everyone's cup of tea, but I for one am very grateful to be able to use it. I hope you all are well and safely weathering the storm.

Warmly,
Peter

**Comment by AlexanderP** [comment]
Hi.
Uploaded to compilation in ppa: [~kvirc/kvirc](https://launchpad.net/~kvirc/+archive/ubuntu/kvirc)

**Comment by RogueScholar** [comment]
@AlexanderP Thanks for doing that, and sorry for forgetting to close this issue. Any chance I could trouble you to push a build for 20.10 "Groovy Gorilla" to the PPA whenever you can get around to it?

Oh, and I noticed a bug too that I think is unique to the PPA packages, namely that they have the wrong path set for fetching the locally-installed documentation through , and thus none of the help pages work when selected from the page index on the right even though navigating through the in-page hyperlinks still works, I assume because the docs are built dynamically whereas the index uses a path that gets registered separately with KHelpCenter upon package installation. Everything in the index is still looking in `/usr/share/kvirc/4.9/help`, which obviously doesn't work since the 5.0 release. That's as far as I got with it, let me know if there's more info that would help you track it down.

**Comment by AlexanderP** [comment]
Hi.
Uploaded to ppa: [~kvirc/kvirc](https://launchpad.net/~kvirc/+archive/ubuntu/kvirc)
