### ISSUE TITLE
Accept command for caller id pass nothing when - is used

### ISSUE THREAD

**Issue by Seeder101** [kvirc/KVIrc#2474]
Is this a bug report? Yes
==============================
/accept command doesn't work if you want to delete someone from the accept list 
but adding or displaying the list works ok with /accept *  or /accept nickname
if you want to delete someone you must use /accept -nickname and that doesnt pass right to the server and result in a /accept raw only without any input 
![Screenshot from 2020-06-01 21-59-11](https://user-images.githubusercontent.com/7802688/83443878-29474980-a453-11ea-8e89-e37206f71906.png)

I'm using KVIrc 5.0.0 fedora package 

Is this a feature request? No
==============================

Thank you for helping us improve KVIrc!

**Comment by ctrlaltca** [comment]
The "-" char followed by a word is considered a command parameter; if you want to send it to the server, you need to escape it using a "\" or to prefix your command with /raw:
```
/accept \-nickname
/raw accept -nickname
```
