### ISSUE TITLE
Server Context in Script-Tester

### ISSUE THREAD

**Issue by johnbraker** [kvirc/KVIrc#2477]
Hey hey,

in KVIRC 4 as a IRC-Operator i used to use the Script-Tester as a quick and easy way to run small "one time use" multilined scripts on the server. (e.g. for editing multible channels modes or access lists)

As of KVIRC 5 the Script-Tester isn't associated with the first IRC-Context anymore. All in all thats a nice feature - its neat to have the output right beside the script. But how can i connect the Script-Tester-Kontext to an Server. I guess its a oneliner but I'm lost. 

Please help :)

**Comment by wodim** [comment]
[rebind](http://kvirc.net/doc/cmd_rebind.html)?

**Comment by johnbraker** [comment]
Thats it! Thank you very much. I had a look in the documentation but i just couldnt find the right command. 

Thanks again!
