### ISSUE TITLE
Spacing in typing box wrong depending on scaling

### ISSUE THREAD

**Issue by gregorius-ov** [kvirc/KVIrc#2482]
I've got 2 monitors with different resolution and scaling. 1920x1080 and 125% scaling, 1680x1050 and 100% scaling. If the KVIrc window is on the monitor with 100% scaling, the spacing between words is completely off. Picture: https://prnt.sc/tqlbln
As soon as I move the window onto the other screen, the size of the window changes and the spacing returns to normal.
Issue appears with 100% scaling on both screens.

Windows 10
KVIrc 5.0.1 'Aria'

KVIrc 5.0.1 'Aria'

Laufzeitinformationen:
System-Name: Windows Release : 10.0.18363
System-Version: Windows 10 vNext Pro (x64) (Build 18363)
Architektur: Intel64 Family 6 Model 94 Stepping 3
Qt-Version: 5.9.9
Qt-Theme: windowsvista

Erstellungsinfo:
Build-Datum: 2020-07-22 13:11:18 UTC
Quellcode-Datum: 20200722
Revisionsnummer: 5.0.0-85-ge68b21c95
CPU-Name: AMD64
Build-Kommando: C:/Program Files (x86)/CMake/bin/cmake.exe
Buildflags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler-Name: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
Compilerflags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt-Version: 5.9.9
Funktionen: IRC, IPv6, Crypt, SSL, IPC, Transparency, Perl, Python, Enchant, Qt5, KVS
OpenSSL version: OpenSSL 1.0.2s 28 May 2019
OpenSSL compiler flags: "compiler: cl -utf-8 -FS /MD /Ox -DOPENSSL_THREADS -DDSO_WIN32 -utf-8 -FS -W3 -Gs0 -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -DUNICODE -D_UNICODE -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DOPENSSL_USE_APPLINK -I. -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_SSL2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_WEAK_SSL_CIPHERS -DOPENSSL_NO_DYNAMIC_ENGINE "
OpenSSL built on: reproducible build, date unspecified

**Comment by DarthGandalf** [comment]
> This might always happen with 100% scaling?

Please try and tell

**Comment by AndrioCelos** [comment]
It doesn't happen on any of my PCs with 100% scaling.

**Comment by wodim** [comment]
Reminds me of #2302

**Comment by ctrlaltca** [comment]
We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix and report if this issue is still present. Thank you
