### ISSUE TITLE
Lag Meter Showing Wrong Ping

### ISSUE THREAD

**Issue by swarfega** [kvirc/KVIrc#2483]
I noticed recently that the lag meter in the status bar seems to be showing the highest ping spike rather than the average. I wonder if this could be looked at please.
![lagmeter](https://user-images.githubusercontent.com/2217248/88892220-6013c300-d23c-11ea-9032-bbbe87be078a.png)

**Comment by DarthGandalf** [comment]
Lag meter is not about your bouncer, it's e2e. Add ping from your bouncer to the IRC server you're connected to

**Comment by swarfega** [comment]
<@LunarBNC> [lunarirc] <Casper> It's a simple ping to de.lunarbnc.net, as all instances are on there it should all be the same. (The status page uses a HTTP GET to detect the speed though)
[08:32:18] <swarfega> i did that but im reporting the ping to kvirc devs and they want it direct from the bnc
[08:32:18] <swarfega> Add ping from your bouncer to the IRC server you're connected to
[08:32:47] <@LunarBNC> [lunarirc] <Casper> Ah, as end-user that's not possible I think.
[08:33:02] <swarfega> hmm
[08:33:18] <swarfega> unless theres a ping module
[08:33:53] <@LunarBNC> [lunarirc] <Casper> Which, as far as I know, there isn't..

**Comment by DarthGandalf** [comment]
In that case, if you subtract the numbers, you'll get approximate ping from bouncer to server :) Also subtract overhead for SSL, processing the message by IRC server, processing the response by KVIrc, processing both messages by ZNC, etc.

**Comment by swarfega** [comment]
So its probably better not to use lag meter then and just occasionally ping the server.

**Comment by DarthGandalf** [comment]
That depends on what you want to use the lag meter for. When I see it going to high numbers, it means that soon `*status` will tell me that it timed out.

**Comment by wodim** [comment]
Lag meter measures your latency to the IRC server and ping measures your latency to your bouncer. When you are using a bouncer the former will be naturally much higher than the latter.

**Comment by swarfega** [comment]
ok thanks Wodim.

Where have you been ?

**Comment by wodim** [comment]
Lockdown. Haven't you heard?

**Comment by swarfega** [comment]
Doesnt mean you cant be online :p

**Comment by swarfega** [comment]
![lagmeter2](https://user-images.githubusercontent.com/2217248/90308025-d4549480-ded3-11ea-9746-1a43d8290fce.png)
![ping2](https://user-images.githubusercontent.com/2217248/90308027-d4ed2b00-ded3-11ea-94ad-57e066fc6db2.png)

**Comment by DarthGandalf** [comment]
Lag meter is correct. It just calculates not the thing you expect it to.

**Comment by swarfega** [comment]
Perhaps we should have a ping meter as well :D

**Comment by wodim** [comment]
In what way would that be useful?

**Comment by swarfega** [comment]
For showing the correct ping and how bad your lag is [not].

**Comment by DarthGandalf** [comment]
You can see ping to the bouncer already, using ping command in terminal.

Your lag though depends not only on that ping, but also on ping between bouncer and server. So the number shown by current lag meter is correct.
