### ISSUE TITLE
Missing Visuals

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [kvirc/KVIrc#2484]
I followed the setup guide for windows. Had to manually copy the module .DLLs and create a `module` folder as well but other than that, the experience has been rather smooth. 

Now that I had built and provided all the modules, I thought I would begin to see some visuals. Unfortunately this is what I get (I've commented out the server I'm connected to):

![Untitled](https://user-images.githubusercontent.com/91709/89371708-b607c100-d6a9-11ea-8785-5dd0800251f2.png)

No icons, no images, and no themes. What am I missing here? Having a warning for an improper configuration for this behavior would be nice. The closest I got to that was 2 back-to-back popups asking to restore my themes and settings, both which I granted "Yes" and  "Restore". It didn't seem to do anything the first or the second time it asked.

**Comment by DarthGandalf** [comment]
> I followed the setup guide for windows.

Which one? Did you build yourself? Which version?

> Had to manually copy the module .DLLs

Why? Copy from where to where?

**Comment by TheMaverickProgrammer** [comment]
https://github.com/kvirc/KVIrc/wiki/Compiling-KVIrc-on-Windows

I said I had to copy the output DLLs from the /modules output.

**Comment by DarthGandalf** [comment]
If you run `nmake install`, you don't need to copy any "modules" anywhere manually. It will also copies images etc for you.

I wonder why that guide says to use robocopy instead of windeployqt to copy Qt DLLs (https://github.com/kvirc/KVIrc/blob/master/.appveyor.yml#L129)

**Comment by wodim** [comment]
That guide predates windeployqt.

**Comment by TheMaverickProgrammer** [comment]
I used cmake and the opened the project in visual studio

**Comment by DarthGandalf** [comment]
So.... you didn't really follow the guide you linked. The guide says to use cmake with nmake

**Comment by TheMaverickProgrammer** [comment]
nmake is window's makefile build tool. and vs uses it. I've never come across a build guide for modern software that required CLI for the entire project. Are you not using IDEs??

**Comment by DarthGandalf** [comment]
The "install" option is required to have images and modules in the correct place. That option is available via nmake. You're free to find it in VS without using nmake. Maybe it's available without nmake, I don't know. If you find it, please say so.

You could also use the prebuilt version instead of building KVIrc yourself. I think that's even more common for Windows.

**Comment by DarthGandalf** [comment]
The guide is written this way because it's partially based on https://github.com/kvirc/KVIrc/blob/master/.appveyor.yml which is used by automation to build the prebuilt version from git. GUI-based build is not very automateable.

**Comment by TheMaverickProgrammer** [comment]
I wanted to experiment with potential features from source. I'll check out CLI only and see if it works.
