### ISSUE TITLE
KVS Feature Request: Persistent variables across sessions

### ISSUE THREAD

**Issue by JinxDojo** [kvirc/KVIrc#2490]
It would be very helpful to be able to declare variables not only "global" but "persistent" so that they will save across sessions. Currently, it seems manual file writing is necessary, but it does not seem straightforward to create a system to "automatically" handle saving all or some selection of global variables (i.e. by reading/writing on KVIrc Open/Close events, respectively).

Variables of different types would require different encodings. Worse: a client crash would still mean loss of all such variables. (Whereas a "persistent" command setter like "set" or "setvar" could be used to save the variable to file upon the setting itself [or it could all be done in one command like "savevars"])

(A somewhat related but too-small-for-its-own-entry request: please create a "local" command to declare variables that begin with capital letters as local, just as "global" can declare lowercase variables global.)

Thank you for considering this feature request.

**Comment by wodim** [comment]
http://kvirc.net/doc/module_config.html

**Comment by JinxDojo** [comment]
Hello wodim; thank you for the reply. I appreciate the suggestion.

Unfortunately, while a file method like that can be used to directly store things from a script, it does not store variables properly without some sort of encoding--which would each be dependent on the datatype. This seems like something better (and more efficiently) done on the engine level, rather than re-inventing the wheel at the script level.

**Comment by wodim** [comment]
http://kvirc.net/doc/fnc_serialize.html
