### ISSUE TITLE
Error in parameter translation in file objects_es.po

### ISSUE THREAD

**Issue by solmon4devx** [kvirc/KVIrc#2496]
Incorrectly translated parameter identifier in the file objects_es.po line 308

```
#: src/modules/objects/KvsObject_memoryBuffer.cpp:131
msgid "Index '%I' out of the buffer size"
msgstr "El índice «%l» es mayor que el tamaño del búfer"
```

in the untranslated line there is a capital letter i in the translated file there is a lower case letter L

**Comment by wodim** [comment]
I have fixed it in Transifex, not sure how to import it (@Dessa?)
