### ISSUE TITLE
kvirc timer

### ISSUE THREAD

**Issue by p0pebp** [kvirc/KVIrc#2497]
Issue KVirc Timer not working..
[06:44:37] [RAW]: timer(test,1000){ echo "Hello!"; }
[06:44:37] timer(test,1000){ is an unknown server command
[06:45:02] [RAW]: timer (test,1000){ echo "using /timer"; }
[06:45:02] timer is an unknown server command
[06:45:15] [RAW]: .timer(test,1000){ echo "using .timer"; }
[06:45:15] .timer(test,1000){ is an unknown server command
[06:45:28] [RAW]: timer(test,1000){ echo "using timer"; }
[06:45:28] timer(test,1000){ is an unknown server command

HELP AND ABOUT BELOW
KVIrc 5.0.0 'Aria'

Runtime Info:
System name: Linux 5.10.0-kali2-amd64
System version: #1 SMP Debian 5.10.9-1kali1 (2021-01-22)
Architecture: x86_64
Qt version: 5.15.2
Qt theme: breeze

Build Info:
Build date: 2020-11-19 19:27:56 UTC
Sources date: 20160102
Revision number: 
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: -g -O2 -fdebug-prefix-map=/build/kvirc-WPAzEI/kvirc-5.0.0+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2
Qt version: 5.15.1
Features: IRC, Debug, IPv6, Crypt, SSL, IfAddr, IPC, KDE, Transparency, Phonon, Webkit, DCCVoice, Perl, Python, Enchant, Qt5, KVS
OpenSSL version: OpenSSL 1.1.1i 8 Dec 2020
OpenSSL compiler flags: compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -ffile-prefix-map=/build/openssl-w7jO3z/openssl-1.1.1i=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OpenSSL built on: Sat Jan 30 13:06:46 2021 UTC

**Comment by DarthGandalf** [comment]
You're using friendly mode instead of KVS mode of the input line. Uncheck the friendly mode on the right bottom side.
