### ISSUE TITLE
$str.grep issues

### ISSUE THREAD

**Issue by CW-151** [kvirc/KVIrc#2501]
The following line produces a human readable copy of the log of the respective channel in the GREP window. The 'search' item is ignored.

%search = 'joined"   # (or anything you want)
%w = "GREP"
echo -w=$window(%w) $str.grep( "%search"  ,$str.split($cr$lf,$file.read($log.file)),"w" )

I have tried this with %search = "*joined*" , same result.
I have tried this with no flags, "w" and "r", same result
Is there something special or weird about the KV log files?

**Comment by Ionic** [comment]
There are multiple potential pitfalls here.

First, your quotes are mismatched in the first line.

Secondly, the log files can be gzip-compressed. In that case, you'd grep through binary, compressed data, which is not likely to get you your desired result. Given that `$str.grep` returns (essentially) everything in the searched file, that's likely not the issue you're seeing.

Then, I'm not sure what line ending KVIrc uses on different operating systems. It might be CRLF on Windows and LF on UNIX-like operating systems, but I'm not sure. In any case, if you find that grep does indeed output the full log file, that likely means that splitting the string failed. Find out the actual line ending.

**Comment by CW-151** [comment]
The quotes may be mismatched cuz I typed them into the message manually. Bumping up the window size in my Firefox shows that I used ' instead of ".. My typing isn't always the best :D.  
When the split function is not used, the text(from multiple log file lines) is all put end-to-end, and it becomes impossible to read. (Why they did this is beyond me)
When opening the log file with a text editor, it shows perfectly fine, and also WITH the split on $CF$LF. (So not binary file)
However, I did try the sample and it seemed to work..
echo $str.grep("^a",$chan.users,"r")

I am stumped.

**Comment by Ionic** [comment]
>When the split function is not used, the text(from multiple log file lines) is all put end-to-end, and it becomes impossible to read. (Why they did this is beyond me)

This totally makes sense. The `$str.split()` function takes an array of strings as its input and returns all string array elements that match the needle string. If you don't split the string, it'll be automatically converted into a string array with one element. That'll naturally match and essentially return the full log file as one big string. No surprises there.

> When opening the log file with a text editor, it shows perfectly fine, and also WITH the split on $CF$LF. (So not binary file)

Again, you'll have to make sure to find out what the actual line ending is. On Windows systems, the line ending is commonly `\r\n` or `$cr$lf`, but that's all application-defined. If KVIrc writes log files with `$lf`/`\n` line endings (which is customary on UNIX-like systems) and you split on `\r\n`, splitting will fail to produce the expected result and instead, again, just return an array with one element - the whole log file as it is.

Text editor won't usually show the line endings directly (at least simple ones or by default), so open up the file in a hex editor and look at the last bytes of a line. `\n` maps to `0x0a`, while `\r` maps to `0x0d`. If you see both, that's `\r\n`/`$cr$lf`, otherwise `\n`/`$lf` only and you finally know on what to split.

This might especially be problematic if transferring/working with log files created on different operating systems. I don't know if KVIrc values compatibility over OS fidelity in this respect and am too lazy to check.

**Comment by CW-151** [comment]
Well, it appears we have digressed from the actual issue. I have identified that KVirc uses $cr$lf when saving .txt/log files, so using $str.split(...) works fine. 

The issue remains that the log file cannot for some reason be sucked into a window(for lack of a better term).

%w is the window name, `@tracker`
%search comes from a dialog.textinput
echo -w=$window(%w) $str.grep("%search" ,$str.split($cr$lf,$file.read($log.file)),"r")
the result is everything in the log.. $str.grep does not appear to be working here. The `@tracker` window contains the entire log file. :(
Am I doing something wrong, or is this a bug in KVirc?

**Comment by CW-151** [comment]
I am now convinced that this is a bug in KVirc.

The following code produces incorrect result:

dialog.textinput -d="Enter something" ("Tracker"," ","GO","Cancel") {
if ($0 == 1) { halt; }
%w = "TRACKER"
if(!$window.exists($window(%w))) { 
	$window.open("m", %w,$context, 39) 
	}
system.setClipboard  $str.split($cr$lf,$file.read($log.file)) 
echo -w=$window(%w)  $str.grep($1,$system.clipboard())
}

Use your fav text edit and paste the result in.,., it should include only lines that contain the search argument ($1), but does not.

Conversely, using a single statement (bypassing the clipboard) produces the same result..
echo -w=$window(%w)   $str.grep($1,$str.split($cr$lf,$file.read($log.file)))
.


KVIrc 5.0.0 'Aria'

Runtime Info:
System name: Windows Release : 10.0.19041
System version: Windows 10 (x64) (Build 19041)
Architecture: Intel64 Family 6 Model 94 Stepping 3
Qt version: 5.9.7
Qt theme: windowsvista

Build Info:
Build date: 2019-01-02 01:21:58 UTC
Sources date: 20190101
Revision number: 5.0.0
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.9.7
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Perl, Python, Enchant, Qt5, KVS
OpenSSL version: OpenSSL 1.0.2o 27 Mar 2018
OpenSSL compiler flags: "compiler: cl -utf-8 -FS /MD /Ox -DOPENSSL_THREADS -DDSO_WIN32 -utf-8 -FS -W3 -Gs0 -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -DUNICODE -D_UNICODE -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DOPENSSL_USE_APPLINK -I. -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_SSL2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_WEAK_SSL_CIPHERS -DOPENSSL_NO_DYNAMIC_ENGINE "
OpenSSL built on: reproducible build, date unspecified

OS: Windows 10 Home 64 bit

**Comment by wodim** [comment]
`echo $str.grep("is", $str.split($cr$lf, "this$cr$lf\is$cr$lf\a$cr$lf\test"))` works as expected.

Can you attach a .log file here? Without editing or copypasting it. Just drag it from the log folder onto the github tab.

**Comment by CW-151** [comment]
[channel_#café.abjects_2021.03.26.log](https://github.com/kvirc/KVIrc/files/6213735/channel_.cafe.abjects_2021.03.26.log)

The log file is from the kvirc]log folder. standard issue

**Comment by wodim** [comment]
That's $lf, not $cr$lf

**Comment by CW-151** [comment]
OK, let's take a step backwards..
using this code:  echo -w=$window(%w)   "$log.file"
produces:
[15:11:53] C:/KVIrc/log/channel_#tst.abjects_2021.03.26.log
it does not send the contents of the log file.
----------------------------------------------------------------------
using this code:  echo -w=$window(%w)  $str.grep( $1, $str.split( $lf,$file.read($log.file)) )   (notice using $lf only)
produces: blank window
----------------------------------------------------------------------
using this code: echo -w=$window(%w)  $str.grep( $1, $str.split($cr$lf,$file.read($log.file)) )  (notice, using $cr$lf)
produces:  readable data but not 'grep'd. the entire log is dumped into the window.

This appears to also be channel dependent. my #tst channel produces blank window, despite have plenty of data. In other channels, the entire log is dumped into the window.

I challenge you to implement the script as above, and see for yourself. Use any channel to get the corresponding log file.

**Comment by wodim** [comment]
It works fine for me.

`/foreach (%line, $str.grep("join", $str.split($lf, $file.read($log.file)))) echo %line`

This prints a list of all joins to the current window.

**Comment by wodim** [comment]
Also take into account log files are not updated immediately after every line. They are flushed to the disk every x minutes (configurable). To flush them immediately call `log.flush`

**Comment by wodim** [comment]
Feel free to reopen if you still think this is an issue in the client.
