### ISSUE TITLE
Font scaling on Windows 10

### ISSUE THREAD

**Issue by swarfega** [kvirc/KVIrc#2503]
Kvirc seems to not be able to handle font scaling very well. If I set scaling to 120% in Windows 10, the input bar text doesnt show spaces so the text is all one line. The only way I know how to remedy this is to edit theme, go to input, click on font then ok out without changing anything. It shows as expected after that.

**Comment by ctrlaltca** [comment]
We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix and report if this issue is still present. Thank you
