### ISSUE TITLE
kvilib/core/KviPointerHas hTable.h:174: possible infinite recursion

### ISSUE THREAD

**Issue by dcb314** [kvirc/KVIrc#2505]
kvilib/core/KviPointerHashTable.h:174:1: warning: all paths through this function will call itself [-Winfinite-recursion]

Source code is

inline bool kvi_hash_key_equal(const KviCString & szKey1, const KviCString & szKey2)
{
        return kvi_hash_key_equal(szKey1.ptr(), szKey2.ptr());
}

**Comment by DarthGandalf** [comment]
Where you get this warning from?

**Comment by dcb314** [comment]
clang, a C++ compiler, with flag -Wall.

**Comment by wodim** [comment]
Doesn't look like that code is called from anywhere

**Comment by DarthGandalf** [comment]
I see other kvi_hash_key_equal functions, but they have an additional bool param; with it, the inner call would choose a different overload. But as is, it looks like recursion yes
