### ISSUE TITLE
CI builds are broken

### ISSUE THREAD

**Issue by ctrlaltca** [kvirc/KVIrc#2513]
Travis-ci.org is in read-only mode and all builds are ceased.
Travis-ci.com or Github actions can be used instead.

Appveyor builds are broken and needs fixing.

**Comment by DarthGandalf** [comment]
> Travis-ci.com

They have an awful pricing model for OSS now. Every once in a while we'd need to ask them to give us more minutes.

Github actions can be used, yes. Circle CI or Gitlab CI are also an option.

**Comment by DarthGandalf** [comment]
Or Jenkins

**Comment by ctrlaltca** [comment]
fixed by #2542 and #2550
