### ISSUE TITLE
KVirc Breaks after Update

### ISSUE THREAD

**Issue by swarfega** [kvirc/KVIrc#2515]
I launched KVirc today and it said there was an update so I let it update. When I restarted KVirc it said do you want to restore settings. Last time I said yes but this time I said no and the result was the same.

It lost the tool bar, theming and custom server information so it is currently unusable.

I am using KVirc 5.0.1 on KDE 5.22.5
![Screenshot_20210927_124125](https://user-images.githubusercontent.com/2217248/134901520-0159ab32-51a5-43e9-97ae-3be5fd59be66.png)

**Comment by ctrlaltca** [comment]
We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix and report if this issue is still present. Thank you
