### ISSUE TITLE
Unable to build KVirc - distros are dropping QtWebkit for security reasons

### ISSUE THREAD

**Issue by lemmy04** [kvirc/KVIrc#2517]
Recently, distributions (namely openSUSE Tumbleweed) have started to drop QtWebkit - so applicxations that need it have stopped working.

Is there a way to build kvirc without it?

**Comment by wodim** [comment]
Disabling WANT_QTWEBKIT should do it.

**Comment by DarthGandalf** [comment]
Dupe of #2178
