### ISSUE TITLE
Can not compile : Qsound not fount

### ISSUE THREAD

**Issue by racine-p-a** [kvirc/KVIrc#2520]
Hello, I wanted to reinstall my beloved irc software on my PC but I failed miserably to install it.

Not sure if it is a bug or a mistake I made. (This might be related to this [issue](https://github.com/kvirc/KVIrc/issues/2166) )

I should have all dependencies.

Here are the steps to reproduce : 
```bash
sudo apt install cmake gettext qt5-default libxmu-dev libxmu-headers freeglut3-dev libxext-dev libxi-dev libperl-dev
mkdir release
cd release
cmake ..
make
```

Whatever the options I used during the `make`, I still got this error : 
```log
/home/user/Logiciels/KVIrc-5.0.0/src/modules/snd/libkvisnd.cpp:37:10: fatal error: QSound: No such file or directory
   37 | #include <QSound>
      |          ^~~~~~~~
compilation terminated.
make[2]: *** [src/modules/snd/CMakeFiles/kvisnd.dir/build.make:76: src/modules/snd/CMakeFiles/kvisnd.dir/libkvisnd.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:8461: src/modules/snd/CMakeFiles/kvisnd.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

- KUbuntu 20.04
- QMake version 3.1
- cmake version 3.16.3
- gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
- msgfmt (GNU gettext-tools) 0.19.8.1
- perl  5.30
- libgsm.so.1.0.18

Did I make a mistake ? If so, which one ? In case of a bug, how to solve it ?

Best regards,

**Comment by ctrlaltca** [comment]
Please ensure the libqt5multimedia5 package is installed.
If it is, try installing also the qtmultimedia5-dev package.
You may need additional -dev packages, if you get similar errors for other files.
Unfortunately i don't have an ubuntu pc available right now to test exactly the needed packages.

**Comment by racine-p-a** [comment]
Thank you for your answer @ctrlaltca : `qtmultimedia5-dev` was indeed the missing package. But I have another problem now :/

A `make install` gives this :
```log
[100%] Automatic MOC for target kviperl
[100%] Built target kviperl_autogen
[100%] Built target kviperl
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/share/applications/kvirc.desktop
CMake Error at data/applnk/cmake_install.cmake:49 (file):
  file INSTALL cannot set permissions on
  "/usr/local/share/applications/kvirc.desktop": Operation not permitted.
Call Stack (most recent call first):
  data/cmake_install.cmake:42 (include)
  cmake_install.cmake:42 (include)


make: *** [Makefile:74: install] Error 1
```

I tried (stupidly) with a `sudo make install` and all errors disappeared BUT when i try to launch kvirc, I get : 
```log
kvirc: error while loading shared libraries: libkvilib.so.5: cannot open shared object file: No such file or directory
```

Do you have any clue ?

**Comment by wodim** [comment]
https://github.com/kvirc/KVIrc/wiki/FAQ#after-compiling-from-source-i-get-an-error-loading-the-libkvilib-shared-library-when-i-try-to-run-kvirc

I recommend option 2

**Comment by racine-p-a** [comment]
It works ! It works ! Thank you very much ! @wodim @ctrlaltca 
I will test all these steps on a KUbuntu 22.04 too.
Do you think it would be useful to update the documentation on this point (on a more DebIan/Ubuntu related PoV). I would gladly help for both (20.04 and 22.04).
