### ISSUE TITLE
Project Status and Download pages are out-of-date (lists 4.2.0 instead of 5.0.0)

### ISSUE THREAD

**Issue by knakamura8** [kvirc/KVIrc#2522]
The Project Status page found here http://www.kvirc.net/?id=status&lang=en references 4.2.0 Equilibrium, rather than 5.0.0 Aria.

Similarly, the Download page found here http://www.kvirc.net/?id=download&lang=en is out-of-date.

**Comment by ctrlaltca** [comment]
Closing, merging with #2524
