### ISSUE TITLE
PVS-Studio issues

### ISSUE THREAD

**Issue by nmariusp** [kvirc/KVIrc#2527]
I have Kubuntu 22.04. I have installed Qt5 using kdesrc-build. I have built https://github.com/kvirc/KVIrc using this Qt. Pseudocode:

git clone https://github.com/kvirc/KVIrc
cd KVIrc && mkdir build && cd build

export CMAKE_PREFIX_PATH=/home/n/kde/qt5:/home/n/kde/usr
export XDG_DATA_DIRS=/home/n/kde/usr/share:/usr/share/plasma:/usr/local/share:/usr/share:/var/lib/snapd/desktop
export PKG_CONFIG_PATH=/home/n/kde/usr/lib/pkgconfig:/home/n/kde/qt5/lib/pkgconfig
export PATH=/home/n/kde/usr/bin:/home/n/kde/qt5/bin:/home/n/kde/src/kdesrc-build:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
export CMAKE_MODULE_PATH=/home/n/kde/qt5/lib/cmake:/home/n/kde/usr/lib64/cmake:/home/n/kde/usr/lib/cmake
export LD_LIBRARY_PATH=/home/n/kde/usr/lib:/home/n/kde/qt5/lib

cmake -B . -S .. -G Unix\ Makefiles -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS:STRING=-pipe -DCMAKE_INSTALL_PREFIX=/home/n/kde/usr -DCMAKE_PREFIX_PATH=/home/n/kde/qt5
pvs-studio-analyzer trace -- make -j `nproc`

pvs-studio-analyzer analyze -j `nproc` -o PVS-Studio.log

plog-converter -a GA:1,2 -d V1042,V1053,V1044 -t tasklist -o report.tasks PVS-Studio.log

The file report.tasks can be opened with Qt Creator. File > Open File or Project. It will be shown in the "Issues" Output Pane (Alt+1).

Attached is the file report.tasks
[report.tasks.txt](https://github.com/kvirc/KVIrc/files/8986585/report.tasks.txt)

**Comment by ctrlaltca** [comment]
Unless you plan to help fixing any issue present in your report, i'm closing this issue.
