### ISSUE TITLE
Default font is not monospace

### ISSUE THREAD

**Issue by gizmore** [kvirc/KVIrc#2528]
The current default font in KVIrc is not a monospace font.

ASCII-Art is part of the IRC culture and thus we should set a monospace font as default font in the shipped themes so people can enjoy ascii art.

**Comment by ctrlaltca** [comment]
During the initial setup you were asked to choose a theme.
You chose the "Fancy" one, that by default is using a sans serif-like font.
You can choose the other "Minimalist" theme, that is using a monospaced font by default.
At any time you can just enter the settings and choose either a global font or a specific for for each section.
