### ISSUE TITLE
KVIrc doesn't remember Bold fonts in themes

### ISSUE THREAD

**Issue by GerbilSoft** [kvirc/KVIrc#2532]
Setting the font for e.g. input, output, userlist, etc. to Terminus Bold works for the current session, but on restarting KVIrc, those fonts are set to Terminus Normal. It seems the font-weight isn't saved in the theme configuration.

**Comment by ctrlaltca** [comment]
This has been fixed in  #2568 
We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix and report if this issue is still present. Thank you
