### ISSUE TITLE
windows crash on latest nightly build

### ISSUE THREAD

**Issue by majinsnake** [kvirc/KVIrc#2533]
Is this a bug report? Yes

Describe what the problem is. 

Downloaded build 5.0.0 and was crashing constantly within the application. Updated to the nightly build 5.0.0.86. I am still crashing.

Attach screenshots if you feel like they will help explain the issue better.
If you can, click "Help → About KVIrc", go to the "Executable Information" tab and copy its contents here. That may help us diagnose the issue.

**Executable information**

KVIrc 5.0.1 'Aria'

Runtime Info:
System name: Windows Release : 10.0.19043
System version: Windows 10 vNext Pro (x64) (Build 19043)
Architecture: AMD64 Family 25 Model 33 Stepping 2
Qt version: 5.9.9
Qt theme: windowsvista

Build Info:
Build date: 2020-07-26 13:29:22 UTC
Sources date: 20200726
Revision number: 5.0.0-86-g20f5ed912
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.9.9
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Perl, Python, Enchant, Qt5, KVS
OpenSSL version: OpenSSL 1.0.2s 28 May 2019
OpenSSL compiler flags: "compiler: cl -utf-8 -FS /MD /Ox -DOPENSSL_THREADS -DDSO_WIN32 -utf-8 -FS -W3 -Gs0 -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -DUNICODE -D_UNICODE -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DOPENSSL_USE_APPLINK -I. -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_SSL2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_WEAK_SSL_CIPHERS -DOPENSSL_NO_DYNAMIC_ENGINE "
OpenSSL built on: reproducible build, date unspecified

I copied the log file from **Event viewer from General TAB.**

Faulting application name: kvirc.exe, version: 5.0.1.0, time stamp: 0x5f1d880e
Faulting module name: Qt5Core.dll, version: 5.9.9.0, time stamp: 0x5de6ca0a
Exception code: 0xc0000005
Fault offset: 0x00000000001cd24b
Faulting process id: 0x170
Faulting application start time: 0x01d8df0020ece5e9
Faulting application path: C:\Program Files\KVIrc\kvirc.exe
Faulting module path: C:\Program Files\KVIrc\Qt5Core.dll
Report Id: c3b6f3c1-e231-4777-aef0-04037ae7ead0
Faulting package full name: 
Faulting package-relative application ID: 

Please fix this crashing issue.

**Comment by pageninetynine** [comment]
experiencing the same issue. usually crashes ~10 minutes after opening

**Executable information**
KVIrc 5.0.1 'Aria'

Runtime Info:
System name: Windows Release : 10.0.17763
System version: Windows 10 2019 Enterprise 2015 LTSB (x64) (Build 17763)
Architecture: Intel64 Family 6 Model 151 Stepping 2
Qt version: 5.9.9
Qt theme: windowsvista

Build Info:
Build date: 2020-07-26 13:29:22 UTC
Sources date: 20200726
Revision number: 5.0.0-86-g20f5ed912
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.9.9
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Perl, Python, Enchant, Qt5, KVS
OpenSSL version: OpenSSL 1.0.2s 28 May 2019
OpenSSL compiler flags: "compiler: cl -utf-8 -FS /MD /Ox -DOPENSSL_THREADS -DDSO_WIN32 -utf-8 -FS -W3 -Gs0 -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -DUNICODE -D_UNICODE -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DOPENSSL_USE_APPLINK -I. -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_SSL2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_WEAK_SSL_CIPHERS -DOPENSSL_NO_DYNAMIC_ENGINE "
OpenSSL built on: reproducible build, date unspecified

**Event viewer**
Faulting application name: kvirc.exe, version: 5.0.1.0, time stamp: 0x5f1d880e
Faulting module name: Qt5Core.dll, version: 5.9.9.0, time stamp: 0x5de6ca0a
Exception code: 0xc0000005
Fault offset: 0x00000000001cd24b
Faulting process id: 0x2360
Faulting application start time: 0x01d95578fad0474f
Faulting application path: C:\Program Files\KVIrc\kvirc.exe
Faulting module path: C:\Program Files\KVIrc\Qt5Core.dll
Report Id: 53b8a10b-3e6a-4cdd-aa31-97f81797270d
Faulting package full name: 
Faulting package-relative application ID:

**Comment by ctrlaltca** [comment]
Can you please try a more recent build like the autogenerated one you can find at the end of this page?
https://ci.appveyor.com/project/DarthGandalf/kvirc/builds/47721944/job/3gg5k6xvow7rtmat/artifacts

**Comment by majinsnake** [comment]
> Can you please try a more recent build like the autogenerated one you can find at the end of this page? https://ci.appveyor.com/project/DarthGandalf/kvirc/builds/47721944/job/3gg5k6xvow7rtmat/artifacts

I went with 5.0.1 version found on the main kvirc page. The beta version i think it is. I could not find a recent build on the link you provided.

**Comment by ctrlaltca** [comment]
> I could not find a recent build on the link you provided.

Sorry, the link expired. Try this one: https://ci.appveyor.com/project/DarthGandalf/kvirc/build/job/bgiq20ayprp5foy0/artifacts

**Comment by ctrlaltca** [comment]
We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix and report if this issue is still present. Thank you

**Comment by ValeZAA** [comment]
It still crashes on the latest commit on windows 11.

**Comment by ctrlaltca** [comment]
Possibly related to https://github.com/kvirc/KVIrc/pull/2578
@ValeZAA  We will release a beta2 shortly please keep tuned

**Comment by ValeZAA** [comment]
Okay, it crashed once and then no longer crashes anymore on beta2. Some state in the config files cleared? As I was testing https://github.com/kvirc/KVIrc/commit/30fc8596f77d38408b9234e6fb5ef7a5ceef6d41 the fix is indeed https://github.com/kvirc/KVIrc/commit/ee642156d181ae2a521b128ee0abcf01303aa2ee

**Comment by ctrlaltca** [comment]
@ValeZAA thank you for the feedback, hopefully  this is fixed then

**Comment by ValeZAA** [comment]
Yep, left it on 20 past hours, did not crash once.
