### ISSUE TITLE
Add registered users sound notification

### ISSUE THREAD

**Issue by DynV** [kvirc/KVIrc#2534]
I'd like to be able to set a sound for registered users notification; there doesn't seem to be one in General Options :: Sound on v5.0.1 for Windows.

This a feature request but I can't seem to be able to set it as so; if there's a way to do so I'd like to know about it in case I want to do another one.

Thanks you for your consideration

**Comment by ctrlaltca** [comment]
We should really remove those builtin sound events.
You request can be accomplished with one line of KVS scripting, adding an event handler for OnNotifyOnline that calls snd.play <file>.
