### ISSUE TITLE
Install KVIRC beta

### ISSUE THREAD

**Issue by Indavoid** [kvirc/KVIrc#2536]
Hi !

How to updta to beta using terminal on linux please ? 

Can you add the smartphone smileys to KVIRC ?

Thanks,

**Comment by ctrlaltca** [comment]
We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix 
Hopefully it will be updated in your distro when the new version is released.
In the meanwhile, we can't help you if you don't state at least the distro/version you are trying to compiler kvirc on.
