### ISSUE TITLE
download for macOS doesn't work http://www.kvirc.net/?id=releases&platform=macosx&version=5.0.0&lang=it

### ISSUE THREAD

**Issue by diamondszx** [kvirc/KVIrc#2537]
http://www.kvirc.net/?id=releases&platform=macosx&version=5.0.0&lang=it

ftp://ftp.kvirc.net/pub/kvirc/5.0.0/binary/macosx/KVIrc-5.0.0.dmg download doesn't work 

![Schermata 2023-04-26 alle 21 50 53](https://user-images.githubusercontent.com/131913947/234687193-421df262-b130-4786-aa48-60b7365839db.png)

**Comment by wodim** [comment]
It works, you need an FTP client

**Comment by ctrlaltca** [comment]
Dup #2516
