### ISSUE TITLE
Installer launches 2 windows after "Previous versions of KVlrc must be uninstalled.": `KVIrc Uninstall` + `KVIrc Setup`

### ISSUE THREAD

**Issue by darkred** [kvirc/KVIrc#2546]
I've noticed that the KVIrc Installer (x64 on win11) launches 2 windows after "Previous versions of KVlrc must be uninstalled.": 
`KVIrc Uninstall` + `KVIrc Setup`.

The former window's process is `C:\Users\User\AppData\Local\Temp\~nsuA.tmp\Un_A.exe` and the latter is the running installer.

I believe it would be better, if possible, if there was only a single window at a time, first `KVIrc Uninstall` and then `KVIrc Setup`, to avoid confusion (because currently the 'Uninstall' window might miss your attention).

<details>
<summary>Screenshots of KVIrc-5.0.0-x86_64.exe on win11:</summary>

![2023-07-16_212732](https://github.com/kvirc/KVIrc/assets/723651/83422954-45f1-485c-95ae-7d5fe7aff8b9)
The two windows in taskbar:
![](https://github.com/kvirc/KVIrc/assets/723651/b10c1268-1608-4a97-925b-4d9f09a126dd)

<code>KVIrc Uninstall</code> window:

![2023-07-16_212825](https://github.com/kvirc/KVIrc/assets/723651/1d0976ce-baed-4bae-abdc-3f7eea77698d)

<code>KVIrc Setup</code> window:
![2023-07-16_212832](https://github.com/kvirc/KVIrc/assets/723651/0e0bdb4f-4912-4895-9ece-f776d6041131)

</details>

</details>

**Comment by abazaba855** [comment]
I've had this happen to me before as well. However, for me it was not consistent behavior (sometimes on some upgrades it happened, other times it didn't), and I don't know why.
