### ISSUE TITLE
KVIrc crashes

### ISSUE THREAD

**Issue by NikoZion** [kvirc/KVIrc#2553]
Hello, I'm on Windows 10. KVIrc crashes and closes on its own when I use it for a while.  Moreover, I have an error to install the Andaris script.  What can I do to solve these two problems please ?

**Comment by ctrlaltca** [comment]
Can you please try a more recent build like the autogenerated one you can find at the end of this page?
https://ci.appveyor.com/project/DarthGandalf/kvirc/builds/47721944/job/3gg5k6xvow7rtmat/artifacts

**Comment by NikoZion** [comment]
Thank you, I will try !

Edit : same problem.

**Comment by Nadineli** [comment]
Same here. Any version I try closes itself after a few minutes.

**Comment by ctrlaltca** [comment]
@Nadineli what version(s) did you try actually?

**Comment by probatya** [comment]
The recent build has a problem with nickserv identification.

**Comment by ctrlaltca** [comment]
Can you please state what recent build you tried?
In the "about KVIrc" menu you'll find something like `Revision number: 5.0.0-139-g4e922196f-dirty`
Also, can you elaborate on the nickserv prioblem?

**Comment by probatya** [comment]
5.0.0-140 and 5.0.0-143
Auto identification on nickserv doesn’t work at all.
I had fallback to build 5.0.0-86 and it worked properly.

**Comment by ctrlaltca** [comment]
Thank you, now that i knot that it doesn’t work at all it will be easy to fix it.
</sarcasm>
Without knowing the server/network you are connecting to, the way you are trying to authenticate (/msg nickserv, sasl, ...) or having any log of the failed authentication attempt, it will be very hard to see your issue fixed.

**Comment by probatya** [comment]
That issue on any server. Nothing happens at logs. It like no command being sent.

**Comment by ctrlaltca** [comment]
We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix and report if this issue is still present. Thank you
This is about the crash issue, for other issues (scripts not installing, chanserv/nickserv problems), please open a new issue.
