### ISSUE TITLE
Font selection issue

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#2567]
Gentoo Linux amd64, version 4a51c0e82d066349c0450a70d010c4e4e1d6ec00
Qt 5.15.11

![Выделение_488](https://github.com/kvirc/KVIrc/assets/325092/972e7277-63f1-4483-9c08-d219dbde0b56)

I was trying to report for #2566 which font I'm using , and clicked the Verdana button on the screenshot. The button has the same font as what I'm actually using. However, the font selection window claims that I have different font settings - the window claims Bold, while I'm using Italic.

**Comment by DarthGandalf** [comment]
In `main.kvc` this looks like `fontApplication=Verdana,10,0,50,i` for almost all fonts. `fontNotifierTitle=Verdana,10,0,75,bi` has the other value

**Comment by ctrlaltca** [comment]
I think the configuration part of the code is fine, since the font is correctly shown in the "Verdana" button.
You can check the value of fontInput for that specific value.
The "select font" dialog is a plain QFontDialog loading the font currently being used by the "Verdana" button:
https://github.com/kvirc/KVIrc/blob/a0f26877b7bd9dec18eb59b53eb55204f0c2609a/src/kvirc/ui/KviSelectors.cpp#L664

I'm not sure what is causing this issue.

**Comment by DarthGandalf** [comment]
This looks similar to https://forum.qt.io/topic/69152/qfontdialog-getfont-doesn-t-use-correct-font-style/11

Before clicking the button `font.toString()` returns "Verdana,10,-1,0,50,1,0,0,0,0", but after selecting the correct style in the dialog and clicking Ok the font becomes "Verdana,10,-1,0,50,1,0,0,0,0,Курсив" - and from now clicking the button selects the correct style. The only difference between the two strings is the localized name of the style in the last element.

**Comment by DarthGandalf** [comment]
It works correctly when I run with `LC_ALL=C`

**Comment by ctrlaltca** [comment]
Added a possible fix in https://github.com/kvirc/KVIrc/pull/2568
Seems like some fonts like Verdana includes localized version of the "style name", and is confusing QFontDialog.

**Comment by ctrlaltca** [comment]
The fix introduced a new bug.
KviCString tokenizer skips empty elements, so if one field in the option string is empty it will get the next one.
```
"Courier 10 Pitch,10,5,50,,"
family=Courier 10 Pitch pointSize=10 styleHint=5 weight=50 options=  stylename= 

"Courier 10 Pitch,10,5,50,,Regular"
family=Courier 10 Pitch pointSize=10 styleHint=5 weight=50 options=Regular stylename= 
```
As you can see "Regular" ended up in the options instead of stylename.
As a result, the font will be underlined (since Regular contains "u")
