### ISSUE TITLE
Is the default install supplied connection for Libra Irc (irc.librairc.net) correct ?

### ISSUE THREAD

**Issue by abazaba855** [kvirc/KVIrc#2580]
I was wondering if the server that is provided with the install for Libra Irc (irc.librairc.net) is correct ? I think it needs to be 'irc.libra.chat' instead. (So 'LIBRA.net, instead of 'LIBRAIRC.net'.)

When I connect to LIBRA.net (connection configured by myself) I get the expected channels and people in those channels. But when I connect to LIBRAIRC.net, all the channels are empty, as if I am the only one there.

Running 'KVIrc-5.2.0-beta1-fix-x86_64.exe' on Windows 11 64-bit.

![librairc](https://github.com/kvirc/KVIrc/assets/106878151/07ad45be-601b-44b7-933a-53c3d78eef30)

**Comment by ctrlaltca** [comment]
The servers defined in KVIrc seems to be the correct ones for that network: https://netsplit.de/servers/?net=LibraIRC

Libra.chat currently point to a domain squatter: https://dan.com/buy-domain/libra.chat?redirected=true
irc.libra.chat resolves to an amazon ec2 instance, but ports 6667 and 6697 are closed now.

**Comment by abazaba855** [comment]
Hrm. It seems I have made a mistake here, and read the names too quickly. Now I read my own post again, I can see the difference now :

both

'libera.chat' (and 'irc.libera.chat') (see attached jpg)

and

'librairc.net' (and 'irc.librairc.net')

seem to be valid networks; they just have similar sounding names that managed to confuse me. Sorry for the noise.

PS: You also seem to have made a similar mistake by reading it as 'libra.chat' (and 'irc.libra.chat').

![libera chat](https://github.com/kvirc/KVIrc/assets/106878151/37b5b08c-4e61-4285-a589-7c323de1ac40)

**Comment by ctrlaltca** [comment]
In your first post you mentioned libra.chat:
> I think it needs to be 'irc.libra.chat' instead

Anyway, thanks for the feedback.
