### ISSUE TITLE
KVIRC closes when I minimize it

### ISSUE THREAD

**Issue by NikoZion** [kvirc/KVIrc#2588]
Hello !

KVIRC closes when I minimize it. What can I do ?

**Comment by ctrlaltca** [comment]
It would be nice to know at least the OS and the KVIrc version you are running.
Do you get any error message when it closes?
You can try to run the about-to-be-released new version from here: https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta3

**Comment by NikoZion** [comment]
KVIRC 5.1.3 
No message
Windows 10

I've downloaded the 5.2.0 beta, now I have the message : "Unable to find the shared KVIRC directory ..."
Still 5.1.3 displayed on KVIRC. Still close when minimize it.

**Comment by NikoZion** [comment]
I've downloaded the 5.2.0 beta, now I have the message : "Unable to find the shared KVIRC directory ..."

**Comment by ctrlaltca** [comment]
kvirc 5.1.3 is already the latest kvirc 5.2.0 beta.
The error message is longer, and it states the folder where kvirc should have been installed.

**Comment by NikoZion** [comment]
What should I do to stop getting this message ? How do I prevent KVIRC from closing when I minimize it ?

**Comment by ctrlaltca** [comment]
The  "Unable to find the shared KVIRC directory ..." is probably the consequence of a borked installation.
I'd uninstall completely kvirc and then try to reinstall.
About the "close on minimize" problem, i'm not sure what's going on. I don't even understand if you mean it's crashing.

**Comment by NikoZion** [comment]
I can't remove KVIRC. "Windows don't found uninstall"

I don't like the new version. Probably because it's beta. 
We no longer see the buttons for example for bans or separating joins / quits...

I think the "close on minimize" should be an option.

**Comment by ctrlaltca** [comment]
> We no longer see the buttons for example for bans or separating joins / quits...

This is due to the fact that KVIrc can't find its installation directory and load the button images.

> I can't remove KVIRC. "Windows don't found uninstall"

I'd try to reinstall it again over the old directory, hopefully it fixes the problem.

> I think the "close on minimize" should be an option.

Try have a look at  the options in  Settings -> Configure KVIrc -> Interface -> Tray icon.
Maybe "close in tray" or "minimize in tray" is what you're looking for

**Comment by NikoZion** [comment]
Everything is in order, thanks !
