### ISSUE TITLE
Deprecation warning with qt6 on macOS Sonoma

### ISSUE THREAD

**Issue by Mattoje** [kvirc/KVIrc#2601]
Qt6 started complaining about this macro:

In file included from /Users/matteo/ports/KVIrc/src/kvilib/config/kvi_settings.h:39:
/Users/matteo/ports/KVIrc/build/kvi_sysconfig.h:76:15: warning: macro 'Q_OS_MACX' has been marked as deprecated: use Q_OS_MACOS instead [-Wdeprecated-pragma]
#if !(defined(Q_OS_MACX) || defined(MINGW) || defined(MSVC))
              ^
/usr/local/opt/qt6/include/QtCore/qsystemdetection.h:167:65: note: macro marked 'deprecated' here

Here is a little patch i did which also appears to work with qt5 
[Q_OS_MACX.deprecation.patch](https://github.com/kvirc/KVIrc/files/14229969/Q_OS_MACX.deprecation.patch)

**Comment by ctrlaltca** [comment]
Thank you for the patch, I've opened a PR https://github.com/kvirc/KVIrc/pull/2603 , will merge when CI succeeds.
