### ISSUE TITLE
[Feature Request] Strip leading spaces on command

### ISSUE THREAD

**Issue by ganego** [kvirc/KVIrc#2626]
My niche problem: I copy a command from some DCC channel but I included the prepending space because I did not properly 'target' the slash before because it's hard for me to properly see it: `  /MSG user text`.   
Result: "Unknown command is an unknown server command"

Can it be changed that when kvirc encounters this error, instead of showing the error and aborting it will strip leading spaces and issue the command again - and only if that fails show the error?

Thank you

**Comment by ctrlaltca** [comment]
Hi, a fix is available at https://github.com/kvirc/KVIrc/pull/2627 if you want to test it.
Anyway it will be available in the next KVIrc version.

**Comment by ganego** [comment]
When I opened this request I did not really expect it to be fixed (anytime soon), yet half an hour later there was a fix.  
I'm impressed - thank you.  

Don't really want to go through all the work to compile it myself, so I'll wait for the merge and try it in the nightly.  

Thank you

**Comment by ganego** [comment]
Works, thank you again.
