### ISSUE TITLE
[macOS] 5.2.4 is ARM-only

### ISSUE THREAD

**Issue by core-code** [kvirc/KVIrc#2643]
version 5.2.4 is ARM-only and does not run anymore on Intel based Macs. is this on purpose?

<img width="255" alt="Screenshot 2024-05-11 at 22 21 13" src="https://github.com/kvirc/KVIrc/assets/1261954/4cf4cc7c-2f21-4f0b-abc5-ad47bab7566d">

**Comment by ctrlaltca** [comment]
Our packages are built using GitHub actions, and it looks like they switched to M1 macs for building now.
I tried switching to an older mac image in https://github.com/kvirc/KVIrc/pull/2644 , i'll publish the resulting package as soon as it builds

**Comment by core-code** [comment]
thanks!
