### ISSUE TITLE
Help automate greetings message on join channel or channel sync. 

### ISSUE THREAD

**Issue by shorewall** [kvirc/KVIrc#2652]
Not a bug but an help request.
KVirc 5.0.0 Aria on Linux.

I spent a couple of days attempting to automate sending greetings whenever KVirc join a channel.
I've used onChannelSync onJoin onMeJoin and I don't remember how many other dozens of event attempting to send such kind of message.
Could some gently soul post here a code snippet and tell me where insert it?

xdccmule is so easy... just a flag to allow greetings on join a channel.

I'm becaming crazy using Kvirc to run this simple task.

Thanks in advance

**Comment by ctrlaltca** [comment]
OnMeJoin is the event you want to use.
The event code can be something as simple as
```
msg $target Hello
```

You may want to have a read at the documentation, eg:
 * `/help onmejoin`
 * https://kvirc.github.io/kvirc-tutorials/AOS_Vol03_Events_and_popups_en.pdf

**Comment by shorewall** [comment]
Thanks very much... I read a lot but w/o understanding exactly how to code the string.
I didn' know about the $target var to be inserted... So my message was partially written on channel join but always receiving an error message.
Thanks again Now works like a charm :-)
