### ISSUE TITLE
Does KVIrc have a dark mode on Windows?

### ISSUE THREAD

**Issue by AbraxasDMG** [kvirc/KVIrc#2662]
Hi everyone.
Is it possible on Windows to have the KVIrc window and all its elements displayed in dark colors (not only the channel/chat window contents)?
Thanks in advance!

**Comment by ctrlaltca** [comment]
You can force KVIrc into using a more modern style (supporting dark mode, too) by running:
```
kvirc -style Fusion
```

We should really consider making the default, I'll keep this ticket open until we fix it

**Comment by AbraxasDMG** [comment]
Thank you very much!

Is it possible to update some configuration file with 5.2.2 to avoid to supply the style information via command line in the meantime?
