### ISSUE TITLE
Missing Languages except English

### ISSUE THREAD

**Issue by LittlDog** [kvirc/KVIrc#2679]

**Comment by LittlDog** [comment]
uhh. my description got lost after posting...

I installed the newest Version 5.2.4 Quasar at Windows 11

All other Languages except English are missing in the Language Settings.

After i copied the "locales" folder from an older Version (5.0.1 Aria) to the new version and restarting KVIrc, the languages appeared in the Languages Settings.

Maybe you could provide an already compiled Language Pack on your website for downloading?
Would be easier to keep them up to date instead of reinstalling KVIrc.

Thanks in advance

**Comment by ctrlaltca** [comment]
Thank you for your report.
The issue has been fixed in https://github.com/kvirc/KVIrc/pull/2680 and the future 5.2.6 will correctly contain the missing localization files.
