### ISSUE TITLE
IP Address

### ISSUE THREAD

**Issue by ptaylor2** [kvirc/KVIrc#2690]
I have a question when using your web chat is there any way to pass the orginal users IP address to the IRCD server?

Phil

**Comment by ptaylor2** [comment]
When this option is enabled is not logging anything in the users folder and I need it to also log the users real IP address.

        // Autoload users
        //
        // When this setting is enabled, your 'users/' folder will be monitored. This is useful
        // if you want to add/remove users while the server is running.
        //
        // @type     boolean
        // @default  true
        //
        autoload: true,

**Comment by ctrlaltca** [comment]
KVIrc is not a web chat; you are probably looking for another project.
Also, learn to use the issue template.

**Comment by ptaylor2** [comment]
I was refering to your web irc chat applet

**Comment by ctrlaltca** [comment]
Do you have un URL or some more explanation? Honestly I don't know what you are referring to

**Comment by ptaylor2** [comment]
Yes, http://sky-chat.net

**Comment by ctrlaltca** [comment]
This is the repository for https://www.kvirc.net/
That website has no connection whatsoever with KVIrc.
