### ISSUE TITLE
Windows Cancels Executable installation file after download.

### ISSUE THREAD

**Issue by symon3so** [kvirc/KVIrc#2692]
![Screenshot 2024-11-26 181714](https://github.com/user-attachments/assets/391ee4bf-4617-4149-8509-dc0ee9cc7a5c)

I downloaded the current version to install in my HP Windows 11 laptop, but Windows canceled the download, please advise.

![Screenshot 2024-11-26 182202](https://github.com/user-attachments/assets/6ec5bb3e-64ea-4424-b82f-27599cf46d53)

Screen shot of my device Laptop.

KVIrc Executable Information

KVIrc 5.0.0 'Aria'

Runtime Info:
System name: Windows Release : 10.0.22631
System version: Windows 10 (x64) (Build 22631)
Architecture: AMD64 Family 23 Model 96 Stepping 1
Qt version: 5.9.7
Qt theme: windowsvista

Build Info:
Build date: 2019-01-02 01:21:58 UTC
Sources date: 20190101
Revision number: 5.0.0
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.9.7
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Perl, Python, Enchant, Qt5, KVS
OpenSSL version: OpenSSL 1.0.2o 27 Mar 2018
OpenSSL compiler flags: "compiler: cl -utf-8 -FS /MD /Ox -DOPENSSL_THREADS -DDSO_WIN32 -utf-8 -FS -W3 -Gs0 -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -DUNICODE -D_UNICODE -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DOPENSSL_USE_APPLINK -I. -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_SSL2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_WEAK_SSL_CIPHERS -DOPENSSL_NO_DYNAMIC_ENGINE "
OpenSSL built on: reproducible build, date unspecified

**Comment by ctrlaltca** [comment]
In your screenshot i presume i can see the download window of a browser, i don't know which one (maybe Microsoft Edge?). You did download two txt files, a zip file and an old version for Windows 7.
 The file you want to download is this one: https://github.com/kvirc/KVIrc/releases/download/5.2.6/KVIrc-5.2.6-Quasar-x86_64.exe
If you are using Microsoft Edge as i suppose, you need to follow some additional steps to download the file, like clicking on three dots to open a semi-hidden popup menu and pressing "keep"
Another option, use another browser, like Firefox or Chrome

**Comment by symon3so** [comment]
Hello,

The new file and tip resolved the issue, i thank you.
