### ISSUE TITLE
find a way to make the help text translatable

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#355]
**Reported by mren on 27 Jan 2009 00:42:30 UTC**
This is not a bug, it's more an reminder for later on, to find a way that makes it possible to translate the help inside KVIrc.
The best way would be if it's possible to extract these texts to po files, so that translators don't have to deal with "svn diff", which could be a PITA the bigger that files get.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/355

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 19 Dec 2009 16:46:32**
Version: 4.0 Insomnia → 4.0rc2 Insomnia

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 02 Feb 2010 14:17:06**
Version: 4.0rc2 Insomnia → 4.0 Insomnia

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 27 Jun 2010 15:18:56**
Version: 4.0 Insomnia → 4.1 Equilibrium

**Comment by pragmaware** [comment]
Unfortunately it's hard to do and in fact the translation of the help files would never be finished
(it's a LOT of text).
Side point: the API is english-based anyway :)
