### ISSUE TITLE
autorun/ where is check to manage autorun

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#422]
**Reported by anonymous on 16 Apr 2009 04:58:59 UTC**
Implement a way to configure (at runtime) whether KVIrc is started automatically on Windows whenever a user logs in (the user is only asked during installation).

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/422

**Comment by DarthGandalf** [comment]
**Comment by mren on 06 Aug 2009 21:33:20**
Sorry, we don't understand what you want here. If you're looking for an option to autostart KVIrc after you log in into your box it's system dependent. See the manual of your OS/WM/DE.

---

Resolution: none → invalid
Status: new → closed

**Comment by DarthGandalf** [comment]
**Comment by anonymous on 05 May 2010 09:43:59**
The question is quite easy. I understand him, maybe a bit more phantasy.

KVIRC is starting automtically and that is NOT done by my system. I dont know how, but kvirc manages it to autostart.

So your answer is just not the right one. The right answer is: "KVIRC hasnt anything todo with autostart, that is everytime part of the system".

Okey, good, but how does it start then? In my case? Aha seems so that there is an entry in the registry on "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run".
Definitly NOT set manually, so your program/installer set it somehow. I am sorry to say that, but this is annoying. It took me sometime to get the autostart of without deinstallation.

---

Resolution: invalid → none
Status: closed → reopened

**Comment by DarthGandalf** [comment]
**Comment by anonymous on 06 May 2010 11:28:08**

```
Windows XP - KVIrc 4.0
Start/ Run... / regedit / OK/
"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run"  
KVIrc REG_SZ C:\Program Files\KVIrc\kvirc.exe
Rightclick /Remove
```

**Comment by DarthGandalf** [comment]
**Comment by curan on 07 May 2010 13:59:27**
Looking at [source:trunk/kvirc/cmake/KVIrc.nsi.cmake#L154 KVIrc.nsi.cmake] it looks to me like you should have been asked whether you want to make KVIrc an auto start application or not during installation. Therefore this bug is a feature request for a way to configure this behaviour at runtime.

In the meantime you might be interested in [http://technet.microsoft.com/de-de/sysinternals/bb963902.aspx Sysinternals' Autoruns tool].

---

Component: KVS Engine → Core
Type: Bug → Feature request
Version: 3.4.3 Shiny → 4.0rc3 Insomnia
Description:

``` diff
--- 
+++ 
@@ -1,6 +1 @@
-Hello.
-
-Bad english...
-
-Autorun program check.
-Where option in program configuration 
+Implement a way to configure (at runtime) whether KVIrc is started automatically on Windows whenever a user logs in (the user is only asked during installation).

```

**Comment by DarthGandalf** [comment]
**Modified by ctrlaltca on 17 May 2010 09:34:14**
Version: 4.0rc3 Insomnia → 4.0 Insomnia

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 27 Jun 2010 15:19:36**
Version: 4.0 Insomnia → 4.1 Equilibrium

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 01 Sep 2010 13:29:46**
Milestone: Code cleanups and documentation → none

**Comment by un1versal** [comment]
Since https://github.com/kvirc/KVIrc/commit/27f5d68ddf1b1bc4473b569f936ebd6db298977e autostart has been removed so this report seem to be invalidated by that.

Closing but if its in error feel free to reopen.
