### ISSUE TITLE
Configurable foreground/background colouring for smart nickname colours

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#429]
**Reported by anonymous on 28 Apr 2009 17:19:33 UTC**
Basically, it would be nice to have the option to get only the nicks' foreground colour "smartly" coloured instead of the background because the coloured background tends to distract me.

More advancedly, kvirc would allow the user to choose between a) both colouring background _and_ foreground (status quo), b) colouring the foreground _only_ and c) colouring the background _only_.

Optimally, the colours used for smart colours would be configurable, too.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/429

**Comment by DarthGandalf** [comment]
**Comment by anonymous on 01 Aug 2009 09:55:45**
So :/ ?

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 19 Dec 2009 16:48:13**
Version: 4.0 Insomnia → 4.0rc2 Insomnia

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 02 Feb 2010 14:18:24**
Version: 4.0rc2 Insomnia → 4.0 Insomnia

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 27 Jun 2010 15:19:40**
Version: 4.0 Insomnia → 4.1 Equilibrium

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 25 Sep 2010 13:42:54**
merged with #812

**Comment by un1versal** [comment]
Duplicate of #353 

Merging this with that and closing here.
