### ISSUE TITLE
I/O traffic Graph needs scaling down

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#612]
**Reported by nucleo on 08 Nov 2009 17:33:55 UTC**
All times I see zero traffic because highest value 15 MB.
Graph range won't scale down.
This is need to be fixed.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/612

**Comment by DarthGandalf** [comment]
**Modified by ctrlaltca on 08 Nov 2009 17:54:54**
Version: 4.0rc1 Insomnia → 4.0 Insomnia

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 19 Dec 2009 16:49:48**
Version: 4.0 Insomnia → 4.0rc2 Insomnia

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 02 Feb 2010 14:19:58**
Version: 4.0rc2 Insomnia → 4.0 Insomnia

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 03 Apr 2010 15:17:34**
implemented in r4238

---

Resolution: none → fixed
Status: new → closed

**Comment by DarthGandalf** [comment]
**Comment by nucleo on 18 Apr 2010 10:02:44**
Now I still see zero traffic in KVIrc 4.0 rc3 but highest and lowest values are 0 bytes.

---

Resolution: fixed → none
Status: closed → reopened

**Comment by DarthGandalf** [comment]
**Comment by nucleo on 18 Apr 2010 10:19:21**
When I started KVIrc with clean configuration then traffic shown as it should.
But with old configuration almost all time 0 there but when connecting to new server was 38 bytes peak.

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 27 Jun 2010 15:20:17**
Version: 4.0 Insomnia → 4.1 Equilibrium

**Comment by un1versal** [comment]
IMO the I/O graph is slightly broken, currently I dont see any thing happening there and also doesnt work (by design) for dcc transfers, so its always 0 no matter what, see also https://github.com/kvirc/KVIrc/issues/1619
