### ISSUE TITLE
Separate timestamps for channel window and log files

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#700]
**Reported by moo on 29 Jan 2010 17:36:22 UTC**
There should be an option so that you can use different timestamps in the log files and in the channel window. For example I'd like to use [hh:mm:ss] in the channel window, but I don't want to use the same timestamp format in the log files, because I prefer a more detailed format within them ([dd.MM.yyyy - hh:mm:ss]).

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/700

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 29 Jan 2010 19:26:26**
dates in log files are useless, since the log file has the date in its name

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 02 Feb 2010 14:22:35**
Version: 4.0rc2 Insomnia → 4.0 Insomnia

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 27 Jun 2010 15:20:48**
Version: 4.0 Insomnia → 4.1 Equilibrium

**Comment by DarthGandalf** [comment]
**Modified by ctrlaltca on 01 Sep 2010 11:11:22**
Milestone: none → Review the log engine

**Comment by ghost** [comment]
I only see this as being useful if #919 is implemented.  And if #919 is implemented, this should be done as part of it.  Any need for this to still be open?

**Comment by un1versal** [comment]
Not really, we can copy and paste this request into #919 and make note of it.

edit-- https://github.com/kvirc/KVIrc/issues/919#issue-97278332
