### ISSUE TITLE
make commandline userfriendlymode smarter based on the command being called

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#80]
**Reported by mren on 20 Feb 2008 18:50:08 UTC**
With "/server -n irc.n00bstories.com" in userfriendly mode i got this error:<br/>
[19:01:51] [KVS] Runtime Error: Invalid data type for parameter "port": found string value "irc.n00bstories..." where type 'unsigned integer' was expected<br/>
[19:01:51] [KVS]   in script context "commandline::userfriendly", line 1, near character 1

After switching to kvs mode it works as expected

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/80

**Comment by DarthGandalf** [comment]
**Comment by anonymous on 13 Mar 2008 02:42:34**
The "User friendly mode" is actually meant as a "you-want-it-so-bad-so-here-it-is"
fix for users that pretend to type "/me is happy ;)" in the commandline.
I don't actually expect it to work for anything else than "/me is happy ;)".

---

Resolution: none → wontfix
Status: new → closed

**Comment by DarthGandalf** [comment]
**Modified by DarthGandalf on 16 Jan 2010 11:34:55**
Resolution: wontfix → none
Status: closed → reopened
Version: 3.2.6 Anomalies → 4.0rc2 Insomnia

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 26 Jan 2010 21:03:45**
This is a bit complex, since it will involve user-created scripts (aliases) and the way they will be handled.

---

Component: Core → KVS Engine
Summary: /server -n server.name.tld doesn't work in userfriendly mode → make commandline userfriendlymode smarter based on the command being called
Type: Bug → Feature request

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 02 Feb 2010 14:12:13**
Version: 4.0rc2 Insomnia → 4.0 Insomnia

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 27 Jun 2010 15:17:13**
Version: 4.0 Insomnia → 4.1 Equilibrium

**Comment by un1versal** [comment]
I just tried to duplicate this and it works just fine

![capture](https://cloud.githubusercontent.com/assets/3521959/16167695/1771524a-34f0-11e6-9d17-1b585b13d86b.PNG)

closing as worksforme, if anyone disagrees reopen or ask to reopen.
