### ISSUE TITLE
Only foreground color for smart nicknames coloring mode.

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#812]
**Reported by Emralegna on 13 Jun 2010 03:15:50 UTC**
Hi,

Coloring nickname is very useful for a better readability and less eye fatigue ; unfortunately it forces the use of background color as well and can be very annoying/ugly when used with a dark themes and/or real transparency.

Can it be added an option to get only a foreground nickname coloring mode ?

Thanks.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/812

**Comment by DarthGandalf** [comment]
**Modified by ctrlaltca on 13 Jun 2010 16:44:27**
Version: 4.0rc3 Insomnia → 4.0 Insomnia

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 27 Jun 2010 15:12:00**
Version: 4.0 Insomnia → 4.1 Equilibrium

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 21 Aug 2010 13:12:13**
merged with #914

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 25 Sep 2010 13:42:45**
dup of #429

---

Resolution: none → duplicate
Status: new → closed

**Comment by un1versal** [comment]
merged with #353
