### ISSUE TITLE
HTTP 301 Moved Permanently not followed

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#850]
**Reported by ambossarm on 14 Jul 2010 10:23:43 UTC**
An avatar got 301, and KVIrc does not follow the redirect, but it should do ;)

12:15:17] [HTTP 6]:   Location: http://tebuaq.blu.livefilestore.com/y1pn19smQoWMNdx94rx0T17n9LSh5JPnbF96vaCYvVmP1jV5Eao_NK0Kd_wypvZw9KWpYEZuoe_Stl0kmklZsOWgA/kaiji150.jpg?psid=1
[12:15:17] [HTTP 6]: Transfer failed: HTTP/1.1 301 Moved Permanently

Firefox simply follows the redirect and gets the image.

there are more codes for redirect
[12:20:08] <egns> http://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/850

**Comment by DarthGandalf** [comment]
**Modified by wodim on 18 Sep 2010 13:13:05**

**Comment by DarthGandalf** [comment]
**Comment by ambossarm on 05 Feb 2011 08:51:41**
[09:45:38] [HTTP 6]: Transfer failed: HTTP/1.1 302 Found

**Comment by un1versal** [comment]
This sounds more like a bug to me in the implementation marked as such.

**Comment by AndrioCelos** [comment]
Is this issue still present? I'm closing this as HTTP redirects seem to be being handled now.
