### ISSUE TITLE
GeoIP coordinates onjoin

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#880]
**Reported by Grommet on 04 Aug 2010 04:56:16 UTC**
I'd like to be able to see the geoip coordinates and city when people join. I already have the country script from hellvis which is nice but I'd like to see the coordinates so I could see where they live on google maps :) 

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/880

**Comment by DarthGandalf** [comment]
**Comment by wodim on 04 Aug 2010 11:15:07**
I see no reason for including this in KVIrc. You can do it with scripting...

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 04 Aug 2010 20:42:01**
work in progress via kvs :)

---

Component: Core → Addon
Owner: pragmaware → HelLViS69
Status: new → assigned

**Comment by pragmaware** [comment]
Closing as this is to be done via scripting anyway.
