### ISSUE TITLE
Use the Growl notifier on OSX

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#896]
**Reported by Pix on 08 Aug 2010 15:26:15 UTC**
as in the [https://svn.kvirc.de/kvirc/ticket/810 810], but for OSX: it should be useful the support to [http://growl.info/ Growl], too. It's the most used notification system on OSX, and is implemented in the most part of mac appz.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/896

**Comment by DarthGandalf** [comment]
**Comment by bugmenot on 08 Dec 2013 09:28:32**
I second the request, it is also available in Windows:
http://www.growlforwindows.com/

**Comment by un1versal** [comment]
@wodim for OSX stuff, please comment.

**Comment by ctrlaltca** [comment]
Growl is dead, closing.
