### ISSUE TITLE
Window width properties are lost for userlist / topic / modes, upon KVIrc's restart.

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#900]
**Reported by Corin on 11 Aug 2010 17:11:41 UTC**
I've had this issue every since Insomnia and it's still happening in Equilibrium. I have noticed that this doesn't happen if you close each tab, individually, as long as each tab is currently selected, when you close it.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/900

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 11 Aug 2010 22:58:49**
confirmed<br/>
I tried also to remove winproperties.kvc

**Comment by DarthGandalf** [comment]
**Comment by Corin on 12 Aug 2010 22:10:52**
Yes, I forgot to mention that doing so hadn't worked.

**Comment by DarthGandalf** [comment]
**Comment by anonymous on 03 Sep 2010 20:11:41**
I can confirm this annyoing bug.

It happens when trying to resize a user's list.
I attached several versions of winproperties.kvc
Hope this helps.

**Comment by DarthGandalf** [comment]
**Comment by Stanzilla on 23 Sep 2010 09:47:32**
Confirmed, and it's annoying as hell.

**Comment by DarthGandalf** [comment]
**Comment by Corin on 04 Feb 2011 06:45:10**
Disabling Preferences > Interface > Remember window properties and deleting the winproperties file seems to solve the issue entirely.

**Comment by DarthGandalf** [comment]
**Comment by Corin on 04 Feb 2011 06:46:22**
Disabling Preferences > Interface > Remember window properties and deleting the winproperties file in the config folder seems to solve the issue entirely.

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 12 Aug 2011 14:06:53**
Corin's workaround is fine if you just don't care about rkvirc remebering previous customizations to the interface. Anyway, r5923 reintroduces a "sizes handling"mechanism that emulates the old kvirc3's way, hopefully making kvirc4 more user-friendly.
The first times you run kvirc with this patch you could experience some oversized userlists; they are supposed to appear when an old (broken) size value had been saved inside the kvirc config. Just resize the userlist as you like it best and it should work from the second time on.
Please comment/feedback on this

---

Owner: pragmaware → ctrlaltca
Status: new → assigned

**Comment by DarthGandalf** [comment]
**Comment by DarthGandalf on 17 Sep 2011 11:06:52**
The real problem here is the way how is winproperties.kvc stored.
It stores every channel in the form #channel@network.
When network name changes, 2 records appear in .kvc - #channel@network1 and #channel@network2.
And kvirc seems to be confused by them, loading wrong one next time winproperties.kvc is loaded.
It saves proper values to one record, but reads another record.
So winproperties.kvc becomes broken. That's why removing it helps... temporary helps.

There're 2 ways when network name can change:
1. When 005 NETWORK=... name differs from the name stored in serverdb, the name changes from one in serverdb to one from 005.
2. When the same IRC context is reused to connect to another server, which sends 005 with new network name.
Probably in the second way the name is changed first to the name from serverdb, and only then to one from 005, not sure.

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 07 Jan 2012 17:01:26**
fixed in r6018 and following

---

Resolution: none → fixed
Status: assigned → closed

**Comment by DarthGandalf** [comment]
**Comment by ambossarm on 10 Jan 2012 00:56:32**
KVIrc Equilibrium 4.1.3, revision: 6043, sources date: 20120101, built on: 2012-01-08 20:04:14 UTC on ARCHLinux

I deleted yesterday my winproperties.kvc and checked all channels after next start, everything was fine.

Now I have 12 fine channels and 5 "bad" ones, with the userlist

Fine-Channel:

```
[%23archlinux.de@Freenode]
PrivateBackground=
commandLineIsUserFriendly=false
TopSplitter=371,83
Splitter=310,160
IsDocked=true
DoubleView=false
TextEncoding_%23archlinux.de=
VertSplitter=384,256
EntryTimestamp=1326122428
inputToolButtonsHidden=true
ToolButtonsHidden=true
IsMaximized=false
UserListHidden=false
WinRect=4,24,476,316
```

Bad-Channel:

```
[%23ubuntu.de@QuakeNet]
PrivateBackground=
commandLineIsUserFriendly=false
TopSplitter=80,14
Splitter=100,31
IsDocked=true
DoubleView=false
VertSplitter=384,256
EntryTimestamp=1326122428
inputToolButtonsHidden=true
ToolButtonsHidden=true
IsMaximized=false
TextEncoding_%23ubuntu.de=
UserListHidden=false
WinRect=4,24,476,316
```

afai see, all fine are equal and all bad are equal.

---

Resolution: fixed → none
Status: closed → reopened

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 10 Jan 2012 09:12:29**
Did you remove winproperties.kvc while KVIrc was NOT started?

**Comment by DarthGandalf** [comment]
**Comment by ambossarm on 10 Jan 2012 09:17:02**
Yes, I quit KVIrc, deleted winproperties.kvc and started KVIrc, checked all windows, all where fine. Next day -> Problem

But I am not sure if I reopend the right ticket, should I have reopend #613
I don't think that I did something special to trigger the bug.

**Comment by un1versal** [comment]
mdi windows is gone and this issue has not repeated itself. closing as works for me

Also https://github.com/kvirc/KVIrc/issues/1543 and https://github.com/kvirc/KVIrc/issues/1544 seem related.

**Comment by Stanzilla** [comment]
It also affected the split view mode and it still happens there for me btw

**Comment by un1versal** [comment]
> un1versal commented on 2 Sep 
> Similar to https://github.com/kvirc/KVIrc/issues/1543

On Kvirc restart
![capture](https://cloud.githubusercontent.com/assets/3521959/9620376/7fb3d2e2-5111-11e5-92bd-d745f35a31c3.PNG)

Before
![capture](https://cloud.githubusercontent.com/assets/3521959/9620412/dfe91a0a-5111-11e5-81a4-40d7d995e53c.PNG)

This affects many channels but not all. and its server independent.

---

Merged duplicate  #1544 Topic is covered by channel modes on Kvirc restart 

---

Before as set
![capture](https://cloud.githubusercontent.com/assets/3521959/9620222/d66ee59c-510f-11e5-8453-ddc76a75c683.PNG)

After restart.
![capture](https://cloud.githubusercontent.com/assets/3521959/9620346/2acb53c2-5111-11e5-9690-2dba6baacabc.PNG)

I have 3 servers and various channels on these 3 servers the main servers one that loads ontop looses size of the user list width I set all the time to half or more when all channels finish reloading. If it helps this is a read only channel

---

Merged duplicate with  #1543  User list width lost on KVIrc restart

**Comment by un1versal** [comment]
> It also affected the split view mode and it still happens there for me btw

@Stanzilla  #1543 has a sort of workaround, mind undocking your channel windows that are affected, adjust the widths until you are happy then dock them and right click _save windows props as default_*?

**Comment by un1versal** [comment]
**Reported by nucleo on 23 Jun 2010 18:55:16 UTC**
Width of user lists on some of autojoin channels changed after restart in http://labs.pragmaware.net/misc/kvirc-4.0.0.tar.bz2 (r4489)

Need to resize them after every restart.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/823

---

Merged with https://github.com/kvirc/KVIrc/issues/823

**Comment by un1versal** [comment]
This is back again

On Kvirc restart
![capture](https://cloud.githubusercontent.com/assets/3521959/9620376/7fb3d2e2-5111-11e5-92bd-d745f35a31c3.PNG)

Before
![capture](https://cloud.githubusercontent.com/assets/3521959/9620412/dfe91a0a-5111-11e5-81a4-40d7d995e53c.PNG)

**Comment by Stanzilla** [comment]
Oh, didn't see the mention, I had kinda given up on it so I did not pay attention if it was still happening or not, will do so now.

**Comment by un1versal** [comment]
Yea I thought I was just talking to myself as usual ;)

**Comment by Stanzilla** [comment]
Yeah still resets, just had it happen when I upgraded to a newer nightly

**Comment by un1versal** [comment]
This re-appeared after compiling new build today userlists are now all short in some channels.
This is beginning to really annoy me since fixing it is a major pain in the neck.

Im beginning to wonder if this will ever be fixed.

**Comment by un1versal** [comment]
And another report at #1864 . Lately with changes to `<center>` tag cleanup, after each compile and KVIRc restart triggers a reset, this is one of the most annoying bugs in KVIrc.

Surely it has to affect all devs as well?

**Comment by xrogaan** [comment]
My userlist shrinks too. I'm using d00p build revision geed2e4d.

I'm not sure if it does it for every channel, but overtime all of the userlist got minimized fully.

**Comment by un1versal** [comment]
Im testing a patch for the user list issue https://github.com/un1versal/KVIrc/commit/051e153b4a8cf12dcec0cd7fd63c0f8fff3513bb this seems to cure this issue but needs more testing

Ill test the others like modes width shortly as well.

**Comment by Stanzilla** [comment]
How is changing a default the cure for an issue where your own setting is lost?

**Comment by un1versal** [comment]
Im thinking it resets to default somehow and so far looks like that is not a bad assumption. but like I said, need more testing

**Comment by un1versal** [comment]
actually my assumptions were incorrect, it doesnt reset to defaults, the values are being overwritten, would have to test against brand new configs but the ideal solution would be to implement #1197 with global minimal defaults and also make them user changeable.

**Comment by un1versal** [comment]
Whoever is suffering from this issue can you test these builds and report back please?

for 32-bit https://ci.appveyor.com/api/buildjobs/a4p82gp2n79245kh/artifacts/KVIrc-4.9.2-dev-git-6762-ged3f2ff-x86.exe

for 64-bit https://ci.appveyor.com/api/buildjobs/ohueuhe0yyr32vfa/artifacts/KVIrc-4.9.2-dev-git-6762-ged3f2ff-x86_64.exe

Relevant PR https://github.com/kvirc/KVIrc/pull/2028

> #### Note: that is only for **UserListWidth**
> 
> The minimum width is 100 pixels, but can be changed since some people may prefer less than 100 pixels wide minimum size.

**Comment by un1versal** [comment]
Well despite the rather negative (and expected reactions) https://github.com/kvirc/KVIrc/pull/2028 when a user sets own size seems to cure the userlist width being lost quite so often, in fact so far not once but it could be early days.

its not intrusive considering the benefits and I rather fix half of this 6 year old issue and allow some customization rather than keep ignoring the many reports.

**Comment by un1versal** [comment]
**The user list width being lost is confirmed as fixed**

Had the problem reoccur and **the split view** (looks like reset to default) + **topic mode width** (was twice the width preset to; were lost.
The minimum userlist width and more importantly custom width set to some channels remained

Ideally the fix for topic would be to add a maximum width to channel mode portion so that the topic part needs no setting.

then maybe wodim can complain somemore when I add a configurable channel view split width to fix this ticket 100%

I think @1977David did also managed to confirm this over IRC.

**Comment by ctrlaltca** [comment]
We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix and report if this issue is still present. Thank you
