### ISSUE TITLE
Option to hide/disable main menu

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#907]
**Reported by z0rc on 16 Aug 2010 20:59:21 UTC**
It would be nice to allow user to hide main menu just like panels and status bar. User needs to press 'Alt' key to show it. Just like it works in latest Firefox.

This feature will allow to preserve a bit more so valuable vertical resolution on nettops.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/907

**Comment by un1versal** [comment]
This was done not long ago, closing
