### ISSUE TITLE
Log folders

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#927]
**Reported by Nakre on 31 Aug 2010 11:46:48 UTC**
Ok what would be nice is an option like 
"Creat Folder for Each Network"
"Creat Folder for Each Nick (into the folder of network of course)"
"Creat Folder for Each Channel (into the folder of network of course)"
at the IRC, Tools, Loggin..

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/927

**Comment by DarthGandalf** [comment]
**Comment by Nakre on 31 Aug 2010 12:51:42**
since i couldnt edit my post and just realised it will also need maybe like popup for remove all files in (channel, network nick)folder :)

**Comment by DarthGandalf** [comment]
**Modified by ctrlaltca on 01 Sep 2010 11:04:38**
Version: none → 4.1 Equilibrium

**Comment by DarthGandalf** [comment]
**Modified by ctrlaltca on 01 Sep 2010 11:11:37**
Milestone: none → Review the log engine

**Comment by DarthGandalf** [comment]
**Comment by Nakre on 01 Sep 2010 18:49:37**
Could be usefull to have order by last change date for nicks or channels folders inside the network folder ?

## An example if we had nicks folder for daily logs of it in.. could be like order(folders) by last change so would have to look easy to see what is last query or what chans been last logged etc.

atm its 
chan - ordered by name
query - ordered by name

## console - ordered by numbers(no idea what are the numbers sorry)

would look like..
network - order by date or name as options on the right click maybe also "remove all these network log files"
chan - order by date or name as options on the right click of channel(where is only has "remove all these channel/query log files" 
query - order by date or name as options on the right click of query
console - order by date or name as options on the right click of console

## The dates would be by fulldate(times included) not just day i think ?

## "remove all these channel/query log files" could be used as

"remove all these channel log files" on the chan folder right click
"remove all these query log files" on the query folder right click
"remove all these console log files"on the console folder right

**Comment by DarthGandalf** [comment]
**Comment by Nakre on 07 Sep 2010 01:17:38**
may i also suggest get better way of text files for log files
im not sure if we can better way that we are able to read from txt files
atm it looks like ermm hell ? too hard to see whos said what etc..
everything is kinda seperated.. ? well i hope the logging will be better with some updates :)

```
0 ### Log session started at Paz 29. Ağu 00:00:00 2010 ###
24 [00:01:57] <
!nc
Nakre
> akult: ty didnt try if it works but seems mren's simpler n working 
34 [00:03:52] 
!n
Ab3L
 [~Ab3L@
!h
65-250.62-188.cust.bluewin.ch
] has quit IRC: Quit: KVIrc 3.2.4 Anomalies http://www.kvirc.net/
2 [00:04:20] <
!nc
akult
> Nakre, as 
!n
ambossarm
 said $channel(#channelname) returns window ID. you should control this quite careful, because window ID isn't static.
```

**Comment by DarthGandalf** [comment]
**Comment by Nakre on 10 Sep 2010 12:42:45**
Replying to [comment:5 Nakre]:

> may i also suggest get better way of text files for log files
> im not sure if we can better way that we are able to read from txt files
> atm it looks like ermm hell ? too hard to see whos said what etc..
> everything is kinda seperated.. ? well i hope the logging will be better with some updates :)
> 
> ```
> 0 ### Log session started at Paz 29. Ağu 00:00:00 2010 ###
> 24 [00:01:57] <
> !nc
> Nakre
> > akult: ty didnt try if it works but seems mren's simpler n working 
> 34 [00:03:52] 
> !n
> Ab3L
>  [~Ab3L@
> !h
> 65-250.62-188.cust.bluewin.ch
> ] has quit IRC: Quit: KVIrc 3.2.4 Anomalies http://www.kvirc.net/
> 2 [00:04:20] <
> !nc
> akult
> > Nakre, as 
> !n
> ambossarm
>  said $channel(#channelname) returns window ID. you should control this quite careful, because window ID isn't static.
> ```
> 
> urg!!! wish i knew the "strip msg type numbers in logs" option sorted the logs i mentioned above

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 12 Sep 2010 19:52:11**
Please keep this ticket's discussion related to the original request. Further ideas can get their way on a new feature request if necessary.

**Comment by DarthGandalf** [comment]
**Comment by ambossarm on 12 Jan 2011 22:44:55**
German forum post
http://www.kvirc.ru/forum/?topic=1053.msg3817;boardseen#new

A feature request to have a folder per network

is that ticket "mergeable" with #609

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 14 Jan 2011 08:19:15**
implemented in r5355, with #609

---

Resolution: none → fixed
Status: new → closed

**Comment by TurkDesk** [comment]
i don't see the log folder for network option in irc, tools, logging or any other options mentioned..

**Comment by un1versal** [comment]
![capture](https://cloud.githubusercontent.com/assets/3521959/16814577/5dd4ae56-492e-11e6-861d-751962dfce3a.PNG)

Whats that then?
