### ISSUE TITLE
alternative nicks

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#958]
**Reported by Nakre on 08 Sep 2010 18:51:53 UTC**
May we have an option for network and server alternative nicks at config servers ? i know we have settings, identity alternative nick setting but that goes to all servers we connect :)

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/958

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 08 Sep 2010 19:03:48**
use network profiles: settings -> identity -> profiles

---

Resolution: none → invalid
Status: new → closed

**Comment by DarthGandalf** [comment]
**Comment by Nakre on 08 Sep 2010 19:30:01**
Ok i tried that but not what i meant kinda same but think u got 2 different servers added in a network with different nicks etc..
i dont see a way to manage by servers in profiles it goes by network name thats why i said "option for network and server alternative nicks at config servers ?" 
maybe we could move profiles to somewhere in config servers with some updates :)

---

Resolution: invalid → none
Status: closed → reopened

**Comment by DarthGandalf** [comment]
**Modified by ctrlaltca on 12 Sep 2010 20:22:59**
Version: none → 4.1 Equilibrium

**Comment by un1versal** [comment]
Each server can have separate nicks and alternate nicks, that's done in server management **_Ctrl+S**_ in between profiles and Identity dialogs, this should be ample for most users.

@ctrlaltca closing here, if closed in error please ping me or reopen
