### ISSUE TITLE
Different styles on the topic bar

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#969]
**Reported by Stanzilla on 19 Sep 2010 13:54:53 UTC**
As you can see on the screenshot (and probably know already) kvirc uses two different background/border styles for the topic and chan mode fields on the bar above the chat window. I think it should use the same style so it looks more streamlined.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/969

**Comment by DarthGandalf** [comment]
**Comment by pragmaware on 16 Apr 2011 02:02:03**
This is likely to be a WindowsXPStyle  / WindowsVistaStyle related bug. The native windows engine renders labels with different border than the edit fields...

**Comment by un1versal** [comment]
With  Qt5 this _**issue_\* seems to be gone, closing as works for me.

if not show some screenshots and this can be reopened.
