### ISSUE TITLE
Channel mode pane hiding

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#980]
**Reported by Stanzilla on 30 Sep 2010 11:56:56 UTC**
Title basicly says it all, would be awesome if one could hide the channel mode pane next to topic bar.

I'd also like to promote https://svn.kvirc.de/kvirc/ticket/969 which would make this feature request less desirable :)

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/980

**Comment by Stanzilla** [comment]
Yup

**Comment by un1versal** [comment]
> I'd also like to promote https://svn.kvirc.de/kvirc/ticket/969 which would make this feature request less desirable :)

That link went to https://github.com/kvirc/kvirc for me.

https://github.com/kvirc/KVIrc/issues/969 works.

**Comment by un1versal** [comment]
this already exists pressing that button/shows/hides channel mode pane

![capture](https://cloud.githubusercontent.com/assets/3521959/10908221/2373c71a-8228-11e5-804d-48964815896a.PNG)
